### ISSUE TITLE
Question: Render multiple Compositions via `npm run build`

### ISSUE THREAD

**Issue by peduarte** [remotion-dev/remotion#1013]
Hey! Finally I've had some time to play with Remotion. Still just scratching the surface, but I can already tell it's an amazing library. Thanks for all the work!

I just have a question, I was unable to find the answer by searching issues — maybe using wrong terms.

I want to make about 10 videos, and have them each being exported (rendered) as unique `mp4` files. I've done that by using 10 `Composition`'s with different `id`'s.

Is there a way to export them all at once? 

Thank you!

**Comment by JonnyBurger** [comment]
Hey Pedro!

Thanks for trying out Remotion and sorry for the late response!

What you are doing is one way of doing it, another way is to make one composition and render it multiple times with different input props: [Parametrized rendering](https://www.remotion.dev/docs/parametrized-rendering)

Going further than that, you can then use the Node.JS APIs to for example loop over an array of compositions and render them in sequence: https://www.remotion.dev/docs/ssr

The CLI commands are atomic, so one command renders one video. You can use bash scripts to render multiple videos though!

Closing as it is just a question, if something is unclear or you have a feature request, just let us know!
