### ISSUE TITLE
setState in timeupdate event handler

### ISSUE THREAD

**Issue by minarainbow** [remotion-dev/remotion#1043]
While I am trying to setState inside the event handler of timeupdate, for the purpose of showing the current progress of the video in custom timeline bar, the video flickers when playing and shows this message everytime:

```
Time has shifted by 0.45807066666666674 sec. Fixing... (isTime=1.591404,shouldBeTime=1.1333333333333333)
use-media-playback.js:45 Time has shifted by 0.45656966666666654 sec. Fixing... (isTime=2.289903,shouldBeTime=1.8333333333333333)
use-media-playback.js:45 Time has shifted by 0.5249420000000002 sec. Fixing... (isTime=3.424942,shouldBeTime=2.9)
use-media-playback.js:45 Time has shifted by 0.5558423333333327 sec. Fixing... (isTime=4.722509,shouldBeTime=4.166666666666667)
```

I couldn't find the source code related to use-media-playback.js
Do you have any idea why this is hapeening?

**Comment by JonnyBurger** [comment]
Hey Mina!

Thanks for raising an issue. It seems like somehow a full re-render of the Remotion player is happening, which would explain the flicker. Could you paste the component to diagnose the issue?

**Comment by JonnyBurger** [comment]
For reference: The code for use-media-playback.ts is here: https://github.com/remotion-dev/remotion/blob/main/packages/core/src/use-media-playback.ts

**Comment by JonnyBurger** [comment]
Because there was no update, I'm going to close it.
If you still need help, just let us know!
