### ISSUE TITLE
prevent constant re-downloading of Chromium

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#1053]
# Feature Request 🛍️

I'm constantly re-downloading Remotion projects &/or updating then rendering old repos.  I'm contently having to re-download Chromium to render.

Good thing at home I have fast Google Fiber, but if I had to work remotely off my cell phone, local rendering could get ugly.

## Possible Solution

* Provide the Chromium you use as a npm package.  (I use pnpm, so re-installing is more or less instant from local cache.
* Instruct / configuration on how to use other Chrome-based browsers (I have Google Canary, Vivaldi, & Brave installed, not excited about installing browser # 7).

TIA :)

**Comment by JonnyBurger** [comment]
Agree. This behavior is actually inherited from Puppeteer, and we want to inline it to make it better.
Another similar problem is #904 that those binaries don't support `<Video>`, so to solve 2 problems at a time, we should supply our own Chrome binaries for all platforms.

Workaround for now is to of course install Chrome, if you have it but it is not recognized, you can help us by adding it to the list of local browser executables: https://github.com/remotion-dev/remotion/blob/main/packages/renderer/src/get-local-browser-executable.ts

**Comment by tomByrer** [comment]
> Workaround for now is to of course install Chrome

Should I add to `local browser executables` Chrome Canary, Edge, Brave, & other Chromium based browsers?
Or too much support headaches? (which would be a fair response)

**Comment by JonnyBurger** [comment]
We'd appreciate that actually 🙌🏼

**Comment by tomByrer** [comment]
Good news, Brave Beta works to build videos!
Bad news, I could not get Canary nor Edge to work
```js
            process.platform === 'win32'
                //FIXME local Chrome Canary
                ? '%USER%\\Local\\Google\\Chrome SxS\\Application\\chrome.exe'
                : null,
            process.platform === 'win32'
                // Brave Beta
                ? 'C:\\Program Files\\BraveSoftware\\Brave-Browser-Beta\\Application\\brave.exe'
                : null,
            process.platform === 'win32'
                //TEST Brave Stable
                ? 'C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe'
                : null,
            process.platform === 'win32'
                //FIXME Edge Stable
                ? '"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"'
                : null,
```
I found logging the used EXE helpful:
```js
const ensureLocalBrowser = async (browser, preferredBrowserExecutable) => {
    const status = getBrowserStatus(mapBrowserToProduct(browser), preferredBrowserExecutable);
    if (status.type === 'no-browser') {
        console.log('No local browser could be found. Downloading one from the internet...');
        await (0, install_1.downloadBrowser)();
    } else {
        console.log('render using', status.path)
    }
};
```

**Comment by JonnyBurger** [comment]
Super nice!
I'm happy to add everything, though I think we cannot resolve `%USER%` like that Node.JS.
Will `path.join(os.homedir(), "Local\\Google\\Chrome SxS\\Application\\chrome.exe")` resolve the right directory?

**Comment by tomByrer** [comment]
I forgot the AppData:
```js
const os = require('node:os');
//...
os.homedir() + "\\AppData\\Local\\Google\\Chrome SxS\\Application\\chrome.exe"
```
works fine!

**Comment by tomByrer** [comment]
I'm wondering if abstracting getting browser paths out to a separate package would be helpful?  Could also use a list of verified browsers installed with [remotion versions](https://github.com/remotion-dev/remotion/issues/1040) to help users/bug-fixers.

**Comment by JonnyBurger** [comment]
Better late than never, #2546 solves this
