### ISSUE TITLE
backgroundColor don't change

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#1054]
# Bug Report 🐛

I'm testing out changing the background color, but seems not to work.
https://github.com/tomByrer/remotion-simple-demo/blob/master/src/HelloWorld.jsx#L22

In Brave & Firefox *Private* window, the HelloWorld background is transparent.
In Firefox normal view, the background is black, though the small previews (icons in the upper-left & start of the component tracks are white (or what ever backgroundColor I hardcode).

I have edited version of more or less the same code that the backgroundColor changes fine.  Unsure why in my remotion-simple-demo it doesn't?

cheers

**Comment by JonnyBurger** [comment]
You're right, this is a bug surfaced in Remotion v3.0.18 and already fixed in 3.0.19!
Sorry for not mentioning this in the release notes!

`npx remotion upgrade` will fix it!

**Comment by tomByrer** [comment]
Oh thanks, & that fixes a rendering bug I thought I found.

For some reason I thought `pnpm i` upgrades, but I guess I need to do `pnpm up`.

**Comment by JonnyBurger** [comment]
`pnpm i` does not upgrade,
`pnpm up` upgrades everything,
`npx remotion upgrade` upgrades only Remotion. I recommend the last one, it even works with pnpm!
