### ISSUE TITLE
Additional Timeline Scrubbing Controls

### ISSUE THREAD

**Issue by Bardent** [remotion-dev/remotion#1058]
As an alternative to space bar causing the timeline scrubber to pause at its current position, use enter to pause playback and return the scrubber to where it was last played from.

# Feature Request 🛍️

Say the timeline scrubber is currently on frame 50 - the user hits space/enter and playback starts. At frame 200, if the user hits space playback is paused and the scrubber now sits at frame 200. If the user were to hit enter instead, playback would stop and the scrubber would return to frame 50.

## Use Case

This is useful when trying to find the exact time you would like video elements to start, especially when trying to line things up with audio. But hitting enter the user can hear playback and decide if that was the right spot or not. If they hit enter again it returns the scrubber to where they played from so the user can easily note what frame it was. Additionally, if minor adjustments are needed, the user can then simply use the arrow keys to scrub a couple of frames forward or back and then repeat to see if the new position is correct.

If you would like to see an example see how scrubbing is handled in Sony Vegas and check the difference between using space and enter keys.

**Comment by tomByrer** [comment]
So basically set up a loop?

It would be handy!

Workaround: Make a custom component that wraps a [<Sequence>](https://www.remotion.dev/docs/sequence#trim-start) to trim the start & end times.

**Comment by JonnyBurger** [comment]
I'm okay with this, adding it to the roadmap!
It's different from a loop as I understand, for looping a certain part of a video, you can use the In/Out markers feature.
