### ISSUE TITLE
"Open in VS Code" is slow

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1059]
I wonder why there is a 10sec delay for that!
When creating a new video

**Comment by tomByrer** [comment]
I've use it only 1 time per 10 hours of coding; I usually have the file(s) open already that broke the code, since I just broke it ;)

**Comment by JonnyBurger** [comment]
Investigated a bit and the curlprit was using the `x86` version of Node.JS on my M1. When changing to the ARM version, it's super snappy!
