### ISSUE TITLE
Download Chromium automatically on ARM

### ISSUE THREAD

**Issue by FelippeChemello** [remotion-dev/remotion#1061]
When running Remotion on ARM architecture for the first time, it shows that chromium isn't available and should be installed manually, however it is already available to lambda, that runs on ARM.

Maybe it should be added to install/build script and download automatically during install/build, instead of throwing error.

**Comment by JonnyBurger** [comment]
Good idea, relevant issue as well: #904 

Are you referring to Linux on ARM or Windows on ARM?

**Comment by tomByrer** [comment]
> I've tested on Linux

Local machine or remote?  If local, or as a workaround, can you [declare a local browser to use](https://github.com/remotion-dev/remotion/issues/1053)?  One advantage; use a beta browser version.

**Comment by JonnyBurger** [comment]
WIP with #1066

**Comment by JonnyBurger** [comment]
Also noting this: On Ubuntu 20.04, by default it will do the wrong thing and not download a browser that is supported.
