### ISSUE TITLE
`getComposition` api in `@remotion/renderer` not working as expected on ec2 instance

### ISSUE THREAD

**Issue by AbdulBsit** [remotion-dev/remotion#1087]
# Bug Report 🐛
Upgrading remotion to v3, every thing work like a charm locally in my machine, but when i deployed every thing to windows ec2 instance, `getComposition` not work as expected, it wait too long for a server to start to `getComposition` from webpack (downloaded on ec2 ) and finally throws the error ```net::ERR_ADDRESS_INVALID at http://localhost:0/index.html```
It seems related to ports, I tried passing port as option in `getComposition` method, but then it says port not available, 
where as i am no where using that port.
May be it is something specific to ports on ec2, I don' know, Please help me out :)

**Comment by JonnyBurger** [comment]
Hey Abdul!

It is a problem with port selection where none of the ports between 3000 and 3100 are available. I now changed it so it does not default to port 0 if none are available.

I also tried to reproduce by spinning up a `Windows_Server-2019-English-Full-Base-2022.06.15` instance on AWS, and running the following Node.JS script on it: 

```ts
const {RenderInternals} = require("@remotion/renderer")

RenderInternals.getDesiredPort(undefined, 3000, 3100).then(port => console.log(port))
```

Which would log `3000`.

I also ran `npm init video` on the VM using Remote Desktop and it was able to render time.

Can you share more details that could be relevant, such as Windows image and security group configuration? Does the EC2 instance allow port binding? These are my security group rules:

![image](https://user-images.githubusercontent.com/1629785/177117089-27f88bd9-15d8-48d1-8398-4a03d5c6681b.png)

**Comment by AbdulBsit** [comment]
@JonnyBurger 
**I narrowed down further behaviour, It is happening because of this timeout, I try after commenting it, It starts working** https://github.com/remotion-dev/remotion/blob/4d42381b4a0db42b4e3db48a92c512105ba356db/packages/renderer/src/get-port.ts#L16

Can we increase it a lil bit more, `1100` works fine, or I can submut a pull request regarding adding option for **timeout to check port availability** , Suggestion for naming and is it necessary or not will be appreciated!

**Comment by JonnyBurger** [comment]
Thanks a lot for pinning it down! I increased the timeout to 3000 now.
This should not make things slower I hope, since if the OS is responsive, it responds eventually with nothing or response.

I'm gonna release a new version now, let me know if it helps!
