### ISSUE TITLE
Player won't work when using Audio tags

### ISSUE THREAD

**Issue by ruspaull** [remotion-dev/remotion#1092]
# Bug Report 🐛

`@remotion/player` will throw an error and won't start when you are using an `<Audio>` tag in your components: `Uncaught Error: No video config found. You are probably calling useVideoConfig() from outside the component passed to <Player />`

Sample reproduction code:

```
import { Player } from '@remotion/player';
import { Audio } from 'remotion';

export const MyComp: React.FC<{ text: string }> = ({ text }) => {
  return (
    <div>
      <Audio src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" />
      Hello {text}!
    </div>
  );
};

export const App: React.FC = () => {
  return (
    <Player
      component={MyComp}
      inputProps={{ text: 'World' }}
      durationInFrames={1000}
      compositionWidth={1920}
      compositionHeight={1080}
      fps={30}
      style={{
        width: 1280,
        height: 720,
      }}
      controls
    />
  );
};
```

If you remove the  `<Audio>` tag, the player will work just fine

**Comment by JonnyBurger** [comment]
Hey Rus!

That looks like a Remotion version mismatch between remotion and @remotion/player.

Do you see a warning in the console and are you able to resolve it?

**Comment by ruspaull** [comment]
@JonnyBurger that was it! amazing! Thanks for the prompt help
