### ISSUE TITLE
`notifyAssetIsDownloaded` calls listeners before marking files as downloaded

### ISSUE THREAD

**Issue by ptrkcsk** [remotion-dev/remotion#1109]
# Bug Report 🐛

in a video which sequences the same media multiple times, i frequently get the following error :

```
TypeError: Cannot read properties of undefined (reading 'split')
    at getTemporaryOutputName (/project/node_modules/@remotion/renderer/dist/ensure-presentation-timestamp.js:15:23)
    at ensurePresentationTimestamps (/project/node_modules/@remotion/renderer/dist/ensure-presentation-timestamp.js:44:26)
    at extractFrameFromVideoFn (/project/node_modules/@remotion/renderer/dist/extract-frame-from-video.js:162:76)
    at /project/node_modules/@remotion/renderer/dist/p-limit.js:17:37
    at run (/project/node_modules/@remotion/renderer/dist/p-limit.js:17:49)
    at /project/node_modules/@remotion/renderer/dist/p-limit.js:26:26
    at /project/node_modules/@remotion/renderer/dist/p-limit.js:35:75
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

when this happens, it's because [`downloadAsset`](https://github.com/remotion-dev/remotion/blob/v3.0.30/packages/renderer/src/assets/download-and-map-assets-to-file.ts#L138) resolves to `undefined` [here](https://github.com/remotion-dev/remotion/blob/v3.0.30/packages/renderer/src/offthread-video-server.ts#L76)

it looks to me like the problem is that [`notifyAssetIsDownloaded`](https://github.com/remotion-dev/remotion/blob/v3.0.30/packages/renderer/src/assets/download-and-map-assets-to-file.ts#L54) [calls the `listeners` callbacks before marking the files as downloaded](https://github.com/remotion-dev/remotion/blob/v3.0.30/packages/renderer/src/assets/download-and-map-assets-to-file.ts#L71-L91), thus `hasBeenDownloadedMap[src] === undefined` [here](https://github.com/remotion-dev/remotion/blob/v3.0.30/packages/renderer/src/assets/download-and-map-assets-to-file.ts#L49)

to reproduce :

1. clone [ptrkcsk / remotion-sequence-video](https://github.com/ptrkcsk/remotion-sequence-video)
1. build the video several times until it fails
    ```sh
    for i in {1..10}; do npm run build; done
    ```

**Comment by JonnyBurger** [comment]
Hi Patrik!

Thanks a lot for the very good reproduction and sorry for the bug! I believe this is is fixed in #1106, but was not yet released. I just released 3.0.31! 10 renders of your repo seem to render out fine now.
