### ISSUE TITLE
Render sometimes failing with ffmpeg/ffprobe exit code 1

### ISSUE THREAD

**Issue by AbdulBsit** [remotion-dev/remotion#1116]
**Problem**

ffprobe exits with code 1 as no file at location exist.`C:\Users\ADMINI~1\AppData\Local\Temp\2\remotion-assets-dirfw0701mg13\371949071995914.mp4: No such file or directory`  
My question is why ffprobe is searching at this location while I have passed the output location of video, also sometimes it renders fine with no error means it is able to find this file, but it is so random behaviour, I don't  know why it is not able to find the file may be it is clearing the file before hand, may be you could help to make my render consistent.

My output location in `renderMedia` API is `C:\code\buzzle-remotion-service\renders\EbTYiJ7PF`

**Additional Details**

This error logs contains `ffprobe` error, some renders failed due to the same error but with `ffmpeg`

**Logs**

```
... 
29 | 7/14/2022, 5:50:23 PM: [EbTYiJ7PF] render progress 81% ...
30 | 7/14/2022, 5:50:47 PM: [EbTYiJ7PF] render progress 94% ...
31 | 7/14/2022, 5:50:55 PM: [EbTYiJ7PF] render progress 98% ...
32 | 7/14/2022, 5:51:00 PM: [EbTYiJ7PF] Render Completed in nullms
33 | 7/14/2022, 6:11:02 PM: [EbTYiJ7PF] Got error while rendering video=> Command failed with exit code 
1: ffprobe -v error -show_entries stream=channels:format=duration -of default=nw=1 
C:\Users\ADMINI~1\AppData\Local\Temp\2\remotion-assets-dirkwgikb710o\6854792297817767.mp4 
C:\Users\ADMINI~1\AppData\Local\Temp\2\remotion-assets-dirkwgikb710o\6854792297817767.mp4: No such file or directory
```

**Comment by AbdulBsit** [comment]
I just compare the time in logs, it seems it freez/stuck for sometime and when resumed files got cleared at that location, `line 32` time is `5:51` and
`line no 33` is at `6:11` , its been freezed for almost `20 minutes`
```
32 | 7/14/2022, 5:51:00 PM: [EbTYiJ7PF] Render Completed in nullms
33 | 7/14/2022, 6:11:02 PM: [EbTYiJ7PF] Got error while initalizing video rendering => Command failed with exit code 
```

**Comment by JonnyBurger** [comment]
Hi @AbdulBsit!

Sorry for the long time to respond to the issue.

I thought this was fixed in a recent release, can you confirm that the version of `@remotion/renderer` is also up to date with the `remotion` version?

You can best confirm this by pasting the output of `npx remotion version`.

If provided, I'll investigate this tomorrow!

**Comment by AbdulBsit** [comment]
Hey, @JonnyBurger , I am using `3.0.31`, which i think is the latest

**Comment by JonnyBurger** [comment]
@AbdulBsit

1. Sorry for being sticky with it - is the `@remotion/renderer` package also updated to that version?
I ask because there are often version mismatches and a similar bug got fixed very recently.

2. If that is being the case that you are on 3.0.31 - are you able to provide a snippet for how you use `renderMedia()` or other SSR APIs?

So far I'm not sure where to investigate, so it'd be good to see how you wrote the code and which codec you used.

**Comment by AbdulBsit** [comment]
**1) - Dependencies as in package.json**

```
"@remotion/bundler": "^3.0.31",
 "@remotion/renderer": "^3.0.31"
 "remotion": "^3.0.31"
 ```

**2) - `renderMedia`  Usage** - 

```
....
const finalOutput = job?.output || path.join(tmpDir, 'output.mp4');
        job.output = finalOutput
        const ffmpegBinary = await getBinary(settings)
        await renderMedia({
            codec: job?.template?.codec??"h264",//default to h264
            composition: video,
            outputLocation: finalOutput,
            serveUrl: bundled,
            onStart: () => settings?.logger?.log(`[${job.uid}] Started rendering frames...`),
            inputProps: job?.template?.inputProps,
            imageFormat: job?.template?.imageFormat,
            onProgress: ({ renderedFrames, encodedDoneIn, encodedFrames, renderedDoneIn, stitchStage }) => {
                if ((renderedFrames + encodedFrames) % 40 === 0) {
                    let progress = ((((renderedFrames + encodedFrames) / (2 * video.durationInFrames)) * 100)).toFixed();
                    settings?.logger?.log(`[${job.uid}] render progress ${progress}% ... `)
                    job?.onRenderProgress && job?.onRenderProgress(job, progress);
                }
                // Time to create images of all frames
                if (renderedDoneIn !== null) {
                    settings?.logger?.log(`[${job.uid}] Encoding...`);
                }
                // Time to encode video from images
                if (encodedDoneIn !== null) {
                    settings?.logger?.log(`[${job.uid}] Encoded Completed in ${encodedDoneIn} ms`);
                }

            },
            dumpBrowserLogs: settings.debug,
            ...(job?.template?.frameRange ? { frameRange: job?.template?.frameRange } : {}),
            ...(ffmpegBinary ? { ffmpegExecutable: ffmpegBinary } : {}),
            onDownload: (src) => {
                settings?.logger?.log(`[${job.uid}] Downloading asset => ${src}`)
            },
            pixelFormat: 'yuv420p',
            // proResProfile:"hq",
            overwrite: true
        })
....
```

**Comment by JonnyBurger** [comment]
Hi @AbdulBsit! 

Thanks - I opened #1144 to hopefully fix it. Release is going to come out today - I'd be happy if you test it and if it happens again, can you log `err.stack` instead of `err.message`? I'd be curious to know how this scenario happened exactly!

Hope the issue gets just fixed though 😊

**Comment by AbdulBsit** [comment]
Hii, @JonnyBurger 

**Stack trace**

```
19/07/2022, 14:06:08: [11ZHS0-2b] Got error while initalizing video rendering => Error: Command failed with exit code 1: ffprobe -v error -show_entries
 stream=channels:format=duration -of default=nw=1 C:\Users\ADMINI~1\AppData\Local\Temp\2\remotion-assets-dirzxpebu7dhz\7477065087296069.mp4
C:\Users\ADMINI~1\AppData\Local\Temp\2\remotion-assets-dirzxpebu7dhz\7477065087296069.mp4: No such file or directory
at makeError (C:\code\buzzle-remotion-service\node_modules\execa\lib\error.js:60:11)
at handlePromise (C:\code\buzzle-remotion-service\node_modules\execa\index.js:118:26)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async getAudioChannelsAndDurationUnlimited (C:\code\buzzle-remotion-service\node_modules\@remotion\renderer\dist\assets\get-audio-channels.js:23:18)
```

**Comment by JonnyBurger** [comment]
Thanks a lot! Don't see any more information from it unfortunately, well hope the PR works!

**Comment by JonnyBurger** [comment]
#1177 Will clean up everything and leave no traces!
