### ISSUE TITLE
3.1.0 upgrade only renders the first frame of a video for the video's duration

### ISSUE THREAD

**Issue by hayley** [remotion-dev/remotion#1119]
# Bug Report 🐛

I have 3 videos I've tested this on so far. I originally thought that it was just rendering a blank video, but with further testing, I'm almost positive that the issue is just that it's rendering whatever is the first frame of the video for the entire length of the video. So if there's a fade-in initially, that would give the impression of a blank video.

Renders are working for me fine on 3.0.31, but after an `npm upgrade` to 3.1.0, I have the first frame render issue. It appears that audio is unaffected by this (and plays fine throughout the video), but 2 of the videos I tested on are silent.

This is happening for me on Void Linux (AMD CPU) and an M1 Mac.

Let me know if I can provide any other details.

Thanks for all your hard work on this project!

**Comment by JonnyBurger** [comment]
Thanks for the excellent reproduction steps and for filing! 🙌
