### ISSUE TITLE
puppeteer issue : i cant render out my video facing this error: Chrome headless doesn't launch on Windows

### ISSUE THREAD

**Issue by Ranjbar1** [remotion-dev/remotion#1125]

**Comment by JonnyBurger** [comment]
Hi @Ranjbar1, thanks for filing the issue!

This error does not seem to come from the Remotion codebase, can you provide the full error message you see in the terminal?

As of now, there is not enough information to investigate unfortunately.

**Comment by JonnyBurger** [comment]
Closing because of no response.
