### ISSUE TITLE
When I use the everynthframe option, I cannot output dynamic GIF

### ISSUE THREAD

**Issue by gexin1** [remotion-dev/remotion#1128]
# Bug Report 🐛
[get-duration-from-frame-range.ts](https://github.com/remotion-dev/remotion/blob/74446abd36a95eada61f063fdf642cb6f47a73e0/packages/renderer/src/get-duration-from-frame-range.ts#L1)
when i set everynthframe=2 ,getFramesToRender  function will filter out some frames，
https://github.com/remotion-dev/remotion/blob/74446abd36a95eada61f063fdf642cb6f47a73e0/packages/renderer/src/render-frames.ts#L232
paddedIndex will be 00 02 04 06
https://github.com/remotion-dev/remotion/blob/74446abd36a95eada61f063fdf642cb6f47a73e0/packages/renderer/src/render-frames.ts#L270
will save frame img element-00.jpeg  element-02.jpeg  element-04.jpeg element-06.jpeg 

When ffmpeg is used to compose pictures, only the first picture is used when ffmpeg cannot find consecutive pictures
```
 ffmpeg -r 30 -f image2 -s 200x200 -start_number 0 -i element-%02d.jpeg -c:v gif -crf 23 -pix_fmt yuv420p -b:v 1M -c:a aac -b:a 512K -map_metadata -1 -y D:/VideoToGif4.gif
```

## solve the problem
* We make pictures named consecutively，but it may affect https://github.com/remotion-dev/remotion/blob/74446abd36a95eada61f063fdf642cb6f47a73e0/packages/renderer/src/stitch-frames-to-video.ts#L278  

* Can ffmpeg  solve this problem？

**Comment by JonnyBurger** [comment]
Good catch! Will try to solve this tomorrow.
