### ISSUE TITLE
Visibility after few frames

### ISSUE THREAD

**Issue by RobinLindhout** [remotion-dev/remotion#1143]
How can i set my element visible when a few frames has past?

Like a delay, but instead of transforming I want the visibility to change

Example: 
![Schermafbeelding 2022-07-19 om 09 48 14](https://user-images.githubusercontent.com/79744544/179696118-85216a8e-c012-4a99-a827-e3fb40273c5f.png)

**Comment by JonnyBurger** [comment]
Hey Robin! 3 possibilities:

- Use a `<Sequence>`: https://www.remotion.dev/docs/sequence
- Animate the `opacity` CSS style property
- Render something conditionally: `frame > 10 ? <div>visible</div> : null`
