### ISSUE TITLE
Cannot find module 'react/jsx-runtime' in AWS lambda

### ISSUE THREAD

**Issue by prabhatmyadbox** [remotion-dev/remotion#1153]
Hi Jonny,
Firstly, thanks for building this awesome tool. It is just amazing.

Well, I'm trying to use `renderMediaOnLambda` on a AWS lambda function. My project is a mono-repo, so I use `serverless-jetpack` to handle dependency hoisting issue. I'm currently facing 2 issues:

1. I am unable to package the function using `serverless package` command, as it does not even package in over 5 mins for some reason.

2. As a workaround, I've created a lambda layer of @remotion/lambda package and included it in the function. However, when I invoke the function I get following Invoke Error:
```
"errorType": "Runtime.ImportModuleError",
"errorMessage": "Error: Cannot find module 'react/jsx-runtime'
```

runtime: `nodejs14.x`
serverless: `v3.21.0`

Any suggestion is highly appreciated. 

Thanks!
Prabs

**Comment by JonnyBurger** [comment]
Hi Prabhat!
Thanks a lot for the praise!

The @remotion/lambda package imports some other stuff automatically as well such as React and CLI stuff.

What you can do is `import {renderMediaOnLambda} from "@remotion/lambda/client";` to only import the functions necessary! See also: https://www.remotion.dev/docs/lambda/light-client

I think this will solve your problem, so I am going to close the issue right away. Let me know if not!

**Comment by prabhatmyadbox** [comment]
Hi Jonny 
Yes, I am importing from `@remotion/lambda/client`.

**Comment by JonnyBurger** [comment]
I see - even that has a dependency on Remotion, which requires React. Can you solve the issue by installing React?

**Comment by prabhatmyadbox** [comment]
I've tried installing React and @types/react as well. No luck.

Here's the stack trace from the error, if it helps.

<img width="726" alt="Screen Shot 2022-07-21 at 10 54 17 pm" src="https://user-images.githubusercontent.com/36719525/180218252-511117ad-634a-4fa4-9790-0a944260fede.png">

Thanks

**Comment by prabhatmyadbox** [comment]
I've finally resolved the issue. I had to install React and React-dom (thought I would chuck this in as well) in the lambda layer I created for Remotion packages.

Thanks!
