### ISSUE TITLE
Playback for Sequences

### ISSUE THREAD

**Issue by RobinLindhout** [remotion-dev/remotion#1155]
How can i set the playbackrate for 1 sequence?

**Comment by JonnyBurger** [comment]
Hi @RobinLindhout!

You cannot set it in there - but you can play around with `useCurrentFrame()`!

Play the video twice as fast using `const frame = useCurrentFrame() * 2`.
Or twice as slow using `const frame = useCurrentFrame() / 2`.

**Comment by RobinLindhout** [comment]
Okay get it, but doesn't work with my current code, Tried to save some work but I have to do it anyways I think ;)
