### ISSUE TITLE
Attempting to play audio with react-speech-kit doesn't work

### ISSUE THREAD

**Issue by deeayeen** [remotion-dev/remotion#1182]
Using https://github.com/MikeyParton/react-speech-kit, attempting to play any audio yields no result.

Is the only way to play audio using the \<Audio /\> tag? That would assume requiring an audio file

**Comment by deeayeen** [comment]
Additionally, when using the \<Audio /\> tag, the console shows the following error:

```get-audio-data.js:34 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu```

**Comment by JonnyBurger** [comment]
Hi Dan,

yes, the only way is to play using an `<Audio>` tag. You can also pass a buffer into the audio tag, but that does not work with react-speech-kit. The browser generally does not allow you to obtain a buffer of the spoken text.

We recommend the TTS template: `npx create-video --tts` (https://github.com/FelippeChemello/Remotion-TTS-Example/generate)
