### ISSUE TITLE
Require undefined break the core remotion dependencies

### ISSUE THREAD

**Issue by rodrigogollo** [remotion-dev/remotion#1200]
# Bug Report 🐛

## I couldn't replicate the bug, but i was trying to require a video source file that doesn't exist (undefined), using the following:

![image](https://user-images.githubusercontent.com/28308024/182955362-ed756b88-b282-430d-a03c-c7b105d75f69.png)

## After this bug, the Remotion Preview gave me the following exception: 

![image](https://user-images.githubusercontent.com/28308024/182956695-be8b6bc8-d98c-4487-a299-ea4fae64266c.png)

## It seems that the tsconfig.json on these three folders is unable to find the modules: **core, bundler, renderer and player.**

![image](https://user-images.githubusercontent.com/28308024/182953111-b92f522e-2a0e-4d5b-8c35-3ccf32245570.png)

**Comment by JonnyBurger** [comment]
Hi @rodrigogollo! Thanks for the report, I can confirm the bug and am putting in a fix in place so that the server does not crash anymore.
