### ISSUE TITLE
Incorrect sequence name on timeline when using default exported component

### ISSUE THREAD

**Issue by JakubekWeg** [remotion-dev/remotion#1213]
# Bug: Incorrect sequence name on timeline when using default exported component 🐛

Hi
When having sequence:
```tsx
<Sequence from={10}>
    <p>anything</p>
</Sequence>
```
I get **untitled** name
![image](https://user-images.githubusercontent.com/20194971/183688122-f803a470-a866-4ce1-9cdc-08f11e1221c7.png)
Which is fine, but having sequence like that:

```tsx
<Sequence from={10}>
    <Foo />
</Sequence>
```
where Foo is
```tsx
export default () => {
    return <p>anything</p>
}
```
I'm getting
![image](https://user-images.githubusercontent.com/20194971/183688410-7e1b109a-3340-46e1-a089-0adeabaaa613.png)
which is probably not what we want, better keep **Untitled** here

**Comment by JonnyBurger** [comment]
Thanks a lot for reporting this!
