### ISSUE TITLE
Interpolate multiple values causes Lambda Render to fail

### ISSUE THREAD

**Issue by rodrigogollo** [remotion-dev/remotion#1219]
# Bug Report 🐛

When using interpolate with more than 2 values, like the following: 

![image](https://user-images.githubusercontent.com/28308024/184037620-18dbb764-5f1f-4a35-917c-34e2d6c1764f.png)

Prevent Lambda to Render, giving the following message:

![image](https://user-images.githubusercontent.com/28308024/184037944-853cebc0-cfb4-4c8d-bc3b-bba00a871562.png)

**Comment by JonnyBurger** [comment]
Hi!

This hints towards `durationInFrames` actually being `-22239`. Are you calculating this dynamically somehow or taking it directly from `useVideoConfig`?

**Comment by rodrigogollo** [comment]
Hey, yeah i'm just using the default values from useVideoConfig and useCurrentFrame.

![image](https://user-images.githubusercontent.com/28308024/184176567-4d223fd8-06ca-46ec-b41b-51e6322a6087.png)

**Comment by JonnyBurger** [comment]
Hi Rodrigo, many apologies for the late response!
It's weird, I have no clue! This is a one of a kind issue that I didn't hear about before, but something is definitely wrong from our side.

- I suppose you are nesting `<Clip>` inside a `<Sequence>`. Are you able to show a bit more of the parent so we can see how the `<Sequence>`'s are structured?
- Can you run a render on the Lambda CLI by adding the flag `--log=verbose` and log `	console.log(useContext(Internals.SequenceContext))` inside the component? That will allow us to see how that negative number is calculated.

**Comment by rodrigogollo** [comment]
Hey Johnny, you are correct, the `<Clip>` is nested inside a `<ClipList>` that maps each `<Clip>` inside a `<Sequence>`: 
Maybe my Video `durationInFrames` is wrong because i do some calculations to get the exact time to render each `<Clip>`

![image](https://user-images.githubusercontent.com/28308024/185966174-6886e61f-4ac5-4be6-8e61-bf7cba729e1b.png)

As for the Lambda CLI render, i tried to do what you told me to, but it didn't log the `console.log(useContext(Internals.SequenceContext))`. 

I think it is because the error occur at the Invoking Lambdas step, or i did something wrong idk.

![image](https://user-images.githubusercontent.com/28308024/185967110-20ebca4c-ab17-4b5b-8884-b70bed2ab824.png)

![image](https://user-images.githubusercontent.com/28308024/185966416-65830194-e0da-4908-bb0e-cb4e9dc7c2ba.png)

**Comment by JonnyBurger** [comment]
Thanks! I'll definitely investigate a bit more and try to reproduce that.

You can put the console.log() one line above the `interpolate` to see the log if you wanna help 🙏

**Comment by rodrigogollo** [comment]
I tried the console.log above the interpolate, but still don't print the message in the console after the lambda render execution. 

Yet, using the React Developer Tools, it seems that the durationInFrames are fine: 

![image](https://user-images.githubusercontent.com/28308024/185975822-3506e613-7acb-4cf5-8b77-33f549ebc513.png)

**Comment by JonnyBurger** [comment]
Sorry I should have mentioned that you can click the CloudWatch link that was printed to see the actual `console.log`'s!
Thanks for providing the logs of the React DevTools, also helpful!

**Comment by rodrigogollo** [comment]
Hey Jonny, i didn't know about the CloudWatch, sorry for that. This is what i got from the Internals on the logs:

![image](https://user-images.githubusercontent.com/28308024/186174499-539cfa7f-6e3e-4bec-ac37-ea8dd5dd588b.png)

It seems to me kinda random when the durationInFrames is negative to some, and not to others.

![image](https://user-images.githubusercontent.com/28308024/186176342-16fdca45-511f-411c-ae46-3def41254268.png)

**Comment by JonnyBurger** [comment]
I was finally able to reproduce it! Turns out the duration can change during the render, which is a stupid behavior of Remotion. I put in a fix and pretty certain that should solve some problems 🎉 A new release will some out in the next hour.
