### ISSUE TITLE
Player ignores Audio.src change once started

### ISSUE THREAD

**Issue by slowbaker** [remotion-dev/remotion#1228]
# Bug Report 🐛

Since version 3.1.5, it's no longer possible to change the audio source when the Remotion Player once started. The player currently needs to reach the end and start from the beginning (loop=true), so the new audio track is picked up. 

The previous behavior was that you could change the audio on the fly without pausing the player.

**Comment by JonnyBurger** [comment]
Thanks a lot! Fix initiated!
