### ISSUE TITLE
Player audio hiccups caused by audio tag updates

### ISSUE THREAD

**Issue by slowbaker** [remotion-dev/remotion#1232]
# Bug Report 🐛

I have a composition with background music and a sequence of individual audio tracks. Version 3.1.5 introduced a bug in which you can clearly hear when audio tags are being remounted (which causes a short pause).

```
|------------------- background music ------------------|
|-- audio 1 --|-- audio 2 --|-- audio 3 --|-- audio 4 --|
              ↑             ↑             ↑
```

Looking into the Chrome dev tools during playback, I can see that all audio tags are being updated on each transition, including the background audio, which causes this "hiccup". 

Before v3.1.5, Remotion updated only adjacent tracks in the DOM, which resulted in a smooth playback (of the background music).

**Comment by JonnyBurger** [comment]
Thanks! I acknowledge this problem and will look for a solution soon.
