### ISSUE TITLE
Audio delay

### ISSUE THREAD

**Issue by RobinLindhout** [remotion-dev/remotion#1240]
How can i play my audio in a component after te component played for, let say 60 frames?
![Schermafbeelding 2022-08-16 om 12 02 57](https://user-images.githubusercontent.com/79744544/184853291-e9b62219-b8a7-4c43-8992-2f9e790be411.png)

I want te audio to start after the red bar
![Schermafbeelding 2022-08-16 om 12 03 17](https://user-images.githubusercontent.com/79744544/184853359-8f7087a7-68bd-4d31-9441-b94079cdf476.png)

**Comment by JonnyBurger** [comment]
Hi Robin!

You can do so using

```ts
<Sequence from={60}>
	<Audio src={bell} />
</Sequence>
```
