### ISSUE TITLE
Allow to pass FFMPEG bitrate parameters

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1247]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24167%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1247)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @Slashgear and up for taking!

---

## Problem

User story from Band on Discord:

> I have a related use case. We are also publishing to Instagram via the ig-user/media API (https://developers.facebook.com/docs/instagram-api/reference/ig-user/media#reel-specifications). We’ve had a lot of flakiness with IG throwing vague errors for video uploads in the past, so we have validators that catch discrepancies between the IG specs and the video we are attempting to upload.
> While the test videos rendered by remotion seem to upload fine, The team is hesitant to remove any validators, since we can point to Instagram as being the source of the issues if we are matching their requirements. It would be convenient if I could add -ab 128 to the ffmpeg call so it passes our validation and everyone is happy.

## Hacktoberfest Acceptance criteria

- Allow to customize `-b:v` and `b:a` parameters using a new option for `stitchFramesToVideo()` and `renderMedia()`
- If using `renderMediaOnLambda()`, the option should also be passed
- If using the `npx remotion lambda render` or the `npx remotion render` commands, new command line flags should be introduced to use the feature from the CLI as well.
- All APIs that accept the parameter should have their API page updated.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $167.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($167.00)

### Submitted pull Requests
- [#1380 feat(ffmpeg): add possibility to override video output bitrate](https://issuehunt.io/r/remotion-dev/remotion/pull/1380)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by gexin1** [comment]
[	const task = execa(options.ffmpegExecutable ?? 'ffmpeg', ffmpegString,](https://github.com/remotion-dev/remotion/blob/df56069c6700389c8c1a988c066c15f0f718fd5a/packages/renderer/src/stitch-frames-to-video.ts#L367)
Can add a hook so that developers can control the final ffmpeg command，
Is this proposal feasible

**Comment by Slashgear** [comment]
👋🏻 @JonnyBurger As I almost finish another issue, maybe I could take that one if you want :)

**Comment by JonnyBurger** [comment]
@Slashgear You got it! 🙌

**Comment by Slashgear** [comment]
I will send you a draft PR with my intention and vison about it, we need to discuss what the best solution because for now I am not a big fan how the one I took. Maybe the way we pass params to `ffmpeg` is not clear enough to me.

**Comment by JonnyBurger** [comment]
Fixed by #1380
