### ISSUE TITLE
Introduce a way to benchmark a computer with Remotion

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1250]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24250%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/1250)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @uragirii and is not for the taking.

Have a command where a certain video is rendered with a certain version and remotion reports the time taken so one can test hoe powerful their setup is.

## Acceptance criteria:

- Have a repository with a Remotion video, which contains various Remotion elements (videos, audio, canvas, SVG, HTML, CSS filters such as blur)
- Have a way to run a benchmark with a certain Remotion version and report the time
- Have a way to run with different `concurrency` parameters and compare the time
- Average out the test results over multiple runs and report them in the command line
- Bonus but not required: If you can run the benchmark on your Remotion video, that's awesome

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $250.00)

- [<img src='https://avatars.githubusercontent.com/u/86873911?v=4' alt='mehmetademi' width=24 height=24> mehmetademi](https://issuehunt.io/u/mehmetademi) ($250.00)

### Submitted pull Requests
- [#1358 benchmark remotion](https://issuehunt.io/r/remotion-dev/remotion/pull/1358)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by uragirii** [comment]
Can I work this? I have created a [repo for benchmarking](https://github.com/uragirii/remotion-bench) already.

**Comment by JonnyBurger** [comment]
@uragirii Yes you can! Will respond to your PRs by tomorrow. Awesome stuff 🤗
