### ISSUE TITLE
Blank video (all frames BLACK) is generated for the site deployed using @remotion/lambda Node.JS API

### ISSUE THREAD

**Issue by leocjacob** [remotion-dev/remotion#1251]
# Bug Report 🐛
**Steps to reproduce the issue.**
Step 1: Install remotion using `npm init video` in your local machine.
Step 2: Select the Tailwind project
Step 3: Setup AWS as described here [SETUP AWS](https://www.remotion.dev/docs/lambda/setup)
Step 4: Install @remotion/lambda dependency `npm i @remotion/lambda`
Step 6: Setup environment variables. REMOTION_AWS_ACCESS_KEY_ID & REMOTION_AWS_SECRET_ACCESS_KEY
Step 7: copy the following code to the root folder in **[createVideo.mjs](https://gist.github.com/leocjacob/58a4d8c8941b817cbb35d559c0fe29e6)**
Step 8: Run `node createVideo.mjs`
Step 9: Click on the video link displayed in the terminal.

**Issue**: Blank video (all frames BLACK) is generated in AWS S3.

Screenshot of project creation.
<img width="871" alt="Screenshot 2022-08-22 at 5 52 26 PM" src="https://user-images.githubusercontent.com/41545049/186028890-31b1cc91-da0f-406d-9689-adc7e61fa80e.png">

Screenshot of Running @remotion/lambda Node.JS API in **local terminal**.
<img width="982" alt="Screenshot 2022-08-22 at 6 14 42 PM" src="https://user-images.githubusercontent.com/41545049/186028345-21a68e92-5864-4d1f-94f0-9d9cf9938cff.png">

Video Screenshot
<img width="874" alt="Screenshot 2022-08-22 at 6 13 57 PM" src="https://user-images.githubusercontent.com/41545049/186028404-eb658806-2a89-433c-9d85-2259fe1e551d.png">
[Sample link ](https://s3.us-east-1.amazonaws.com/remotionlambda-ovwh9hu1iw/renders/5qlajip4jj/out.mp4)

**Comment by JonnyBurger** [comment]
Hi @leocjacob!

The problem is that the Lambda APIs require the `webpackOverride` function to be passed. Sorry, we realize that this is not documented well! We added a notice to the README.md, you can follow the new instructions we put there: https://github.com/remotion-dev/template-tailwind/commit/342ec698ec269ff9a785acc6f9b15815866f4e7d

I'm gonna leave this open to also update our homepage to better document this.

**Comment by leocjacob** [comment]
Hi @JonnyBurger , I tried as you said, but there is a problem importing .ts file into .js file. Can you just describe how to execute @remotion/lambda Node.JS API.  I am struggling with the following error.

`(base)  ✘ leocj@Leos-MacBook-Pro  ~/video-project/tailpro   main ±  node createVideo.mjs
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/leocj/video-project/tailpro/src/webpack-override' imported from /Users/leocj/video-project/tailpro/createVideo.mjs
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:416:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:1044:11)
    at Loader.resolve (node:internal/modules/esm/loader:89:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}`

Screenshot of my code.
<img width="697" alt="Screenshot 2022-08-23 at 4 18 45 PM" src="https://user-images.githubusercontent.com/41545049/186257884-b37534f7-04f0-4c39-93d5-4cbd601cac12.png">

**Comment by JonnyBurger** [comment]
Hi @leocjacob!

I that case, you must rename `webpack-override.ts` to `webpack-override.js` and remove the type annotation (`: WebpackOverrideFn`). That should work in both files then.

**Comment by leocjacob** [comment]
Hi @JonnyBurger, Awesome that worked! i have renamed `webpack-override.ts` as `webpack-override.mjs` and made your changes. I am sharing the code if anyone needs it.
[createVideo.mjs and webpack-override.mjs](https://gist.github.com/leocjacob/c9ca53efa248da49b936e6b59ce4f09f)
[webpack-override.mjs](url)
