### ISSUE TITLE
<Sequence.Series> durationInFrames prop is not optional?

### ISSUE THREAD

**Issue by ekeijl** [remotion-dev/remotion#1280]
The [documentation](https://www.remotion.dev/docs/series#seriessequence-) states:

> durationInFrames **(optional)**: For how many frames the sequence should be displayed. Children are unmounted if they are not within the time range of display. By default it will be Infinity to avoid limit the duration of the sequence.

If I understand correctly, the main purpose of `<Series.Sequence>`  is to create a sequence of scenes where you only need to pass `duration` (without a `from` prop). Then how can `durationInFrames` be optional (except for the last scene, maybe)? I think the docs are incorrect here?

# Bug Report 🐛

If I try to do the following, errors will occur:

```
<Series>
	<Series.Sequence layout="none">
		<Title titleText={String(total)} />;
	</Series.Sequence>
	// more <Series.Sequence> elements
</Series>
```

Typescript complains:

```
Property 'durationInFrames' is missing in type '{ children: (string | Element)[]; layout: "none"; }' but required in type '{ durationInFrames: number; offset?: number | undefined; }'.ts(2741)
index.d.ts(4, 5): 'durationInFrames' is declared here.
```
[Source](https://github.com/remotion-dev/remotion/blob/main/packages/core/src/series/index.tsx#L10)

And a console error when using it in the `<Player>`

```
Uncaught Error: The "durationInFrames" prop of a <Series.Sequence /> component must be a number, but you passed a value of type undefined
```

And when passing `durationInFrames={Infinity}`:

```
Uncaught TypeError: The "durationInFrames" prop of a <Series.Sequence /> component must be an integer, but got Infinity.
```

**Comment by JonnyBurger** [comment]
You are completely right, thanks for reporting this!
Currently, `durationInFrames` is required because otherwise it wouldn't make any sense. The only way the durationInFrames property can be omitted or made `Infinity` is if it is the last Sequence in a Series.

For now fixing this by updating the documentation in #1289
