### ISSUE TITLE
Generating last image of a Composition

### ISSUE THREAD

**Issue by Slashgear** [remotion-dev/remotion#1283]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24167%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/1283)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @Slashgear and not for taking!

---

I was playing with the CLI and `still` action to generate image.
Awesome feature 🎉 

I wanted to generate the last frame of my Composition and found no other solution than to pass the correct number to the command. 

## Use Case

```
 remotion still src/index.tsx Example --frame -1
```

## Possible Solution

💡 Negative values of frame could be useful to generate frame relative to the last one.
I could take this subject as a contribution.

## Hacktoberfest Acceptance Criteria
(_edit by @JonnyBurger_)

- Take negative integers in `renderStill()`, `renderStillOnLambda()`, `npx remotion still` and `npx remotion lambda still` and treat them as frames from the back: `-1` means last frame, `-2` means second to last frame etc.
- Keep up the strict validation, e.g. `-200` should not be possible if the duration is only 100 frames.
- Document the feature in the documentation pages of the APIs and commands that accept this option.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $167.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($167.00)

### Submitted pull Requests
- [#1364 feat(render-still): handle negativ frame index](https://issuehunt.io/r/remotion-dev/remotion/pull/1364)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JonnyBurger** [comment]
Good idea! Not gonna implement immediately and think a bit about the right API, but definitely putting this on the roadmap!

**Comment by Slashgear** [comment]
@JonnyBurger Could I take that ?
