### ISSUE TITLE
Experts page lags on scroll

### ISSUE THREAD

**Issue by satelllte** [remotion-dev/remotion#1306]
# Bug Report 🐛

On https://www.remotion.dev/experts page there's a lag when user scrolls it. The lag caused by `background-attachment: fixed;` on https://www.remotion.dev/img/background-hire-page.svg asset as background. 

Reproducible in Chrome 105 / Mac OS 11.4

_I didn't find out yet how to fix it unfortunatelly, so reporting an issue with a bug_

**Comment by JonnyBurger** [comment]
This is a good point, it's most likely because of the background image. @MehmetAdemi Maybe we need to remove the shadow which might be expensive, or if it still causes a lag, we remove it entirely.

**Comment by satelllte** [comment]
@JonnyBurger @MehmetAdemi 
I think it's not about any shadow but about using `background-attachment: fixed` which I believe might be workarounded somehow.

**Comment by satelllte** [comment]
@JonnyBurger @MehmetAdemi
Didn't find anything yet except just making a fixed-position `div` with the background
