### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by reactone** [remotion-dev/remotion#1338]
When running 'yarn start' to run the preview / player I got the following error. Any advice?

**Comment by JonnyBurger** [comment]
Hi @reactone! I don't see it by default, so I suspect it happens with a specific version. Can you run `npx remotion versions` and `node -v` and tell me the output as a first step?

**Comment by reactone** [comment]
It happens no matter which node version Im using. So when I setup the project initially and preview the video it all works. 
Ive tried to add react-movable and then when I try to run preview again using the cli I get this error. I thought its something with the movabkle package itself, so I set up a new project with CRA using the guide on the website -[(https://www.remotion.dev/docs/player/integration)] Again it runs for the first time but gives an error the next time Im trying to run it.Node.js v18.9.0

`node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:607:11)
    at ***/node_modules/@remotion/cli/dist/preview-server/start-server.js:69:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}`

**Comment by JonnyBurger** [comment]
Hi @reactone, thanks for providing more information.
I used Node 18.9.0 and the latest Remotion version and couldn't reproduce the error.

As far as I understand you combine Remotion with Create React App - I suspect they might share ports together and that might cause an error in the Remotion server if the React App talks to Remotion. I improved this somewhat by logging the error in 2f0dcff7e1add24f6b939685ffca945644610d59, so now the error gets logged.

Nonetheless I could not trigger it myself, do you have commands to reproduce?

Regarding your question about the editing interface: We recommend using the [Remotion Player](/docs/player), which has the necessary APIs to build an editing interface around it, but there are currently no pre-made building blocks by us for making e.g. a timeline! We hope to add this in the future.

**Comment by Amatewasu** [comment]
Hi both of you :)

I encountered the same error by forking the TypeScript template and installing the packages:
```
npx create-video --hello-world
yarn install
yarn start
```
I also have node v18.9.0 installed, on Windows 11.

Here's my trace if it can helps:
```
$ yarn start
yarn run v1.22.19
$ remotion preview src/index.tsx
Server ready - Local: http://localhost:3000, Network: http://192.168.56.1:3000
Built in 3029ms
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:607:11)
    at C:\Users\*********\node_modules\@remotion\cli\dist\preview-server\start-server.js:71:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v18.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Have a great day!

**Comment by Amatewasu** [comment]
Ok, I've ran `remotion upgrade` and it fixed the issue!

**Comment by reactone** [comment]
I remember it ran for me the first time, but when I close the terminal and run again it doesn’t. Did it permanently fix the issue?

**Comment by JonnyBurger** [comment]
My belief is that another service in your computer is making a request to localhost:3000 and the Remotion server does not handle it well.

I changed it now so that there is no crash. If this happens again, there will also always be another error message - feel free to open an issue for those ones!
