### ISSUE TITLE
Report slowest frames of renderMedia()

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1344]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24167%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1344)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @uragirii!

There is already a function for finding the slowest chunks inside renderMediaOnLambda(), but it would be useful to measure each single frame in renderMedia() and return the slowest frames so one can optimize the render times of it.

Acceptance criteria:

- Measure the time for each frame and store it in-memory, e.g. in a JavaScript object
- Make sure to free up the memory afterwards to not create a memory leak
- Make `renderMedia()` return an object of which one of the properties is `slowestFrames`, which returns the 10 slowest frames (if there are any)
- In the `cli` package, grab that information, and print the slowest frames using `Log.verbose`
- In the `lambda` package, in `renderer.ts`, log the slowest frames as well.
- Add documentation to `render-media.md` describing the feature and mention the version it's going to be available in (current version + 0.0.1)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $167.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($167.00)

### Submitted pull Requests
- [#1381 Report slowest frames](https://issuehunt.io/r/remotion-dev/remotion/pull/1381)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by uragirii** [comment]
I'd like to work on this 😄

**Comment by JonnyBurger** [comment]
@uragirii I'll make a new rule for Hacktoberfest that you need to finish a PR before tackling the next one! (Will post all rules in a few moments).

I know that this can only proceed if I review the PRs, I will prioritize that tomorrow!

**Comment by uragirii** [comment]
Haha! sure i will finish my pending PRs first then.

**Comment by uragirii** [comment]
@JonnyBurger now that all the other PRs are finished, can i work on this ?

**Comment by JonnyBurger** [comment]
@uragirii Assigned it to you!
