### ISSUE TITLE
`imageFormat`, `maxRetries`, `privacy` should not be mandatory for renderMediaOnLambda()

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1348]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1348)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @uragirii and is not available for taking.

## Acceptance criteria

Acceptance criteria for this PR:

- Have sensible default values
- Mention in docs that properties are optional and since which version
- Mention default values in docs

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)

### Submitted pull Requests
- [#1355 `imageFormat`, `maxRetries`, `privacy` are optional for renderMediaOnMedia](https://issuehunt.io/r/remotion-dev/remotion/pull/1355)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by uragirii** [comment]
Is there a claim process or do I just directly submit the PR?

**Comment by JonnyBurger** [comment]
@uragirii You can reserve this issue, the official start is on October 4th, which is why there is no bounty on it yet, but we don't mind if you submit a PR before and we'll pay it out nonetheless!

**Comment by JonnyBurger** [comment]
Acceptance criteria for this PR:

- Have sensible default values
- Mention in docs that properties are optional and since which version
- Mention default values in docs
