### ISSUE TITLE
volume component of Player is not responsively designed

### ISSUE THREAD

**Issue by UmungoBungo** [remotion-dev/remotion#1352]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24167%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1352)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @Pompette and is not for the taking.

# Bug Report 🐛
When using the Player component in a portrait view, with a narrow width, the volume controller is not responsively designed. Pehaps it should be a vertical control when there is a narrow width?

https://user-images.githubusercontent.com/22192773/193221768-1f8f00d9-2702-4333-829d-3112180e7dbe.mp4

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $167.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($167.00)

### Submitted pull Requests
- [#1356 feat: make volume slider responsive according to player size](https://issuehunt.io/r/remotion-dev/remotion/pull/1356)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by imrishabh18** [comment]
@JonnyBurger I would like to take up this issue. Can you assign this to me please?

**Comment by JonnyBurger** [comment]
@imrishabh18 It was already started by @Pompette unfortunately!
Mind taking another issue with the Hacktoberfest label?

**Comment by imrishabh18** [comment]
Okay, the issues here on GitHub labeled `hacktoberfest` is not assigned to anybody. So, can't make out which one's are up-for-grabs?

**Comment by JonnyBurger** [comment]
Acceptance criteria for this PR:

- Make slider go upwards if space is not sufficient
- Be resilient if used in Next.JS server-side rendering / React strict mode
-

**Comment by JonnyBurger** [comment]
Sorry, I'm still preparing all the issues and will mention in each one of them clearly which ones are taken and how to claim one. Check back in a few hours!

**Comment by JonnyBurger** [comment]
Fixed by #1356
