### ISSUE TITLE
Old Node/FFMPEG version should trigger an error even when rendering via Node.JS APIs

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1359]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1359)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently taken by @JRavi2!

---

## Hacktoberfest Acceptance Criteria

- Currently in the CLI we check for the FFMPEG version: https://github.com/remotion-dev/remotion/blob/33668831b0335fcf1ff5580e53046dad97ff6273/packages/cli/src/validate-ffmpeg-version.ts#L8
- And for the Node.JS version: https://github.com/remotion-dev/remotion/blob/33668831b0335fcf1ff5580e53046dad97ff6273/packages/cli/src/check-version.ts#L16
- These checks should be moved into the `renderer` package so the warnings also appear when using the Node.JS APIs.
- The Node.JS version should be immediately checked once the `@remotion/renderer` package is loaded.
- The FFMPEG version should be checked before `renderMedia()`, `renderFrames()`, `getCompositions()`, `stitchFramesToVideo()` gets called.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)

### Submitted pull Requests
- [#1412 Move version checks for node and ffmpeg to the renderer package](https://issuehunt.io/r/remotion-dev/remotion/pull/1412)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by wa-candra** [comment]
Hi @JonnyBurger ,

can I take this issue? I think I can handle this.

Thanks

**Comment by JonnyBurger** [comment]
@wa-candra Yes, you got it!

**Comment by JRavi2** [comment]
Hey @wa-candra @JonnyBurger, is this still active? If not, can I pick up this issue?

**Comment by JonnyBurger** [comment]
Since the issue got inactive, a I'll hand it over to you! 
Just checking if @wa-candra has not already started working on it?
