### ISSUE TITLE
Write a tutorial for how to export from Figma to Remotion

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1361]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24111%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1361)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently taken by @kaf-lamed-beyt 

---

Right now this is a Twitter video:

https://twitter.com/jnybgr/status/1496748768821133312

It would be nice if it was turned into a documentation page, step by step with pictures.

## Hacktoberfest Acceptance criteria
- Create a new documentation page under the `Techniques` section and explain how one can export SVG from Figma and import it into Remotion.
- Show an example and include screenshots (can also be a different example than the one shown in the video)
- Expect that the reader has some very basic understanding of React and Figma.
- Feel free to credit yourself at the bottom of the post.
- Link https://www.remotion.dev/docs/lottie/after-effects in the `See also` section.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $111.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($111.00)

### Submitted pull Requests
- [#1378 Exporting from Figma to Remotion ](https://issuehunt.io/r/remotion-dev/remotion/pull/1378)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger,

I'd love to take on this issue

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt You got it!

**Comment by kaf-lamed-beyt** [comment]
Great! 🚀

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger,

The description of this issue says I should "create a new documentation page under the `Techniques` section" but I can't really locate that. I've navigated into the [docs](https://github.com/remotion-dev/remotion/tree/main/packages/docs/docs) folder, and I'm not seeing anything related to that. Perhaps you could show me?

**Comment by JonnyBurger** [comment]
Hi @kaf-lamed-beyt, look for a file called `sidebars.js` that defines the sections on the left! You can edit it to add a new page to that section.

**Comment by kaf-lamed-beyt** [comment]
Awesome!

I'll get started now
