### ISSUE TITLE
Issue a warning if using an Apple Silicon Mac under Rosetta

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1362]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1362)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @danmana and is not for taking

---

Node 14 uses Rosetta under M1, which makes Remotion 2x slower.
But also newer versions like Node 16 could be running the x86 version on Apple Silicon.

A warning should be issued, ideally pointing to a new documentation article (Could be hosted under remotion.dev/docs/troubleshooting/rosetta), urging the user to upgrade

## Hacktoberfest acceptance criteria

- Write code that correctly identifies that the user has this problem and add it to the `@remotion/renderer` package, and run it once the package is imported.
- Avoid false positives and false negatives
- Add a new documentation page to the docs and describe how the user can fix this issue (upgrade from Node 14, if already on a higher version then prefix the command with `arch -arm64`)
- Write a good error message and link the documentation page you posted.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)

### Submitted pull Requests
- [#1373 feat: warn apple silicon rosetta. Closes #1362](https://issuehunt.io/r/remotion-dev/remotion/pull/1373)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by danmana** [comment]
Hi, I'd like to take this.

Did I understand correctly that the warning message should be shown when the CPU model is Apple silicon (M1 or others from the family), but the architecture is x64 instead or arm64.

The recommendation would be:
* if using Node 14 -> upgrade to node 16
* if using Node 16 -> recommend using `arch -arm64`

**Comment by JonnyBurger** [comment]
@danmana Nice, good luck!
Yes that is correct, if that also seems to you like the best way to do it, let's take this route.

**Comment by danmana** [comment]
Added a PR.

First time working with remotion, so I'm open for feedback.
Note: I wasn't able to test the doc changes, docusaurus kept crashing ...

**Comment by JonnyBurger** [comment]
Thanks a lot, will give this a review tomorrow! Looking good! 🙌🏼

**Comment by danmana** [comment]
I managed to get docusaurus running and realized I added the docs in the wrong place and forgot to link to it in the sidebar.
I updated the PR with this fix
