### ISSUE TITLE
Load new env variables if `.env` has changed

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1363]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24164%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1363)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @Slashgear and not for taking

---

## Acceptance criteria

- If the environment variables changed while `npx remotion preview command` is running, inject them into the browser and reload the server
- Use a file watcher if `.env` only if the file exists.
- Only inject variables that start with `REMOTION_` (use `getProcessEnv()` to filter out acceptable)
- Use the `EventSource` logic (search `new-input-props` in the codebase) to push a notification to the client that the environment variables have changed and apply a full reload
- Figure out how to update the environment variables via Webpack. Maybe it is not possible, in that case you have to write some code that updates the variables on page load.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $164.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($112.00)
- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($52.00)

### Submitted pull Requests
- [#1368 feat(env): load new env variable on update](https://issuehunt.io/r/remotion-dev/remotion/pull/1368)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by Slashgear** [comment]
👋🏻 
I could definitely take that @JonnyBurger

**Comment by JonnyBurger** [comment]
As discussed via DM, the issue is unassigned until the other one by Antoine is merged :) It will probably be gone by tomorrow!
