### ISSUE TITLE
Write a tutorial on how to import a design from spline.design into Remotion

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1376]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24196%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1376)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is taken by @ayatkyo!
💰 Thanks to [CodeChem](https://codechem.com) for sponsoring this issue!

https://app.spline.design/ is a web 3D editor that allows to design 3D models on the web and then export them in React Three Fiber. We also support React Three Fiber, so there should be a tutorial on how you can design a scene and then import it into Remotion.

## Acceptance criteria

- Write a tutorial on how to design a very simple scene and then explain how one can export the React Three Fiber code and put it into Remotion. Then, show a simple animation, like for example a spin.
- The Three template (Found on the Remotion website) can be taken as a reference.
- Include screenshots to visually guide.

![Screenshot 2022-10-06 at 16 20 51](https://user-images.githubusercontent.com/1629785/194337841-f3b5925f-ecfd-4a33-b31e-7589bc678330.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $196.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($196.00)

### Submitted pull Requests
- [#1429 Spline tutorial on exporting a spline design and animating in remotion](https://issuehunt.io/r/remotion-dev/remotion/pull/1429)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by aacevski** [comment]
I'd like to work on this, if possible 🚀

**Comment by JonnyBurger** [comment]
@aacevski Reserved it for you! No guarantee that this will become a Hacktoberfest issue or that it will hold a bounty, but stay tuned  because we hope to make it happen 🙂

**Comment by pabloescoder** [comment]
@aacevski Are you still working on this issue? If not, then can I work on this @JonnyBurger?

**Comment by aacevski** [comment]
> @aacevski Are you still working on this issue? If not, then can I work on this @JonnyBurger?

Hey, sorry I had no time to pay attention to this - please take this!

**Comment by pabloescoder** [comment]
@aacevski @JonnyBurger Thank you! I'll get started with it right away.

**Comment by pabloescoder** [comment]
@JonnyBurger Just so that I'm clear, should I make a Markdown file with the tutorial content and add it to this repository (if yes, then where should I place the Markdown file), or should I write a tutorial on a blogging website like Medium, DEV (or anything else that you prefer)?

**Comment by JonnyBurger** [comment]
@pabloescoder It should be a Markdown file that gets put in this repo! It can be colocated to this one: https://github.com/remotion-dev/remotion/blob/main/packages/docs/docs/figma.md

**Comment by pabloescoder** [comment]
> @pabloescoder It should be a Markdown file that gets put in this repo! It can be colocated to this one: https://github.com/remotion-dev/remotion/blob/main/packages/docs/docs/figma.md

Alright! Sounds good.
