### ISSUE TITLE
fix installation and development guide to use pnpm instead of yarn

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [remotion-dev/remotion#1379]
When I try using yarn to start the development process locally on my PC. I get this error below, and I'd love to fix it.

![yarn error](https://user-images.githubusercontent.com/48127194/194503950-a94f674b-5953-4d92-abb5-2afc26e23f61.png)

Doing `pnpm pstart` or `pnpm install` fixes this

**Comment by JonnyBurger** [comment]
Thanks for reporting! I guess you did this because it was written like that in packages/docs/README.md. I updated that document now, if you have more ideas on how to avoid developers getting confused, feel free to let me know.

**Comment by kaf-lamed-beyt** [comment]
Great! I'll definitely do so. 😎
