### ISSUE TITLE
envVariables of renderMediaOnLambda()

### ISSUE THREAD

**Issue by ivanandresdiaz** [remotion-dev/remotion#1388]
Context: 
I took the steps to render my video with Lambda. So I generate the page. https://remotionlambda-mrpeqb4h7s.s3.us-east-1.amazonaws.com/sites/my-video/index.html

I am able to render the video from CLI. perfectly. 

However, I plan to render the video from Cloud functions Firebase (Nodejs). 
    "@remotion/lambda": "^3.2.29"
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.18.0"

1. **So I set the .env variables but when I was going to render. it Showed me this message**: 

> KMSAccessDeniedException: Lambda was unable to decrypt the environment variables because KMS access was denied. Please check the function's KMS key settings. KMS Exception: AccessDeniedExceptionKMS Message: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

2. So, I decided to apply what the other option **of the documentation. to add them manually.**
**https://www.remotion.dev/docs/renderer/render-media#envvariables**

```
` const { bucketName, renderId } = await lambda.renderMediaOnLambda({
        region: "us-east-1",
        functionName: "remotion-render-3-2-27-mem2048mb-disk2048mb-120sec",
        serveUrl:
          "https://remotionlambda-mrpeqb4h7s.s3.us-east-1.amazonaws.com/sites/my-video/index.html",
        composition: "HelloWorld",
        inputProps: {},
        codec: "h264",
        imageFormat: "jpeg",
        maxRetries: 1,
        framesPerLambda: 20,
        envVariables: {
          REMOTION_AWS_ACCESS_KEY_ID: "my_accesskeyId manually",
          REMOTION_AWS_SECRET_ACCESS_KEY: "my access key manually",
          AWS_ACCESS_KEY_ID:
            "my_accesskey_ID, just maybe it could work with this name manually",
          AWS_SECRET_ACCESS_KEY: "my access key manually",
        },
        privacy: "public",
      });`
```

Despite that I type them manually. i showed me this message:

>  You have tried to call a Remotion Lambda function, but have not set the environment variable AWS_ACCESS_KEY_ID or REMOTION_AWS_ACCESS_KEY_ID.

So I think this might be a Bug.  **envVariables when I render with lambda.renderMediaOnLambda() from NodeJs** CLOUD FUNCTIONS FIREBASE. 
https://www.remotion.dev/docs/renderer/render-media#envvariables

**Comment by JonnyBurger** [comment]
Hi Ivan!

By setting them manually, we mean not passing them to envVariables, but before calling renderMediaOnLambda, set it like this:

process.env.REMOTION_AWS_ACCESS_KEY = "xxx"

Does that help? I see we need to clarify some docs!

**Comment by ivanandresdiaz** [comment]
Hello Jhony, 

**I  solved the problem**. However, I will explain a little bit about the problem. Just for the **sake of you know** that I think **remotion-lamba is not working calling it from Firebase  Cloud functions**, at least in the version ("firebase-functions": "^3.18.0"). 

I was using **Firebase Cloud functions** and I set the env variables. I could **access these env variables** in my function using process.env.REMOTION_AWS_ACCESS_KEY_ID = "xxx", normally.

My function got the envVariable; I could `console.log(envVar)`. However, it seemed like remotion-lambda was not able to get it.
it showed this message:

`KMSAccessDeniedException: Lambda was unable to decrypt the environment variables because KMS access was denied. Please check the function's KMS key settings. KMS Exception: AccessDeniedExceptionKMS Message: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.`.

to solve the problem I simply change and **use NEXTJS functions Serverless**, instead of cloud functions. I set the env variables, it worked without a problem. 

anyways, thank you.  I thought, envVariables attribute was  a way to send the variables as well.
