### ISSUE TITLE
`<Thumbnail>` component

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1389]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24223%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1389)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
⏲️ This issue is currently assigned to @Slashgear! 
💰 Thanks to [CodeChem](https://codechem.com) for sponsoring this issue!

Currently, the `@remotion/player` package has a `<Player>` component for playing a video on the web.
A common task is to display a thumbnail of a video somewhere on the page, and to accomplish that, one could render a Player and disable all interactivity and freeze it.

I propose a new `<Thumbnail>` component that gets shipped in the Player package that only displays a still image.
The implementation could be similar to the Player, but without controls. Also logic from the`<Thumbnail>` component from the preview could be used: https://github.com/remotion-dev/remotion/blob/b579cc25eea72d1123f7de6bd75bd2605b579bbc/packages/cli/src/editor/components/Thumbnail.tsx

## Acceptance criteria

- Implement a new `<Thumbnail>` component that fits the description above and export it in the `<Player>` package
- Should have  at least props for dimensions and `style` like for `<Player>`
- Write a documentation page describing all the props and an example snippet.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $223.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($223.00)

### Submitted pull Requests
- [#1405 feat(player): implement Thumbnail component for player](https://issuehunt.io/r/remotion-dev/remotion/pull/1405)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by Slashgear** [comment]
Hi @JonnyBurger Could I take this one after the on that I almost finished.
I already work on few rendering sujet but working on remotion component is really something I want to try :)

**Comment by JonnyBurger** [comment]
@Slashgear Sure! Go ahead 😊

**Comment by JonnyBurger** [comment]
@priyang12 Already assigned this issue now to @Slashgear :(

Mind taking another one or coming back to this if it becomes inactive?

**Comment by priyang12** [comment]
@JonnyBurger  ok

**Comment by JonnyBurger** [comment]
Fixed by #1405
