### ISSUE TITLE
Implement a `@remotion/noise` package

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1395]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24223%20Funded-%2300A156.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1395)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently taken by @satelllte!
💰 Thanks to [CodeChem](https://codechem.com) for sponsoring this issue!

Noise is an often used tool to make interesting visuals. Here is an example of a DotGrid from the MKBHD intro:

https://github.com/wcandillon/mkbhd-intro/blob/da1c99236e4b4566f86be667b255230ee2dcc72b/src/Intro/Background.tsx

This uses the simplex-noise package, but the experience for Remotion developer is not yet so streamlined:

- There are two versions of the package with different API
- It uses Math.random() by default, so one has to also install alea to set a custom seed. Ideally the seed is set using Remotions `random` function.
- No examples or documentation beyond just the API reference.

## Task / Acceptance criteria

- Implement a new package in the monorepo called `@remotion/noise`
- Expose the `noise2D`, `noise3D`, `noise4D` functions from `simplex-noise` (it is allowed to use it as a dependency)
- Don't use the default Math.random() algorithm, use Remotion's random()
- Create a new documentation page that explains the API with the same quality standard as the other API pages
- Create a documentation page explaining how one can use noise to for example create the DotGrid in the example above. Implement some sliders to allow the user to play around with the parameters like in the Motion Blur PR #1392 and the Greenscreen example (https://www.remotion.dev/docs/video-manipulation#greenscreen-example)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $223.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($223.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by satelllte** [comment]
Hey @JonnyBurger. I'd like to work on this

**Comment by JonnyBurger** [comment]
@satelllte Assigned!
