### ISSUE TITLE
Implement a Remix + Remotion + Lambda template

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1396]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24280%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1396)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
⏲️ This issue is currently assigned to @florentpergoud! 
💰 Thanks to [CodeChem](https://codechem.com) for sponsoring this issue!

Remix is one of the more popular React frameworks out there at the moment, and it would be nice to have an example such as https://github.com/karelnagel/remotion-next-example for Remix to have a starting point for getting Remotion + Player + Lambda to work.

## Acceptance criteria

- Cloneable Remotion template with similar quality to the other templates
- Include Remotion Player with some basic option to modify input props and trigger a render
- Trigger a render via Lambda and tracking the progress of the render
- Documentation explaining how to set up environment and how to deploy to at least 1 provider (e.g. Vercel) - can reference existing Remotion documentation of course.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $280.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($280.00)

### Submitted pull Requests
- [#1421 fix(license): fix some mistakes in license](https://issuehunt.io/r/remotion-dev/remotion/pull/1421)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by florentpergoud** [comment]
Hi !
Can I take this issue ? :)

**Comment by florentpergoud** [comment]
Hello @JonnyBurger !
Here is the template  : https://github.com/florentpergoud/remotion-remix-template/
Please tell me if it meets the expectations :)

**Comment by JonnyBurger** [comment]
@florentpergoud Sorry that I am lagging a bit behind with the PR queue! :(
It looks like I will only be able to take a look tomorrow It will stay however on my radar!

**Comment by JonnyBurger** [comment]
@florentpergoud Can you give me an estimation of how long you spent on the template? I'll make a statistic in the end 😃
