### ISSUE TITLE
Solve GitHub actions deprecation warnings

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1400]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1400)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
✅ This issue is currently taken by @glokta1! 
💰 Thanks to [CodeChem](https://codechem.com) for sponsoring this issue!

## Problem

When running a GitHub workflow a lot of warnings are popping up:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Iamshankhadeep/setup-ffmpeg, actions/cache

`actions/cache` should be updated, a PR can be made to the `Iamshankhadeep/setup-ffmpeg` repo

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files

> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands

## Acceptance criteria

- Upgrade the YAML files and make PRs to get these three errors fixed
- Keep the previous behavior of the pipeline

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($112.00)

### Submitted pull Requests
- [#1404 bump actions/cache to to 3.0.11](https://issuehunt.io/r/remotion-dev/remotion/pull/1404)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by druwan** [comment]
Hi, can I make an attempt for this?

**Comment by glokta1** [comment]
Hi, I'd like to work on this

**Comment by glokta1** [comment]
Seems like deprecation for `set-output` and `save-state` have already been dealt with by the folks at `actions/cache`. See https://github.com/actions/cache/pull/950. Just need to update to the new versions.

**Comment by JonnyBurger** [comment]
@glokta1 Assigned and will take a look tomorrow! Thanks a lot!

@druwan Sorry for not responding swiftly!

**Comment by druwan** [comment]
@JonnyBurger No worries mate 👍🏽

**Comment by JonnyBurger** [comment]
@glokta1 How long do you estimate you spent on the 2 PRs? For statistics 😇

**Comment by glokta1** [comment]
@JonnyBurger This one luckily ended up not requiring much. I'd say about an hour.

**Comment by JonnyBurger** [comment]
Fixed by #1404
