### ISSUE TITLE
Dark mode is broken in the remotion player website

### ISSUE THREAD

**Issue by soumakkdev** [remotion-dev/remotion#1419]
# Bug Report 🐛

In the footer section of the following website, dark mode is slightly broken 
https://www.remotion.dev/player

![image](https://user-images.githubusercontent.com/100508336/196839899-174989c7-2bbc-416f-88f4-55137652a162.png)

**Comment by soumakkdev** [comment]
Please assign this issue to me, I'll start the PR

**Comment by JonnyBurger** [comment]
Fixed in #1420
