### ISSUE TITLE
Make the `from` prop of `<Sequence>` optional

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1431]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1431)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
✅ This issue is currently assigned to @pabloescoder!
💰 Thanks to [CodeChem](https://codechem.com) for sponsoring this issue!

Currently, `<Sequence>` takes two props for timing: `from` and `durationInFrames`, of which `durationInFrames` is optional.
We can also make `from` optional.

## Acceptance criteria

- Make `from` optional and default it to `0`.
- Update the documentation and mention that the prop is optional from the next version on 
- Go through all uses of `<Sequence>` in the docs and make remove `from={0}` (unless making it more explicit makes it clearer)
- Copy this ESLint rule which automatically removes `durationInFrames={Infinity}`: https://github.com/remotion-dev/remotion/blob/main/packages/eslint-plugin/src/rules/no-duration-frames-infinity.ts and make the new rule remove `from={0}`.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($112.00)

### Submitted pull Requests
- [#1436 Make the from prop of <Sequence> optional](https://issuehunt.io/r/remotion-dev/remotion/pull/1436)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by pabloescoder** [comment]
Hey @JonnyBurger! Can I start working on this once my previous issue (#1376) is completed? I've already made a PR for that issue.

**Comment by JonnyBurger** [comment]
Fixed by #1436
