### ISSUE TITLE
Write article about how to create a series of videos from a dataset

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1433]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24195%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1433)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
⏲️ This issue is currently assigned to @ThePerfectSystem!
💰 Thanks to [CodeChem](https://codechem.com) for sponsoring this issue!

A common problem that users want to solve with Remotion is that they have a dataset (let's assume JSON for simplicity) and create a video for each one of the entries in their set.

How I would recommend to do it is to create a TypeScript script, and use `renderMedia()` to render a video for each data and parametrize the video based on [input props](https://www.remotion.dev/docs/parametrized-rendering). There is already https://remotion.dev/docs/ssr which is similar but does not specifically explain how to approach the problem if you have a dataset.

## Acceptance criteria

- Write an article and add it to the website (take for example the Figma article as a reference: #1378)
- In that article, assume that you have a simple example video (it can for example be the example from https://www.remotion.dev/docs/player, source can be found at the bottom of the page) with few parameters (e.g. color and name)
- Explain step for step, how one would write and run a script that renders a video for each person in a dataset. Also create a small sample dataset, for example of 10 people who each have a name and favorite color.
- Include code snippets and screenshots where it makes sense.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $195.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($195.00)

### Submitted pull Requests
- [#1503 add documentation for rendering from dataset](https://issuehunt.io/r/remotion-dev/remotion/pull/1503)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by flynnzler** [comment]
Hello! Can I work on accomplishing this?

**Comment by JonnyBurger** [comment]
@ThePerfectSystem Yes, good luck 😊

**Comment by ThePerfectSystem** [comment]
thanks, @JonnyBurger! I wanted to ask, the dummy dataset should be fine as declared inside the TypeScript script or should I try to demonstrate that as say a .csv file?

**Comment by JonnyBurger** [comment]
@ThePerfectSystem A TypeScript array is totally fine, thanks for asking 😊 I think there are plenty of tutorials that show how to import CSV already.

**Comment by ThePerfectSystem** [comment]
yess thanks a lot, i'm having trouble taking out time these days since uni exams are approaching :sweat_smile: but i wanted to confirm that I should write the article as a .md file and store it as `packages/docs/docs/videosFromDatasetOrSomeOtherName.md`, right? (like how the markdown file for the figma article was stored)

**Comment by JonnyBurger** [comment]
@ThePerfectSystem That's correct! Good luck with uni and if you feel stressed, let us know and we totally understand if you don't want to do it anymore!

**Comment by ThePerfectSystem** [comment]
Thank you soo much for your concern! I would absolutely let you know in case I feel stressed. But for right now, this feels like a really fun task to take on. Would it be okay if I'm not able to finish it by october-end?

**Comment by ThePerfectSystem** [comment]
welp, looks like i wouldn't be able to complete this before october end after all. but i'm still on it!

**Comment by JonnyBurger** [comment]
@ThePerfectSystem No problem 😊

**Comment by ThePerfectSystem** [comment]
Hey @JonnyBurger I can't thank you enough for your patience, I managed my uni exams just fine and, in the meanwhile, got myself acquainted with react and remotion. However I'm having trouble pinpointing which componentID I will be rendering when rendering the output videos, could you maybe provide any pointers? 😅

**Comment by JonnyBurger** [comment]
@ThePerfectSystem Glad to hear the exams went well! 🥳  Congrats!

You would define one static composition ID (not of componentID, make sure you use the correct term in the docs) which can be anything, like `MyComp` for example. Some more info on what it is: https://www.remotion.dev/docs/terminology#composition-id

**Comment by ThePerfectSystem** [comment]
Hey @JonnyBurger thanks for your help, but I must admit that I was a rookie when I came to the issue, I've spent the past couple of days learning about react, remotion and node (and it has been a very informative experience, absolutely worth it!). 

Apologies but a very much a newbie question ahead, I'm still unable to figure out what the example at https://remotion.dev/docs/ssr already assumes the user to have set up. I tried creating a folder, `npm init`ialising it and then installing the remotion npm package. Is the code snippet just meant to go in a .js file and running it as `node filename.js`?

 I've been stuck on this for a few days now, I tried looking for it but have been unable to do so partly because I find the problem hard to describe. Any help would be tremendously appreciated!

**Comment by JonnyBurger** [comment]
@ThePerfectSystem Very good question! We expect the user to have already installed a Remotion template with `npm init video`.  Then they already have an entry point and the necessary packages. After that, indeed they can create a .js file and run it with node.

We want to promote TypeScript though, in that case it would be a .ts file and it would be executed with ts-node.

**Comment by RamiroMonte** [comment]
Hello. I know @ThePerfectSystem is already assigned this issue, but I wonder if I can work on it together? I found the idea very interesting and can think of several remotion applications with it :)

**Comment by ThePerfectSystem** [comment]
Hey @RamiroMonte! Really appreciate it but though it took me a while, I think I got it pretty much figured out now except for a few gaps here and there :sweat_smile:. Should be done with it soon!

**Comment by JonnyBurger** [comment]
Nice, thank you @RamiroMonte! 

How about you create a draft pull request soon @ThePerfectSystem and @RamiroMonte will then be able to add some feedback to it?

**Comment by ThePerfectSystem** [comment]
Sure @JonnyBurger, that sounds like a great idea! Will be doing that.

**Comment by ThePerfectSystem** [comment]
Hi, I'm terribly sorry for this delay but I have been unwell and had to take care of some other deadlines on top of that, will be opening the draft PR by today

**Comment by alexfernandez803** [comment]
@JonnyBurger From the description of the issue at hand. I have created a project in here.
https://github.com/alexfernandez803/remotion-dataset. If you are happy with it, I will create a pull request.

Looks like I am late on the party

**Comment by ThePerfectSystem** [comment]
might as well share what i'd been working on ^
