### ISSUE TITLE
Resume rendering frames after "Target closed." crash.

### ISSUE THREAD

**Issue by siderakis** [remotion-dev/remotion#1435]
# Feature Request 🛍️

Currently I get 40% done Rendering frames before a "Target closed. https://www.remotion.dev/docs/target-closed" crash. When I run the build command again I get roughly the same progress before another crash. Ideally the build would continue from the last frame when I run build again. Even better it would automatically retry after a "Target closed" crash and just continue on.

**Comment by JonnyBurger** [comment]
This is a good idea! I want to implement this.

**Comment by JonnyBurger** [comment]
Implemented in @siderakis

**Comment by JonnyBurger** [comment]
Fixed in #1456
