### ISSUE TITLE
I can’t dynamically render components

### ISSUE THREAD

**Issue by reactone** [remotion-dev/remotion#1455]
Im trying to dynamically render components in the video. The use-case is as follows - the user add shapes to the canvas and these are passed via props to render. Basically I store a list of components  in redux store and then show them on canvas using map function. The problem is that when I try to render the video and pass the array of components it only renders the default number of components. It seems that this is specified on render and can’t be dynamically changed. I can somehow overcome that by providing initial empty components and then providing their content through props but this is a nasty hack and it won’t work at scale because I don’t know how many components the user will add. Any ideas how this could be implemented?

**Comment by mykeels** [comment]
Can you show a code sample? @reactone

**Comment by JonnyBurger** [comment]
+1, we need to see some code to better help you.

Often times, people will pass a JSON array as input props where each item in the array represents one item, be it shapes, videos, text. Then they map over the array and render such element.

**Comment by reactone** [comment]
@JonnyBurger I did exactly that, I’m passing a JSON array and then map it outputting an <Element> for each item. It works on the canvas and I’m able to add multiple elements. If I add like 2 elements as initialValues in store it would also render them and change their contents via props but it won’t render more than these 2 elements. I thought that there is a limitation in remotion so that the components or at least their number have to be prespecified and cannot be dynamically adjusted. I’m glad that you are saying that it’s not the case and probably something is wrong with my code. I will try to add some snippets.

**Comment by reactone** [comment]
@JonnyBurger There was a bug in my app, I was updating the canvas but not updating the list properly when rendering. Solved now 👯
