### ISSUE TITLE
@remotion/google-fonts doesn't work in iframe

### ISSUE THREAD

**Issue by marcusstenbeck** [remotion-dev/remotion#1459]
Hey!

Was trying out the new `@remotion/google-fonts` today, and after some wrangling I got it to work. Unfortunately, using it within an iframe doesn't work.

I have a workaround in which I set a dynamic CSS import too, which makes it flicker a little but does work on both client and later when rendering with SSR.

The issue is that the font is loaded in the parent document and not in the iframe document. 

Why would anyone use an iframe? In order to isolate a remotion composition's styles from the surrounding webpage.

Here's my workaround for enabling dynamically choosing a font.
```tsx
import React, { useEffect, useState } from 'react';
import {
  AbsoluteFill,
  continueRender,
  delayRender,
  useVideoConfig,
} from 'remotion';
import { TextEntity } from '../../types';
import { useTemplateInfo } from '../TemplateInfoProvider';
// @ts-expect-error for some reason types don't work
import { getAvailableFonts } from '@remotion/google-fonts';

const availableFonts: {
  fontFamily: string;
  importName: string;
}[] = getAvailableFonts();

export const RenderTextEntity: React.FC<TextEntity> = ({
  text,
  width,
  x,
  y,
  color,
  fontSize,
  fontWeight,
  fontFamily,
  textShadow,
  textAlign,
}) => {
  const videoConfig = useVideoConfig();
  const { baseSize } = useTemplateInfo();
  const [handle] = useState(() => delayRender());
  const [remotionGoogleFont, setRemotionGoogleFont] = useState<any>(null);

  useEffect(() => {
    (async function maybeLoadGoogleFont() {
      const gFont = availableFonts.find(
        (font) => font.fontFamily === fontFamily
      );

      if (gFont) {
        const googleFont = await import(
          `@remotion/google-fonts/${gFont.importName}`
        );
        setRemotionGoogleFont(googleFont);
        await googleFont.loadFont();
        continueRender(handle);
      }
    })();
  }, [fontFamily]);

  const pixelWidth = videoConfig.width * (width / 100);
  const pixelOffsetX = baseSize * x;
  const pixelOffsetY = baseSize * y;

  return (
    <AbsoluteFill
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        transform: `translate(${pixelOffsetX}px,${pixelOffsetY}px)`,
      }}
    >
      {remotionGoogleFont && (
        <style>{`@import url("${remotionGoogleFont.getInfo().url}");`}</style>
      )}
      <div
        style={{
          color,
          width: pixelWidth,
          fontSize,
          fontWeight,
          fontFamily: `"${fontFamily}"`,
          textShadow,
          textAlign,
        }}
      >
        {text}
      </div>
    </AbsoluteFill>
  );
};
```

@ayatkyo

**Comment by JonnyBurger** [comment]
Interesting, we use `document.fonts.add(fontFace)` to add the font.

Should we allow to pass a custom document? Seems like you can get the document of an iframe using ` document.querySelector('iframe')?.contentDocument`.

That being said, probably a lot of APIs are breaking if you use an iframe. This might only be the tip of the iceberg 🤔

**Comment by marcusstenbeck** [comment]
Yes, I think being able to pass in a custom document would be good. Do you know of any other way to isolate the styles of a Remotion composition from the outer page when using `<Player/>`. Iframe looked like the only option when I was investigating this...

**Comment by ayatkyo** [comment]
@marcusstenbeck That looks interesting, do you have an example repo for this case? I don't have experience using iframe before.

If I am not mistaken, the case is you have a webpage that embed remotion composition using `<Player />` but styling from the webpage get applied into the embedded remotion composition and vice versa, so to fix that you wrap it in an 'iframe'. But when using `@remotion/google-fonts` the font is loaded into the webpage instead of the remotion composition that using it (in an iframe)?

**Comment by marcusstenbeck** [comment]
That's exactly right, you can use the `<IframePlayer />` to test it, snippet here: https://www.remotion.dev/docs/miscellaneous/snippets/player-in-iframe

**Comment by aaronnuu** [comment]
Just spitballing here, but could you achieve what you're after using `shadow-dom` with something like [react-shadow](https://www.npmjs.com/package/react-shadow)?

**Comment by marcusstenbeck** [comment]
@aaronnuu interesting! I’ll have to try it out and see how it works.

**Comment by JonnyBurger** [comment]
New option - you will be able to pass `document` to loadFont() and pass the document of the iframe: https://www.remotion.dev/docs/google-fonts/load-font#document
