### ISSUE TITLE
Unexhaustive handling for using Img tag as child in Mask tag

### ISSUE THREAD

**Issue by greffgreff** [remotion-dev/remotion#1460]
# Bug Report 🐛
I am using Remotion and the web version of skia react native. I am getting this error when passing an Img tag with an svg logo under the children property of a Mask tag. I have looked online for an explanation of the issue but I haven't found one. 

Below is my current setup:
```
<Mask
  children={<Img style={{...logoStyle}} src={Logo} />}
  mask={<Rect x={0} y={0} width={256} height={256} color="lightblue" />}
/>
```
Any ideas why this is?

**Comment by JonnyBurger** [comment]
Hi @greffgreff!

React Native Skia renders on a Canvas, and therefore you cannot render an HTML `<img>` tag on it. You need to use the Image tag from Skia: https://shopify.github.io/react-native-skia/docs/images/
