### ISSUE TITLE
full screen button is not visible on mobile

### ISSUE THREAD

**Issue by HenriqueMatias** [remotion-dev/remotion#1468]
# Bug Report 🐛

 The player component doesn't display the fullscreen button on mobile.
 
 OS: Android, IOS
 Browsers: safari, chrome
 
 How can I make the player go fullscreen on mobile? 
Maybe it's possible to stream the result to a normal player?

Thank you in advance

**Comment by JonnyBurger** [comment]
@HenriqueMatias We have an overrideFfmpeg option: https://www.remotion.dev/docs/config#overrideffmpegcommand

But I don't think it can solve the fullscreen problem.
