### ISSUE TITLE
Allow to style/add a ref to `<Series.Sequence>` and `<Loop>`

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1475]
Like a `<Sequence>`!

**Comment by JonnyBurger** [comment]
And a `<Loop>`!

**Comment by JonnyBurger** [comment]
Taken by @afzsalsayed96!

**Comment by afzalsayed96** [comment]
Facing issues setting up Algora for UAE. Let me know if wire transfer or [wise.com](https://wise.com) would be feasible for you.
<img width="517" alt="Screenshot 2022-11-23 at 9 52 30 PM" src="https://user-images.githubusercontent.com/14029371/203598023-2cf10c09-118c-4f5d-8ec2-76146f02f271.png">

**Comment by MehmetAdemi** [comment]
Hi Afzal, just checked with Algora and they said it should work now. Can you try it again?

**Comment by afzalsayed96** [comment]
@MehmetAdemi Ran into another issue. Contacted folks from Algora again.
Meanwhile rechecking feasibility of direct transfer.
