### ISSUE TITLE
Not applying changes with javascript events to the sequence tag in the video output

### ISSUE THREAD

**Issue by RezaRamezanisani** [remotion-dev/remotion#1490]
I change the color of the sequence tag with a button, but this sequence color change is not applied to the video output, help me

this is my code  :
             const [color,setColor] = useState('blue');
                <Sequence style={{
                    position: 'absolute',
                    background: color,
                    width:'300px',
                    height: '300px'
                }}>
                    <LottieHolder_01/>
                </Sequence>
                <button onClick={()=>setColor('orange')}>change color</button>

notice : tag LottieHolder_01 is a lottie file.

**Comment by JonnyBurger** [comment]
Hi @RezaRamezanisani!

While rendering, Remotion will always reset to the initial state. There is no way to save the local state for rendering.

Instead, you should make the color an input prop (https://www.remotion.dev/docs/parametrized-rendering).

Using the `<Player>`, you can code a webapp that allows users to parametrize their video for example using a button click. If you then want to render the video, you can pass in the input props that the user has customized.
