### ISSUE TITLE
How to insert the props of the component in the player tag

### ISSUE THREAD

**Issue by RezaRamezanisani** [remotion-dev/remotion#1491]
Hello, don't be tired and thank you for your quick response  🥇 
How to insert the props of the component in the player tag help me:
Is this method correct?
It gives an error that it does not recognize the props
My code:
`
export const Comp : React.FC<{
    color: string,
    width:number
}> = ({color,width}) => {
   return (<Sequence style={{width:width,color:color}}></Sequence>)
}
export const App: React.FC = () => {
    const [play, setPlay] = useState(false);
    const playerRef = useRef<PlayerRef>(null);
    useEffect(() => {
        if (playerRef.current) {
            console.log(playerRef.current.play);
        }
    }, []);
    return (
            <Player  inputProps={width,color} ref={playerRef} component={Comp} durationInFrames={120} compositionWidth={700} compositionHeight={400} fps={30}/>
    );
}`

**Comment by JonnyBurger** [comment]
You can use the `inputProps` prop for the Player - here is an example: https://www.remotion.dev/docs/player/examples#interactive-player
