### ISSUE TITLE
Possible to use symlinked static files?

### ISSUE THREAD

**Issue by L-TheG** [remotion-dev/remotion#1498]
Hi,

I have some pretty big files that I want to use in different remotion projects. Those projects have their own assets as well, which are in their respective git repositories.
Since I don't want to copy the large files into the remotion public directory of every project, everytime I re-clone and re-render a project, I came up with a different solution.

I symlink the directory with the large files into the public directory of the remotion project. I am hitting a problem though: upon executing the rendering command, after finishing the bundling (completes to 100%), I get the following error message:
```Error: EPERM: operation not permitted, copyfile 'C:\Users\User\Documents\remotionProject\public'\symlinkedDir -> 'C:\Users\User\AppData\Local\Temp\react-motion-graphicsxsPO5x\public\symlinkedDir'```

As you can see from the message, I am using Windows. I have double-checked that I am executing the command as admin.

Am I doing something wrong or is, what I am attempting, just not possible?

Thanks!

**Comment by JonnyBurger** [comment]
Hey @L-TheG, great point thanks for raising it!

We did not support symlinks but we can. I just implemented it and you'll be able to use it in v3.3.3 which will probably come out by Monday.

**Comment by JonnyBurger** [comment]
Fixed by #1500!
