### ISSUE TITLE
How to hide part of the element that comes out of the composition during video output

### ISSUE THREAD

**Issue by RezaRamezanisani** [remotion-dev/remotion#1499]
Hi remotion
How to hide part of the element such as a sequence when it exceeds the size of the composition or by giving a position greater than the size of the composition during video rendering or video output. 
Thank you.

**Comment by JonnyBurger** [comment]
Hi @RezaRamezanisani!

When an element exceeds the canvas, it should be default be cut off in the output.
Can you elaborate the question?

**Comment by RezaRamezanisani** [comment]
yes.
Suppose my composition has a width of 1920 and a height of 1080. Then I give the sequence element a css style for example:
position=absolute, left= 1918px, top=1070px
In a way that exceeds the width and height of the composition.
 when I type the npm run build command, the element that I positioned is not cut for the final output. 
my code:
`
const Comp: React.FC<{
    property: object
}> = ({property}) => {
    return (<>
 <Sequence style={{position:'absolute',top:'1070px',left:'1918px',background:'blue',width: '500px', height: '500px'}</Sequence>
    </>);
}
export const RemotionRoot: React.FC = () => {
    return (
        <>
            <Composition
                // You can take the "id" to render a video:
                // npx remotion render src/index.ts <id> out/video.mp4
                id="Render"
                component={Comp}
                durationInFrames={30}
                fps={30}
                width={1920}
                height={1080}
            />
        </>
    );
};
`

**Comment by RezaRamezanisani** [comment]
The problem was solved.
Thank you.
