### ISSUE TITLE
Infinite loop structure created by bundler

### ISSUE THREAD

**Issue by uluhonolulu** [remotion-dev/remotion#1513]
I'm trying to put the bundle into the public folder so that it becomes a part of the deployed React app. I'm trying to set `outDir: path.resolve("../public/bundle")` in the `bundle()` argument. 

However, it causes an infinite directory structure to appear on my system which looks like `\public\bundle\public\bundle\...`.

This is caused by the `copyDir` function that copies `\public\` into '\public\bundle\public`, then proceeds recursively.

1. Would it be useful to create a safeguard against such situations in `copyDir()`?
2. What should I set as `outDir` to make my bundle a part of the deployed app?

**Comment by JonnyBurger** [comment]
Hi @uluhonolulu, great question!

The public folder is part of the bundle, so if you copy the bundle into the public folder, that is indeed recursive and not good.
We should indeed add some safeguards for this.

Maybe it would make sense for you to use a separate public/ directory for Remotion asset

I am questioning whether it's really necessary to put the bundle into the public folder of the React app, what purpose are you trying to fulfill? Are you trying to serve the bundle in a subfolder? Then it is better to copy the directory into the `build` / `dist` folder instead. Make sure to set `publicPath` if you serve the bundle from a subfolder.

**Comment by uluhonolulu** [comment]
Hi @JonnyBurger,

I'm using Azure Static Website deployment. It builds the React app and copies the contents of the `build` folder into the web root. It also has the API Functions feature (similar to Lambda) so that we are able to run serverside code.

I'm using it to render a video. But I can't run `bundle()` after the site is deployed because the entry point (`src/index`) is not there anymore. My idea is to run `bundle` at an earlier stage and put the bundle into the `public` folder so that it is copied to the website and is accessible at runtime.

If you have any idea how to make this, please let me know.

**Comment by uluhonolulu** [comment]
Now that I think of it, I could modify the `build` action to include the render stage after the build and use the `build` folder instead.

Do I need to set `publicPath` in this case? How do I set it to avoid the same issue?

**Comment by uluhonolulu** [comment]
I was able to have the bundle as a part of the deployed site, but I still can't render a video because the API functions that work with Azure Static can't run for more than 45s. This is not a problem with Remotion so I'm closing this.

**Comment by JonnyBurger** [comment]
@uluhonolulu Thanks for self-closing the issue and apoligies for not following up on the latest comment.

For rendering, you could now also pass the hosted bundle URL that you have generated to Remotion Lambda and this would work, if you want to consider this. It is no problem to pass a 'site' that is hosted on a different cloud.

Unfortunately we don't have any guidance on Azure yet.
