### ISSUE TITLE
Use the "packageManager" field after scaffolding a template

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1520]
Scenario:

If you create a project based on a template with Yarn (as an example, but also with npm or pnpm), it should detect the current yarn version (`yarn -v`, let's say it yields `1.22.19`) and add `"packageManager": "yarn@1.22.19"` to the package.json.

This will prevent someone from accidentally using pnpm or npm in that project and also force everybody to use the same version, so hopefully fewer problems occur. (This only applies if the user has corepack enabled though, at least for now)

It can be implemented here: https://github.com/remotion-dev/remotion/blob/main/packages/create-video/src/patch-package-json.ts

**Comment by alexfernandez803** [comment]
@MehmetAdemi can I take this?

**Comment by alexfernandez803** [comment]
oh, all good @MehmetAdemi

**Comment by RamiroMonte** [comment]
Hi, if someone can give me a hint on how this can be done, maybe I can get

**Comment by MehmetAdemi** [comment]
Hi Ramiro, thanks for your interest! During Hacktoberfest, we try to give guidance and encourage new contributors whenever possible, but it's hard to give this guidance throughout the year. We assume that Jonny's description should be enough to solve it. Hope you don't mind. :)

**Comment by mykeels** [comment]
Happy to take this if possible

**Comment by JonnyBurger** [comment]
Good luck @mykeels! :)
