### ISSUE TITLE
renderStill() should also be able to return a Buffer

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1525]
As requested by @FelippeChemello 

One unfortunate design decision we made in renderMedia() was that we returned the raw buffer, not an object. This led to us having to implement the "slowest frames" API in an unfortunate way. Let's not make that mistake again

**Comment by JonnyBurger** [comment]
Acceptance criteria:

- Implement returning a buffer if no output path is specified, similar to how renderMedia() works.
- Document this behavior similarly to how it is documented in renderMedia()-
- Difference between renderMedia() and renderStill(): The blob should be returned as part of an object, so that in the future, different data can also be added to the return value

**Comment by afzalsayed96** [comment]
Open to taking a stab at this. Let me know

**Comment by MehmetAdemi** [comment]
Go for it! 👍🏼
