### ISSUE TITLE
Latest stable chrome build seems to break aspect ratio for generated stills and videos

### ISSUE THREAD

**Issue by aaronnuu** [remotion-dev/remotion#1527]
Versions:
- Latest Remotion - `3.3.5`
- Google Chrome Stable (not Chromium) - `108.0.5359.71`
- Linux - Ubuntu 20.04
- Docker - `20.10.21`
- Container base: `node:16-slim`

When using the latest stable version of google chrome the aspect ratio of the rendered videos and stills seem to not be respecting the resolution that I have asked for in my `Composition`.

I am running Remotion from within a docker container that installs the latest chrome build whenever the container is built, and as far as I can tell this is the only difference between old working containers and the new broken ones that could make this difference. The bug started only on new builds from today, and the latest chrome was [promoted to stable](https://chromereleases.googleblog.com/2022/11/stable-channel-update-for-desktop_29.html) within the last day.

Is this a known issue? I can't confirm this in my specific environment since Google doesn't allow you to download old versions of Chrome, however if the issue is unable to be reproduced on your end, I am happy to put together a reproduction repo when I have more time tomorrow.

**Comment by JonnyBurger** [comment]
Hi Aaron!

Sounds concernign indeed, I just tried updating my Chrome on Mac and I could not reproduce it with 1080x1080 and 1920x1080 videos. 

Could you share everything that is easy for you to share (Docker image, resolution, description of how the output is malformed) so I can try to dig into it?

**Comment by aaronnuu** [comment]
For now I can share some more details and images, I will create a basic docker image with the problem later tonight.

The issue seems to be that the content of my video or still is trying to fit into the frame rather than force the frame to be the exact resolution. So for my use case I am creating YouTube thumbnails, I create some image that is `576x576` and transform it how I would like, scale, rotate and translate. This often means the image "breaks out" of the bounds of the box that it's in. I also add a background that could be anywhere from `1024px` wide to `2048px` wide, which is then centred within the frame how I like by translating it negatively.

### This is what the thumbnail looks like in the preview
** Note that this is a screenshot and does not have the exact dimensions
<img width="709" alt="Good Thumbnail" src="https://user-images.githubusercontent.com/8295812/204949985-fa19ebdf-55a7-4406-8189-a5a9d429caac.png">

### This is the output that I get when running `renderStill()`
** This is the exact image generated
![bad thumbnail](https://user-images.githubusercontent.com/8295812/204950066-bd2f9a03-cc92-474c-a82a-077aeae75a64.png)

I'm not really sure what's going on here - the dimensions aren't what I would expect at all 🤔

FWIW the image generation works fine if I use an image sized to exactly `1024x576`

A similar thing happened generating a video before, except the generated video was smaller than I expected (I am just absolutely positioning the video with `inset: 0`), however I can't reproduce that locally right now and will need to dig in further.

**Comment by JonnyBurger** [comment]
Trying to fix it with #1529! Please try the new version that will come out shortly: https://remotion.dev/changelog

Thanks for reporting this!

**Comment by aaronnuu** [comment]
No problem at all - thanks for looking into it so quickly!

**Comment by JonnyBurger** [comment]
@aaronnuu Thanks a lot for confirming that! 🙌

**Comment by JonnyBurger** [comment]
@alexanderson1993 Thanks a lot for the appreciation! 🤗
