### ISSUE TITLE
@remotion/google-fonts gives error when trying to dynamically import fonts

### ISSUE THREAD

**Issue by karelnagel** [remotion-dev/remotion#1531]
When importing fonts dynamically with the google-fonts package, webpack errors because it also wants to include a Licence.md file in the bundle but this has no loader. One solution I can think of is putting all the fonts into a subdir like @remotion/google-fonts/fonts/Inter or something like that, or updating Webpack config. When I delete the licence file from node-modules then it's working ok.

I used this in a useEffect hook:
```
  useEffect(() => {
    for (const font of fontFamilies) {
      import(`@remotion/google-fonts/${font.replaceAll(" ", "")}`)
        .then(f => f.loadFont())
        .catch(() => console.warn(`No ${font} font!`))
    }
  }, [fontFamilies])
```

The error:
```
An error occurred:
Error: Module parse failed: Unexpected character ' ' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> # Remotion License
| 
| Depending on the type of your legal entity, you are granted permission to use Remotion for your project. Individuals and small companies are allowed to use Remotion to create videos for free (even commercial), while a company license is required for for-profit organizations of a certain size. This two-tier system was designed to ensure funding for this project while still allowing the source code to be available and the program to be free for most. Read below for the exact terms of use.
undefined
    at bundle (/Users/karel/Documents/projects/audiogram/node_modules/@remotion/bundler/dist/bundle.js:117:15)
    at async bundleOnCli (/Users/karel/Documents/projects/audiogram/node_modules/@remotion/cli/dist/setup-cache.js:99:21)
    at async bundleOnCliOrTakeServeUrl (/Users/karel/Documents/projects/audiogram/node_modules/@remotion/cli/dist/setup-cache.js:17:21)
    at async render (/Users/karel/Documents/projects/audiogram/node_modules/@remotion/cli/dist/render.js:66:53)
    at async cli (/Users/karel/Documents/projects/audiogram/node_modules/@remotion/cli/dist/index.js:74:13)
error Command failed with exit code 1.
```

**Comment by JonnyBurger** [comment]
To be investigated...
I think when writing an import statement like this, the Webpack dynamic behavior is triggered as described here: https://github.com/remotion-dev/remotion/issues/1531

So this way is definitely not recommended, but I'll leave it open because we need to figure out what actually is the best way.

**Comment by Balastrong** [comment]
Not sure if this is related, but I also get an error on "standard" imports for fonts, for example this one

https://github.com/remotion-dev/remotion/blob/415dd028e63b17886a096eb2b79ab862d6480fdb/packages/example/src/Fonts/index.tsx#L1

Gives me
```
Cannot find module '@remotion/google-fonts/Genos' or its corresponding type declarations.ts(2307)
```

**Comment by JonnyBurger** [comment]
I wonder if this happens when the module is imported in ESM mode 🤔 do you know if you are importing it in a module?

**Comment by JonnyBurger** [comment]
@Balastrong what you described should be fixed in the next version. Testing appreciated!
