### ISSUE TITLE
Support ffmpeg binary download for linux/windows on Arm

### ISSUE THREAD

**Issue by GagnDeep** [remotion-dev/remotion#1535]
# Bug Report 🐛

when there is no ffmpeg binary installed on the system, behaviour is remotion downloads the ffmpeg binary. 
It works well on windows and macos but on linux on arm it throws this error

`Syntax error: Unterminated quoted string`  and with bunch of ffmpeg related error logs

### Reproduction
Running remotion in linux on arm without ffmpeg binary installed globally will reproduce this issue

### Temperory fix
Installing ffmpeg binary globally and clearing out node modules fixed this issue

### Cause of issue
[getBinaryDownloadUrl in ffmpeg-flags.ts](https://github.com/remotion-dev/remotion/blob/main/packages/renderer/src/ffmpeg-flags.ts#L255-L306) generates the download url, but it does not check `arch` for linux/windows and downloads unsupported binaries for those platforrms. This then results in weird errors while building.

**Comment by JonnyBurger** [comment]
Thanks for reporting the bug and posting the root cause of the bug as well! 🙌
