### ISSUE TITLE
Cannot render Vp9 video with alpha channel

### ISSUE THREAD

**Issue by Cospel** [remotion-dev/remotion#1538]
# Bug Report 🐛

I'm trying to run this rendering:

`remotion render src/index.tsx --image-format=png --pixel-format=yuva420p --codec=vp9 MUSICTITLE out/result.webm --props=\"./src/compositions/musicstart/example-props.json\"`

However this results in TypeError:

An error occurred:

> TypeError: The out name is out/result.webm but --codec=vp9 was passed. The out name implies a codec of vp8 which does not align with the --codec flag.

By looking at:
https://github.com/remotion-dev/remotion/blob/main/packages/cli/src/get-final-output-codec.ts

The vp9 configuration is completely missing ...

**Comment by JonnyBurger** [comment]
Thanks for reporting this! Will be fixed soon!
