### ISSUE TITLE
`useCurrentPlayerFrame` does not work

### ISSUE THREAD

**Issue by viclafouch** [remotion-dev/remotion#1550]
# Bug Report 🐛

Hello ! Yesterday, @JonnyBurger shared me an article about displaying the current frame outside of a composition. The thing is, it does not work at all for me, sometime it works when I force the app to rerender.. Can't explain why.

The article : https://www.remotion.dev/docs/player/current-time
A reproduction : https://github.com/viclafouch/remotion-use-current-frame (`npm i` and `npm run dev`) 

Last version of remotion, and i'm using Next.JS last version.

On the video bellow, as u can see,  it does not work.. :/ `frame` is blocked on `0`

https://user-images.githubusercontent.com/23353836/206416867-84c0a756-164d-4c43-843a-208e9124bfc1.mov

**Comment by JonnyBurger** [comment]
Thanks for reporting and providing a repro!
I don't know why it worked when I tried it, there is indeed a bug. Fixing with #1551
