### ISSUE TITLE
Hello World (Javascript) template doesn't hot reload

### ISSUE THREAD

**Issue by thegamerhat** [remotion-dev/remotion#1557]
# Bug Report 🐛

I've been trying remotion for the past week without realizing that hot reload actually exists. Unless I'm seriously missing something, I can't get hot-reloading in the "Hello World (Javascript)" and "Tailwind" template (which is typescript based).

What I've tried so far:
- Created new vanilla projects (via `npm init video`) with Hello World TS and JS templates, and Tailwind template, but only the Typescript version of HW is able to hot-reload.
- Converting the HW TS template to JS by renaming `.ts` and `.tsx` files to `.js` and `.jsx`, and removing `tsconfig.json` as well as uninstalling `@types` and `typescript` via npm. But it still doesn't work.

Any workarounds to this problem?

I guess I'll just use the TS version for now. Thanks!

**Comment by JonnyBurger** [comment]
HI Pranav!

Thanks for reporting, I tried to reproduce it by running `npm init video` as well and then tried to change the text in the Hello World template, and hot reload worked well. I could not get to reproduce the behavior you described.

Did you change something specifically? Could it be you're on a different operating system than me? (Tested on macOS)

**Comment by thegamerhat** [comment]
I've tried it on a virtual machine running Ubuntu 22.04, used exclusively for JS/TS projects.

So now I tried this again just to be extra sure that I'm not doing something incorrectly.
I ran `npm init video` for the HW JS template, tried changing the subtitle, and the hot reload worked!

But then I went and did this exact same thing in my Projects directory where I have all my projects stored, and the hot reload didn't work this time.

I suppose my Projects folder being a remote directory mounted via `sshfs` is the problem, no idea why. Changing the contents in any `.jsx` file from the ssh host itself seems to be problematic, but typescript doesn't seem to have this issue in my experience.

Very weird problems, and I understand that edge cases like these might not always be caught in your testing.
But anyways, thanks for your response. If you want me to report more info regarding this use case, do let me know, I'll be happy to help :)

**Comment by thegamerhat** [comment]
I tried running `WEBPACK_OPTS='--watch-poll 1000' npm start`, but no luck!

I even followed this issue on vscode-remote repo, but not sure as to what solution I should follow:
https://github.com/microsoft/vscode-remote-release/issues/2371

**Comment by thegamerhat** [comment]
So in the meanwhile I tried using Remote Explorer [SSH] extension in VSCode, and `virtiofs` through Virt Manager as an alternative to SSHFS.

Remote explorer worked flawlessly. It sets up port forwarding via SSH tunnel to view the projects as if natively running.

Using `virtiofs`, however, results in no different outcome than SSHFS, and webpack still refuses to hot reload without custom polling.

So, Remote explorer is my best workaround for now, without any compromises.

**Comment by JonnyBurger** [comment]
Closing this after #1578 is merged - adding a flag for implementing Webpack polling.
That it does not work by default with remote file systems is a bug or deliberate decision of Webpack and I don't see what we can do about it.

**Comment by JonnyBurger** [comment]
This issue can also be seen if a file is imported with the wrong capitalization!

See https://github.com/remotion-dev/remotion/issues/1685
