### ISSUE TITLE
Remotion not working with github actions properly anymore

### ISSUE THREAD

**Issue by micartey** [remotion-dev/remotion#1560]
# Bug Report 🐛

I use remotion to display an always up-to-date summary about me on my profile. However, without any changes I realized that the generated images start to warp and change. This is weird because I haven't changed anything and locally just works fine. Even after deleting the node folder. So this is probably just a github actions issue. I thought that changing the github actions runner version would solve the problem, but nothing worked so far.

![img](https://raw.githubusercontent.com/micartey/micartey/master/prod/video2_bug.gif)

Has anyone experienced the same issue or even found a solution?

**Comment by JonnyBurger** [comment]
I think this is due to a Chrome update, we have adjusted our code in the meanwhile and it should be fixed!

Run `npx remotion upgrade` to see if it's fixed. Please close the issue if it works :)

**Comment by micartey** [comment]
This indeed solved the issue.
But I am still wondering how the bug was created in the first place

**Comment by JonnyBurger** [comment]
This is the change that was necessary: https://github.com/remotion-dev/remotion/pull/1529

I guess the problem in the first place was that the newest Chromium version is always pulled and that version broke Remotion actually. We'll try to improve that by pinning Chromium in the future.
