### ISSUE TITLE
Allow to open project in VS Code or other editor from the preview

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1561]
Workflow:

I `cd` into a project, run `npm start`.
Then I realize I forgot to run `code .`, and I need to Ctrl+C, run it and then start the preview again.

Somewhere around here we could put a button "Open in VS Code", but of course it should be editor agnostic. The logic from the error overlay should be reused:

![Screenshot 2022-12-12 at 09 17 44](https://user-images.githubusercontent.com/1629785/206995442-da3c6dca-50bd-4513-a123-e7623ec522d6.png)

**Comment by JonnyBurger** [comment]
Better idea: Put it as another item in the `File` menu, then it can also be invoked using `Cmd+K`!

**Comment by mykeels** [comment]
How can an "Open in VS Code" button be editor-agnostic? Does it let you open in any editor of your choice?  Perhaps, a link to the error overlay logic will help?

**Comment by mykeels** [comment]
Sounds great!

**Comment by RohovDmytro** [comment]
I made a shallow search. 
- The editor package should be updated
- use-menu-structure.tsx contains buttons handlers
- launch editor inspiration from react team: 
https://github.com/facebook/create-react-app/blob/19fa58d527ae74f2b6baa0867463eea1d290f9a5/packages/react-dev-utils/launchEditor.js

I'm not planning to proceed further. It should be easy to open a specific file, not sure about opening a specific folder.

**Comment by orimdominic** [comment]
I've started working on this

**Comment by MehmetAdemi** [comment]
@RohovDmytro Thanks for the input!
@orimdominic Let's go! 🚀

**Comment by uditkumar01** [comment]
Instead of showing a button, we can ask user to open the project in their preferred code editor, such as Visual Studio Code when the `npm start` command runs. This approach is much simpler and have a similar implementation [here](https://github.com/remotion-dev/remotion/blob/main/packages/create-video/src/open-in-editor.ts).

what do you think 🤔 ?

**Comment by orimdominic** [comment]
I think that @uditkumar01 has a point.
If the button is on the UI, how many times would the user need to use it? Once the editor is opened, they will have no need to click on the button again.

**Comment by JonnyBurger** [comment]
We already ask the user after they have initialized the project if they want to open it in their editor.
So this flow is intended for the all the times after the initialization of the project.

Allowing to do it via CLI is also a good idea, but it should never block the start of the preview server.
For simplicity, I suggest that we simply add a menu item that opens the folder in the users favorite editor from the preview.

This should be simple, as this functionality has already been implemented in the error overlay: https://github.com/remotion-dev/remotion/blob/a255b47c0daa632e4fbb49675853dff618a42788/packages/cli/src/preview-server/error-overlay/remotion-overlay/OpenInEditor.tsx
