### ISSUE TITLE
Get cost in Webhook response

### ISSUE THREAD

**Issue by TharakaSl** [remotion-dev/remotion#1563]
# Feature Request 🛍️

Currently we can get the costs in getrenderprogress response
https://www.remotion.dev/docs/lambda/getrenderprogress

but in Webhook response we cants see costs not sending in 
https://www.remotion.dev/docs/lambda/webhooks

Can we have cost in Webhook response as well ?

**Comment by JonnyBurger** [comment]
Planning to implement!
