### ISSUE TITLE
cancelRender()

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1565]
Like delayRender() and continueRender(), but if called, your render *immediately* stops.

Can be used to flag a failure.

**Comment by kaf-lamed-beyt** [comment]
So @JonnyBurger,

Where would the `cancelRender()` function go? I'm guessing [packages/src/core](https://github.com/remotion-dev/remotion/tree/main/packages/core/src)?

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Yes, alongside delayRender()! It can be it's own file though
