### ISSUE TITLE
Use URL time fragments for displaying the time in the video

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1572]
See here: https://stackoverflow.com/questions/56428378/no-way-to-preload-first-video-frame-on-ios-safari
And the spec: https://www.w3.org/TR/media-frags/

We can append a fragment to the end of the video and it will get preloaded. `#t=0.5`

Moreso, we can signal when the video ends. We know the composition has a fixed duration, and therefore we can save resources by signaling to the browser it does not have to fetch the end of the video:

http://www.example.org/video.ogv#t=60,100

## Acceptance criteria

- Update the `VideoForDevelopment` component to, if there is no URL fragment specified, append a URL fragment to the URL to signal the expected portion of the video.
- The time must be specified in seconds and both start and end should be correctly calculated
- It should work for both raw URLs and URLs that have been prefetched().
- If the URL already has a fragment, nothing should be appended to the URL.
- Nothing should be done for Base64 URLs.

**Comment by faisalsayed10** [comment]
I can take this up

**Comment by MehmetAdemi** [comment]
Go for it @faisalsayed10! 😊

**Comment by JonnyBurger** [comment]
Doesn't seem to work, we'll payout once @MehmetAdemi is back. In the meanwhile you can create an Algora account!

**Comment by MehmetAdemi** [comment]
Thanks for the contribution!
I'm facing an issue with the payment. I submitted a report to Algora. They solve it by themselves or might come directly back to @faisalsayed10. Sorry for the hassle. Let's keep each other updated, OK?

**Comment by faisalsayed10** [comment]
Yeah, sure!
