### ISSUE TITLE
The rendering block the audios or videos if you increase the speed of one them 

### ISSUE THREAD

**Issue by Natega** [remotion-dev/remotion#1585]
If you put 2+ audios or (1video and 1audio) or 2 videos. 
And increase the speed "playbackRate" of one them. 
And this speedy audio finishes before the end of composition. 
All other audios block at this end of the first one.    

Explanation in video:
https://youtu.be/2ve8s9tt2AU

Component to reproduce the bug 
```
import {
	AbsoluteFill,
	Audio
} from 'remotion';

 

export const HelloWorld: React.FC<{
	titleText: string;
	titleColor: string;
}> = () => {
	/**
	Audio 1
	playbackRate => 16 very short song 
	 
	Audio 2
	playbackRate => 1 around 2 mins of music
	 */
	return (
		<AbsoluteFill style={{backgroundColor: 'white'}}>
		
		<Audio src={"http://127.0.0.1:8080/Nouveau%20dossier/lofi-rhodes-for-introoutro-0132-12949.mp3"} playbackRate={16} /> 
		<Audio src={"http://localhost:8080/Nouveau%20dossier/ambient-technology-12165.mp3"} playbackRate={1} />
		</AbsoluteFill>
	);
};
}
```

Demo of the bug with 2 song 
https://youtube.com/shorts/ZXanlnRY7XM

**Comment by JonnyBurger** [comment]
Thanks for helping resolve this issue! 🙌
