### ISSUE TITLE
What breaking changes should be made for Remotion v4?

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1602]
In the next major version, we can modernize Remotion and make some breaking changes. My suggestions:

- [x] Drop Node 14 and Node 15 support --> https://github.com/remotion-dev/remotion/pull/1824
- [x] Drop Lambda x64 support --> https://github.com/remotion-dev/remotion/pull/1825
- [x] ~~Migrate to ES Modules~~ --> Make this separate
- [x] Change `renderMedia()` return signature to return an object, not a buffer, and remove the 'slowest frames' callback and instead return it in renderMedia() --> #1826 

As I get more ideas, I will write them in here!

**Comment by JonnyBurger** [comment]
- Rename `quality` to `jpegQuality`

**Comment by JonnyBurger** [comment]
Google fonts should use export patterns instead of exporting each font individually

**Comment by JonnyBurger** [comment]
Still image format and Video image format should be two separate options

**Comment by JonnyBurger** [comment]
default props should also become mandatory in `<Composition>`

**Comment by JonnyBurger** [comment]
Remove "Rich timeline" mode, it is problematic

**Comment by with-heart** [comment]
> Remove "Rich timeline" mode, it is problematic

😭

I have felt what's problematic about it and totally understand this but I was wondering if you could go into more detail about the problem.

**Comment by JonnyBurger** [comment]
@with-heart The main reason is that we have an easy to use button that might kill the performance of the preview. If you toggle this button for a graphics-intensive app, then the whole app can render multiple times including network requests and console.logs.

This is also the reason why we limit the amount of timeline tracks to 15 which is just a workaround to keep the performance alive. IMO this is a "footgun" where it's way too easy to get into this problem, at least from what I've see after we launched the feature.

**Comment by JonnyBurger** [comment]
Should Webpack be replaced with Vite?

**Comment by JonnyBurger** [comment]
ProRes should use uncompressed audio by default

**Comment by JonnyBurger** [comment]
h264-mkv should be broken up into two options: codec and audio-codec

**Comment by JonnyBurger** [comment]
Remove options that were deprecated a while ago

**Comment by 0xflotus** [comment]
> Should Webpack be replaced with Vite?

Did you considered to switch to [Turbopack](https://turbo.build/pack)?

**Comment by JonnyBurger** [comment]
@0xflotus Nope, it has no docs/APIs for framework developers, therefore we cannot use it.

**Comment by JonnyBurger** [comment]
Drop React 17 support

**Comment by JonnyBurger** [comment]
Remove Remotion legacy config proxy

**Comment by JonnyBurger** [comment]
It should be documented that the default video image format is now JPEG when rendering via Node.JS APIs

**Comment by JonnyBurger** [comment]
Dockerfile page should not install FFmpeg anymore - test that it still works

**Comment by JonnyBurger** [comment]
onBucketEnsure is kinda pointless

**Comment by JonnyBurger** [comment]
rmdirSync() is deprecated in favor of rmSync()

**Comment by JonnyBurger** [comment]
`<Img>` should call cancelRender() if image fails to lod

**Comment by JonnyBurger** [comment]
- [ ] `staticFile()` should handle URL-unsafe characters better, e.g. by calling encodeURIComponent

**Comment by JonnyBurger** [comment]
- [ ] Schema should be validated if users renders a video and passes input props, or at least give an option for it

**Comment by JonnyBurger** [comment]
- [ ] Make a better solution for dynamically calculating the duration, fps and dimensions of a compositions without having to use an useEffect()

**Comment by JonnyBurger** [comment]
It's out
