### ISSUE TITLE
Option to not open browser on `remotion preview`

### ISSUE THREAD

**Issue by windowsdeveloperwannabe** [remotion-dev/remotion#1605]
# Feature Request 🛍️

It might be useful to add a command line flag to not open browser when running `remotion preview`. 🙂

## Use Case

For those who use a separate browser for dev than operating system default it might be better for remotion to just print the usual `Server ready - Local: http://localhost:3000` message and let us open the browser ourselves.

**Comment by JonnyBurger** [comment]
Good idea, planning to implement!

**Comment by thepiark** [comment]
Adding the value of `BROWSER=none` to `.env` works on React project, but not on Remotion. Maybe use that env value because React supports it and other devs may be used to it?

**Comment by JonnyBurger** [comment]
@thepiark Good idea!
