### ISSUE TITLE
Are there any plans to locally render the video in the browser

### ISSUE THREAD

**Issue by reactone** [remotion-dev/remotion#1607]
Are there any plans to implement local rendering in the browser? In the ideal scenario rather than using lambda for rendering (which means costs, limitations, queues, etc)  it could be rendered in the browser. It's definitely possible because they are doing just that - https://img.ly/video-sdk @JonnyBurger

**Comment by JonnyBurger** [comment]
Hi @reactone! I have written about it in more detail here:
https://remotion.dev/docs/miscellaneous/render-in-browser

I suppose img.ly is using a canvas-based renderer.
