### ISSUE TITLE
Template copied icon on homepage does not respect dark mode

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1608]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/1629785/209356649-8f883c1f-c5f5-42e3-96cb-14c5b9df8966.png">

**Comment by KarthikRaju391** [comment]
Hey @JonnyBurger, I would love to fix this issue!

**Comment by JonnyBurger** [comment]
@KarthikRaju391 This would be much appreciated! 😊

**Comment by KarthikRaju391** [comment]
Hey @JonnyBurger, I am finding it a bit confusing where to find the template page. Can you let me know where it is?

**Comment by JonnyBurger** [comment]
@KarthikRaju391 looks like it's in `packages/docs/src/components/CommandCopyButton.tsx`

**Comment by KarthikRaju391** [comment]
Thank you so much!
