### ISSUE TITLE
Can't add .mp3 <Audio />  to <Player /> 

### ISSUE THREAD

**Issue by selemessaied** [remotion-dev/remotion#1611]
I'm having an issue: "random.js:39 Uncaught Error: random() argument must be a number or a string
    at random (random.js:39:11)" while adding an MP3 audio from URL to <Player />, I tried with video from URL it works, I'm only having this issue with audio.

Second error:

The above error occurred in the <ForwardRef(AudioForDevelopmentForwardRefFunction)> component: at AudioForDevelopmentForwardRefFunction

# Bug Report 🐛

Deps:

"typescript": "^4.6.4",
"vite": "^3.2.3"
"remotion": "^3.3.5",
"react": "^18.2.0",
"@remotion/cli": "^3.3.5",
"@remotion/media-utils": "^3.3.5",
"@remotion/player": "^3.3.5",

**Comment by JonnyBurger** [comment]
Post the code snippet that is causing this?

**Comment by selemessaied** [comment]
VideoComponent.tsx

```
                 <Player
                  component={MyComposition}
                  inputProps={{
                    text: scene.text,
                    captions: scene.captions,
                    audio: scene.audio,
                    video: scene.video
                  }}
                  errorFallback={errorFallback}
                  durationInFrames={300}
                  compositionWidth={1920}
                  compositionHeight={1080}
                  fps={30}
                  style={{
                    width: 350,
                    height: 350
                  }}
                  controls
                />
```

MyComposition.tsx

```
  <AbsoluteFill className="flex items-center justify-center">
      <Captions text={captions} />
      {audio && <Audio src={audio} />}
      {video && <Video muted src={video} />}
    </AbsoluteFill>
```

Root.tsx


```
<Composition
        id="Empty"
        component={MyComposition}
        durationInFrames={150}
        fps={30}
        width={1080}
        height={1920}
      />
```

**Comment by JonnyBurger** [comment]
Can you log `audio` variable? What is it?

**Comment by selemessaied** [comment]
Well, just found out that I was sending an array of URLs not a single string 🤦🏻‍♂️

You may actually close this, and many thanks to you @JonnyBurger for being so active and responsive! Your work has really impressed me!

**Comment by JonnyBurger** [comment]
@selemessaied Nice! Happily!

Made a PR to harden it even more so you get an error for it: #1616
