### ISSUE TITLE
Importing or Requiring webpack in the webpack-overrides.ts file, throws errors

### ISSUE THREAD

**Issue by mykeels** [remotion-dev/remotion#1612]
# Bug Report 🐛

I am trying to experiment with loading a composition over a URL, so I want to use module federation in the generated webpack-overrides.ts file.

However, as soon as I require/import webpack with any of:

- `import webpack = require('webpack')`
- `import * as webpack from 'webpack'`
- `const { container } = require('webpack')`

A bunch of errors are thrown, such as:

```
ERROR: Could not resolve "pnpapi"
ERROR: Could not resolve "uglify-js"
ERROR: Could not resolve "@swc/core"
"./processChild" should be marked as external for use with "require.resolve"
``` 

See actual console output:

![image](https://user-images.githubusercontent.com/11996508/209479909-ab0c3ea0-d86d-476c-aa1b-05342dea38a7.png)
![image](https://user-images.githubusercontent.com/11996508/209479914-df41086b-3c9e-4448-b5e8-c684e03b36ac.png)
![image](https://user-images.githubusercontent.com/11996508/209479918-75b46519-fec4-410f-9c93-55841f247cc2.png)

## Question

I noticed the bundler uses both esbuild and webpack, so perhaps there is some interplay going on between these bundlers, that prevents requiring webpack from working out of the box? Some pointers would be helpful.

**Comment by JonnyBurger** [comment]
I managed to fix it with #1621, ESBuild has a new option to exclude all dependencies from the bundle which is exactly what we need.

If you have good or bad experiences, I'd be happy to know about it, as we are considering supporting it as well! #1326
