### ISSUE TITLE
Create an article explaining how to use Remotion Lambda with SQS

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1619]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24200%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/1619)

## Acceptance criteria

Create an article with step by step instructions on how to queue renders with Remotion Lambda using AWS SQS that a user with no prior knowledge is able to follow.

## Note about bounty
Note that IssueHunt will take 10% commission, so you'll get approximately $180.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $200.00)

- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($200.00)

### Submitted pull Requests
- [#1787 1619 sqs remotion](https://issuehunt.io/r/remotion-dev/remotion/pull/1787)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by sarthakkathpalia** [comment]
Hey @JonnyBurger  . Would like to work on this issue !

**Comment by JonnyBurger** [comment]
@sarthakkathpalia Happily! Good luck 🙂

**Comment by sarthakkathpalia** [comment]
Hey! This one's taking me a lil time, still on it 😊

**Comment by JonnyBurger** [comment]
@sarthakkathpalia It's okay! Thanks for the `keepalive`!

**Comment by JonnyBurger** [comment]
Hey @sarthakkathpalia! Are you making any progress? Asking because @alexfernandez803 also has knowledge about it and would like to pick it up if it is stuck.

**Comment by sarthakkathpalia** [comment]
Hello @JonnyBurger 👋 
So I tried but I think it's taking too long for me to understand SQS and other things. For this one I am unassigning myself. Thanks for showing faith and assigning it to me. Will definitely try to contribute in future issues of Remotion 😊
Regards

**Comment by alexfernandez803** [comment]
@JonnyBurger  I'll take this one then.

**Comment by JonnyBurger** [comment]
@alexfernandez803 Happily, thanks!

**Comment by MehmetAdemi** [comment]
Thanks, @alexfernandez803!
