### ISSUE TITLE
Make editor contexts independent from each other

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1642]
Right now clicking one button triggers rerender of all editor contexts in `EditorContext.tsx`. Should refactor each context to be independent

**Comment by Tonie-NG** [comment]
@JonnyBurger Could you throw more light on this issue?

**Comment by JonnyBurger** [comment]
Many functionalities are using the same context, which means if one setting changes, many updates are happening. We can optimize it by spreading it out

**Comment by JonnyBurger** [comment]
Implemented in the `v4` branch!
