### ISSUE TITLE
"recursive": true in fs.watch() raises ERR_FEATURE_UNAVAILABLE_ON_PLATFORM on Linux

### ISSUE THREAD

**Issue by gregonarash** [remotion-dev/remotion#1649]
@JonnyBurger first: What a fantastic project!!! 🙌🎉🙏  I started playing with it recently and building a small project - hope to share soon on discord!

# Bug Report 🐛

### Background 
Between 3.3.25-3.3.26 you have introduced function `watchPublicFolder` (in `packages/cli/src/preview-server/public-folder.ts`)

Git diff: https://github.com/remotion-dev/remotion/compare/v3.3.25...v3.3.26

It uses `fs.watch` and `{recursive: true}`

### Error

On my system: WSL 2 Ubuntu 20.04, Node v18.13

After upgrading to 3.3.26 or 3.3.27
`npx remotion preview` results in

```
An error occurred:
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at new NodeError (node:internal/errors:400:5)
    at watch (node:fs:2313:11)
    at watchPublicFolder ( /projects/remotion/node_modules/@remotion/cli/dist/preview-server/public-folder.js:31:20)
    at initPublicFolderWatch ( /projects/remotion/node_modules/@remotion/cli/dist/preview-server/public-folder.js:13:35)
    at previewCommand ( /projects/remotion/node_modules/@remotion/cli/dist/preview.js:91:47)
    at async cli ( /projects/remotion/node_modules/@remotion/cli/dist/index.js:68:13)

```

### Issue

Looks like the recursive feature is not supported on Linux.

From [Stackoverflow] (https://stackoverflow.com/questions/61806341/how-to-fix-the-feature-watch-recursively-is-unavailable-on-the-current-platform)

> Node v14 introduced a breaking change to the fs.watch() API, specifically that the recursive option (which has never been supported on Linux) [now raises the ERR_FEATURE_UNAVAILABLE_ON_PLATFORM error if used on Linux](https://nodejs.org/docs/latest/api/fs.html#fs_caveats).

From [Node documentation] (https://nodejs.org/docs/latest/api/fs.html#fswatchfilename-options-listener):
> recursive [<boolean>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type) Indicates whether all subdirectories should be watched, or only the current directory. This applies when a directory is specified, and only on supported platforms (See [caveats](https://nodejs.org/docs/latest/api/fs.html#caveats)). Default: false.

 ### Solution
 
 I am way out of my depth here, but I have seen two possibilities:
- use {chokidar)[https://github.com/paulmillr/chokidar] instead of fs.watch, it will stop error from happening on Linux, but I have no experience with this library   
- turn of recursive option in case of `process.platform === "linux"`

I did not look on the implication of removing the "recursive", so I won't dare to submit any PR, but I hope this is helpful!

Thank you guys!

**Comment by JonnyBurger** [comment]
@gregonarash Thanks a lot for the nice words even though you encountered an issue!

Acknowledged, and will fix tomorrow as the highest priority issue 🫡
