### ISSUE TITLE
`remotion render --sequence` fails when output path starts with a dot

### ISSUE THREAD

**Issue by akx** [remotion-dev/remotion#1651]
# Bug Report 🐛

```
$ yarn remotion render Foo ./out --crf 19 --muted --sequence
The output directory of the image sequence cannot have an extension. Got: /out
```

I suppose whatever determines whether a pathname has an extension shouldn't think that leading dots are part of an extension. (Also, why wouldn't `./out/foo.1.2.3` be a valid directory name?)

**Comment by JonnyBurger** [comment]
You are right, thanks for filing !Acknowledge the bug, will try to fix it soon!
