### ISSUE TITLE
Concurrency in percent

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1652]
I think extending the API of the `concurrency`property in the `renderMedia()` function by a percentage value would be a great addition, for example `100%` using all CPU Threads avaibale on the machine.

**Comment by JonnyBurger** [comment]
Should work via CLI and Node APIs. renderFrames/renderMedia node APIs. Needs documentation and should reject invalid values!

@MehmetAdemi $100 bounty?

**Comment by JRavi2** [comment]
Hey, can I take this?

**Comment by MehmetAdemi** [comment]
Hi Ravi, sure. Let's go!

**Comment by JRavi2** [comment]
Need a little clarity on the task.
Do we want to introduce a new property that takes in the concurrency in percentage, or, should the working of the existing `concurrency` property be modified to work with percentage input instead of the thread count?

**Comment by akx** [comment]
It should be noted that a (Bash) user could just do e.g.

```
remotion render --concurrency $(($(nproc) * 40 / 100))
```
for the same effect as `40%`.
