### ISSUE TITLE
Multiple versions warning can come up when loading the same version twice

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1669]
In Next.JS when fast refreshing. We should investigate this I guess!

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger,

I'd love to work on this. Would this be something you may want to put me through?

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt If you know what causes the problem to occur, happily! I think that is the problem right now - lack of a good repro of this problem

**Comment by kaf-lamed-beyt** [comment]
I see. I may not be able to take this on, since there's no proper reproduction of the issue yet, maybe I should just pick another issue. Which one would you recommend I jump on?

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Thanks so much! How about https://github.com/remotion-dev/remotion/issues/1565? For now it could just be a function that throws an error.

**Comment by kaf-lamed-beyt** [comment]
Niceee! I'll have a look now.

**Comment by JonnyBurger** [comment]
We have fixed this now by not throwing the error if it is the same version. This is something that happened in ESM mode I believe

**Comment by kaf-lamed-beyt** [comment]
Why does ECMA have to be the problem everytime. 

Glad that this has been fixed now, though! 🎊🚀🚀

**Comment by JonnyBurger** [comment]
Rant about this is coming :P
