### ISSUE TITLE
`@remotion/shapes` package

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1674]
Idea:

Make a new `@remotion/shapes` package that allows to draw common shapes in SVG, like `<Square>`, `<Triangle>`, `<Circle>`.
A component like `<Star>` would also have props to control the amount of points.

## Readiness for SVG-only rendering mode
In the future, we will also support a "SVG-only" rendering mode where instead of HTML, you can return SVG and the render will be much faster and not rely on Google Chrome. This mode will require a singular SVG tag to be returned. Therefore it would make sense that the `@remotion/shapes` package either does only return a `<path>` or has an option to omit the top-level `<svg>` component.

## Documentation
Each component should have a section in the docs with all the props it supports, and an example.
A page with installation instructions should also be created and it should list the table of contents. It can be adapted from https://remotion.dev/paths.

## Path-only mode
It would be useful to have functions like `makeSquare()`, `makeTriangle()` which only return the path. The `<Triangle>` component would then call `makeTriangle()`. 

- It is useful for path manipulation using `@remotion/paths`.
- It is useful for passing the paths into Rough.JS

## Acceptance criteria

Implement at least two shapes in a new package and document it according to the design in this issue.

**Comment by alexfernandez803** [comment]
@MehmetAdemi  can I take this?

**Comment by JonnyBurger** [comment]
@alexfernandez803 You got it!
