### ISSUE TITLE
Transparent @remotion/gif renders frames on top of each other

### ISSUE THREAD

**Issue by victorbalan** [remotion-dev/remotion#1678]
When using `@remotion/gif` with a transparent background gif it renders each gif frame on top of each other instead of refreshing the canvas for each render.

This is the resulting video of a transparent background gif:
<img width="92" alt="image" src="https://user-images.githubusercontent.com/9076766/212316493-0891a847-8ab2-4fc0-9e86-1a03f2a69e6b.png">

and this is how it should look like in the end: 
<img width="119" alt="image" src="https://user-images.githubusercontent.com/9076766/212316580-61f48240-2caa-4724-bbcb-10724476c5ef.png">

Is this a limitation of the Gif component? Is there any known workaround for this?

**Comment by JonnyBurger** [comment]
Thanks! Might indeed be a bug, can you post the reference GIF?

**Comment by victorbalan** [comment]
There you go

![1dpmw](https://user-images.githubusercontent.com/9076766/212657745-a6e4e16c-e014-4469-b014-0cf0133ef8b3.gif)

**Comment by JonnyBurger** [comment]
Thanks, was able to track down the issue because of this!
