### ISSUE TITLE
Ease Player controls gradient

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1681]
Like https://twitter.com/jaffathecake/status/1612766262064455681?s=46&t=d92JEcELcBvrKmSiu_prJw

**Comment by CruuzAzul** [comment]
Hi @JonnyBurger I also saw this little problem on the player, I can take a look to do like the example if you want ? 😉

**Comment by CruuzAzul** [comment]
Would something like this be good? I've taken some of what was in the example and adapted some values 😊

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/60877626/212567379-e6a35b13-e4c0-48a3-94fd-f1a402b4a334.png">

**Comment by JonnyBurger** [comment]
@CruuzAzul Awesome, thanks for taking this on!
I think the gradient is now smoother, nice! But it is very dark, how about making it a bit lighter?

**Comment by CruuzAzul** [comment]
@JonnyBurger is it better this way ? 😊 If it's good I can make a pull request 🎫

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/60877626/214242207-2a6a99cd-acfd-4f13-a1c8-a6b0de1519d3.png">

**Comment by JonnyBurger** [comment]
Yes much better, still quite the difference in darkness! Is it a legibility concern?

Feel free to open a PR 😇

**Comment by CruuzAzul** [comment]
I will open the PR to look at the final adjustments

**Comment by JonnyBurger** [comment]
Fixed by #1742
