### ISSUE TITLE
Remotion cannot be imported if `esm` module is required

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1684]
See: https://github.com/standard-things/esm/issues/924

As a workaround, we may be able to add a version.js nonetheless

**Comment by jmaguirrei** [comment]
@JonnyBurger
Given that esm has not solved the issue and the lambda issue happened today (https://www.remotion.dev/docs/lambda/feb-2023-incident) I must upgrade to remotion version 3.3.54, but I need to avoid this esm issue first.
Is it possible add version.js in next version?
Thanks

**Comment by JonnyBurger** [comment]
@jmaguirrei I'll try to prioritize it and get it working soon!
Can you for now use the alternative workaround with locking the version in the console for now? I'll make sure to not have you do it for long! Sorry

**Comment by jmaguirrei** [comment]
Yes! But I cannot find the config option, I write you on discord

**Comment by jmaguirrei** [comment]
My mistake, I can confirm it works fine
