### ISSUE TITLE
Docs say `Config.Preview.setShouldOpenBrowser` defaults to `false`, but starting the preview always opens a browser window

### ISSUE THREAD

**Issue by fwextensions** [remotion-dev/remotion#1686]
# Bug Report 🐛

- Run `npm run start` in the console

Result: a new browser tab opens to show the preview on localhost, even though [the docs](https://www.remotion.dev/docs/config#setshouldopenbrowser) say the default is `false`.

Adding `Config.Preview.setShouldOpenBrowser(false);` to the `remotion.config.js` file and then running the preview *does* prevent a tab from being opened.  So either the code has a bug or the docs are wrong.

**Comment by JonnyBurger** [comment]
True! Thanks for reporting!
