### ISSUE TITLE
Horizontal scrollbar appears in `TimelineScrollable` area of preview when the frame indicator is on the far right edge

### ISSUE THREAD

**Issue by fwextensions** [remotion-dev/remotion#1688]
# Bug Report 🐛

When the preview is paused, press right-arrow to move the red frame indicator to the very last frame.  Then press it one more time, which will cause the indicator to move just to the right of any sequence bars.  At that point, a horizontal scrollbar appears, because it seems like the indicator's handle is slightly outside the timeline's bounds.

This is only really noticeable when scrollbars are on by default, as they are on Windows.  Setting `overflow-x: hidden` on the timeline  container would remove the scrollbar, which doesn't seem necessary to actually scroll to any hidden content.

![image](https://user-images.githubusercontent.com/61631/212620358-6f6ff01c-59c8-4fb5-86d9-09add51d8155.png)

**Comment by JonnyBurger** [comment]
There is a bug indeed, thanks for reporting!
