### ISSUE TITLE
`@remotion/paths`: translatePath()

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1711]
It would be handy to have a function in `@remotion/paths` which takes a path and adds X / Y translation to it.

Could use this code: https://github.com/michaelrhodes/translate-svg-path/blob/master/index.js and re-use the path parsing patterns already existing in `@remotion/paths`.

Should also have 1-2 basic unit tests and a new documentation article like the other path functions.

**Comment by alexfernandez803** [comment]
@MehmetAdemi  if no one take this, I'll take it.

**Comment by JonnyBurger** [comment]
@alexfernandez803 Happily, good luck!

**Comment by MehmetAdemi** [comment]
Thanks @alexfernandez803!
