### ISSUE TITLE
`create-video`: disallowing project creation if inside `git` repo breaks my long-time workflow

### ISSUE THREAD

**Issue by with-heart** [remotion-dev/remotion#1729]
# Bug Report 🐛

The recent work in #1713 currently breaks the workflow I've used to manage most code on my machines over the last 5 years! Here's what happens:

- I store [my dotfiles](https://github.com/with-heart/home) in `~` using `git`
- I store all code in `~/code` or `~/github` (which are listed in `~/.gitignore`)
- Attempting to create a new project in either folder throws an error because we're "inside" a `git` repo (even though the directories are ignored)

I think there are a couple of separate issues + maybe a feature request or two hidden in here?:

- we shouldn't fail if user is already inside a `git` repo because there are legitimate use cases for doing so (+ I can't think of another tool I've used that has blocked my workflow like this)
- if creating a repo inside of another repo is meant to protect users from accidentally doing so, we might want to consider using a warning + prompt instead of an outright failure
- if in a `git` repo, we should detect if the directory is ignored by that repo and allow project creation if so
- if none of the above is feasible, we should add an override flag (`--ignore-git`? so much potential for bikeshedding! 🎉) to `create-video` so that users who know what they're doing can create the project anyway

**Comment by JonnyBurger** [comment]
Thanks for the user story!
I'll include a prompt in the next version that will still allow you to create a project if you dismiss a warning.

**Comment by with-heart** [comment]
Thank you Jonny! Much appreciated! ❤️
