### ISSUE TITLE
Remotion <Player /> triggers React hooks error when used alongside <Thumbnail /> and <Img />

### ISSUE THREAD

**Issue by matt-sanders** [remotion-dev/remotion#1730]
# Bug Report 🐛

This issue only happens in production.

To reproduce, create a simple component that returns Remotion's `<Img />` component. On the page, display this component using a `<Thumbnail>` component exported from `@remotion/player`. Then display and hide a `<Player />` component. You'll see that `<Thumbnail />` throws [this error.](https://reactjs.org/docs/error-decoder.html/?invariant=300)

I've created a [sample project](https://github.com/matt-sanders/remotion-img-hook-error) and you can see the error in the [live preview](https://remotion-img-hook-error.vercel.app/). Note that it only happens when running in production.

Under the hood I think I've narrowed it down to the following issues. Firstly, `remotion/Img.tsx` uses `useLayoutEffect` inside a conditional. See [lines 48 - 74](https://github.com/remotion-dev/remotion/blob/1ac8aad0e1e1fa2a465936e63a143f1e0a902dbf/packages/core/src/Img.tsx#L48-L74). React states that you should not use hooks inside a conditional statement.

The reason we only see this in production is because `getRemotionEnvironment` is set [differently in production](https://github.com/remotion-dev/remotion/blob/1ac8aad0e1e1fa2a465936e63a143f1e0a902dbf/packages/core/src/get-environment.ts#L8-L14). I believe that before the player is open, `window.remotion_isPlayer` is undefined, and when it's rendered, the Remotion player sets this variable. It is also unset when the component is removed, but in the example the `<Thumbnail />` is mounted _before_ the player has time to remove the variable. This results in the `useLayoutEffect` being run conditionally which causes the error.

The temporary fix is to remove the `<Thumbnail />` while the `<Player />` is visible, which means that by the time the `<Thumbnail />` is remounted, the `<Player />` has had time to remove the `window.remotion_isPlayer` variable.

Hopefully that helps to narrow it all down, let me know if you need any extra info, thanks!

**Comment by JonnyBurger** [comment]
Thanks a lot for providing a bug report and also finding out the reason at the same time!
I made it so it does not depend on the `window` variable which indeed seems like a bad idea.

So now it uses React context!

**Comment by matt-sanders** [comment]
Thanks so much!
