### ISSUE TITLE
Document how to use Lambda with serverless.com

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1738]

**Comment by MehmetAdemi** [comment]
Hi @alexfernandez803, this one is for you! 
Let me know if there is any review needed at the end. 🙌🏽

**Comment by alexfernandez803** [comment]
Thanks for this, this only covers remotion in AWS via Serverless.com

**Comment by JonnyBurger** [comment]
@MehmetAdemi Ready to reward 🫡
