### ISSUE TITLE
Can we support a `<video>` tag with HLS?

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1749]

**Comment by JonnyBurger** [comment]
The main reason to support this is to avoid downloading the whole video.

With FFmpeg, it looks like it still has to download a lot of portions of the video and since it is remote, we either have to do it for every frame, or download the entire video once.

Instead of implementing this now, I hope that we can enable better efficiency with the new Rust + Layers infrastructure where we can determine beforehand what's needed and then download only what's needed.

**Comment by koenvo** [comment]
Hi @JonnyBurger!

First, thanks for this great library!

We have some videos that are stored as HLS streams (VOD). I could try to create a work-around to download the files and replace urls before starting the render but that feels very hacky (and need to make sure they end up in the public folder).

Some work seems to be done in https://github.com/remotion-dev/remotion/blob/f7f1035374e65132eb2c5c2dca92693349a1589f/packages/docs/src/components/MuxVideo.tsx but this will/should give errors during rendering phase.

It seems that a change in https://github.com/remotion-dev/remotion/blob/f7f1035374e65132eb2c5c2dca92693349a1589f/packages/renderer/src/ensure-presentation-timestamp.ts#L68-L79 might solve it. 

Would you be open for a PR to make this work in the meanwhile?

**Comment by JonnyBurger** [comment]
Hi @koenvo!

It is true that OffthreadVideo could support HLS streams by downloading the video using HLS, but this would have a few caveats:

- FFmpeg still will just download the whole video, negating the benefits of HLS
- It also doesn't play in the Preview.

So it is not ideal and while we could support it (maybe it inadvertedly already does?), it would only be a patch for those who only have HLS available.

Currently, in the branch for Remotion 4.0, we have a custom FFmpeg binary that does only include a few supported codecs, HLS is not one of them. If business critical and no other workarounds available, we could enable it there as well.
