### ISSUE TITLE
Flat config file

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1764]
Currently, the config file works like this:

```ts
Config.Puppeteer.setChromiumOpenGlRenderer('angle');
```

I and others find it cumbersome to discover all the options by having to trigger TS autocompletion for every category.
It would be better if you can just do:

```ts
Config.setChromiumOpenGlRenderer('angle');
```

## Notes

- The old behavior should also be possible for now for backwards compatibility
- The documentation needs to be updated
- Note the config type is in `packages/core/src/config.ts` but the implementation is in `packages/cli/src/config/index.ts`.

## Contributors guide

https://remotion.dev/docs/contributing

**Comment by alexfernandez803** [comment]
can I take this one?

**Comment by JonnyBurger** [comment]
@alexfernandez803 Yes! If you want the SQS one also became available, you can choose one at a time.
