### ISSUE TITLE
Confusing statement in docs

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1779]
![image](https://user-images.githubusercontent.com/1629785/216444810-17247a9b-3080-4834-92b6-a3fdd2255546.png)

**Comment by CruuzAzul** [comment]
@JonnyBurger You just want to change the text that describes the code to make it clearer ? If so, I can change that 😊

**Comment by JonnyBurger** [comment]
@CruuzAzul Yes, it is actually wrong because a `<Sequence>` by default is already positioned absolutely, so the layout would not shift anyway

**Comment by JonnyBurger** [comment]
If you take this on, it is appreciated! 😊

**Comment by CruuzAzul** [comment]
I take it 😉

**Comment by JonnyBurger** [comment]
Closed by #1838
