### ISSUE TITLE
Add an option to not make the Player UI disappear

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1790]
> Is there an option to make the controls of the player fixed and not let them disappear when the mouse is outside the player? I think it might be useful as some sort of "watermark", preventing users from screen-recording videos instead of rendering them (assuming the business model of your project is based on a fee per render)

**Comment by CruuzAzul** [comment]
Is it interesting knowing that people can remove it from the browser console ? 😊

**Comment by JonnyBurger** [comment]
Yes, not a very sophisticated piracy protection... nonetheless I think we can support this feature!

/bounty 75

**Comment by JonnyBurger** [comment]
Acceptance critera:

- Add a new prop that prevents the player UI from disappearing.
- Add the prop to the player documentation.
- Add a toggle to the testbed in the `player-example` folder.

**Comment by CruuzAzul** [comment]
I'm willing to try to do this if possible 😊

**Comment by JonnyBurger** [comment]
@CruuzAzul Good luck!
