### ISSUE TITLE
Link documentation in JSDoc

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1796]
Like In NextAuth.js, they link the documentation for every API. You can do it providing a simple markdown link. We should do it as well!

**Comment by kaf-lamed-beyt** [comment]
@JonnyBurger I'd love to fix this when #1767 is marked as complete

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger 👋🏼, 

I'm circling back to this comment. ICYMI

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Sorry for the long wait! It would be very cool if you take it! :)

Here is a reference to get started: https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/index.ts#L76

In Next Auth, they add `@see` comments and then references to the homepage. Any one of these would be cool, no need to do this for all APIs of course!

**Comment by kaf-lamed-beyt** [comment]
Oh great! no big deal, and welcome back @JonnyBurger!

I took a look at the Next Auth example and I noticed that they're using the `@see` keyword in a TypeScript file of their API of some sort. Is this the same approach I am required to take? Since you said 👇🏼 

>  You can do it providing a simple markdown link

That means I'll have to add the corresponding links to all the APIs right here, in the `cli` folder, right? Or would it be for all the dirs in `packages`?

If that's the case, I actually have no problem doing it for all the APIs.

**Comment by JonnyBurger** [comment]
Thanks a lot!

Yes the same approach as NextAuth would be great! They also use a Markdown link.

We'd love to have it for all APIs that are public, so those who can be found on https://remotion.dev/api. The private ones are not required and they obviously also have no link.

**Comment by kaf-lamed-beyt** [comment]
Awesome! I'll get started, and update you as I progress 😎

**Comment by kaf-lamed-beyt** [comment]
Quick question, @JonnyBurger 

In the `useCurrentFrame()` API, I can see that the `@link` keyword is already being used here. Should I still go ahead with adding the `@see` keyword?

![image](https://user-images.githubusercontent.com/48127194/220708639-203d1bbf-bce2-4b3a-bf74-417417058d4d.png)

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt You can replace it! A clickable link is better than displaying the URL :)

**Comment by kaf-lamed-beyt** [comment]
Great! I'll get back to it now 🚀

**Comment by kaf-lamed-beyt** [comment]
I've completed the onboarding process @JonnyBurger, But this is what I am currently seeing. 👇🏼 

![image](https://user-images.githubusercontent.com/48127194/221411934-7882b8c4-6c7b-44ca-a65d-8e572931d55e.png)

How do I get the bounty? 😄

**Comment by JonnyBurger** [comment]
Like this 🎉

**Comment by kaf-lamed-beyt** [comment]
Oh!! Thanks, @JonnyBurger! 😆
