### ISSUE TITLE
can i render an animated SVG file with remotion? 

### ISSUE THREAD

**Issue by mtrud** [remotion-dev/remotion#1821]
I'am rendering an animated SVG file https://raw.githubusercontent.com/mtrud/testings/main/esc.svg

`import { Img } from "remotion";
  import logosvg from "./esc.svg";
 
export const MyComp: React.FC = () => {
  return < Im g src={logosvg} /> ;
};`
 
but the video is not smooth.. how can i improve it?

https://user-images.githubusercontent.com/122753872/219022378-37d0f0f0-b25f-4528-b3b4-af5302f97652.mp4

**Comment by JonnyBurger** [comment]
Hi @mtrud! Thanks for the question.

Remotion's tools are based around raster-based graphics, not vector based ones, since videos don't use vector formats. So this is unfortunately out of scope for Remotion!

**Comment by mtrud** [comment]
Thank you @JonnyBurger.. using ` --codec h265` helped a bit
