### ISSUE TITLE
Feat: Support `className` prop in `Sequence` element

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#1837]
# Feature Request 🛍️

I'm currently using tailwindcss with remotion, and it's inconvinient to have to pass `layout="none"` to the Sequence and add a direct child with the classNames that I would have added to the Sequence if it would've supported it. Since Sequence just renders a div/other element (I guess, since it also supports the style prop), I think it's a low-hanging fruit 🙃

## Use Case

As described above.

## Possible Solution

Alongside `style`, also support the `className` and other possibly `React.HTMLAttributes<HTMLElementThatSequenceIsUsingBehindTheScenesElement>` props.

cc: @JonnyBurger for visibility

**Comment by JonnyBurger** [comment]
Good idea, thanks for the issue 👍

**Comment by Just-Moh-it** [comment]
Thanks, @JonnyBurger, you're the best! 🔥
