### ISSUE TITLE
Last `<Series.Sequence>` `durationInFrames` should allowed to be `Infinity` 

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1840]
It is not allowed yet, but nothing is should speak against it

![image](https://user-images.githubusercontent.com/1629785/220098880-cde970e8-0215-497f-89bf-dd87f5df1d9e.png)

**Comment by JonnyBurger** [comment]
Acceptance criteria:

- Allow the last `<Series.Sequence>` to have a `durationInFrames` of `Infinity`, but not the previous ones
- Copy a test in `packages/core/src/test/series.test.tsx` and adapt it to test the new behavior
- Make all tests run in core if some break because of this
- Add the new behavior to the docs

**Comment by JRavi2** [comment]
Hi @JonnyBurger 
I'd like to work on this

**Comment by agustif** [comment]
Hey @JonnyBurger I took a look at this, but from the docs it seems that's the case by default if not passing any number. Any need to pass it explicitly? Otherwise if no durationInFrames is passed its duration is Inifinity in fact

```
### `durationInFrames`



_optional_



For how many frames the sequence should be displayed. Children are unmounted if they are not within the time range of display. By default it will be `Infinity` to avoid limit the duration of the sequence
```

**Comment by JonnyBurger** [comment]
@agustif Sorry, I have already assigned the bounty to @JRavi2 :(

I think you are referencing the documentation for `<Sequence>`, however this issue is about `<Series.Sequence>`. It is true that a sequence can have `Infinity` as the parameter for `durationInFrames`
