### ISSUE TITLE
Disable zoom in remotion's previewer (possibly using a CLI flag)

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#1853]
# Feature Request 🛍️

Currently, pinching/scrolling into the video preview (that appears when you run `remotion preview ./index.tsx`), triggers a zoom. This was recently introduced. However, I've had my setup in such a way that I use `@react-three/drei`'s `<OrthographicCamera />` component, which adds pan/zoom controls to the react-three fiber scene. 

However, the `<OrthographicCamera />`'s gestures conflict with those of Remotion's previewer. So an option to disable zooming/panning on the Remotion previewer would be super useful.

## Use Case

As explained above

## Possible Solution

Have a CLI argument `remotion preview ./index.tsx --disable-zoom` or something similar

**Comment by Just-Moh-it** [comment]
cc @JonnyBurger for visibility

**Comment by JonnyBurger** [comment]
Sounds good! The whole thing can be disabled in https://github.com/remotion-dev/remotion/blob/4e838d228cf9e6ae42e5ebe9376543d805d9f334/packages/cli/src/editor/components/Canvas.tsx#L87

This can become an entry in the menu like for example the transparency toggle: https://github.com/remotion-dev/remotion/blob/4e838d228cf9e6ae42e5ebe9376543d805d9f334/packages/cli/src/editor/helpers/use-menu-structure.tsx#L310

Adding a bounty if someone wants to grab it!

/bounty 125

**Comment by kaf-lamed-beyt** [comment]
I can take this, if you'd love me to @JonnyBurger

**Comment by Just-Moh-it** [comment]
Hey @JonnyBurger, thanks for the prompt response! 

Was mostly free this weekend. How about I take this bounty? Would love to finally contribute to the source code of Remotion and not just the docs, haha 🙃

**Comment by kaf-lamed-beyt** [comment]
> I can take this if you'd love me to @JonnyBurger

I think it'll be great if @Just-Moh-it takes this issue, @JonnyBurger. Since they opened it initially (and is interested in working on it), and there'd be a huge understanding of how to fix it.

**Comment by JonnyBurger** [comment]
Should I throw a coon 🤔

**Comment by kaf-lamed-beyt** [comment]
What's a coon? 😃

**Comment by JonnyBurger** [comment]
A coin 😄

**Comment by kaf-lamed-beyt** [comment]
Oh okay! 😂 I'm actually okay with @Just-Moh-it fixing it. I can just pick another issue, that I can make my contributions to.

**Comment by Just-Moh-it** [comment]
Thanks, @kaf-lamed-beyt! 🫂

Excited to work on this 🔥

Also, saw [this](https://rauno.me/interfaces#:~:text=To%20open%20immediately,click) the other day, and noticed Remotion's top menu had an `onClick` instead of `onMouseDown` 🙈 and I was unable to select something with just a single press, so I could bundle this minor fix with this PR 🙃

https://user-images.githubusercontent.com/48997634/221402545-0dae5626-339e-4ce8-9e7b-6f093c129038.mov

(notice I'm holding the mouse throughout the menu selection process, which is unfortunately prevented in Remotion's menu)

**Comment by kaf-lamed-beyt** [comment]
Remotion's menu? 

I don't quite get this @Just-Moh-it

**Comment by JonnyBurger** [comment]
Ok, thanks a lot for agreeing on this on your own! 😃 no coin needed then. This would be a nice papercut improvement @Just-Moh-it!
