### ISSUE TITLE
Add Devcontainer tutorial to docs

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1854]
https://github.com/openscript/remotion-devcontainer-template

Nice contribution by Robin on Discord

**Comment by kaf-lamed-beyt** [comment]
What should be done to this issue @JonnyBurger? I notice the link points to a remotion project

**Comment by JonnyBurger** [comment]
Easy mode: Add it to the resources docs: https://remotion.dev/docs/resources
Hard mode: Create a page which has the code but also adds some comments to it like https://www.remotion.dev/docs/docker. But the Devcontainer could be a lot simpler, only explaining the JSON and referencing the Docker page

**Comment by kaf-lamed-beyt** [comment]
Okay, great! I think I may just take a look at the "hard way" you mentioned. If I'm not able to carry it out. I'll circle back to the easy way.

BTW, upon clicking the /resources link, I'm getting an error. The page doesn't load. Perhaps it is my internet connection though. I'll also check if it is the same on my PC.

I'll update you about my progress.

**Comment by JonnyBurger** [comment]
Awesome @kaf-lamed-beyt - thanks a lot!

Pushing a fix now for the resources ink, thanks a lot for reporting that!

**Comment by kaf-lamed-beyt** [comment]
Anytime! 🫡

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger, 

I'm sorry for the late update. I was having an error, with `pnpm i` when I synced my forked repo with the main Remotion repo. Apparently, it was due to my connectivity.

I've been able to fix that, and I'm currently building all the packages. When it is done, I'll get started with this issue.

**Comment by kaf-lamed-beyt** [comment]
@JonnyBurger,

I'm trying to take the hard route here. But, I'm finding it a bit difficult to understand what the DevContainer example is all about. Perhaps you can explain a bit? 

So I know what I need to place in the README file.

**Comment by JonnyBurger** [comment]
I don't know either, I never used it! 

But that's okay, we can add documentation still ("To set up dev containers in VS Code, set up the following files" - basically describe the structure of the example repo).

If you really want to know, i'm sure you can find out more about devcontainers on the internet.

**Comment by kaf-lamed-beyt** [comment]
Okay, great! 

I guess I'll just add the example to the resources route 😄

**Comment by JonnyBurger** [comment]
Fixed by #1871
