### ISSUE TITLE
Face dedection while rendering

### ISSUE THREAD

**Issue by Pexeus** [remotion-dev/remotion#1861]
I am using [the face-api ](https://github.com/vladmandic/face-api/tree/master/demo) to dedect and track faces while rendering the video. In preview, this does work fine, however it doesnt during render (npm run build). I am using this logic for tracking.:

```
async function dedect() {
    await faceapi.tf.ready()
    await faceapi.nets.ssdMobilenetv1.loadFromUri(staticFile("models"))
    await faceapi.nets.faceLandmark68Net.loadFromUri(staticFile("models"))
    await sleep(1000)

    const video = document.querySelector("video")


    while(true) {
        await sleep(50)
        const detections = await faceapi.detectAllFaces(video)
        
        if (detections.length == 1) {
            const face = detections[0]
            const offset = (face._box._x + (face._box._width / 2)) / video.videoWidth

            video.style.objectPosition = `${offset * 100}% 0`
        }
    }
}
```
I do not get any Error messages. The function just seems to not run.

**Comment by JonnyBurger** [comment]
Some weird stuff going on.. seems like you are intentionally putting an infinite loop in your code?

Can you give me an example repo so I don't have to build the project out on my own?
