### ISSUE TITLE
Add a CORS testing tool to the serveUrl homepage

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1862]
Each serve URL has a homepage:

https://github.com/remotion-dev/remotion/blob/1e95c8cff20c99b469e46314d33363a77258ad43/packages/bundler/src/homepage/homepage.tsx

It would be nice if you can enter a URL and it would test if CORS is working from that URL

**Comment by kaf-lamed-beyt** [comment]
I'd love to pick this up @JonnyBurger

**Comment by kaf-lamed-beyt** [comment]
So, I'm thinking. 

Would this be a component with an input that accepts a URL, and checks if CORS is enabled or not? And where would it be, exactly? Would we have to place this component across all the "serve" URLs.

PS: I am still trying to wrap my head around the "serve URL" concept. Do you mind explaining it to me?

**Comment by JonnyBurger** [comment]
Good luck @kaf-lamed-beyt! 

The idea is indeed that there is an input field inside homepage.tsx where you can enter a URL and it will try to get fetched.
Since this site will be deployed to the same domain from where the requests will also happen during a Lambda render, this can be done to do some basic testing whether a URL supports CORS for this domain or not.

For Serve URL, see here: https://www.remotion.dev/docs/terminology#serve-url

**Comment by kaf-lamed-beyt** [comment]
I submitted a PR (#1879) just now. And thanks for the `serveURL` link, it is informative.

**Comment by JonnyBurger** [comment]
Fixed by #1879
