### ISSUE TITLE
ignoreRegisterRootWarning option added to @remotion/bundler:bundle() is not supported in @remotion/lambda:deploySite()

### ISSUE THREAD

**Issue by MBrendel** [remotion-dev/remotion#1866]
# Bug Report 🐛

The recently introduced option `ignoreRegisterRootWarning` for the `bundle()` function in the `@remotion/bundler` package is not supported by `deploySite()` function from the `@remotion/lambda` package.  

As `deploySite()` is using `bundle()` internally, it should accept this option and pass it on.

**Comment by JonnyBurger** [comment]
Adding it as an option!

I'm curious, do you use this option? If yes, why?

**Comment by MBrendel** [comment]
Thanks for adding the option quickly!!

We are using this option because we created a generic "render engine" that can consume different "templates" to render the same video in different looks.

So our entry points look like this:
```ts
// imports removed
createTemplate(template);
```

And only the `createTemplate` function contains the `registerRoot` call:
```ts
// imports removed
export const createTemplate = (template: Template) => {
  registerRoot(() => <MainComposition template={template} />);
};
```
