### ISSUE TITLE
No audio when rendering `mp4` with h264 codec

### ISSUE THREAD

**Issue by tmarshall07** [remotion-dev/remotion#1877]
### Description
I'm trying to render an `mp4` video with an audio track. Whenever I render with the `h264` codec, it finishes fine (no errors or warnings), but the final video file doesn't have audio. Based on [the docs](https://www.remotion.dev/docs/encoding#audio-codec), I have `audioCodec` set to `aac` and the audio file is also `.aac`.

### Specs
2021 Mac Apple M1 Pro
macOS Ventura 13.0
Node v16.18.1

# Bug Report 🐛

After setting up the demo project with `yarn create video`, I've added this to `HelloWorld.tsx`:
```tsx
	return (
		<AbsoluteFill style={{backgroundColor: 'white'}}>
			<AbsoluteFill style={{opacity}}>
				<AbsoluteFill style={{transform: `translateY(${logoTranslation}px)`}}>
					<Logo />
				</AbsoluteFill>
				{/* Sequences can shift the time for its children! */}
				<Sequence from={35}>
					<Title titleText={titleText} titleColor={titleColor} />
				</Sequence>
				{/* The subtitle will only enter on the 75th frame. */}
				<Sequence from={75}>
					<Subtitle />
				</Sequence>
			</AbsoluteFill>

                         {/* Added audio 👇 */}
			<Audio src="https://ai-summaries.s3.amazonaws.com/audio/hello.aac" />
		</AbsoluteFill>
	);
```

Then run
```bash
yarn run build
```
I've also tried updating the `build` script to
```bash
remotion render --codec=h264 --audioCodec=aac HelloWorld out/video.mp4
```
but still no dice 😭

This is the output and the `mp4` file:
<img width="1154" alt="Screenshot 2023-03-01 at 6 12 55 PM" src="https://user-images.githubusercontent.com/12277245/222287992-f6bca29e-0641-4b12-8166-a5288e2eba05.png">
https://user-images.githubusercontent.com/12277245/222288061-716b59c7-5515-48ae-98a7-b462591adb89.mp4

If I change the `build` script to
```
remotion render --codec=h264 --audioCodec=aac HelloWorld out/video.mp4
```
then the audio renders fine (but of course—no video).

It's very possible I'm not using the right combination of codecs and/or file input types, but I feel like I've exhausted the docs and it otherwise seems like I'm doing the "right" thing. Any help would be much appreciated!

**Comment by tmarshall07** [comment]
Well, as soon as I submitted this I realized that it's apparently an issue with the VSCode previewer. Audio plays fine in native MacOS and in browser 🙄

**Comment by JonnyBurger** [comment]
I noticed this as well in VS Code! Thanks for self-answering your question.
