### ISSUE TITLE
Vercel style preview deployments on composition codebase change

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#1883]
# Feature Request 🛍️

I'm currently working on multiple codebases with organizations that have motion designers, and they often have suggestions for minor changes in templates. I believe the Remotion docs outline a process to use GitHub actions to render videos.

While thinking about a way for designers to effectively test out changes made in a pull request, I was thinking of using GitHub actions to render out each registered composition, and add the results in a comment under the pull request after rendering has completed through GitHub actions. 

Having to only render out only the compositions that have changes could be a great addition too, though not necessary!

Is there a way to have something close to Vercel style preview deployments for Remotion, or a pre-existing solution that would enable designers to easily get rendered links for each composition under pull requests, so they could easily verify changes.

If having to create a bot account for commenting the preview links adds too much friction, we could just have the GitHub action run and render the videos under the artifacts of the action run and have users manually download those rather than commenting under the pull request.

## Possible Solution

If there isn't something out there that solves the problem, adding a workflow/article to the docs would be a great start.

It could contain a GitHub action script that

1. Detect changes in the codebase, and pick out the names of compositions that have changed. (optional; could just default to return every composition ID in case detecting is not feasible).
2. Runs the render command against each composition.
3. After the action runs and all renderings succeed, either comment the links for previewing the video under the GitHub pull request, or add the rendered videos under action's artifacts.

I think this could reduce quite some friction and manual labour from the development process.

cc @JonnyBurger

**Comment by JonnyBurger** [comment]
Check out Stoat! https://github.com/stoat-dev/example-remotion
I think this is pretty much what they are up to.

If it matches what you want, you can close the issue.

**Comment by JonnyBurger** [comment]
Here is a better link: https://docs.stoat.dev/docs/tutorials/preview-remotion

**Comment by Just-Moh-it** [comment]
Oh, that's awesome to learn! Definitely a life-saver. Thanks @tuliren!

**Comment by tuliren** [comment]
@Just-Moh-it, hope that you like it. Let us know if you need any help set it up.

**Comment by tuliren** [comment]
@jrhizor FYI.
