### ISSUE TITLE
npm init video error: No matching version found for @remotion/cli 

### ISSUE THREAD

**Issue by ohld** [remotion-dev/remotion#1886]
I started to explore Remotion and learn React. When I write in terminal `npm init video` it outputs the error: 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @remotion/cli@3.3.60-alpha.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I tried to uninstall all globally installed npm packages and rerun the script -- doesn't work. I have macos Monterey 12.6 (M1). I attached the full log below

[2023-03-02T17_37_26_078Z-debug-0.log](https://github.com/remotion-dev/remotion/files/10874181/2023-03-02T17_37_26_078Z-debug-0.log)

**Comment by JonnyBurger** [comment]
Sorry about that! I tried a prerelease today but it got tagged as @latest and nom wouldn't let me retract it :/ 

I've now released v3.3.60 which means the issue should be fixed!
