### ISSUE TITLE
issue with volume during render

### ISSUE THREAD

**Issue by White-Green** [remotion-dev/remotion#1888]
I use following environment.

- OS: Windows 11 Pro Version 22H2 (Build 22621.1265)
- ffmpeg: version 4.4-full_build-www.gyan.dev
- Google Chrome: 110.0.5481.178（Official Build）（64 bit）

I am using Remotion 3.3.61. There seems to be a bug where the volume decreases as the video length increases.
The following image shows audio rendered from the same project with `--frames=0-1800`, `--frames=0-600`, and `--frames=0-300`.

![image](https://user-images.githubusercontent.com/43771790/222619196-89e5a560-6ef8-4c91-b261-68d874fa35e9.png)

The following image is audio rendered by Remotion 3.3.60, so it seems to be a different kind of bug.

![image](https://user-images.githubusercontent.com/43771790/222619229-d61c7d8b-9db2-46a1-9acc-05e6ccd61113.png)

Thank you for your attention to this matter.

**Comment by White-Green** [comment]
I also tried Remotion 3.3.59.

![image](https://user-images.githubusercontent.com/43771790/222622583-75791cfe-f34d-4e13-bcb9-3687617c3769.png)

**Comment by JonnyBurger** [comment]
Thanks for the report, I can confirm the issue, will work on a solution asap
