### ISSUE TITLE
renderStill() should support pdf

### ISSUE THREAD

**Issue by bennodev19** [remotion-dev/remotion#1899]
Besides `.png` and `.jpg`, `renderStill()` should also support `.pdf` export.

## Use Case

`.pdf` exports aren't raster images like `.png` and `.jpg`, instead it is based on vectors which makes it scale without lost in detail. This is useful in case of printing the exported image in high dpi without having to deal with large `.png` or `.jpg` files to keep the same amount of detail.

## Possible Solution

See MR linked to this Issue

## Definition of Done (DoD)
- [x] `renderStill()` renders a valid `.pdf` file if the `imageFormat: "pdf"` is defined
- [x] Documentation is updated
- [x] Tests are working

**Comment by bennodev19** [comment]
thanks @JonnyBurger :)
when does the remotion team plan to release the v4 or alpha prerelease besides the v3?
Couldn't find any roadmap in the docs.
Are [4.0.0-gif-esmsmsm.10](https://www.npmjs.com/package/@remotion/renderer/v/4.0.0-gif-esmsmsm.10) prerelease of the v4 though.
thanks :) and keep up the good work 👍

**Comment by JonnyBurger** [comment]
Thanks @bennodev19!

I expect Remotion 4.0 to ship within the next two months, and there will be some prerelease versions before. No hard promise on the dates though 😬
