### ISSUE TITLE
`overrideWebpackConfig` doesn't appear in `config.d.ts`, causing a TypeScript warning in `remotion.config.ts`

### ISSUE THREAD

**Issue by fwextensions** [remotion-dev/remotion#1905]
# Bug Report 🐛

Version: 3.3.64

When I switched to using .ts for the remotion config file, I started getting a type warning in Webstorm:

![image](https://user-images.githubusercontent.com/61631/223967433-d08da0d6-4031-4c1a-aff4-48089380a64e.png)

If I click through to the `config.d.ts` file in the npm package, I don't see the `overrideWebpackConfig()` method defined anywhere in that file:

```ts
declare global {
    interface RemotionBundlingOptions {
        /**
         * Specify the entry point so you don't have to specify it in the
         * CLI command
         */
        readonly setEntryPoint: (src: string) => void;
        /**
         * Whether Webpack bundles should be cached to make
         * subsequent renders faster. Default: true
         */
        readonly setCachingEnabled: (flag: boolean) => void;
        /**
         * Define on which port Remotion should start it's HTTP servers during preview and rendering.
         * By default, Remotion will try to find a free port.
         * If you specify a port, but it's not available, Remotion will throw an error.
         */
        readonly setPort: (port: number | undefined) => void;
        /**
         * Define the location of the public/ directory.
         * By default it is a folder named "public" inside the current working directory.
         * You can set an absolute path or a relative path that will be resolved from the closest package.json location.
         */
        readonly setPublicDir: (publicDir: string | null) => void;
    }
```

I assume that's why I see the TS error when trying to use that method.  I took a look at the config source file in the repo, and it does define `overrideWebpackConfig()` as part of that interface.  I guess something is going wrong in the creation of the type files?

**Comment by JonnyBurger** [comment]
You are right, thanks for reporting!
The option  appears when the type `WebpackOverrideFn` `@remotion/bundler` is being imported (workaround), but that isn't obvious, so I am reverting the recent change to make it appear always again. Should be fixed in the next version!
