### ISSUE TITLE
svg has Unexpected margin-top

### ISSUE THREAD

**Issue by winner106** [remotion-dev/remotion#1907]
svg has Unexpected margin-top

![image](https://user-images.githubusercontent.com/50519642/224010645-53ec4c78-267c-4bd6-8388-b915ccd7e0a4.png)

![image](https://user-images.githubusercontent.com/50519642/224011166-bc82afef-8db4-4ba3-a1ef-423ec5bf3f46.png)

![image](https://user-images.githubusercontent.com/50519642/224011312-b673651d-5775-4730-b79d-6f65a5b1a5a6.png)

**Comment by JonnyBurger** [comment]
This style does not come from Remotion. It must be something else in your stack that adds this.
