### ISSUE TITLE
Serverless example

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#191]
Many people ask, can you render a video using serverless? If it works, let's provide some documentation or an example!

**Comment by JonnyBurger** [comment]
Should also give some guidance how much RAM / CPU is needed

**Comment by JonnyBurger** [comment]
I am working on providing an official serverless library with docs and guidance!

**Comment by samdoeswork** [comment]
Hi, any progress on this? I'd be interested in trying to run this on Google Cloud Functions which seems to have ffmpeg available & I'm happy to share my experience for the docs

**Comment by JonnyBurger** [comment]
@samdoeswork We are actively working on it and have a preview available, which you can test by joining our Discord and coming into the #lambda channel! 🙂

**Comment by Muurilo** [comment]
Will it be possible to use serverless functions from vercel?

**Comment by BrunoQuaresma** [comment]
That is awesome! Some questions:
- Does Remotion deploy the lambda for me? 
- I see it renders the video by calling `npx remotion lambda render <serve-url> <composition-id>` but how could I pass the parameters to update the dynamic content?
- Instead of CLI, is that possible to use a URL like https://mylambdaip.com?title=Hi

**Comment by JonnyBurger** [comment]
@BrunoQuaresma 

- We provide a framework that manages the infrastructure via CLI commands or Node.JS APIs. However, you deploy this to your own AWS account!
- You can pass `--props` to define a JSON payload you want to be used by the video. Most often you would use the `renderMediaOnLambda()` API though rather than the CLI commands.
- Not directly, but you can use a Node.JS environment (e.g. Express server or another serverless function) to call `renderMediaOnLambda()` and expose that via an HTTP endpoint.

**Comment by BrunoQuaresma** [comment]
Nice, I went through all the steps, and looks like I was able to deploy it. Is there a way to use the CLI to get the deployed lambda function URL?

**Comment by BrunoQuaresma** [comment]
Also, is that possible to automate all these AWS steps?

**Comment by JonnyBurger** [comment]
@BrunoQuaresma You can use `npx remotion lambda functions ls` to get the deployed function name. It also supports a `-q` flag to only print the name.
It is only automateable via scripts - either bash, or all the actions that are possible via CLI are also available as Node.JS APIs!

You have to setup the AWS accounts and their policies yourself though, maybe that can be automated in other ways like Terraform.

**Comment by BrunoQuaresma** [comment]
@JonnyBurger that is great! I'm almost there haha. How can I update a site or function after updating my compositions?

**Comment by JonnyBurger** [comment]
Yes, you can! Pass a site name:

https://v3.remotion.dev/docs/lambda/deploysite#sitename
https://v3.remotion.dev/docs/lambda/cli/sites#--site-name

and it will overwrite the previous deploy, therefore updating the site!

**Comment by BrunoQuaresma** [comment]
Thanks, just a minor thing: I missed something like `update` or `deploy`. Maybe having an alias like:
```
npx remotion lambda sites update src/index.tsx --site-name=my-project
```
 could be worth a try.

**Comment by JonnyBurger** [comment]
@BrunoQuaresma Thanks for the feedback, it is noted that it's hard to figure out how to update it. We'll consider an alias or a new command!

**Comment by JonnyBurger** [comment]
We have now made the source code for githubunwrapped.com available: https://github.com/remotion-dev/github-unwrapped

Showing an AWS Lambda + Next.JS integration!
