### ISSUE TITLE
`speculateFunctionName()`

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1913]
Based on RAM, disk and timeout, we can calculate the Remotion Lambda function name without having to call getFunctions().

The logic is as follows:

![image](https://user-images.githubusercontent.com/1629785/224365605-8ebf576d-610b-4184-8724-018fd774026d.png)

(disk, ram and timeout should come from a function argument, not from a config file)

## Acceptance criteria

- Implement this function in `@remotion/lambda`
- Have the same JSDoc annotations as the other APIs
- Create a documentation page for it
- Add it to the lambda docs table of contents

/bounty 100

**Comment by Just-Moh-it** [comment]
Hey @JonnyBurger! I'd be glad to help with this 😃

**Comment by JonnyBurger** [comment]
@Just-Moh-it Haopily 🥳
