### ISSUE TITLE
TypeScript warning when passing a variable as the options parameter to `interpolate()`

### ISSUE THREAD

**Issue by fwextensions** [remotion-dev/remotion#1916]
# Bug Report 🐛

Version 3.3.64

Passing a literal object with extrapolate options to `interpolate()` works fine, but assigning that same value to a variable and then passing that variable to `interpolate()` shows a TS warning:

![image](https://user-images.githubusercontent.com/61631/224416669-06b1e3c6-0112-470f-a590-6b711f9524d1.png)

```
TS2345: Argument of type '{ extrapolateLeft: string; }' is not assignable to parameter of type 
'{ easing?: ((input: number) => number) | undefined; extrapolateLeft?: ExtrapolateType | undefined; 
extrapolateRight?: ExtrapolateType | undefined; }'.
   Types of property 'extrapolateLeft' are incompatible.
     Type 'string' is not assignable to type 'ExtrapolateType | undefined'.
```

I see that `ExtrapolateType` isn't exported from the package, but I don't know TS well enough to say if that matters.  The `interpolate()` function should definitely be typed in a way that options can be defined once in a const and then passed into different calls so that they're all using consistent flags.

**Comment by CruuzAzul** [comment]
I can look at this

**Comment by JonnyBurger** [comment]
Thanks a lot `CruuzAzul`!

This is actually a TypeScript behavior - you need to write it as 

```ts
const option = { extrapolateLeft: "clamp" as const }
```

just so that the variable has the right type.

But we can indeed export the type of InterpolateOptions, this would be nice!

**Comment by Just-Moh-it** [comment]
Agree @JonnyBurger... was super confused the first time I saw this warning too

**Comment by fwextensions** [comment]
Hmm, I've never seen `as const` on an individual field before.  But adding it to the object as a whole also fixes the warning.

I haven't used TS a ton, but I feel like I would've run into this before if there weren't some way of defining the `interpolate()` function to accept const variables of the right shape without also having to plunk `as const` on them.  I wasn't able to find anything obvious after a bit of searching, though.

Strangely, this doesn't show any warning:

```ts
const option: Record<any, any> = { extrapolateLeft: "derp" };
```

Exporting an `InterpolateOptions` interface/type (I don't think there is one currently?) would probably help, as then the error would list that type, which would hopefully prompt people to slap it on their const definition, fixing the issue.  I still suspect there's a way of defining the parameter that wouldn't require this, though.

**Comment by JonnyBurger** [comment]
@CruuzAzul Hope it's okay that I fast-tracked this! PR is now on the way

@fwextensions What you are describing is regular TypeScript behavior though. Explicit any will allow it to be passed to another function with no typechecking. You can use `as const` on either the string or the object.
