### ISSUE TITLE
@remotion/lambda 3.3.54 - unmet depedency

### ISSUE THREAD

**Issue by alexfernandez803** [remotion-dev/remotion#1917]
I've noticed that, @remotion/bundler is being left behind in versioning with other packages. I've upgraded to  3.3.54, but @remotion/lambda is complaining of unmet dependency.

 ✕ unmet peer @remotion/bundler@3.3.44: found 3.3.54

I've noticed also this behaviour up to latest version, shouldn't be remotion/bundler carries the same package version of the main package?

**Comment by JonnyBurger** [comment]
This is true, it's already fixed by #1911, I just need to release it which I'll do very soon!
