### ISSUE TITLE
Update `action-rs/toolchain@v1`GH actions node env to > v12 (deprecated)

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#1921]
![image](https://user-images.githubusercontent.com/48997634/224666740-d917dbbb-7b10-4b31-93ee-4bd202961e0d.png)

While checking out the progress of some GitHub actions on this repo recently, I noticed a bunch of node v12 deprecation warnings. Since some actions in the GH Actions workflow run directly/indirectly on node v12, and it is supposed to be dropping support by early 2023 (we might just be a few days away from support being dropped), we should migrate away from using node v12... 🙃

**Comment by JonnyBurger** [comment]
Good point, thanks for filing!
Relevant issue: https://github.com/actions-rs/toolchain/issues/219

**Comment by JonnyBurger** [comment]
So funny, I was just able to remove it and it still works!
