### ISSUE TITLE
Transparent ProRes videos on Apple Silicon M2 machines flickers

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1929]
This is an M2 specific bug in the FFmpeg prores_ks encoder or possible in the macOS media engine.

Ticket created here: https://trac.ffmpeg.org/ticket/10255
As a workaround, render an image sequence using `--sequence --image-format=png` and select all images and drag them into your video editor.

**Comment by adamgoose** [comment]
I'm experiencing playback issues on my new M2 after having rendered a ProRes 4444 video on my M1. It plays fine on the M1, but looks awful on the M2. Re-rendering on the M2 did *not* help.

**Comment by adamgoose** [comment]
Rendering on Lambda has not solved my issue. [Here](https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-kwvleb1pd3/renders/jlvhbcg1uo/out.mov) is an example of the video that renders poorly on the M2. 

Below is a screenshot of the alpha-channel freaking out during playback in Quicktime. (plays fine in VLC)

![Screenshot 2023-05-22 at 6 30 53 PM](https://github.com/remotion-dev/remotion/assets/611068/4a8536b1-d518-4508-b66e-d89d585dde0d)

**Comment by JonnyBurger** [comment]
This is fixed in the next version by applying https://ffmpeg.org//pipermail/ffmpeg-devel/2023-December/318922.html 😊
