### ISSUE TITLE
Better error handling for when changing the name of an exported component

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1942]
Let's say I have a component:

```ts
export const A: React.FC = () => null
```

and I copy paste another component from the internet:

```ts
export const B: React.FC = () => null
```

No error appears, because I did not have the other file open:

```ts
import {A} from './comp'
```

When rendering, then I get the following error:

```
Minified React error #306; visit https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Which users get very confused by. We could look for this error and handle it like the other common errors here:

https://github.com/remotion-dev/remotion/blob/40a47c91ad185ef180309e09a780c5b18ff9ba92/packages/cli/src/handle-common-errors.ts

**Comment by kaf-lamed-beyt** [comment]
I'd love to jump on this @JonnyBurger

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Thanks a lot Caleb! Good luck 🙌🏼

**Comment by kaf-lamed-beyt** [comment]
Aye!! @JonnyBurger 👨🏼‍🍳
