### ISSUE TITLE
Image format should be better validated for stills

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1955]
The following command:

```console
npx remotion still HelloWorld out.pdf
```

renders a JPEG instead of a PDF.

For videos, it is very strict, it would not allow a file extension mismatch.

The order of importance should be:

1) Explicitly passed `--image-format`
2) Output extension out.pdf
3) Config file
4) default

And there should be a whitelist of allowed extensions, so a JPEG cannot be rendered with a .pdf extension

**Comment by Slashgear** [comment]
I could work on that for sure.
Could we define allowed format in this issue ? :)

**Comment by Slashgear** [comment]
No worries, I could still help with the review/testing if you @ me

**Comment by patsalv** [comment]
Fixed for 4.0
