### ISSUE TITLE
ESLint `staticFile`: Disallow absolute paths to filesystem and starting the path with `public/`

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1962]
Disallow `staticFile("/Users/jonathanburger/remotion/public/my-asset.png")` and `staticFile("public/my-asset.png")`

With ESLint using the `staticfile-no-relative` rule, or maybe even at runtime?

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger, 

I checked the eslint docs a moment ago, and I don't think the `staticfile-no-realtive` rule is a valid one. Or is it one peculiar to Remotion, alone?

Although, one approach that I think could work would be to use the `import` plugin from [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import). But, I'm a bit confused on which one to use from the available plugins. 

I read [here](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/imports-first.md) that the `import/import-first` rule is deprecated.

Enough of the story. What I'm trying to say here is that, would this be a nice approach? Probably with a [import/no-absolute-path](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-absolute-path.md) and  [simple-import-sort/imports](https://github.com/lydell/eslint-plugin-simple-import-sort) rules?

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt I am referring to this ESLint rule here: https://github.com/remotion-dev/remotion/blob/main/packages/eslint-plugin/src/rules/staticfile-no-relative.ts

This is one that we made ourselves but is enabled if you install a Remotion template.
It has nothing to do with import statements, since staticFile() only generates a string!

**Comment by kaf-lamed-beyt** [comment]
Okay, great!

So now, what we need to do is add a check for absolute and `public` paths too. Something like this should suffice;

```js
if (value.startsWith("public/")) {
  context.report({
    messageId: "PublicStaticFile",
    node,
  });
}
```

I can take this if you'd love me to.

**Comment by JonnyBurger** [comment]
Yes I think so 😊
Would be really cool, thanks @kaf-lamed-beyt!

**Comment by kaf-lamed-beyt** [comment]
Ayy! I'll start now. 😎
