### ISSUE TITLE
Recommend `onClickCapture` over `onClick` when starting the player with autoplay

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1969]
Insight here: https://discord.com/channels/809501355504959528/817306238811111454/1090991811729829898

We could add this to the documentation here: https://www.remotion.dev/docs/player/autoplay

**Comment by kaf-lamed-beyt** [comment]
Went through the thread of this issue in the server, and I think it should give me a head start. Am I just going to modify the autoplay doc?

Or do I have to contribute code too.

And BTW, @JonnyBurger, how exactly are you even able to attend to all the issues of people in the #help channel and still have time to ship code. 

Can't even imagine how strenuous that would be!

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Would be appreciated!

Lol, it is time-consuming, luckily I get to do it fulltime :D

**Comment by kaf-lamed-beyt** [comment]
> Lol, it is time-consuming, luckily I get to do it fulltime :D

I know the vibe! 😃 

I asked if I'll be modifying the autoplay doc, for this contribution to count @JonnyBurger

**Comment by JonnyBurger** [comment]
Sorry - yes this is pretty much what I had in mind!

**Comment by kaf-lamed-beyt** [comment]
Awesome! I'll send a PR soonest. 😃

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger,

I'm sorry that I haven't attended to this. I'm a bit occupied with a particular event I've been prepping for, and it has consumed my time and focus. 

But, when it is over on Saturday, I should be able to send a PR by Sunday or Monday, latest. Please bear with me. 🙏🙏

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt No rush!

**Comment by kaf-lamed-beyt** [comment]
Huge thanks! ✌🏽
