### ISSUE TITLE
Git not found on Windows

### ISSUE THREAD

**Issue by antoninklopp** [remotion-dev/remotion#1971]
While doing the installation following [the documentation](https://www.remotion.dev/docs/), I failed to make the `pnpm create video` or `npm init video` command work because of the following error message
```
Git is not installed or not in the path. Install Git to continue.
```

It seems to come from the following change detecting Git on windows machines: https://github.com/remotion-dev/remotion/pull/1724

I have a 64 bit machine but `os.platform()` returns `win32` (win32 seems unrelated to whether you are on a 32 or 64-bit machine from what I read). 

The command `which` is working fine and I have git installed, but the code is trying to use the command `where` which is:
- Not working on Git Bash
- Not returning anything on powershell

I avoided the issue by doing an alias from `where` to `which` in my git aliases file and afterwards the installation worked like a charm! 

I am not sure what should be the good check on how to choose `where` or `which` however. 

Thanks!

**Comment by JonnyBurger** [comment]
Thanks for the report, adding some testing notes...

PowerShell: 

process.platform => "win32"
which does not exist
where does exist

cmd.exe:
process.platform => "win32"
which does not exist
where does seem to exist (appears to be different command than in powershell)

GitBash:
process.platform => "win32"
which seems to exist as well as where

Where is the same as in cmd.exe, but different to PowerShell

**Comment by JonnyBurger** [comment]
I couldn't really reproduce the issue, since on my Windows 11 installation, `where` seems to be installed (`c:/Windows/System32/where.exe`).

But I think the better thing to do is to check for `git --version` instead anyway, so I hope that will fix the issue for you!

**Comment by antoninklopp** [comment]
Thanks a lot for the fix. 
I am still on Windows 10, maybe Microsoft changed the way they handle these tools between versions.
