### ISSUE TITLE
Mute properties for @remotion/player

### ISSUE THREAD

**Issue by thecmdrunner** [remotion-dev/remotion#1972]
# Feature Request 🛍️

1. `muteInitially` - Mutes remotion videos by default when the page loads for the first time, similar to `<video muted>` in HTML. While this can currently be implemented by various methods, having a single property will make things much simpler.

2. `muted` - A simple controlled prop that keeps the player muted regardless of other properties. An alternative to this could be an onMuteChange property that passes a boolean in a callback.

```tsx
<Player
   muteInitially
   muted={isMuted}
   onMuteChange={(mute: boolean) => setShowCaptions(mute)}
   fps={30}
   component={Component}
   ...props
/>
```

## Use Case

1. `muteInitially` - This is especially useful if the developers decide that the video must autoplay, but want to respect user's choice for whether to play sound.

2. `muted` - Useful for conditionally muting the video, or other stuff like - turning captions on and off conditionally.

**Comment by JonnyBurger** [comment]
Thanks a lot for filing!

I see the point of `initiallyMuted` and have implemented it.

However, the `muted` prop seems redundant and is in conflict with the UI that allows the user to mute a video on button click. If you want to keep a video muted, I suggest setting `initiallyMuted` in combination with the `showVolumeControls` prop.

**Comment by thecmdrunner** [comment]
Yay! Thanks for clarifying the conflict behind `initiallyMuted`. I see the clever use of `showVolumeControls` can be a viable solution for muting the video.
