### ISSUE TITLE
Website buttons cannot be clicked between 545px and 700px viewport

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1985]
The three buttons at the bottom cannot be clicked. Original bug report:

> I've encountered an issue with remotion.dev webapp. Specifically, three of the buttons are not completely responsive specially between 545px to 700px screen width. I've attached a screenshot of the issue for your reference.

[Screencast_from_04-04-23_075343_PM_IST.webm](https://user-images.githubusercontent.com/1629785/230006894-2efe1250-c4ab-45fe-8e6e-1274fa0556ca.webm)

**Comment by Safouene1** [comment]
Can you assign me this one

**Comment by harshbisle** [comment]
Hey @JonnyBurger would like to work on this issue. Please assign it to me.
Thank you for considering my feedback.

**Comment by JonnyBurger** [comment]
Thanks a lot! Good luck 🙌

**Comment by harshbisle** [comment]
Thank you @JonnyBurger 😊

**Comment by Safouene1** [comment]
Wow. Alright

**Comment by JonnyBurger** [comment]
@Safouene1 Whoops, sorry I did not see this comment 😵‍💫 By no means I wanted to ignore you!
It would be cool to see you as a contributor for another issue, I think there are more layout bugs on the website, if you would like to improve it I can make another issue with bounty!

**Comment by Safouene1** [comment]
No worries , probably because of the mention you didn't notice my message .
 it's alright you don't need to make another issue about it.
I'll be happy to help contribute to any issues you consider important.

**Comment by JonnyBurger** [comment]
Fixed by #1998
