### ISSUE TITLE
UI/Shortcut labeling mismatch (Zoom)

### ISSUE THREAD

**Issue by feliskio** [remotion-dev/remotion#1999]
# Bug Report 🐛

The hint in zoom dropdown suggests that pressing "0" resets the zoom to 100% while in reality it resets it to "Fit".
It probably makes sense to move the hint rather than changing the shortcut behavior.

<img width="261" alt="grafik" src="https://user-images.githubusercontent.com/33993147/230679007-d45b6750-b6ab-4625-9d6e-8e61e3f8a716.png">

**Comment by JonnyBurger** [comment]
Wow, what an oversight! Thanks for reporting
