### ISSUE TITLE
Experts page: Clicking any button does take you to the detail page instead of the profile

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2012]

**Comment by harshbisle** [comment]
Can I give it a try?

**Comment by MehmetAdemi** [comment]
For sure!

**Comment by harshbisle** [comment]
Thank you!

**Comment by Slashgear** [comment]
@harshbisle this is html issue here, the whole card in a `Link` and they are link within that are "captured" by the parent link.
Social link should be siblings, not children.

i could take this If you want I would try to explain how I fixed it in my Pull Request in order to let you know how this works ?

**Comment by MehmetAdemi** [comment]
@Slashgear Thanks for the hint! That would be much appreciated!
@harshbisle Alternatively, you can tackle the "Find a template" issue, of course, only if you want and have time :)

**Comment by harshbisle** [comment]
@Slashgear Thank you for the hint, working on it. 
@MehmetAdemi Yes, will submit a PR for this by the EOD and will move on to the "Find a template" issue. Is this feasible?

**Comment by MehmetAdemi** [comment]
For sure, appreciate your commitment! Let's do it this way!

**Comment by harshbisle** [comment]
Please have look at the PR. @Slashgear thanks again for the hint.

I have messed up some CSS styles. I would be glad to make the required changes based on your input.
 
Thank You!

**Comment by Slashgear** [comment]
This could be considered closed @JonnyBurger ;)

**Comment by MehmetAdemi** [comment]
@harshbisle Awesome! Thanks for the contribution! 
Thanks for guiding @Slashgear! Very much appreciated. 💙
