### ISSUE TITLE
Label for Sequence name is multiline

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2016]
Improve the layout of this:

![image](https://user-images.githubusercontent.com/1629785/231974169-203e54b2-f855-4f99-a49d-bfb6eced85fa.png)

Probably it is just an `<Audio>` tag with a long `src`

**Comment by thecmdrunner** [comment]
Since `<Audio>` already has an `about` and `id`, either one can be displayed there.
I'd vote for `id` since its more self explanatory, and will be intuitively understood by most, when they see it in that panel.

```tsx
<Audio id={`Topic-${index + 1}`} about="Lorem Ipsum" src={url} />
```

**Comment by Slashgear** [comment]
@JonnyBurger I could take this, is this only v4 bug ? 

We could handle a multi-line ellipsis ?
What is your opinion on this ?

**Comment by JonnyBurger** [comment]
Audio has an ID, but it is not human-readable, it is for uniqueness. So I would prefer if we just truncated it.
I will assign it to @Slashgear since this is his proposal 🙂
