### ISSUE TITLE
Home page: "Find a template" button doesn't appear as button but as link

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2029]
Reported by: @harshbisle

**Comment by harshbisle** [comment]
Thanks, @MehmetAdemi was about to comment. Hope I can pick this up now.

**Comment by MehmetAdemi** [comment]
Let me know if you encounter any issues or get stuck!

**Comment by harshbisle** [comment]
For sure!

**Comment by harshbisle** [comment]
Fixed by #2138

**Comment by MehmetAdemi** [comment]
@harshbisle 
Great, thanks!
