### ISSUE TITLE
Color of inline button is always white in editor

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2034]

**Comment by Slashgear** [comment]
@JonnyBurger Could you tell more on this issue, I may be able to fix it ;)

**Comment by JonnyBurger** [comment]
Ok, didn't expect contributors for V4 issues, but I'll gladly explain it! 🙂

There is a component, `<InlineIcon>`, whose icons are always white (`#fff`). They are meant to be `LIGHT_TEXT` instead, but in the Remotion Preview, we need to set all styles explicitly with inline CSS.

This is very special, but consider if someone imports a CSS file `* { background: red; font-family: Comic Sans !important; }`, then the Remotion Preview should not be affected by this. The way we do this is pass inline style 😄

But it is not implemented currently. We probably want a hover listener (like this https://github.com/remotion-dev/remotion/blob/4cd40c8a711b1258e6aeccdf341438ccd8e5c1ae/packages/cli/src/editor/components/NewComposition/RemInputTypeColor.tsx#L32) and then pass the color down to the icons explicitly.

Let me know if you want the issue, then we'll assign it to you!

**Comment by Slashgear** [comment]
Can't wait for the V4 so If I could help a bit, that would be great !

I think I see what to do, I will try to fix it.

**Comment by JonnyBurger** [comment]
Awesome! Thanks a lot and good luck!

**Comment by Slashgear** [comment]
OK

**Comment by JonnyBurger** [comment]
Fixed by #2148
