### ISSUE TITLE
Mention that OffthreadVideo imageFormat type has been removed and the option as well

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2045]
before: png (so could be transparent) or jpeg
now: imageFormat no longer existing. If you want to png, set transparent prop. 

-> idea to hide implementation details. Doesnt matter if png or jpeg or whatever, what matters is if we user wants it transparent or not.

**Comment by patsalv** [comment]
imageFormat accepted in current v4 implementation?
