### ISSUE TITLE
Update all Example Projects to 4.0

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2072]
- [x] [Music with Tone.JS](https://github.com/remotion-dev/tone-js-example)
- [x] [Animate a .glb model](https://github.com/remotion-dev/glb-example)
- [x] [Typewriter effect](https://github.com/remotion-dev/typewriter)
- [x] [D3.js](https://github.com/remotion-dev/d3-example)
- [ ] [Greenscreen Effect](https://www.remotion.dev/docs/video-manipulation)
- [ ] [Noise visualization](https://www.remotion.dev/docs/noise-visualization)
- [ ] [Audio visualization](https://www.remotion.dev/docs/audio-visualization)
- [x] [3D Text](https://github.com/JonnyBurger/3d-text)
- [x] [Wavy TikTok Effect](https://github.com/JonnyBurger/wavy-meme)
- [x] [Apple "Spring loaded" animation](https://github.com/JonnyBurger/spring-loaded)
- [x] [ThreeJS particles demo](https://github.com/JonnyBurger/three-particles)
- [x] [Text Morphing](https://github.com/JonnyBurger/morph-text)
- [x] [Text warping](https://github.com/remotion-dev/text-warping)
- [x] [Include GLTF models](https://github.com/JonnyBurger/remotion-three-gltf-example)
- [x] [OpenGL transitions](https://github.com/JonnyBurger/remotion-gl-transitions)
- [ ] ~~[Conference talk in React](https://github.com/pomber/record-talk-with-remotion)~~
- [ ] [Conference talk in React #2](https://github.com/JonnyBurger/react-summit-talk)
- [x] [Twitch stinger example](https://github.com/JonnyBurger/ledevevent-stinger)
- [x] [DevContainer Template](https://github.com/openscript/remotion-devcontainer-template)
- [x] [Usage with Anime.JS](https://github.com/remotion-dev/anime-example)
- [x] [Displaying a spinner while content is loading](https://github.com/remotion-dev/video-buffering-example)
- [x] https://github.com/stoat-dev/example-remotion
- [x] [Apple WOW](https://github.com/remotion-dev/apple-wow-tutorial)

**Comment by MehmetAdemi** [comment]
Is this still open?

**Comment by JonnyBurger** [comment]
Yep, those without checkmark have not been updated

**Comment by JonnyBurger** [comment]
🔥
