### ISSUE TITLE
Validate schema if user renders a video and passes input props

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2084]
or at least give an option

**Comment by JonnyBurger** [comment]
Still planning to add a `--validate` flag, but it should not block the V4 release. Adding afterwards!

**Comment by JonnyBurger** [comment]
Not seeing it as a feature we need now, if one desires, they can call .parse() themselves in calculateMetadata() since they have the schema and the data

Also no one asked for this
