### ISSUE TITLE
Search all docs to see if there is inaccurate information about how we use FFmpeg

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2099]
- [x] Revise [installing ffmpeg](https://www.remotion.dev/docs/ffmpeg#ffmpeg-and-ffprobe ) in docs
- [x] Revise [ensureFfmpeg()](https://www.remotion.dev/docs/renderer/ensure-ffmpeg) in docs
- [x] Revise FFmpeg requirement in [Installation](https://www.remotion.dev/docs/#ffmpeg-requirement)
- [x] Update text for [--ffmpeg-executable](https://www.remotion.dev/docs/cli/compositions#--ffmpeg-executable)

-> Was already done in v4 alpha docs :D

**Comment by patsalv** [comment]
Whole docs checked. Seems good

**Comment by JonnyBurger** [comment]
Excellent!
