### ISSUE TITLE
Check the new Date picker, scrollbars, input[type=range] elements in Firefox and Safari as well

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2102]

**Comment by patsalv** [comment]
Firefox:
- Scrollbar has default design, not the intended thin design
- Font is not the same as in chrome(sans-serif vs serif). 
- Date Picker is smaller in firefox and looks different (still good though)

Safari:
- Scrollbar looks good, same as in Chrome
- Datepicker too small
- Calender symbol for datepicker not shown (see screenshots)



![Image](https://user-images.githubusercontent.com/89481679/233638441-82d41521-2a62-4bc9-8023-3d9388da9187.png)



vs




![Image](https://user-images.githubusercontent.com/89481679/233638565-bfef97fd-861c-4934-a0e0-c5624de641f6.png)


- - "/" vs "."
