### ISSUE TITLE
Allow fragments for `Series`

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2129]
Similar to how TransitionSeries added support for fragments:

https://github.com/marcusstenbeck/remotion-transition-series/commit/9a017922ba7a7876f728289b6b5cb73763192a26#diff-b32088b0064b3b7c1e269133ef72e53fdcc70613c13dd71b09636c0880cd3c3d

/bounty 40

**Comment by kaf-lamed-beyt** [comment]
@JonnyBurger, would modifying `childrenValue` to accept `Series.Sequence` and `React.Fragment` suffice in this case?

**Comment by rjackson** [comment]
@JonnyBurger Been looking into this one and, unless I'm missing something, it appears Series already supports fragments?

The Series component accepts `children` (React.ReactNode), flattens all nested children into a one-dimensional array, and then checks to make sure every item in that children array is of type SeriesSequence:

https://github.com/remotion-dev/remotion/blob/784fd282a16d3917651d7356c51b440b6718d2c1/packages/core/src/series/index.tsx#L59-L63

And there's a currently-passing test proving this works with fragments:

https://github.com/remotion-dev/remotion/blob/784fd282a16d3917651d7356c51b440b6718d2c1/packages/core/src/test/series.test.tsx#L75-L98

**Comment by JonnyBurger** [comment]
@rjackson You are totally right!

For context, I opened this issue to not forget about it when I wasn't in a position to check myself at that time.
Thanks for investigating this and if you submit a dummy PR we'd be happy to honor it with half of the bounty amount! 😄

**Comment by JonnyBurger** [comment]
Ok, plan change, Algora made a new feature for us where I can tip you directly! Let's try it out!

/tip $20 @rjackson
