### ISSUE TITLE
PlayerMethods isFullscreen is defined as () => void;

### ISSUE THREAD

**Issue by kacperadach** [remotion-dev/remotion#2140]
# Bug Report 🐛

https://github.com/remotion-dev/remotion/blob/e032d48fd9ace58415dd668f061e42f8fbcebf75/packages/player/src/player-methods.ts#L17

Shouldn't this be () => boolean? The documentation says it returns a boolean indicating whether the player is in fullscreen or not.

**Comment by JonnyBurger** [comment]
Indeed seems like a bug to me!
Will try to provide a fix soon. Thanks for reporting it!
