### ISSUE TITLE
`volumeupdate` event on player

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#2141]
# Feature Request 🛍️

Similar to #2011

## Use Case

Need this for a custom editor UI where we have a custom volume slider somewhere far apart in the ui from the `<Player ... />` component

## Possible Solution

Simple `volumeupdate` event with payload containing the new volume.

**Comment by JonnyBurger** [comment]
I'm in favor of this 👍 I can add it easily

**Comment by JonnyBurger** [comment]
Fixed by #2146
