### ISSUE TITLE
Deploying a site can no longer create public S3 bucket

### ISSUE THREAD

**Issue by stshort** [remotion-dev/remotion#2149]
As of today, due to changes in S3 bucket policy, `npx remotion lambda sites create src/index.ts` cannot create a public S3 bucket. 
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

Due to this change in default behavior, running this script to deploy remotion sites fails, giving the error:
`InvalidBucketAclWithObjectOwnership: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting.`

# Bug Report 🐛

See the above notice from AWS about the S3 default behavior change, attempt to deploy a site on latest remotion version, see error message.

**Comment by JonnyBurger** [comment]
Thanks for reporting this!
Will make a new version which will take this into account.

**Comment by JonnyBurger** [comment]
See: https://www.remotion.dev/docs/lambda/s3-public-access
v3.3.87 is now being released!

**Comment by stshort** [comment]
Great, thanks for the quick turnaround!

**Comment by stshort** [comment]
@JonnyBurger I tried using the new version, and I'm now running into this issue on the `Uploading to S3` step:

`AccessControlListNotSupported: The bucket does not allow ACLs`

Does the code that creates the bucket need to be updated to allow ACLs? I did the following steps:
1. Upgrade to 3.3.87
2. Update the user policy, both by taking the output of  `npx remotion lambda policies user`, and also via copy+pasting the json from the `s3-public-access` document you provided (both are identical).
3. Redeployed my lambdas
4. Attempted to deploy the site (new site)

Ran into that issue on the Uploading step. 

Interestingly, I do not see the S3 bucket either, I was going to try and manually update the bucket and try but all I see is the `remotionlambda` bucket. I'm new to remotion, evaluating it now, so I'm not sure if I'm doing something incorrectly from my end.

**Comment by JonnyBurger** [comment]
@stshort Thanks for trying it out so fast!

The `remotionlambda` bucket was maybe created in a way that it should not have been, can you try to delete it and run `npx remotion lambda sites create` again? This should create a new bucket and should theoretically configure the bucket correctly, unless there is a bug. If there is one, I'll try to reproduce it tomorrow!

**Comment by stshort** [comment]
Awesome, looks like wiping out the bucket and recreating it worked fine, thanks again for the quick support!

**Comment by JonnyBurger** [comment]
Thanks for the issue + quick feedback, adding a better error message for the second error you had to guide the user better in this case as well!
