### ISSUE TITLE
No browser found to render frames

### ISSUE THREAD

**Issue by multimokia** [remotion-dev/remotion#2150]
No browser found even if there is one found

# Bug Report 🐛
![image](https://user-images.githubusercontent.com/22531674/234336222-a53a7eaa-a876-4a5f-a8f0-651010289f0f.png)

As you can see by the output, there is indeed a browser (and this one worked on older versions of remotion), but after upgrading to latest, it seems it's no longer recognized?

To get to this point:
- I ran `npm run upgrade` (it's been about 6 months since I upgraded last, but I'm not sure the version I started at)
- I ran `npm run build`

How would I go about fixing this?

**Comment by multimokia** [comment]
Okay actually turns out I just needed to remove the old chromium and let it download a new one. Still odd it happened.

Would you like to keep this open for potential tracking or just close it as resolved?

**Comment by JonnyBurger** [comment]
Thanks for filing this, I just fixed the bug and found the same reason!
Happens when for example the browser download has failed before and the folder still exists.

Now the logic is much simpler and I was able to refactor this so there is only 1 check, so this cannot happen again.
