### ISSUE TITLE
ECMA Error

### ISSUE THREAD

**Issue by Malay-Acharya** [remotion-dev/remotion#2163]
I am getting this error: 
./node_modules/@remotion/player/dist/esm/index.mjs
Can't import the named export 'Composition' from non ECMAScript module (only default export is available)

All packages are installed, I am using TS, React-scripts is at 4.0.1.

**Comment by JonnyBurger** [comment]
The `@remotion/player` does not export `Composition`, it only exports `Player`.

Use the player and pass a React component directly, no composition component needed.
The error message seems weird, but with react-scripts 5.0.1 it is better!
