### ISSUE TITLE
Project title in the upper middle of the preview

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2174]
Intuitively, I think the project title should be moved to the middle.
![Remotion Preview](https://user-images.githubusercontent.com/86873911/235184414-feeca9b7-a36e-46c4-8e85-7112202479db.png)

**Comment by MehmetAdemi** [comment]
@JonnyBurger & @patsalv 
Does this make sense?

**Comment by JonnyBurger** [comment]
Sounds good to me 👍🏼
