### ISSUE TITLE
Allow a ref to be attached to a `<Gif>`

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2176]
Should use forward ref and allow a ref to be attached. Should work for both GifForDevelopment and GifForRendering.
See how the refs are forwarded in `<Video>` for reference. Further similar issues for reference: https://github.com/remotion-dev/remotion/pull/1507 https://github.com/remotion-dev/remotion/pull/1285

/bounty 50

**Comment by rjackson** [comment]
I'll be happy to take a look at this :-)

**Comment by JonnyBurger** [comment]
@rjackson Thank you and good luck! 🙌🏼
