### ISSUE TITLE
Implement a `delay` param for springs

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2209]
It is already possible - delay a spring by 25 frames:

```ts
const spr = spring({fps, frame: frame - 25})
```

but especially for beginners it is not obvious. It would be nice if it would also be possible to:

```ts
const spr = spring({fps, frame, delay: 25})
```

- This should be documented in spring.md as well - mention the next version number using `<AvailableFrom>`
- Write 1-2 unit test assertions

/bounty 50

Refer to https://www.remotion.dev/docs/contributing and https://www.remotion.dev/docs/contributing/bounty!

**Comment by rjackson** [comment]
Heya, I'm having a look at this one :)
