### ISSUE TITLE
Implement a `reverse` prop for spring()

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2210]
You can already reverse a spring function:

```ts
const spr: Partial<SpringConfig> = {
	damping: 200,
};

const duration = measureSpring({fps, config});

const two = spring({
	fps,
	frame: duration - frame,
	config,
});
```

But (even for me) it requires quite some mental gymnastics to figure that out.

**Bounty**
- Should implement a `reverse` parameter for spring() that takes care of this calculation (default `false`)
	- Important: Take into account the `durationInFrames` option!	
- Should document in spring.md and label as available in the next Remotion version using `<AvailableFrom>`
- Write 1-2 unit test assertions

**Comment by JonnyBurger** [comment]
💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 75

**Comment by tachyonicbytes** [comment]
Hi! I would like to work on this issue! And nice to meet you, and the whole Algora project.

**Comment by JonnyBurger** [comment]
@tachyonicbytes Awesome! Good luck! 🙌
