### ISSUE TITLE
Docs: Make a Table of contents for Lottie

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2228]
The same as all the other packages have a table of contents!

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger, 

I'd love to take this up, if it hasn't been.

**Comment by JonnyBurger** [comment]
This would be super nice! Thanks! 🙌🏼

**Comment by kaf-lamed-beyt** [comment]
Awesome! I'll send a PR soon.

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger this may take a little while. I hope that's fine.

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger. Just to be 100% sure. 

I found a `TableOfContent` folder in packages/docs/components. In it, there are components whose contents correlate with what's on the live documentation website. Is this where I should be working?

Two, I also noticed that some APIs do not have their corresponding TOCs. Should I add them too?

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Yes! Orient yourself by another table of contents, e.g. https://github.com/remotion-dev/remotion/edit/main/packages/docs/docs/media-utils/index.md and then you can port it over in the same way.

If you find missing APIs, would be glad if you add them as well!

**Comment by kaf-lamed-beyt** [comment]
I submitted a PR just now. 

#2453
