### ISSUE TITLE
How to render video at highest possible quality? Please provide the render command with arguments.

### ISSUE THREAD

**Issue by anjalipandith** [remotion-dev/remotion#2238]
Hi Team
Greetings
I am not happy with the quality of the rendered video.
How to increase the resultant video quality to the highest.

Thanks
Anjali

**Comment by JonnyBurger** [comment]
Use `crf` as the setting for quality: https://www.remotion.dev/docs/encoding/#controlling-quality-using-the-crf-setting

If that is not enough, also consider another codec such as ProRes which support very high quality video.
