### ISSUE TITLE
Support for `--output` in `remotion render` command to customize render output file location.

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#2249]
# Feature Request 🛍️

Just like how the lambda cli command the `--out-name` flag for setting the output file name, it would be great to have an option for `--output` in the cli for normal rendering to specify the path of the file.

## Use Case

I'm using the `remotion render` command in a GitHub action, and I have a composition called `base-comp` that is rendered in the workflow. Since it requires you to specify the path of the file to save as downloadable artifacts on GitHub actions run, having an obscure file called `out/base-comp.mp4` is weird and limits the possibility of using automations like Zapier (since they require a specified file-name), but the comps I render are dynamic, and I don't like the idea of having to change the comp names for the sake of uniformity in output file names...

## Possible Solution

Just support the `--output` flag in the CLI, simple 😊

PS: @JonnyBurger you could assign this to me, would love to learn more about Remotion's CLI's inner workings!

Any tips welcome too 😉

**Comment by Just-Moh-it** [comment]
Oh, right 🤦🏼‍♂️ Almost forgot the basics

I'm used to the `--output` flag from build tools and almost never render through the cli, so my first instinct was to look for the flag in the docs, but didn't find it, so made this issue.

> But since this is a positional argument, and the comp name can be omitted, it would still make sense to have a flag for it!

Totally agree! I think having optional arguments without flags limits the ability to add future required arguments to the cli command without making a breaking changes or breaking existing workflows, making it harder to upgrade.

I think we should move this to a flag instead with the v4 release:

- Leaves room for future required params next to the comp name and doesn't require the outname to be specified, so the ordering doesn't mess up.
- Users from other tools usually look for the `--outname` or the `-o` arg since it's the standard with most build tools.

wdyt @JonnyBurger?

**Comment by JonnyBurger** [comment]
Sounds good to me, but can we also make it so that if you pass an additional argument, it is being treated as --output?

Would be very happy to assign it to you and would also be happy to make a small bounty for it :)

BTW: It makes sense to do it in the v4 branch I think, because the CLI been torn apart and put together

**Comment by Just-Moh-it** [comment]
@JonnyBurger sure, sounds good... Would be happy to work on this 😃

> BTW: It makes sense to do it in the v4 branch I think, because the CLI been torn apart and put together

Also, this would only be a v4 feature then, right?

**Comment by JonnyBurger** [comment]
@Just-Moh-it Awesome, assigned!
Yes, I think this would be easiest if you just point it towards the V4 branch :)

/bounty 100
