### ISSUE TITLE
upgrade templates for Remotion 4.0

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2308]
- [x] HelloWorld TypeScript template - https://github.com/remotion-dev/template-helloworld/pull/14
- [x] HelloWorld JavaScript template - https://github.com/remotion-dev/template-helloworld-javascript/pull/12
- [x] Blank template - https://github.com/remotion-dev/template-empty/pull/3
- [x] React Three Fiber template - https://github.com/remotion-dev/template-three/pull/4
- [x] Still template - https://github.com/remotion-dev/template-still/pull/5
- [x] TTS template - https://github.com/FelippeChemello/Remotion-TTS-Example/pull/4
- [x] Audiogram template - https://github.com/marcusstenbeck/remotion-template-audiogram/pull/8
- [x] Skia template - https://github.com/remotion-dev/template-skia/pull/8/files
- [x] Tailwind template - https://github.com/remotion-dev/template-tailwind/pull/2
- [x] GTTS template
- [x] Stargazer

**Checklist for each template:**

While testing:
- Does use `schema` where it makes sense?
- `remotion.config.ts` uses `@remotion/cli/config` and `setVideoImageFormat()`?
- In config file, the following comment should be:

```
/**
 * Note: When using the Node.JS APIs, the config file
 * doesn't apply. Instead, pass options directly to the APIs.
 * 
 * All configuration options: https://remotion.dev/docs/config
 */
```

- License typo in README fixed?

`Notice that` -> `Note that`

- Can render a video via GUI and via `npm run build`
- In package.json, changed `remotion preview` to `remotion studio`?
- Is prettier on the newest version?

Before merging:
- Does `npm start` run successfully?
- Does `npm test` run successfully without warnings?
- Remotion versions are set to `^4.0.0`? (not alpha, with `^`?)
- Lockfiles deleted? `package-lock.json`, `pnpm-lock.yaml`, `yarn.lock` all should be deleted

**Comment by JonnyBurger** [comment]
Well done!
