### ISSUE TITLE
`npm create video`: Would you like to use tailwindcss?

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#2320]
# Feature Request 🛍️

The title says it all! Next.js and other tools have integrated Tailwind CSS into their CLIs! Was wondering if we could save effort on the user's side.

Also, worth considering: Would you like to use ESLint?

**Comment by Just-Moh-it** [comment]
@JonnyBurger you could assign this to me btw! Would love to take this on if we're gonna be working on this

**Comment by JonnyBurger** [comment]
With the new Tailwind package, this seems realistic..
For ESLint, I don't want to add an option, rather we want to mandate ESLint since it also has a few Remotion related rules that will catch quite some bugs!

**Comment by JonnyBurger** [comment]
@Just-Moh-it And happy to assign you to it!
I estimate that it will work by adding the override to the `remotion.config.ts` config file and then adding `@remotion/tailwind` as a dependency.

Some templates will be hard, like the Skia template already has a Webpack override, in this case maybe we want to skip that.
