### ISSUE TITLE
Freezing when specifying a framerange in renderMedia

### ISSUE THREAD

**Issue by takax2021** [remotion-dev/remotion#2328]
When using the renderMedia function, there is a freezing issue that occurs when specifying a specific framerange. 
More specifically, when the framerange is set to [0, 10], the application freezes.

However, when setting the framerange to [0, 9], [0, 11], or [0, 20], the freezing issue does not occur.

When using headless=false to check the rendering in the browser, the rendering process works fine. 
However, after closing the browser, control does not return to the renderMedia function, causing a freeze.

No error logs are generated during this process.

# Bug Report 🐛

Node Version
node -v
v18.16.0

Remotion Version
remotion": "^3.3.94

Code
await renderMedia({
    composition: composition,
    frameRange: [0,10],//frameRange,
    serveUrl: bundleLocation,
    codec: "h264",
    chromiumOptions: chromiumOptions,
    outputLocation: outputLocation,
    inputProps: {foo: "bar" },
    dumpBrowserLogs:process.env.MY_ENV === 'local'?true:false,
    onBrowserLog: (log) => console.log(log),
    verbose: true,
    concurrency: 1
});

Logs
[verbose] ffmpeg ffmpeg in PATH
stitch-frames-to-video.js:149
[verbose] encoder libx264
stitch-frames-to-video.js:150
[verbose] audioCodec aac
stitch-frames-to-video.js:151
[verbose] pixelFormat yuv420p
stitch-frames-to-video.js:152
[verbose] codec h264
stitch-frames-to-video.js:156
[verbose] shouldRenderAudio true
stitch-frames-to-video.js:157
[verbose] shouldRenderVideo true
stitch-frames-to-video.js:158
[verbose] proResProfileName null

**Comment by JonnyBurger** [comment]
Hey @takax2021!

Most likely this is dependent on the React code associated with this render.
I did a quick test and it does not seem like this happens with any component that renders `0-10`.

Can you post the React code as well?

**Comment by takax2021** [comment]
@JonnyBurger
Thank you for the helpful advice and suggestions.
After conducting some research, it appears that the issue might be caused by the "remotion-transition-series" library.
I disabled this transition, and the freezing issue no longer occurs.
It is still unclear whether the problem lies with the library itself or with its usage.
Considering it is likely not an issue with Remotion itself, I suggest closing this ticket.

[remotion-transition-series](https://github.com/marcusstenbeck/remotion-transition-series)

**Comment by JonnyBurger** [comment]
@takax2021 Thanks for reporting back!

Indeed then this should be raised on the Transition Series repository, I'm sure @marcusstenbeck will be glad if you have a reproduction!

Also note that remotion-transition-series had an update last week, maybe it solved exactly your issue!

**Comment by marcusstenbeck** [comment]
@takax2021 Yes if you post an issue in the [remotion-transition-series](https://github.com/marcusstenbeck/remotion-transition-series) repo with a reproduction (either a repo or a codesandbox) I could have a look at it.
