### ISSUE TITLE
Limited to 1 frame per second when creating a <Still /> from a <Video /> due to fps default value

### ISSUE THREAD

**Issue by Sterv** [remotion-dev/remotion#2363]
# Bug Report 🐛

I want to render a thumbnail using `<Still />` and `<Video startFrom={thumbnailFrame} />`. If `Still.fps` is not customizable and `fps = 1`, there is only 1 frame available per second to use from a video. In other words, you can't select a frame that lands outside of the first frame of every second.

`const fps = useVideoConfig().fps // 1 by default`

`<Video
    startFrom={32} // 32s into a video
 />`
  
Ideally, the `fps` for a `<Still />` is customizable so user's have more frames to choose from. For example, if we could pass in `Still.fps = 30`, we could select a frame 32.2s into the video like this:

`<Video
    startFrom={966} // 32.2s
 />`

**Comment by JonnyBurger** [comment]
Hey Stephen! 🙂

This is a good point, and something that I didn't think about while designing this API.

At the same time, it seems confusing to add a `fps` to the `<Still>` component. Before we do this, may I suggest some alternatives..

- There seems to be no restriction in the latest version that you cannot use a float. So `startFrom={32.2 * fps}` should work if I see this correctly?
- Internally, Remotion does actually not look if you use `<Still>` or `<Composition>`. So you can just mount a `<Composition>` with `1` duration and `30` fps and Remotion will still treat it as a still, including hiding the timeline.

**Comment by Sterv** [comment]
Yes, the alternative works!  We can just pass the fps into the defaultProps of our `<Still />` and use that to target frame:

`<Still
	component={VideoThumbnail}
	defaultProps={{
		videoSrc,
		fps,
		thumbnailFrame
		}}
	/>`

Inside `<VideoThumbnail />`:

`<Video startFrom={thumbnailFrame / fps} src={videoSrc} />`

Thank you.

**Comment by JonnyBurger** [comment]
Great! Hopefully people will find this issue if they stumble upon this.
