### ISSUE TITLE
Add `mutechange` event to player

### ISSUE THREAD

**Issue by pawelkontek** [remotion-dev/remotion#2376]
# Feature Request 🛍️

A way to keep` playerRef.current.isMuted()` in a state 

## Use Case

...so I could display messages like: "please turn on sound" if the player is muted.

**Comment by JonnyBurger** [comment]
Acceptance criteria:

- Implement a `mutechange` event similar to `volumechange` and `fullscreenchange` (https://www.remotion.dev/docs/player/player)
- Document it in the player.md

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 100

**Comment by rjackson** [comment]
Happy to have a look at this

/attempt #2376

**Comment by JonnyBurger** [comment]
Thanks! Good luck @rjackson 🙌🏼

This issue is taken, please no further attempts 🙅‍♂️
