### ISSUE TITLE
v4 /docs/lambda/feb-2022-outage architecture prop removed

### ISSUE THREAD

**Issue by UmungoBungo** [remotion-dev/remotion#2417]
A twoslash error appears on this page, as the architecture prop no longer exists. For the cloudrun build, i just commented it out for now;
<img width="507" alt="image" src="https://github.com/remotion-dev/remotion/assets/22192773/603ac8cc-014d-4b49-bd00-9c51353e3927">

I'm not sure what the solution is, but here are some options

- Remove the page altogether
- Remove the code sample, and explain that there was a solution for Remotion >3.x <4/0
- Edit the code sample the way I have for cloudrun, and put a comment there explaining the situation

I made some tasks here so we don't lose sight of the jsdoc updating too;
- [ ] fix the page so that it builds
- [ ] Update the jsdoc comments on src/api/deploy-function.ts as they reference the architecture prop

**Comment by JonnyBurger** [comment]
Thanks, fixed in 472242d3983d9e890f73891451f88efb90a37197!
