### ISSUE TITLE
ability to call getVideoMetadata()  from a node js app.

### ISSUE THREAD

**Issue by alexfernandez803** [remotion-dev/remotion#2430]
# Feature Request 🛍️

Ability to use getVideoMetadata to query the width, height and other metadata from nodejs app.
Right now, I am seeing this error 
node_modules/@remotion/media-utils/dist/get-video-metadata.js:13
        throw new Error('getVideoMetadata() is only available in the browser.');

## Use Case

This is nice to have to precompute the width and height of the video as a parameter for getInputProps().

## Possible Solution

use ffprobe to get the metadata, we just need to expose a function.
https://superuser.com/questions/841235/how-do-i-use-ffmpeg-to-get-the-video-resolution

**Comment by JonnyBurger** [comment]
Legit request!

**Comment by JonnyBurger** [comment]
`@remotion/media-utils` should stay a browser-only package, so it doesn't break suddenly when you import via browser.

We could add this as APIs for `@remotion/renderer`.
