### ISSUE TITLE
Is there a way to keep Sequence children mounted while not within the time range of display?

### ISSUE THREAD

**Issue by Harukisatoh** [remotion-dev/remotion#2435]
Hello guys, first of all I would like to thank you all for the lib, it's amazing!

I'm trying to animate the entrance of a text in the screen, where each word of the text fades in to the screen in sequence. I've made a working version, but there's one detail that I would like to change. Here's the working version:

![Screen Recording 2023-06-22 at 5 38 34 PM](https://github.com/remotion-dev/remotion/assets/37125288/67ba6fa5-a914-4e82-9749-6d9cd60380aa)

The problem for me is that each new word pushes the already rendered words a little bit since the element is only mounted when each animation starts to play.

Here's how I created this animation, maybe this will help:
```ts
import {Sequence} from 'remotion';

import {Text} from '../components/Text';

import {FadeStart} from './FadeStart';

interface Props {
	// How long does it take to each word to start transition
	entranceIntervalInFrames?: number;
	// How long all the words will be shown together
	durationInFrames?: number;
	children: string;
}

export function AnimatedWords({
	entranceIntervalInFrames = 10,
	durationInFrames = 80,
	children,
}: Props) {
	const words = children.split(' ');

	return (
		<div className="flex flex-wrap gap-4 justify-center content-center h-full">
			{words.map((word, index) => (
				<Sequence
					layout="none"
					name="Word Fade In"
					durationInFrames={
						durationInFrames + entranceIntervalInFrames * (words.length - index)
					}
					from={index * entranceIntervalInFrames}
				>
					<FadeStart
						className="inline-block h-fit"
						startValue={0}
						endValue={1}
						duration={10}
					>
						<Text>{word}</Text>
					</FadeStart>
				</Sequence>
			))}
		</div>
	);
}

```

So my question is, is there a way to force the sequence to render its children even though the animation is not within the time range of display?

**Comment by JonnyBurger** [comment]
A `<Sequence>` will always remove the children if they are not shown at the current time.

What you can do though, is to instead of using a Sequence, to keep the opacity at 0 as long as the animation does not start.
For this you could for example implement a `delay` prop for the `FadeStart` component, and then delay the animations depending on this value.
