### ISSUE TITLE
want to pass an id to the composition from the url

### ISSUE THREAD

**Issue by anjalipandith** [remotion-dev/remotion#2459]
I have a composition and i want to pass an id to the composition from the url

http://localhost:3001/MyComp/23

How to pass id (23) argument so that i can fetch the json from the backend?

	const fetchData = useCallback(async () => {
		try {
			const response = await fetch(`http://127.0.0.1:3000/api/videos/${id}`);
......
.
.
.
.
		} catch (error) {}
	}, [handle]);

**Comment by JonnyBurger** [comment]
Don't use a URL parameter, use input props https://www.remotion.dev/docs/parametrized-rendering#input-props together with data fetching techniques: https://www.remotion.dev/docs/data-fetching

**Comment by JonnyBurger** [comment]
For V4, we will improve it a lot, also wrote new docs for how to do that:

https://v4.remotion.dev/docs/data-fetching
