### ISSUE TITLE
Show a list of files in the public/ folder in the Studio

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2466]
Mockup:

<img width="384" alt="image" src="https://github.com/remotion-dev/remotion/assets/1629785/fee33fdc-331a-4938-9ecc-4e69426f875e">

- Let's add a second panel the left sidebar and make two tabs
- In the `Assets` panel, we show a list of files that have been added to the public/ folder - listing `getStaticFiles()`
- For now, let's allow to users to click on a folder icon and it will reveal that asset in the file explorer (take same logic as in the render queue where you can also reveal a file in the explorer)

Future ideas (but not part of this issue!)
- Drag and drop a new file in the studio to add it to the public/ folder
- Delete files from the studio
- Click on an asset to preview it

/bounty 160

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

**Note**: As we are close to a major release, we might be unable to review the pull request immediately.

**Comment by Just-Moh-it** [comment]
/attempt #2466 @JonnyBurger would love to take this on!

**Comment by JonnyBurger** [comment]
@Just-Moh-it This would be fire! 🔥

**Comment by Just-Moh-it** [comment]
@zcesur algora out of office today? 😂

**Comment by JonnyBurger** [comment]
lol, let's try again

/bounty 160

In any case it shall count!

**Comment by zcesur** [comment]
> @zcesur algora out of office today? :joy:

<img width="221" src="https://github.com/remotion-dev/remotion/assets/17045339/9846e469-4f84-4ded-88b4-8f70a1971727" />

@Just-Moh-it @JonnyBurger we had some constraints that made it nontrivial to support slash commands in the issue body (rather than in a comment), but i just rewrote a bunch of stuff and it should work going forward :nerd_face:
