### ISSUE TITLE
lambda functions rmall exits on first 'no' from the user

### ISSUE THREAD

**Issue by UmungoBungo** [remotion-dev/remotion#2469]
# Bug Report 🐛

For the cloudrun package, the `services rmall` CLI command allows the user to selectively delete the services found
![image](https://github.com/remotion-dev/remotion/assets/22192773/aee48903-1b7b-4970-b219-d6cd52aa9b8c)

For the lambda package, the `functions rmall` CLI command will quit as soon as a no is received
![image](https://github.com/remotion-dev/remotion/assets/22192773/c02f3368-87cf-4254-9942-47a330dca84b)

This is because it makes use of the confirm helper at `src/cli/helpers/confirm.ts`, which has the behaviour baked in. Perhaps we can instead use the yesOrNo function from within confirm.ts instead.

Alternatively, this is the behaviour you want, and I can change cloud run to be consistent!

**Comment by JonnyBurger** [comment]
What you do in Cloud Run seems more sensible to not quit outright.
I'm in favor of porting this over to Lambda rmall.
