### ISSUE TITLE
Error when requesting lambda rendering without passing composition name

### ISSUE THREAD

**Issue by UmungoBungo** [remotion-dev/remotion#2470]
# Bug Report 🐛

In these screenshots, I'm creating a site named `render-test`, then I'm trying to render without passing a composition name, then I am successfully rendering with a composition name. You can see that when no composition is passed, it says `No compositions passed. Fetching compositions...` but then fails.

![image](https://github.com/remotion-dev/remotion/assets/22192773/86c4a669-0e4c-4ba7-a5a4-1c03a813dd5d)

There is similar behaviour in Cloud Run, in that it fails if no composition is passed, but it doesn't produce the same error message. I assume this is related to the fact that I haven't implemented `getCompositionsOnCloudrun()` yet.

![image](https://github.com/remotion-dev/remotion/assets/22192773/14a0b7aa-a049-4792-b90b-fb33d484bcb7)

**Comment by JonnyBurger** [comment]
This is already tracked in https://github.com/remotion-dev/remotion/issues/2425
