### ISSUE TITLE
Remotion Studio Feature: Copy still to clipboard

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2478]
This would be sick so you can immediately paste it into Figma

**Comment by clearlysid** [comment]
Nifty! Happy to make this happen.

We could:
1. use something like [html2canvas](https://html2canvas.hertzen.com) and save the result.
2. use remotion's own `renderStill` either via the CLI or via Node.

The former will be pretty quick to try, but I remember using it and finding it quite unreliable a few years ago. Will give it a try nonetheless, things might've improved 🙌

**Comment by clearlysid** [comment]
Nope, still wonky. Lots of CSS properties are not supported with html2canvas (and similar tools). Our best bet is to use the Remotion renderer itself.

Can give this a go next weekend perhaps.

**Comment by JonnyBurger** [comment]
The html2canvas approach does not work (https://www.remotion.dev/docs/miscellaneous/render-in-browser)

This is my idea: We can already render a still in the preview and we enhance this functionality – we already have a "open in explorer" action, and we pretty much duplicate it but change the functionality a bit, to instead execute a command to read the file and copy it to clipboard. This logic can be used: https://github.com/kufii/img-clipboard/blob/master/index.js

This is the open in explorer action: `packages/cli/src/preview-server/routes/open-in-file-explorer.ts`

If you are still interested in contributing this, let me know!

**Comment by clearlysid** [comment]
🚀🚀🚀
