### ISSUE TITLE
Create a nicer experience for rendering a portion of a video

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2482]
Current experience of rendering a portion of a video:

![image](https://github.com/remotion-dev/remotion/assets/1629785/f7293a04-e443-435f-b435-78b03dd2c0ed)

Wouldn't something like this be much better?

![image](https://github.com/remotion-dev/remotion/assets/1629785/777385ed-8b63-4418-966c-3fa7f95636d3)

(Design wise, it may also be improved of course)

Requirements:

- Should use no external JS or CSS dependencies
- handles should be keyboard accessible
- should handle the case well where the duration of the video suddenly changes by changing the code

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 150

**Comment by mnmt7** [comment]
@JonnyBurger, I would like to work on this issue.

**Comment by JonnyBurger** [comment]
@mnmt7 Very cool! Good luck!

**Comment by Tonie-NG** [comment]
Hello @JonnyBurger If this issue is still available, I wouldn't mind taking it up
