### ISSUE TITLE
Allow to set per-composition render defaults

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2487]
Currently the codec (any many other options) are determined by a few factors:

1. Specified in the render dialog in the Remotion Studio?
2. Specified as a CLI flag?
3. Passed explicitly to renderMedia()?
4. Specified in the config file?
5. Fallback: Default codec

The idea is to add another way that allows per-default configuration, starting with `codec`

```tsx
<Composition calculateMetadata={() => {
	return {defaultCodec: "vp8"}
}}/>
```

This will have a higher priority than the config file, but less priority than explicitly passing the option to renderMedia().

The `VideoConfig` type should be expanded with a `defaultConfig` field:

https://github.com/remotion-dev/remotion/blob/b2f80dca690b414050495e6e6f0c8416a2a9dc92/packages/core/src/video-config.ts#L1-L5

This is a good first step and TypeScript should reveal the places where you need to implement additional functionality

## Acceptance criteria

- Make the composition get rendered with this codec if nothing with higher priority was specified.
- In the Remotion Studio, when rendering, the codec should be preselected in the modal but overridden.
- Logs should also tell when this was used for resolution ([extend this here](https://github.com/remotion-dev/remotion/blob/b2f80dca690b414050495e6e6f0c8416a2a9dc92/packages/cli/src/get-final-output-codec.ts#L23))
- Add it to the `calculateMetadata()` docs

## Bounty

💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion | Remotion | Make videos programmatically in React](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 200

**Comment by JonnyBurger** [comment]
@mnmt7 Still planning to do this?

**Comment by mnmt7** [comment]
@JonnyBurger Will create a PR by tomorrow.

**Comment by JonnyBurger** [comment]
@mnmt7 Cool, no rush though!
