### ISSUE TITLE
Showing spawn start ENOENT when opening rendered video from remotion studio

### ISSUE THREAD

**Issue by musafiroon** [remotion-dev/remotion#2488]
After rendering a video, I am not able to open the rendered video using the link below in the right sidebar
# Bug Report 🐛
![Image](https://github.com/remotion-dev/remotion/assets/73289588/869ef8b2-eec5-49a7-ad1d-e022105fbd99)
OS: Windows 11
I believe this is because it is opening the file using [`cp.spawn`](https://github.com/remotion-dev/remotion/blob/main/packages/cli/src/preview-server/render-queue/open-directory-in-finder.ts#L24)

can we change the code to use `cp.exec`

**Comment by JonnyBurger** [comment]
Thanks for the report, I just reproduced this on Windows!
And your suggestion is also on point, this is the solution!

Will be fixed in 4.0.1
