### ISSUE TITLE
Prevent exiting the page if there are unsaved changes to the default props

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2495]
If the Remotion Studio Props Editor has unsaved changes, and you are about to reload, then an alert should be triggered using `window.onbeforeunload` telling the user that there are unsaved changes.

To determine if there are unsaved changes, check only if the root object is changed.

Once the changes are saved, the handler should be removed.

**Special case:** 

There are 5 cases where Remotion Studio will reload itself (look for `window.location.reload()`):

- New input props or env variables (packages/cli/src/event-source.ts) ❌
- Fatal React error (packages/cli/src/preview-server/error-overlay/entry-basic.ts) ✅
- Hook order changed (packages/cli/src/preview-server/error-overlay/react-overlay/listen-to-runtime-errors.ts) ❌
- Failed fast refresh (packages/cli/src/preview-server/hot-middleware/process-update.ts) ❌

✅ The error is unrecoverable and we anyway lost our changes, so we can refresh
❌ The error is not recoverable, and we should not refresh, instead show a notification using `notificationCenter.current?.addNotification`

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 100

**Comment by mnmt7** [comment]
@JonnyBurger Can I work on this issue?

**Comment by JonnyBurger** [comment]
@mnmt7 Sorry for missing this comment!
Would you still like to do this?

**Comment by mnmt7** [comment]
@JonnyBurger Sure, I would like to work on this issue.

**Comment by rishi-raj-jain** [comment]
@JonnyBurger Can I work on this?

**Comment by JonnyBurger** [comment]
Giving it to @mnmt7 now who was the first to ask!

More bounties coming 🙂

**Comment by rishi-raj-jain** [comment]
@JonnyBurger 

Keen for the upcoming bounties!

**Comment by rishi-raj-jain** [comment]
@JonnyBurger

Can I work on this now?

**Comment by rishi-raj-jain** [comment]
@JonnyBurger

Can I work on this now?

**Comment by rishi-raj-jain** [comment]
when you say root object changed, you mean root-file-changed event, right?

**Comment by JonnyBurger** [comment]
No, this means that if the object in the props editor in the right sidebar has changed. This is the case if there is an unsaved indicator in the props editor (as seen here in the beginning https://www.youtube.com/watch?v=ABQErIOxUNg)

**Comment by JonnyBurger** [comment]
@rishi-raj-jain Note that I did not yet assign you to the issue. This should be avoided in the future otherwise there will be a conflict at some point. Nonetheless, I'll proceed reviewing your PR, thanks a lot!
