### ISSUE TITLE
Add 1.5x speed to the Remotion Studio 

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/remotion#2508]
![Screenshot 2023-07-05 at 15 53 58](https://github.com/remotion-dev/remotion/assets/86873911/49fc1064-919a-4601-bffe-12f0f4f61671)

**Comment by dvyne10** [comment]
will work on this

**Comment by MehmetAdemi** [comment]
For sure, if you like, give it a go! 👍
