### ISSUE TITLE
Fullscreen button in Studio

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2523]
In the Remotion Player, we have a fullscreen button.

Can we also add one in the Studio? Mockup:

![image](https://github.com/remotion-dev/remotion/assets/1629785/59ec5bc3-7af5-4706-99a1-4441dbda1baf)

Fulfillment Criteria:

- Should only show if the browser supports fullscreen
- Should fullscreen the canvas element, and size the video correctly that it takes the biggest space it can, but not stretch or go beyond the edges (standard video behavior)
- Keyboard shortcuts should remain functional, probably no change is required for this.

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 100

**Comment by tobihans** [comment]
I'd like to pick this.

**Comment by JonnyBurger** [comment]
@tobihans Good luck!
