### ISSUE TITLE
Unable to open orb (`packages/example`) in studio: `R3F: Hooks can only be used within the Canvas component!`

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#2534]
# Bug Report 🐛

Opening the `three/Orb` example on `packages/example` in the studio gives this error

<img width="1177" alt="image" src="https://github.com/remotion-dev/remotion/assets/48997634/750e1fd9-a68a-4f45-8478-8aca1baa8480">

## Full Error

<details>
	<summary>Full error</summary>
	R3F: Hooks can only be used within the Canvas component!

Open in VS Code Insiders⌘O

Search GitHub Issues ⌘G

Ask on Discord ⌘D
useStore
../../node_modules/.pnpm/@react-three+fiber@8.8.10_react-dom@18.2.0_react@18.2.0_three@0.145.0/node_modules/@react-three/fiber/dist/index-21f75f82.esm.js:1626

 1623
}
 1624
function useStore() {
 1625
  const store = React.useContext(context);
 1626
  if (!store) throw new Error('R3F: Hooks can only be used within the Canvas component!');
 1627
  return store;
 1628
}
 1629
/**
useFrame
../../node_modules/.pnpm/@react-three+fiber@8.8.10_react-dom@18.2.0_react@18.2.0_three@0.145.0/node_modules/@react-three/fiber/dist/index-21f75f82.esm.js:1644

 1641
 */
 1642
 1643
function useFrame(callback, renderPriority = 0) {
 1644
  const store = useStore();
 1645
  const subscribe = store.getState().internal.subscribe; // Memoize ref
 1646
 1647
  const ref = useMutableCallback(callback); // Subscribe on mount, unsubscribe on unmount
(anonymous function)
../../node_modules/.pnpm/@react-three+drei@9.37.0_@react-three+fiber@8.8.10_react-dom@18.2.0_react@18.2.0_three@0.145.0/node_modules/@react-three/drei/core/MeshDistortMaterial.js:71

   68
  ...props
   69
}, ref) => {
   70
  const [material] = React.useState(() => new DistortMaterialImpl());
   71
  useFrame(state => material && (material.time = state.clock.getElapsedTime() * speed));
   72
  return /*#__PURE__*/React.createElement("primitive", _extends({
   73
    object: material,
   74
    ref: ref,
renderWithHooks
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:7363

 7360
    }
 7361
  }
 7362
 7363
  var children = Component(props, secondArg); // Check if there was a render phase update
 7364
 7365
  if (didScheduleRenderPhaseUpdateDuringThisPass) {
 7366
    // Keep rendering in a loop for as long as render phase updates continue to
updateForwardRef
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:11457

11454
  {
11455
    ReactCurrentOwner$1.current = workInProgress;
11456
    setIsRendering(true);
11457
    nextChildren = renderWithHooks(current, workInProgress, render, nextProps, ref, renderLanes);
11458
    hasId = checkDidRenderIdHook();
11459
11460
    if ( workInProgress.mode & StrictLegacyMode) {
beginWork
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:13880

13877
13878
        var _resolvedProps2 = workInProgress.elementType === type ? _unresolvedProps2 : resolveDefaultProps(type, _unresolvedProps2);
13879
13880
        return updateForwardRef(current, workInProgress, type, _resolvedProps2, renderLanes);
13881
      }
13882
13883
    case Fragment:
HTMLUnknownElement.callCallback
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:14219

14216
      function callCallback() {
14217
        didCall = true;
14218
        restoreAfterDispatch();
14219
        func.apply(context, funcArgs);
14220
        didError = false;
14221
      } // Create a global error event handler. We use this to capture the value
14222
      // that was thrown. It's possible that this error handler will fire more
invokeGuardedCallbackDev
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:14268

14265
      // errors, it will trigger our global error handler.
14266
14267
      evt.initEvent(evtType, false, false);
14268
      fakeNode.dispatchEvent(evt);
14269
14270
      if (windowEventDescriptor) {
14271
        Object.defineProperty(window, 'event', windowEventDescriptor);
invokeGuardedCallback
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:14329

14326
function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
14327
  hasError = false;
14328
  caughtError = null;
14329
  invokeGuardedCallbackImpl$1.apply(reporter, arguments);
14330
}
14331
function hasCaughtError() {
14332
  return hasError;
beginWork$1
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:19537

19534
      } // Run beginWork again.
19535
19536
19537
      invokeGuardedCallback(null, beginWork, null, current, unitOfWork, lanes);
19538
19539
      if (hasCaughtError()) {
19540
        var replayError = clearCaughtError();
performUnitOfWork
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:18686

18683
18684
  if ( (unitOfWork.mode & ProfileMode) !== NoMode) {
18685
    startProfilerTimer(unitOfWork);
18686
    next = beginWork$1(current, unitOfWork, subtreeRenderLanes);
18687
    stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
18688
  } else {
18689
    next = beginWork$1(current, unitOfWork, subtreeRenderLanes);
workLoopSync
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:18597

18594
function workLoopSync() {
18595
  // Already timed out, so perform work without checking if we need to yield.
18596
  while (workInProgress !== null) {
18597
    performUnitOfWork(workInProgress);
18598
  }
18599
}
18600
renderRootSync
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:18565

performConcurrentWorkOnRoot
../../node_modules/.pnpm/react-reconciler@0.27.0_react@18.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:17836

workLoop
../../node_modules/.pnpm/scheduler@0.21.0/node_modules/scheduler/cjs/scheduler.development.js:266

flushWork
../../node_modules/.pnpm/scheduler@0.21.0/node_modules/scheduler/cjs/scheduler.development.js:239

MessagePort.performWorkUntilDeadline
../../node_modules/.pnpm/scheduler@0.21.0/node_modules/scheduler/cjs/scheduler.development.js:533
</details>

**Comment by JonnyBurger** [comment]
Thanks for reporting - we've seen your issue and acknowledge it!
Given an increase in issues and requests, it will take a few days for us to investigate and respond to it - thanks for your patience.
