### ISSUE TITLE
v4 introduced flickering - blank black screens

### ISSUE THREAD

**Issue by gevorggalstyan** [remotion-dev/remotion#2544]
After upgrading to v4 the generated videos have missing/black frames.

# Bug Report 🐛

I have upgraded the emotion to version 4 and the videos generated started flickering. This is different from the background image flickering mentioned in the official docs Troubleshooting sections as the frames are fully black, with no text, no images, nothing, just pitch black frame. They get added randomly with no pattern.

This is happening on a 2018 15-inch MacBook Pro, 2.9 GHz 6-Core Intel Core i9, Intel UHD Graphics 630 1536 MB, 32 GB 2400 MHz DDR4.

After downgrading to v3 the videos are generating normally again.

There are no exceptions or errors.

The image type for the video has been set to jpeg and the quality was set to 100%.

**Comment by JonnyBurger** [comment]
Can you describe, or even better, show the code of your composition?
It would be good to know which component had this regression.

**Comment by ieiekk** [comment]
I encounter the same problems in v4.0.8, black frame randomly appeared in my renders,
and I use @remotion/renderer to render out videos.

- Main.tsx(output comp)
```javascript
import { AbsoluteFill, Sequence } from "remotion";
import Wave from "./comp/Wave";
import Base from "./comp/Base";
import Name from "./comp/Name";
import Photo from "./comp/Photo";

export const Main = ({ name, url }: { name: string; url: string }) => {
  return (
    <AbsoluteFill>
      {/* Base */}
      <Sequence durationInFrames={240}>
        <Base />
      </Sequence>
      {/* Photo */}
      <Sequence durationInFrames={240}>
        <Photo url={url} />
      </Sequence>
      {/* Name */}
      <Sequence durationInFrames={240}>
        <Name name={name} />
      </Sequence>
      {/* Wave */}
      <Sequence durationInFrames={48}>
        <Wave />
      </Sequence>
    </AbsoluteFill>
  );
};
``` 

Which Photo and Name comp are lottie, Wave is webm video with alpha, and Base is mp4.
I notice that glitch frames only appear at frame that has the webm playing.

**Comment by ieiekk** [comment]
Fix it by changing [Video](https://www.remotion.dev/docs/video) to [OffthreadVideo](https://www.remotion.dev/docs/offthreadvideo).
