### ISSUE TITLE
"Jump to Beginning" button should jump to "Mark In" frame if active

### ISSUE THREAD

**Issue by BrodyRas** [remotion-dev/remotion#2573]
# Bug Report 🐛
When the "Mark In" frame is active, the "Jump to Beginning" button should jump to that frame, instead of the actual first frame of the composition.

## Steps to Reproduce
- Open a composition
- Use the "Mark In" button on a frame that isn't the first frame of the composition
- Press the "Jump to Beginning" button
- Note how the playhead is now outside the active frames

![Jul-12-2023 10-16-50](https://github.com/remotion-dev/remotion/assets/49171024/b48e1f1c-b5ae-43cf-842d-68d2f7e2501e)

**Comment by JonnyBurger** [comment]
Good point!

**Comment by mnmt7** [comment]
@JonnyBurger, can I have a go at this?

**Comment by JonnyBurger** [comment]
Happily! @mnmt7
