### ISSUE TITLE
Support rational fps like 24000/1001

### ISSUE THREAD

**Issue by XeroAlpha** [remotion-dev/remotion#2582]
# Bug Report 🐛

FPS of output video is incorrect when using a rational fps, for example, given fps=23.976023976023978 (24000/1001) will output a video with fps=23.976 (23976/1000).

It seems that [pre-encode](https://github.com/remotion-dev/remotion/blob/1635e45a65aeb90b50703d820c9290281e3048cc/packages/renderer/src/prespawn-ffmpeg.ts#L89C34-L89C34) decreases the accuracy of fps.

**Comment by JonnyBurger** [comment]
Thanks, we tested for regressions and did not find any, so we removed this.
