### ISSUE TITLE
Allow changing of frame output dir via CLI or GUI in Remotion

### ISSUE THREAD

**Issue by multimokia** [remotion-dev/remotion#2602]
Looking over the docs, I see `renderFrames()` has the option to specify `outputDir` however that option doesn't seem to be exposed via `npx remotion render`'s flags, nor in the GUI for remotion's rendering ability. 

# Feature Request 🛍️
I would like the ability to directly configure remotion's frame render directory via the CLI or GUI.

## Use Case
For users who don't have space on their primary drive, but have other drives that can be rendered to, this allows them to still use remotion to render videos.

## Possible Solution
Simply a CLI flag (`--outputDir`) and GUI option (likely in the `Other` option) to specify a path to render frames to.

**Comment by patsalv** [comment]
Hey @multimokia, thanks for your request!

Actually, this can already be done in the way explained [here](https://www.remotion.dev/docs/miscellaneous/changing-temp-dir), therefore I'd close this issue.
