### ISSUE TITLE
Memory limit exceeded when using <OffthreadVideo> on Google Cloud Run

### ISSUE THREAD

**Issue by tzvc** [remotion-dev/remotion#2611]
Hey there,

I have a composition with two videos. After getting missed frames and flicker with the `<Video>` component, I switched to `<OffthreadVideo>` and now I'm getting `Memory limit exceeded` error when trying to render on google cloud run.

I've tried allocating more memory to the cloud run instances (up to 10Gb), but it always end up exceeding it.

The same render runs fine on my 8Gb macbook (even tho there was instances where the render made my system crash, probably due to bad memory allocation).

I had a look at the code and it seems like the frames exported are cleared periodically to free up memory. However, that check is done only on system memory with `os.freemem()` and does not account for disk space. See below [source](https://github.com/remotion-dev/remotion/blob/main/packages/renderer/src/compositor/compositor.ts#L34)

```typescript
// in packages/renderer/src/compositor/compositor.ts
export const getIdealMaximumFrameCacheItems = () => {
	const freeMemory = os.freemem();
	// Assuming 1 frame is approximately 6MB
	// Assuming only half the available memory should be used
	const max = Math.floor(freeMemory / (1024 * 1024 * 6));

	// Never store more than 2000 frames
	// But 500 is needed even if it's going to swap
	return Math.max(500, Math.min(max, 2000));
};
```

In cloud run, memory refers to [the addition of RAM and disk usage](https://cloud.google.com/run/docs/configuring/memory-limits).

So my theory is that the limit of 2000 saved frames (6MB * 2000 = 12000 MB) is enough to exceed the disk allocation of the instance.

Perhaps an option would be to make the number of cached frames configurable in the `renderMedia()` call.

What do you think?

**Comment by tzvc** [comment]
@JonnyBurger awesome! Any idea off the top of your head for a quick fix we could deploy in the meantime? We're currently running maxed out (32Gb, 8 vcpu) to mitigate the issue but it is less than ideal haha

**Comment by JonnyBurger** [comment]
@tzvc `4.0.12` to the rescue! It fixes the memory leak for good I hope. Feel free to report if you still encounter any problems.
