### ISSUE TITLE
Input props not being passed to Lambda (PHP)

### ISSUE THREAD

**Issue by chris-sev** [remotion-dev/remotion#2626]
Hey I'm trying to call this code and I'm seeing that input props aren't being passed to Lambda. 

```php
$client = new PHPClient($region, $serveUrl, $functionName, [
    'key' => config('services.remotion.aws_key'),
    'secret' => config('services.remotion.aws_secret'),
]);

$params = new RenderParams();
$params->setComposition('HelloWorld');
$params->setInputProps(['message' => 'yo whats up']); // <--- these get passed in but are overridden somewhere

$renderResponse = $client->renderMediaOnLambda($params);
```

I'm seeing input props always null. It seems like they are getting overridden.

### Possible fix

I think the issue is in [line 39 of PHPClient.php](https://github.com/remotion-dev/lambda-php-sdk/blob/main/src/PHPClient.php#L37)

`$render->getData()` always shows as null for me. 

```php
$input = $this->serializeInputProps(
    $render->getData(), // <---- ❓ should this be $render->getInputProps()
    $this->getRegion(),
    "video-or-audio",
    null
);
```

I believe we can change that line to `$render->getInputProps()` so that it will pull in the correct props.

After changing that line, the props look correct:

![CleanShot 2023-07-24 at 12 09 20@2x](https://github.com/remotion-dev/lambda-php-sdk/assets/1857851/632ed12d-a7e0-4ec4-8f56-2b1d87452317)

**Comment by alexfernandez803** [comment]
@chris-sev  for PHP, the inputProps is set as 
$params->setData(['message' => 'yo whats up']);

**Comment by JonnyBurger** [comment]
Thanks for the report!
This is not good DX, we'll improve it based on this!

**Comment by JonnyBurger** [comment]
With #2639. setInputProps() will now work as expected (alias for setData() now).

Also, the responses are now type-safe so you should get autocompletion in PHP!
