### ISSUE TITLE
Error: Runtime exited without providing a reason Runtime.ExitError

### ISSUE THREAD

**Issue by kacperadach** [remotion-dev/remotion#2670]
I am getting this error occasionally when rendering on Remotion 4.0.14. This appears to be one of the lambda's that renders a portion of the video: `Rendering frames 3174-3219 in this Lambda function.` The line before the error says: `INFO Cleaning up and writing timings`. I know there isn't much to go off of, but I'd be willing to provide more context if needed.

**Comment by JonnyBurger** [comment]
This is actually the success message! We call `process.exit(0)` to clean up the memory and browser for the next invocation.

Do you have a problem when using Lambda?

**Comment by kacperadach** [comment]
Oh, good to know this isn't actually an error message. Yes I am seeing issues but it has to do with this issue: https://github.com/remotion-dev/remotion/issues/2642

I will close this issue and follow up on the other one.
