### ISSUE TITLE
Lambda times out before renders finishes

### ISSUE THREAD

**Issue by alexfernandez803** [remotion-dev/remotion#2671]
# Bug Report 🐛

We have 8 minutes and 10 seconds. The composition has an audiogram same as audiogram template and audio. 
The lambda has 3008 Mb memory and  timesout on  15mins limit. It uses 4.0.15 version.

Is the length of the audio not a valid use case for this audio length?

**Comment by JonnyBurger** [comment]
It seems to me like this should be doable. What do the logs of the timed out chunk say? Can you post one of them?

**Comment by alexfernandez803** [comment]
Here is the error that I've encountered.

Error\n    at makeTimeoutError (/var/task/index.js:187233:12)\n    at getProgress (/var/task/index.js:187408:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async innerHandler (/var/task/index.js:188284:22)\n    at async Runtime.routine [as handler] (/var/task/index.js:188335:5)\n    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1118:26)

**Comment by alexfernandez803** [comment]
pre-render-metadata.json snippet.
lambdaVersion":"4.0.16","framesPerLambda":108,"memorySizeInMb":3008,"region":"us-east-1","renderId":"5q1facd6po","privacy":"private","everyNthFrame":1,"frameRange":[0,14729],"audioCodec":null}

"width":1280,"height":720,"fps":30,"durationInFrames":14730,

**Comment by JonnyBurger** [comment]
Give the full logs of one the timed out chunks please?

With the newer versions, you can even run with --log=verbose and you get a link to it directly.

We can look at the timings and see what is slow

**Comment by alexfernandez803** [comment]
sent it in discord.

**Comment by JonnyBurger** [comment]
Discussed in Discord: The reason for it was a too low Lambda concurrency limit.
