### ISSUE TITLE
there is something wrong when rendering except for English 

### ISSUE THREAD

**Issue by log901108** [remotion-dev/remotion#2676]
# Bug Report 🐛
I just created repository from npm init video with tsx template.
and then only change 'titleText' in the Root.tsx with Korean, Chinese, Japanese. It gives same error with broken text like below.

![korean](https://github.com/remotion-dev/remotion/assets/35515018/0f1985e9-a797-4c7f-ac87-ee65c4470ae6)

It worked before remotion v"3.3.98", however this problem occurs after update to ^v4.
Is there my npm or machine has problems?

  "dependencies": {
    "@remotion/cli": "4.0.16",
    "@remotion/zod-types": "4.0.16",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "remotion": "4.0.16",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@remotion/eslint-config": "4.0.16",
    "@types/react": "^18.0.26",
    "@types/web": "^0.0.86",
    "eslint": "^8.43.0",
    "prettier": "^2.8.8",
    "typescript": "^4.9.4"
  },
  "packageManager": "npm@9.8.1"

Root.tsx
`
import {Composition} from 'remotion';
import {HelloWorld, myCompSchema} from './HelloWorld';
import {Logo, myCompSchema2} from './HelloWorld/Logo';

// Each <Composition> is an entry in the sidebar!

export const RemotionRoot: React.FC = () => {
	return (
		<>
			<Composition
				// You can take the "id" to render a video:
				// npx remotion render src/index.ts <id> out/video.mp4
				id="HelloWorld"
				component={HelloWorld}
				durationInFrames={150}
				fps={30}
				width={1920}
				height={1080}
				// You can override these props for each render:
				// https://www.remotion.dev/docs/parametrized-rendering
				schema={myCompSchema}
				defaultProps={{
					titleText: 'にほんご',
					titleColor: '#000000',
					logoColor1: '#91EAE4',
					logoColor2: '#86A8E7',
				}}
			/>
			{/* Mount any React component to make it show up in the sidebar and work on it individually! */}
			<Composition
				id="OnlyLogo"
				component={Logo}
				durationInFrames={150}
				fps={30}
				width={1920}
				height={1080}
				schema={myCompSchema2}
				defaultProps={{
					logoColor1: '#91dAE2' as const,
					logoColor2: '#86A8E7' as const,
				}}
			/>
		</>
	);
};

`

**Comment by log901108** [comment]
May be my WSL gives this error... never mind

**Comment by kingh0730** [comment]
I'm facing the same issue
