### ISSUE TITLE
Port assignment sometimes does not work on Windows

### ISSUE THREAD

**Issue by winner106** [remotion-dev/remotion#2679]
## Render Failed

![image](https://github.com/remotion-dev/remotion/assets/50519642/f98f7dd6-2af5-4f12-bf22-4539af6418a1)

![render](https://github.com/remotion-dev/remotion/assets/50519642/026e8a48-baf5-4cb3-bc4b-8c0b04e0c3da)

## Port 3001 is not being occupied.

![image](https://github.com/remotion-dev/remotion/assets/50519642/65ef996f-8979-42f0-a4b3-f4c4ee9990f4)

**Comment by JonnyBurger** [comment]
Thanks for reporting!
What do you see when you visit  localhost:3001 in the browser?

This woud help us better understand it.

**Comment by winner106** [comment]
The page is displayed as follows.

![image](https://github.com/remotion-dev/remotion/assets/50519642/ddc46d8e-d9d3-4cf8-b6f4-e04144f780fb)

**Comment by JonnyBurger** [comment]
OK, thanks.. do you use some virtual environment stuff? WSL? Docker?

How come you have a `[remotion]` log in front of all of your logs?

**Comment by winner106** [comment]
Because I used a package called "[concurrently](https://github.com/open-cli-tools/concurrently)", which allows running multiple commands concurrently.

![image](https://github.com/remotion-dev/remotion/assets/50519642/dbfa1d62-68df-4540-b681-970bdd42c7b4)

**Comment by JonnyBurger** [comment]
The dev server you start, is there a chance it takes port 3001?

**Comment by winner106** [comment]
no, the server is running on port 5000. I tried several other ports to run Remotion, but the rendering still failed.

**Comment by winner106** [comment]
Perhaps the bundled has never been started?

**Comment by winner106** [comment]
when I set `Config.setPort(3005);` in `remotion.config.ts`, the Remotion Studio Server is running on `http://localhost:3005/`, then I try to Render:

![image](https://github.com/remotion-dev/remotion/assets/50519642/5c6a2bb3-b650-4a98-9bd8-855b13210247)

should it choose port `3006` to execute the render task?

**Comment by JonnyBurger** [comment]
@winner106 No, this will use the same port for the Studio and for the rendering, this is obviously incompatible. 
Another issue we should fix.
