### ISSUE TITLE
 renderMedia not passing/overwriting defaultProps

### ISSUE THREAD

**Issue by nitinthewiz** [remotion-dev/remotion#2688]
# Bug Report 🐛

Similar to bug https://github.com/remotion-dev/remotion/issues/2672, I observed that `renderMedia` too isn't respecting `inputProps` and overwriting `defaultProps`. I hoped that this issue would be resolved in the 4.0.17 release of today, but that isn't the case.

However, it seems this is more about my understanding about `renderMedia` than anything else.

In remotion v3, I was using `getCompositions` to find the right composition using code similar to this - 
```const compositionIntro = allCompositions.find((c) => c.id === "Intro");```

However, in v4, when I use the above and then try to pass inputProps to the composition using code similar to the below, I see that the defaultProps are not overridden by the inputProps - 
```
await renderMedia({
        composition: compositionIntro,
        serveUrl: bundleLocation,
        codec: "h264",
        outputLocation: `out/${inputProps.id}.mp4`,
        onProgress: onProgress2,
        inputProps,
    }).then(() => {
        console.log(">>>>>>>>>> " + inputProps.id + ".mp4 file done");
    });
```

However, I noticed that the SSR page mentions selectComposition() [here](https://www.remotion.dev/docs/ssr).
Thus, I set up the composition search as follows - 
```
const compositionIntro = await selectComposition({
      serveUrl: bundleLocation,
      id: compositionId,
      inputProps,
    });
```
and used it as above in `renderMedia`, but without passing the `inputProps` to `renderMedia` and I got the expected `inputProps` in the produced video.

Essentially, this means that when I pull the composition, I must fill in the `inputProps` right then instead of at render-time.
This also means that in `render.ts`, instead of getting a `Composition` once and then calling `renderMedia` on it over and over with new `inputProps`, I have to now add `selectComposition` to the loop and using `inputProps` in it instead.

So, I suppose here's my question - is this a breaking change in v4? If so, please add it to the v4 migration page. Otherwise, it seems to be a bug that `renderMedia` doesn't seem to be accepting inputProps to override `defaultProps`.

**Comment by JonnyBurger** [comment]
Happy to improve the docs upon this, for now the short answer:

- `inputProps` is what can be read from `getInputProps()`
- The actual props fed to the component are being determined from `composition.props` that is being passed to `renderMedia()`.

Indeed the API is not meant to be used in a way where different `inputProps` are passed to `selectComposition()/getComposition()` and `renderMedia()`. We need to clarify that in the docs.

**Comment by nitinthewiz** [comment]
Thanks for the response @JonnyBurger, though it's left me a little confused.

My understanding has always been that `inputProps` are what we can use to parameterize videos during server side rendering. I'm talking about [this section about passing inputs to `renderMedia()`](https://www.remotion.dev/docs/passing-props#passing-input-props-when-using-server-side-rendering).

Since `inputProps` override `defaultProps`, we don't need `getInputProps()` as the default behavior of the component changes when using `inputProps`.

Let me give you an example - 
Say I want to create a customized Christmas video that says "Merry Christmas Nitin" in one video and "Merry Christmas Nipun" in another. I want to scale this to tens or hundreds of videos.

Best way to do this? Render using `renderMedia` in a `render.ts` file, set the relevant component to use `{element.user_name}` as the variable (see example below), and pass `inputProps` as the names of the people I want to make the video for, right? No need to use `getInputProps`.

So could you tell me what you mean by `composition.props` and "API is not meant to be used in a way where different `inputProps` are passed to `selectComposition()`/`getComposition()` and `renderMedia()`" please?

> If I'm reading your explanation clearly, it seems that in v4, as I have observed, we have a breaking change - the `inputProps` *only* work to override the `defaultProps` during the `selectComposition`/`getComposition` phase. Not during `renderMedia`. That means I do need to call `selectComposition` in the loop, as I've shown in my sample code below.

Lastly, this works in my render.ts in remotion v4. Are you saying this is not the best approach for the purpose of making these Merry Christmas videos? - 

```
const compositionId = "MerryXMas";
await Users.forEach(async (element: UserProps) => {
    const compositionMerryChristmas = await selectComposition({
        serveUrl: bundleLocation,
        id: compositionId,
        inputProps: element,
    });

    if (!compositionMerryChristmas) {
        throw new Error(`No composition with the ID ${compositionId} found.`);
    }
    
    // Setting duration to 10 seconds since that seems enough time to wish Merry Xmas.
    compositionMerryChristmas.durationInFrames = 300; //HARDCODE 
    
    await renderMedia({
        composition: compositionMerryChristmas,
        serveUrl: bundleLocation,
        codec: "h264",
        outputLocation: `out/${element.id}.mp4`,
        onProgress: onProgress2
    }).then(() => {
        console.log(">>>>>>>>>> " + element.id + ".mp4 file done");
    });
});
```

This used to work in v3, but doesn't work in v4 any more - 
```
const compositionId = "MerryXMas";
const allCompositions = await getCompositions(bundleLocation);
const compositionMerryChristmas = allCompositions.find((c) => c.id === compositionId);

if (!compositionMerryChristmas) {
    throw new Error(`No composition with the ID ${compositionId} found.`);
}
    
// Setting duration to 10 seconds since that seems enough time to wish Merry Xmas.
compositionMerryChristmas.durationInFrames = 300; //HARDCODE 
    
await Users.forEach(async (element: UserProps) => {
    await renderMedia({
        composition: compositionMerryChristmas,
        serveUrl: bundleLocation,
        codec: "h264",
        outputLocation: `out/${element.id}.mp4`,
        inputProps: element,
        onProgress: onProgress2,
    }).then(() => {
        console.log(">>>>>>>>>> " + element.id + ".mp4 file done");
    });
});
```

**Comment by nitinthewiz** [comment]
Apologies for the long-winded write-up. I know you've said the better place for your explanation is in the documentation. But I'm simply looking for validation on the breaking change, as well as the idea that we should or shouldn't use the API for programmatically creating videos in the way I've described.

**Comment by JonnyBurger** [comment]
I can confirm this is a breaking change, and we'll update the docs for this! Just wanted to give a quick answer to get you unstuck.

The intended way to use it is to pass `inputProps` to both `getCompositions()` and `renderMedia()`, because the props get calculated in `getCompositions()` / `selectComposition()` in v4 on.

Since you don't want to do that for every element, you need to do the following:

```ts
await renderMedia({
        composition: {...compositionMerryChristmas, props: element},
		inputProps: element
    })
```

`composition.props` is what gets passed to the component, `inputProps` is what you can read by calling `getInputProps()`.

**Comment by nitinthewiz** [comment]
Oh, that's brilliant! Thank you so much for the code snippet. That does indeed make it easier to not process the composition for every input in the loop.

I understand that the `inputProps` can be used in different ways in `getCompositions` and in `renderMedia`. In `getCompositions`, it can be used to calculate video length, dimensions, etc.
While in `renderMedia` it can input the actual content of the video.

**Comment by JonnyBurger** [comment]
This breaking change is now properly documented #2716

**Comment by JonnyBurger** [comment]
This breaking change is now properly documented #2716
