### ISSUE TITLE
Failed video render report

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2690]
To be investigated:

> Hi 👋, 
I have an issue wtih a ".mov" video. It works fine in the Remotion Player, but in the rendered .mp4 file I only have a black screen and the sound of the video playing.
I the used ShutterEncoder to change the fps from 24.53 to 24 using a software called ShutterEncoder with H264 and it worked. I suspect that it comes from the video's framerate 🤔.
> Still with the "bugged" video, I also tried to wrap all of my video components with the  "FpsConverter" component but it doesn't work either. I get a black screen and the audio sounds "flickery"/"chopped"
> Here is the file that causes the "bug" => https://we.tl/t-PEkjPaeyne

**Comment by APZdev** [comment]
I'm using Remotion v4.0.16
I'm using normal <Video/> components.
I'm not using <OffthreadVideo/> component.


```tsx
  <Sequence
    from={sequenceStart * fps}
    durationInFrames={(sequenceEnd - sequenceStart) * fps + 1}
    style={{
      left: `${left}px`,
      top: `${top}px`,
      width: `${width}px`,
      height: `${height}px`,
      opacity: `${opacity}`,
      transform: `rotateZ(${rotation.z}deg) scaleX(${rotation.x}) scaleY(${rotation.y})`,
      overflow: 'hidden',
    }}
  >
    <AbsoluteFill id={`sequence_${timelineSequence.uuid}`}>
      <Video
        style={{
          width: '100%',
          height: '100%',
        }}
        defaultValue={1}
        volume={timelineSequence.properties.audio?.volume}
        muted={timelineSequence.properties.audio?.muted}
        src={sequenceSrc}
        startFrom={mediaStart * fps}
        endAt={mediaEnd * fps + 1}
      />
    </AbsoluteFill>
  </Sequence>
```

**Comment by JonnyBurger** [comment]
As discussed in Discord, the fix was to use `<OffthreadVideo>`. It seems like the video was not suitable to be played in a video tag, either due to missing timestamps or the wrong codec.
