### ISSUE TITLE
Player tag regression since 4.0.16

### ISSUE THREAD

**Issue by kacperadach** [remotion-dev/remotion#2704]
My app is on Remotion version 4.0.14 and our Player is using the BufferManager/PauseableVideo implementation from the docs. It works perfectly on this version. When I upgrade to 4.0.16 or higher, the player is constantly stuttering and I see the seeking spinner show up. Not exactly sure what caused it but potentially something in [this PR](https://github.com/remotion-dev/remotion/pull/2666)?

**Comment by JonnyBurger** [comment]
I have also seen some unusual seeking in the Studio and wanted to investigate this. I think you are right and we should revert it for now until we are sure that it does break something

**Comment by JonnyBurger** [comment]
I appreciate if you can test 4.0.18 and let me know if it resolves the bug!

**Comment by kacperadach** [comment]
@JonnyBurger unfortunately I am still experiencing the issue in 4.0.18

**Comment by JonnyBurger** [comment]
Are you sure,

**Comment by JonnyBurger** [comment]
Found another change in 4.0.16 which I am going to revert: https://github.com/remotion-dev/remotion/pull/2709

Also, someone elses similar issue got resolved yesterday with `4.0.18`, but only after they removed `node_modules/.next`. Make sure to clear all your caches and maybe 4.0.18 already works for you!

**Comment by kacperadach** [comment]
I cleared .next but still have the issue. I'll wait for the next release.

**Comment by JonnyBurger** [comment]
@kacperadach Please try 4.0.19!
