### ISSUE TITLE
video editor

### ISSUE THREAD

**Issue by Manubi** [remotion-dev/remotion#2714]
Hi,  

is it possible to add the remotion video editor to a webpage? My usecase is a customer records a video and I'd like to give her the opportunity to edit it. 

thanks!

**Comment by JonnyBurger** [comment]
We will develop this in two directions:

- Being able to deploy the Remotion Studio #669 
- Allowing people to build their own video editor by building an interface around the Remotion Player and hooking it up to Remotion Lambda - for example using our new Next.js template https://www.remotion.dev/templates/next

We'll also launch a marketplace this year where over time we will add useful components for building video editors.

Besides those plans, there is no plan to expose the current components like the timeline.
