### ISSUE TITLE
[FeatureRequest] Add custom data to lambda webhook return POST request

### ISSUE THREAD

**Issue by tdurand** [remotion-dev/remotion#2718]
# Feature Request 🛍️

I would like to add a custom data in the webhook POST request sent by remotion after the lambda function returns.

On the API I imagine this would look like this:

```javascript
const webhook: RenderMediaOnLambdaInput["webhook"] = {
  url: "https://mapsnap.app/api/webhook",
  secret: process.env.WEBHOOK_SECRET as string,
  customData: { yourDataHere }
};
```

and we would get that data on the webhook payload:

```javascript
 {
      type: "success";
      lambdaErrors: EnhancedErrorInfo[];
      outputUrl: string | undefined;
      outputFile: string | undefined;
      timeToFinish: number | undefined;
      renderId: string;
      expectedBucketOwner: string;
      bucketName: string;
      // Available from v3.3.11
      costs: {
        estimatedCost: number;
        estimatedDisplayCost: string;
        currency: string;
        disclaimer: string;
      };
      customData: { yourDataHere } // new 
    }
```

I don't believe this is possible right now

## Use Case

In my use case, I would like to send an email with the link to the video after the lambda function finishes

## Possible Solution

I could work on a PR for that, but let me know if this is something you would accept 😎

**Comment by JonnyBurger** [comment]
We would accept this PR!

**Comment by vgserafim** [comment]
Hi, I'd like to work on this PR if @tdurand hasn't started yet. Thanks!

**Comment by tdurand** [comment]
Hey sorry, somehow I didn't get those notification, I didn't work on it yet and got sidetracked with other stuff, so you can go ahead @vgserafim !

**Comment by vgserafim** [comment]
Thanks, working on it!

**Comment by JonnyBurger** [comment]
That's awesome, thanks a lot @vgserafim!

One thing to consider: There is a maximum payload size for Lambda, so I would put a limit on the the payload that you can put for the webhook data (let's say we reserve 1KB and the rest must be fetched from input props).

Then we decrease the threshold for when the input props get uploaded to an S3 bucket, and ensure we never hit the payload limit. Happy to explain it more on Discord if that is not so clear.

Also:
/bounty 70

**Comment by JonnyBurger** [comment]
@vgserafim You may also claim a cash bounty by using the above mentioned command!

**Comment by vgserafim** [comment]
Thanks, Jonny. But I don't think it's fair because I didn't do the full PR.

**Comment by tdurand** [comment]
@JonnyBurger @vgserafim just want to sent some love here 💙💙💙💙 , that feeling of coming back to your side project on a sunday and have a feature request already implemented that makes your life easier is so good 🍾

**Comment by JonnyBurger** [comment]
@tdurand Thanks for the random love! 😊💙 definitely extending that feeling, thanks a lot @vgserafim 🙌🏼🙌🏼

**Comment by vgserafim** [comment]
Thanks everyone! This was exactly my requirement as well. 💙
