### ISSUE TITLE
Cloudrun: fetching render output only accepts output file name and not full path

### ISSUE THREAD

**Issue by alimirjahani7** [remotion-dev/remotion#2723]
While rendering with Cloud run we can pass a file name at the end of CLI command to determine to the result file name and it will put the output in the ./out/[file_name]
if we pass path it will result to this error:
Cloud run Download media is not working on custome location outside ./out
Codec = h264
Output Bucket = xxx
Output File = out.mp4
Output File Privacy = public
                Downloaded File = /tmp/test.mp4

Rendering on Cloud Run:  ╭───────────────────╮ Rendered 23333ms

Public URL = https://storage.googleapis.com/xxx/renders/lta0b8fuaw/out.mp4
Cloud Storage Uri = gs://xxx/renders/lta0b8fuaw/out.mp4
Size (KB) = 871
Bucket Name = xxx
Privacy = public-read
Render ID = lta0b8fuaw
Codec = h264 (derived from download name)

downloading file...
Error: ENOENT: no such file or directory, open 'out//tmp/test.mp4

while rendering local or on lambda the passed argument means the hole path and it is totally ok

**Comment by JonnyBurger** [comment]
Thanks for filing this!
