### ISSUE TITLE
three documentation not showing the video example

### ISSUE THREAD

**Issue by alexfernandez803** [remotion-dev/remotion#2727]
# Bug Report 🐛

[From]( https://www.remotion.dev/docs/three) the example video is not showing.

<img width="921" alt="Screenshot 2023-08-13 at 8 41 16 pm" src="https://github.com/remotion-dev/remotion/assets/7582277/d7c88b7a-bdf7-4acf-8ee0-fa1980cb8974">

**Comment by patsalv** [comment]
Hey Alex
Thanks a lot for pointing this out!
We had a look at it and turns out it's not a trivial fix. We will look for a solution in the near future but have some higher priority issues to tackle first.
