### ISSUE TITLE
Implement FFmpeg x264 presets

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2753]
The following presets are available:

https://trac.ffmpeg.org/wiki/Encode/H.264#a2.Chooseapresetandtune

This can be added to the FFmpeg command.
This option should be added to the following APIs:

- renderMedia() + Add to docs
- renderMediaOnLambda() + Add to docs
- renderMediaOnCloudRun() + Add to docs
- npx remotion render + Add to docs
- npx remotion lambda render + Add to docs
- npx remotion cloudrun render + Add to docs
- Display a dropdown in the Remotion Studio (same place as ProRes profile, only display if codec = h264)
- In the cli-autocomplete for npx remotion render

The option can be implemented 1:1 as the "ProRes profile" option already available in Remotion.

/bounty 150

**Comment by JonnyBurger** [comment]
Good luck @neo773!

**Comment by rishi-raj-jain** [comment]
I'm the one next in line!
