### ISSUE TITLE
Timeout of Inter font on Next.js template

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2757]
https://next-app-dir.remotion.dev/

In console, 

![image](https://github.com/remotion-dev/remotion/assets/1629785/c72bdd38-07e6-4362-877d-4a663f7fced6)

**Comment by IamSAL** [comment]
@JonnyBurger 

I inspected the link and your screenshot, but could't identify the issue.

can you elaborate the problem a bit?

thanks.

**Comment by JonnyBurger** [comment]
I can not reproduce it anymore either unfortunately. If somebody can, please let me know
