### ISSUE TITLE
OffthreadVideo's High disk write usage

### ISSUE THREAD

**Issue by brzostekd** [remotion-dev/remotion#2760]
## Description

Excessive disk usage is observed when utilizing the `<OffthreadVideo>` feature in Remotion. When rendering compositions that use `<OffthreadVideo>`, the puppeteer's browser instance generates a stream of data that is being written to the directory `C:\Users\<user>\AppData\Local\Temp`. This results in significant disk space consumption, making it a showstopper for users with limited disk resources and processing power. Additionally, this issue not only impacts disk performance but also causes unnecessary wear and tear on the storage device due to the continuous writing and removal of large amounts of data.

**This Issue makes OffthreadVideo not suitable to use in video production.**

## Steps to Reproduce

1. Use the `<OffthreadVideo>` component in a Remotion composition.
2. Render the composition using studio or remotion render command.
3. Monitor disk write usage and observe the growth of temporary files in `C:\Users\<user>\AppData\Local\Temp`.

I've made a repository showcasing the issue: https://github.com/brzostekd/remotion_offthreadvideo_issue_demo.
1. Clone the repository.
(optionally, set browser executable in config)
2. Run ```remotion render test```.
3. Monitor disk write usage with Resource Monitor and observe the growth of temporary files in `C:\Users\<user>\AppData\Local\Temp`.

## Expected Behavior

Disk usage should be reasonable and not result in the excessive creation of temporary files.

## Actual Behavior

Excessive disk usage is observed, leading to the creation of a large number of temporary files in the `C:\Users\<user>\AppData\Local\Temp` directory.

## Additional Information

- Issue may be related to Puppeteer, but I suspect that some Remotion code that loads the extracted frames in browser might be at fault.
- Issue occurs with different browsers (e.g., Brave, standalone Thorium).
- It does not matter if video source is served locally via a local HTTP server, or staticFile() source is used.
- `preloadVideo` is used in the `CalculateMetadataFunction`.
- Screenshots provided as evidence clearly demonstrate the excessive disk usage.

## References

- Possibly related issue discussed at https://github.com/puppeteer/puppeteer/issues/1791 and https://github.com/puppeteer/puppeteer/issues/6414.

## Environment

- Remotion version: 4.0.21, all remotion packages.
- Browser(s) tested: Brave Version 1.57.49 Chromium: 116.0.5845.96 (Official Build) (64-bit), Thorium Version 115.0.5790.172 (Official Build) (64-bit)
- Operating System: Microsoft Windows 10 Enterprise Version 10.0.19045 Build 19045

![Capture](https://github.com/remotion-dev/remotion/assets/125189180/4c9f17ad-d938-4783-9700-a9333c7a3896)
<img width="583" alt="Code_RM67YY5tnK" src="https://github.com/remotion-dev/remotion/assets/125189180/21ee67e2-1ca3-4016-bf99-d1f13c5d9bfa">
![issue](https://github.com/remotion-dev/remotion/assets/125189180/ff4f4e67-c891-4475-ad2d-aee17761ea46)
<img width="1911" alt="Taskmgr_LvQzHWuLTc" src="https://github.com/remotion-dev/remotion/assets/125189180/7ac8acec-4191-4d3c-9193-33dbd9f6139d">
<img width="1910" alt="Taskmgr_vLfk8PNGsH" src="https://github.com/remotion-dev/remotion/assets/125189180/3f670152-0c11-4ae9-93c5-9869d26d69c5">
<img width="1205" alt="TreeSize_cquT8LL51z" src="https://github.com/remotion-dev/remotion/assets/125189180/333976ce-7566-46f8-97db-f50ae9487488">

**Comment by JonnyBurger** [comment]
Thanks for the nice report, this will be improved in v4.0.22!

**Comment by brzostekd** [comment]
Anticipating the update. Thanks a lot! 😃

**Comment by JonnyBurger** [comment]
It's out! https://remotion.dev/changelog
