### ISSUE TITLE
Lambda: Don't call process.exit() to keep Lambdas warm

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2774]
Right now, we get quite a slow start every time

**Comment by gupta-piyush19** [comment]
Hi @JonnyBurger, I am quite new to the lambdas and learned about the cold and warm start. Should I comment the ```process.exit(0)``` in ```remotion-dev/remotion/packages/cli/src/lambda-command.ts```  to solve this issue?

**Comment by JonnyBurger** [comment]
@gupta-piyush19 This would be great! 

It is only the start, from then on we need to ensure that the Lambda function actually ends once the response is sent.
I had some problems with that, but did not have time to investigate for a proper solution yet.

**Comment by gupta-piyush19** [comment]
I'll spend some time on it and ask more questions if required.

**Comment by JonnyBurger** [comment]
This is fixed in recent versions!
