### ISSUE TITLE
Export GIF with transparent background

### ISSUE THREAD

**Issue by nico-martin** [remotion-dev/remotion#2805]
# Feature Request 🛍️

I have a transparent Video (PNGs images and text) that I want to export using the `gif` codec.
Right not it always rendes a black background. It would be great if it was possible to export the gif with transparent background.

## Use Case

As far as I know, animated gifs support transparent background.
But currently it does not work with remotion. I do think there are a lot of usecases where it could make sense. In my example I just want to convert a PNG image to a blinking git (2 frames, 4FPS)

**Comment by JonnyBurger** [comment]
Good request, for this we need to implement two-pass rendering: #1276

**Comment by peteruithoven** [comment]
It might be good, in the mean time, to clarify that transparency currently is not supported on the following page:
https://www.remotion.dev/docs/render-as-gif
Maybe even link to this issue to follow.
