### ISSUE TITLE
selectComposition() attribute - loglevel<string> in docs, verbose<boolean> in code

### ISSUE THREAD

**Issue by UmungoBungo** [remotion-dev/remotion#2850]
# Bug Report 🐛
logLevel is listed for the API in the docs, but verbose is instead available as a boolean attribute in the code.

[Docs link](https://www.remotion.dev/docs/renderer/select-composition#loglevel)
[Code link](https://github.com/remotion-dev/remotion/blob/main/packages/renderer/src/select-composition.ts)

**Comment by JonnyBurger** [comment]
Deprecated `verbose` in favor of `logLevel`, no breaking change
