### ISSUE TITLE
benchmark not as reliable as render command

### ISSUE THREAD

**Issue by UmungoBungo** [remotion-dev/remotion#2877]
# Bug Report 🐛

I have a composition that has this structure;

- Introduction, just CSS
- `<OffthreadVideo />` starting at frame 467
- `<OffthreadVideo />` starting at frame 2315
- Outro, just CSS

I am testing out different VMs on GCP, trying to find a cost/speed tradeoff. I am using the following command
```bash
remotion benchmark <entryPoint> <compName> out/video.mp4 --runs 1 --concurrency 100% --gl angle
```

This has been consistently completing successfully for the following VMs;
- 4 vCPU, 16gb memory, no GPU (1 run)
- 8 vCPU, 32gb memory, no GPU (5 runs)
- 4 vCPU, 16gb memory, with GPU (1 run)

After switching to 8 vCPU, 32gb memory, with GPU, I have had 4 benchmark tests fail like this;
```bash
An error occurred while rendering frame X:
 Error  A delayRender() was called but not cleared after 28000ms. See https://remotion.dev/docs/timeout for help.
...👇👇👇...
at src/hooks/useVideoMetaData.ts:14
```
For the logs I still have access to, I saw frame X was very close to the first couple of frames that feature the `<OffthreadVideo/>`. The source for these videos are in a storage bucket, in GCP, in the same region as the VM. I have opened both videos in incognito windows to test that they have public access.

Instead of using the benchmark command, I used render with `time` in front, and it rendered successfully.

Always hard to pin down an inconsistent bug, and I haven't checked the code yet to see how benchmark compares to a render command.

**Comment by UmungoBungo** [comment]
Oh just had an issue using the render command as well, so it is probably some intermittent issue with accessing the asset via GCP storage.

**Comment by JonnyBurger** [comment]
@UmungoBungo Do you see any actions we need to take then? Otherwise, you can close the issue.
