### ISSUE TITLE
Recommend a workflow for using the GPU on a AWS instance

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2889]
Remotion 4.0 does not support Glibc 2.33 anymore, but there are no templates on AWS that have GPU drivers installed but use a new enough version of Glibc

**Comment by bilalmughal** [comment]
While working on GPU acceleration for headless Chrome/Chromium, I couldn't help but wonder: why not harness the full power of GPUs for video transcoding as well?  I have just finished with my cost-centric analysis comparing CPU vs GPU for video transcoding and the results were astonishing, benchmark data reveal GPUs proved to be both faster and more cost-effective. You can check out my detailed findings [here](https://mirzabilal.com/cpu-vs-gpu-for-video-transcoding-challenging-the-cost-speed-myth). So this compelled me even more to pitch this idea to the Remotion community.
This will not only offload more rendering workload to GPU but it will also free up the CPU, to perform so many general purpose tasks we generally need to perform.

And the best part is it's within our reach. All it takes is recompiling the FFmpeg binary with hardware acceleration support. I'm more than eager to lend a hand in this and see the results for myself. 
Here is a graph from the post reflecting the stark difference in performance.
![Transcoding-time-benchmark](https://github.com/remotion-dev/remotion/assets/2370808/2da6738a-9795-4c29-a0f6-63c64b123bc8)
https://mirzabilal.com/cpu-vs-gpu-for-video-transcoding-challenging-the-cost-speed-myth

**Comment by UmungoBungo** [comment]
nice work! We have found that arm has better price performance than x86-based CPUs, which your post shows as well. I think it would be good to mention the architecture of each instance as I had to jump back and forth between your post and the AWS docs to understand 😄

**Comment by UmungoBungo** [comment]
so based on the method in your post, you are suggesting that the Remotion renderer would first check if a GPU is available, and if it is, perform transcoding using the GPU?

**Comment by UmungoBungo** [comment]
Related: #3013

**Comment by UmungoBungo** [comment]
ahh I see, thanks for pointing that out! I had guessed `g` for Graviton and `i` for Intel but wasn't sure about the `a`

**Comment by bilalmughal** [comment]
Related to https://github.com/remotion-dev/remotion/pull/3038

**Comment by JonnyBurger** [comment]
True, this is done now! https://www.remotion.dev/docs/miscellaneous/cloud-gpu
