### ISSUE TITLE
`extractAudio()` API

### ISSUE THREAD

**Issue by alexfernandez803** [remotion-dev/remotion#2900]
# Feature Request 🛍️
There should be an ability in the library to separate the audio track from the video.

## Use Case

This is beneficial in cases where we need the audio to be transcribed, as some cloud providers don't transcribe video out of the box; some require the content to be in audio format. Sending video would waste bandwidth and slow down the upload and transcription process, as only the audio is needed.

## Acceptance criteria

- Implement a new function in Rust which takes a local file path and an output path and extracts only the audio stream of the video.
- It should avoid re-encoding the audio if possible. A setting for would be a nice-to-have but not necessary.
- Documentation should be written for it with the same quality as other APIs in `@remotion/renderer`

## Resources
- getVideoMetadata() implementation, another function from @remotion/renderer: https://github.com/remotion-dev/remotion/blob/main/packages/renderer/src/get-video-metadata.ts
- getVideoMetadata() documentation as a template: https://www.remotion.dev/docs/renderer/get-video-metadata
- How to work with Rust code: https://www.remotion.dev/docs/contributing/rust
- FFmpeg Rust examples: https://github.com/zmwangx/rust-ffmpeg/tree/master/examples

## Bounty
💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion | Remotion | Make videos programmatically in React](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

**Comment by JonnyBurger** [comment]
Sounds like a good idea for a `@remotion/renderer` API 👍

**Comment by thecmdrunner** [comment]
Ah just what I need right now

**Comment by reubence** [comment]
I like this issue, Let me know if i can /attempt this! 😄

I don't have any doubts. 

I don't write a lot of rust so will ask for feedback before submitting.

**Comment by JonnyBurger** [comment]
@reubence Cool! Thanks a lot for attempting this and good luck! 🙌🏼

**Comment by reubence** [comment]
@JonnyBurger pls assign this issue to someone else , I think this one is a little above my current skillset. I'm gonna track this issue instead and learn from the code :)

**Comment by JonnyBurger** [comment]
@reubence Sure, thanks for getting back! We'll find someone else.

@ken0x0a Are you interested in this?

**Comment by josefeliuf** [comment]
Hey @JonnyBurger ! i would like to /attempt this :)

**Comment by JonnyBurger** [comment]
Hey @josefeliuf! Very cool, I'll give it to you then. Good luck! 🙌🏼

**Comment by alexfernandez803** [comment]
I'll be in the queue just in case :).

**Comment by josefeliuf** [comment]
@JonnyBurger hey! based on the acceptance criteria, should i just create the rust function or create the code in typescript too? for example i notice that every command has its equivalent as a CompositorCommand in payloads.ts.

**Comment by JonnyBurger** [comment]
@josefeliuf I forgot to mention that, I thought a JS wrapper would also be nice, like this one: https://github.com/remotion-dev/remotion/blob/main/packages/renderer/src/get-video-metadata.ts

But I forgot to write that, just if you like to.

Looks super good so far! Thanks for sending a PR 🙌
