### ISSUE TITLE
Create new zod type to display textarea

### ISSUE THREAD

**Issue by CruuzAzul** [remotion-dev/remotion#2903]
In some cases we need to use a textarea in the customisation fields of our video, but we don't have the option of doing so.

# Feature Request 🛍️

In some cases we need to use a textarea in the customisation fields of our video, but we don't have the option of doing so. 

## Use Case

We often need to display a textarea in the form of a Remotion composition, for example, in order to have a larger input for writing and making line breaks.

## Possible Solution

Similar to how the `zColor()` function is implemented as a custom Zod type (https://github.com/remotion-dev/remotion/blob/main/packages/zod-types/src), a type should be implemented that represents a multiline textarea.

If this type is specified, in the Remotion Studio a multiline text area should appear.

zColor Implementations in the Studio for reference here here: https://github.com/remotion-dev/remotion/blob/bd888812c3e4569a4c269ecd94c8fcab478b3b81/packages/cli/src/editor/components/RenderModal/SchemaEditor/ZodSwitch.tsx#L274 https://github.com/remotion-dev/remotion/blob/bd888812c3e4569a4c269ecd94c8fcab478b3b81/packages/cli/src/editor/components/RenderModal/SchemaEditor/create-zod-values.ts#L82

## Acceptance criteria

- Build a `zTextArea()` type that shows a multiline textarea in the Remotion Studio sidebar
- Visually it should fit in with the rest of the UI - may use the existing RemTextarea component
- It should be keyboard-navigable (which it should be by default)
- Add a documentation page and add it to the table of contents of @remotion/zod-types.

💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion | Remotion | Make videos programmatically in React](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

**Comment by CruuzAzul** [comment]
Hey @JonnyBurger ! Is everything all right ? 😊

**Comment by CruuzAzul** [comment]
I take this @JonnyBurger 😊

**Comment by JonnyBurger** [comment]
@CruuzAzul Awesome! 😊 Thanks a lot and good luck!

**Comment by mrkirthi-24** [comment]
Hi @JonnyBurger, If the assigned contibutor is not actively working on this issue, then I would like to work on this.

**Comment by rishi-raj-jain** [comment]
Hi @JonnyBurger, If the assigned contributor is not actively working on this issue, then I would like to work on it.

**Comment by CruuzAzul** [comment]
I'm on it, I've had a few problems getting it to work properly 😅

**Comment by CruuzAzul** [comment]
Sorry about the delay @JonnyBurger, I was having trouble testing my modifications on the local studio
