### ISSUE TITLE
Create a template for developing Remotion libraries + components

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2907]
Create a template that allows one to develop a library in the Remotion ecosystem with the best practices applied out of the box.

Should be a monorepo (for example with pnpm, same as this repository) which includes two packages:

- A simple Remotion library that as a starter, includes a simple function (e.g. `useSeconds()`).
- Should include a sample project with the Remotion Studio so that one can test the function
- It should package the library as CJS+ESM for maximum compatibility (for example using tsup)
- The template should be allowed to live in the remotion-dev GitHub organization (while crediting you as the author)
- There should be a README or doc site that explains how to use the template (clone, start, change name, publish to npm)

## Acceptance criteria

Deliver a repository that one can clone as a template and develop their own Remotion function / component and publish to NPM as well as test it in a Remotion Studio environment.

## Bounty 

💎 This issue is part of Hacktoberfest and has a bounty on it!
* **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion | Remotion | Make videos programmatically in React](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 300

**Comment by Just-Moh-it** [comment]
Hey Jonny! Always wanted to learn turborepo which I did a few months ago but never tried making a library package myself, just used others’ templates… this would be a fun one for the weekend :)

(ps if it’s unclear lol i’d like to take this on)

**Comment by JonnyBurger** [comment]
Nice 🙌🏼 Thanks and good luck Mohit!
