### ISSUE TITLE
CloudRun is having issues with version

### ISSUE THREAD

**Issue by alexfernandez803** [remotion-dev/remotion#2911]
# Bug Report 🐛

I've noticed that there is an issue with 4.0.39 and 4.0.40

This log is shown on cloudrun log, it seems like there is a mismatch on versions. This could be a bug.
`
The site was bundled with version 4.0.39 of @remotion/bundler, while @remotion/renderer is on version 4.0.38. You may not have the newest bugfixes and features.
`
The site was bundled with version 4.0.40 of @remotion/bundler, while @remotion/renderer is on version 4.0.39 You may not have the newest bugfixes and features.

**Comment by JonnyBurger** [comment]
Did you re-deploy the service after upgrading the Remotion version?
If not, this is actually expected.

**Comment by alexfernandez803** [comment]
Yes, I did a fresh redeploy of service 4.0.40 and I can see this error in Cloudrun logs. It could be during the docker build it is referencing a wrong version due to caching.,, 

`
The site was bundled with version 4.0.40 of @remotion/bundler, while @remotion/renderer is on version 4.0.39. You may not have the newest bugfixes and features.

`

**Comment by JonnyBurger** [comment]
I think I found the issue! Thanks for letting me know!
If it still occurs, comment here and we'll look
