### ISSUE TITLE
Add function name to be passed on deployFunction

### ISSUE THREAD

**Issue by BrenoMazieiro** [remotion-dev/remotion#2926]
Add function name to be passed on deployFunction

# Feature Request 🛍️

Add functionName on deployFunction function.

## Use Case

When working with multiples environment i would like to use different remotion versions, ergo i would like to create my own costumized function name.

## Possible Solution

Add functionName on deployFunction function.

**Comment by JonnyBurger** [comment]
Different versions and configurations are already distinguished by it's name, e.g. `remotion-render-4-0-42-mem3000mb-disk2048mb-120sec`.

Each Lambda function is also a binary and has the same code for every user and is identical no matter if running in development or production - the custom React code is contained in the "site" instead.

If you want to use a different version in development, just deploy a new function, the other will not delete or conflict.

See also: https://www.remotion.dev/docs/lambda/upgrading#separating-production-and-testing-environments
