### ISSUE TITLE
API keys/creds exposed

### ISSUE THREAD

**Issue by tarunfy** [remotion-dev/remotion#2938]
Hey,
I was going through the code and found out that the Algolia creds/keys are exposed publically, they should be in the environment variables. Please make them secure asap.
![Screenshot 2023-09-27 at 2 52 26 PM](https://github.com/remotion-dev/remotion/assets/51208270/5684099b-5de3-4c6a-b08a-33623ad96d79)

Thanks.

**Comment by JonnyBurger** [comment]
These are meant to be public according to Algolia Docs.
