### ISSUE TITLE
Add a `playbackRate` prop to the <Gif> component

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2942]
Could just divide the current frame with the `playbackRate` to make the GIF play faster or slower.

And then document the new prop in gif.md!

**Comment by JonnyBurger** [comment]
Here is the file to get started in

https://github.com/remotion-dev/remotion/blob/main/packages/gif/src/useCurrentGifIndex.tsx

/bounty 100


💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

**Comment by anikdhabal** [comment]
@JonnyBurger  Hey can you assign me this issue?

**Comment by JonnyBurger** [comment]
@anikdhabal @DevGajjar28 

Whoops, that was almost at the same time! @anikdhabal was first, so I will give them this issue.

Sorry @DevGajjar28, more bounties coming soon!

**Comment by Vishal-Sikka** [comment]
oh forgot to comment attempt here, i already figured it out

**Comment by DevGajjar28** [comment]
I have also figured out but my bad it was assigned

**Comment by JonnyBurger** [comment]
Sorry @Vishal-Sikka, we will for the bounty only consider a PR by the assignee. 

We want to avoid multiple people doing the same work. Nonetheless thanks for your willingness to contribute!

**Comment by Vishal-Sikka** [comment]
@JonnyBurger it's ok

**Comment by anikdhabal** [comment]
@Hitesh-sisara As you can see, this issue is assigned to me, and I'm working on it. @JonnyBurger clearly mentioned the guidelines.

**Comment by JonnyBurger** [comment]
This is right, @anikdhabal you are eligible for the bounty. We are going to continue process and also work with Algora to make this more smooth.
