### ISSUE TITLE
Cloud Run : deploying a site is not reliably uploading all assets

### ISSUE THREAD

**Issue by andreibarabas** [remotion-dev/remotion#2948]
Whenever we run the deploy command

`yarn remotion cloudrun sites create index.ts --site-name=videos`

although it says it was successful, we periodically discover in the logs that rendering could not happen because certain files do not exist, and then we end up going and redeploying manually the site again.

After it happened several times, now after each deployment we go on the bucket and see if there might be something missing, but as you can imagine this is error-prone.

# Bug Report 🐛

TBD. I honestly don't yet have good repro steps, but will continue monitoring this and provide more information ASAP.

Remotion version is `4.0.42`
<img width="304" alt="Screenshot 2023-09-29 at 12 45 57" src="https://github.com/remotion-dev/remotion/assets/2101405/5aad7a2d-6d32-4759-ab8b-f133c9fa10da">

The error we see in logs are these types, and indeed, the file does not exist in the bucket, so we go and manually deploy again

`[https://storage.googleapis.com/remotioncloudrun-ipcjvnpe2l/sites/videos/public/video-assets/iphone-14-pro.png] Failed to load resource: the server responded with a status of 403 ()`

**Comment by JonnyBurger** [comment]
Interesting, hard for me to take any action on this because never seen this, but I believe you.

403 kind of indicates that the file is there, but you are not allowed to read this right?
Are there any special policies that you added to your bucket?

**Comment by andreibarabas** [comment]
No. I created everything with the CLI, as per your request in the docs.

Haven't deployed any new videos in 2 weeks, so could not replicate it myself, but let's keep this open and I'll come back

**Comment by JonnyBurger** [comment]
Feel free to report here or open a new issue if you can describe the issue better.
As of now, there is nothing we can do concretely.
