### ISSUE TITLE
Can edit and import svg with layers in remotion  like svgedit?

### ISSUE THREAD

**Issue by nazemi0101** [remotion-dev/remotion#2959]
I need import a svg image into scene than can edit layers position or order or add or delete some path or image on scene .with layer of svg and another shapes or path .how to do?
Like svgedit repository

**Comment by JonnyBurger** [comment]
Remotion is not an SVG editor and therefore does not have any features like this planned.
To edit the SVG, you need to manually change the markup.

**Comment by JonnyBurger** [comment]
If you need to dynamically change the SVG, don't import an .svg file, but instead, use an inline SVG as React markup. You can convert SVG to React markup here: https://react-svgr.com/playground/
