### ISSUE TITLE
Easing docs are confusing

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2973]
![image](https://github.com/remotion-dev/remotion/assets/1629785/70baa0b0-0599-4824-b7b0-cee68ca53198)

You can call Easing.bezier yourself, but not Easing.bounce, but they look equivalent in the docs

**Comment by JonnyBurger** [comment]
Same thing with React Native docs!

**Comment by kaf-lamed-beyt** [comment]
Hey @JonnyBurger, what do you think could be done? 

Perhaps I could take a look.

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Thanks for the interest in fixing this! The confusing thing is that you would use `bezier` like that:

```tsx
interpolate(0.5, [0, 1], [0, 1], {
	easing: Easing.bezier(0.5, 0.01, 0.5, 1)
})
```

but you would use `bounce` like that: 

```tsx
interpolate(0.5, [0, 1], [0, 1], {
	easing: Easing.bounce
})
```

One function you have to call, one function you don't.
Which can be seen if you use TypeScript, it will complain.
But the docs doesn't distinguish it, they write it as `static bounce(t)` as well as `static bezier(x1, y1, x2, y2)`.

We could make it clearer by either changing the signature to `static bezier(x1, y1, x2, y2) => (t): number` and `static bounce(t): number` to signalize the difference.

We copied this documentation from React Native and they suffer from the same problem, could be another high-profile PR!

**Comment by kaf-lamed-beyt** [comment]
Ah! Nice! I see where you're coming from now @JonnyBurger!

Can you point me to the file where I can change these signatures? If my guess is right, It should be in the API category of Remotion.

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt It's just a documentation issue, https://www.remotion.dev/docs/easing

You can click `Edit this page` at the bottom

**Comment by kaf-lamed-beyt** [comment]
Ah! I see. I thought with the illustration you shared in your previous comment, one would've have to work on the signatures. 

Thanks for clarifying again. I'll get started and ping you when I submit a PR.
