### ISSUE TITLE
Get notified when `staticFile()` changes

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2977]
## Use Case

When a file in the public folder changes, you cannot get notified for it to for example re-`fetch()` the asset.

With this code snippet here, we can get notified if the public folder changes (compare lastModified timestamps to previous array): 

https://github.com/remotion-dev/remotion/blob/7e8a76640db310aa35e5b4842e98fe506fe56100/packages/cli/src/event-source.ts#L53-L57

## Acceptance criteria

Implement a new function `watchStaticFile()` in the `remotion` package:

```ts
import {StaticFile, watchStaticFile} from "remotion";

const cancel = watchStaticFile('my-data-json', (newData: StaticFile | null) => {
	if (newData === null) {
		// File was deleted
	} else {
		// File was added or modified
		console.log(newData.lastModified)
	}
})

cancel() // Stop watching
``` 

- You can implement the logic on the `window` object if needs to be. Prefix all variables on the window object with `remotion_` to not pollute the scope.
- Write a documentation page similar to https://www.remotion.dev/docs/getstaticfiles and add it to the sidebar + remotion package table of contents. Mention minimum version (next release), add a code example, warning that this feature only works in Remotion Studio, document the function signature, mention how to cancel it.
- Cleanly compare the previous static file array with the new one and implement a change listener without any false positives or negatives. The change callback should not fire initially.
- Add a `console.warn` once if the function is called outside of the Remotion Studio (use `getRemotionEnvironment()` to determine if that is the case).

## Bounty
💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 250

**Comment by evoxf1** [comment]
i gave it a thought @JonnyBurger , in this approach, we maybe can create a custom hook utilizing useState and useEffect. It periodically fetches updated static files from the server using the Fetch API. After each fetch, it triggers a re-render by updating the staticFiles state. The hook also clears the interval to prevent excessive requests. If any errors occur during fetching, it handles them.

**Comment by evoxf1** [comment]
@JonnyBurger ?

**Comment by JonnyBurger** [comment]
@evoxf1 We already get notified via HTTP EventStream if the static files change.

I just tried to specify the requirements, but realize that I need some time to being fair to all the use cases (get notified when the whole folder changes, or only get notified when the contents of a certain file changes - maybe this should not involve calling `getStaticFiles()` at all).

Need some time to think this through properly, but already thanks for caring about this issue!

**Comment by JonnyBurger** [comment]
@evoxf1 I now added a spec. Since you already solved two issues this hacktoberfest, it would be nice if someone new also gets a chance.

**Comment by evoxf1** [comment]
@JonnyBurger 
Okay, let someone else try this, i will be in queue.

**Comment by JonnyBurger** [comment]
Thanks for understanding @evoxf1!
You are good to go @mrkirthi-24! Thanks for attempting this

**Comment by devshah7774** [comment]
is the assignee still working on this issue??

**Comment by JonnyBurger** [comment]
@devshah7774 They still are yeah, we are talking via DM
