### ISSUE TITLE
renderMedia giving error locally

### ISSUE THREAD

**Issue by btahir** [remotion-dev/remotion#2985]
Hi - 

Amazing project!

I'm having some issues trying to use renderMedia instead of the cli to build locally.

The `remotion render MyComp out/video.mp4` works just fine. However if I follow this [example](https://www.remotion.dev/docs/ssr) (I only changed the composition Id), and try to run the script locally (`node script/render.mjs`), I get this error:

```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[SymbolicateableError [SyntaxError]: Unexpected token '<', "<!DOCTYPE "... is not valid JSON] {
  stackFrame: [],
  frame: null,
  delayRenderCall: null
}
```

The src files are in Typescript so not sure if that is causing any issues with the mjs script. 

Thanks!

**Comment by JonnyBurger** [comment]
Hi @btahir,

can you describe which template you used and name any relevant changes to it?
Or even deliver a way to reproduce it?

**Comment by btahir** [comment]
Sure - 

I made a repo with the code [here](https://github.com/btahir/remotion-debugging).

The steps I took for this:

`npm init video`
pick Tailwind Typescript starter
Added render.mjs from [here](https://www.remotion.dev/docs/ssr) to a scripts folder
Changed Comp id to MyComp
tried `node scripts/render.mjs`
Got same error now 
Also tried installing @remotion/renderer but no change

My Node version is v18.12.1.

**Comment by JonnyBurger** [comment]
@btahir Sorry for the late response and thanks for the reproduction!

I followed the steps and for me it did render successfully. I suspect a different bug, namely that your port 3000 is being blocked by another website (that would make sense that when trying to access port 3000, it returns an HTML page instead).

Are you still able to reproduce it locally and can you confirm there is something else running on port 3000, if you don't start the Remotion script?

**Comment by JonnyBurger** [comment]
^4.0.48 has a potential fix for it, which is also worth trying out

**Comment by btahir** [comment]
Thanks for looking into it!

I tried upgrading and killing the 3000 port (there was none running) and it didn't work.

I can still use the terminal commands so its not a blocker but will look into more on why its happening.

**Comment by JonnyBurger** [comment]
@btahir Hey, some more improvements made :)

- Port selection is now even more robust
- `SymbolicateableError` would swallow the actual error message, and now it doesn't anymore! So you will be able to get a much better stack and maybe this will give you an idea where the error comes from.

**Comment by JonnyBurger** [comment]
Can you try 3.0.50 or 3.0.51 once it comes out?

**Comment by JonnyBurger** [comment]
Is it true what the error message says? Maybe missing an extension?

**Comment by btahir** [comment]
Ah I think I got it. Yes - you're right. Caue it's mjs we have to add extensions to imports.

```
const bundleLocation = await bundle({
  entryPoint: path.resolve("./src/index.ts"),
```

**Comment by btahir** [comment]
Interesting - the output video seems to not have the width, height and css settings that were being rendered using the CLI command. Maybe have to attach those explicitly?

**Comment by btahir** [comment]
Got it. Thanks for looking into this!
