### ISSUE TITLE
On Windows, does not avoid busy port 3000

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2989]
![image](https://github.com/remotion-dev/remotion/assets/1629785/0de372e1-16c9-4837-9657-39b1f8853202)

**Comment by evoxf1** [comment]
Usually it doesn't happen, id one port is occupied apps usually choose the other. Maybe it is cached somewhere(just a guess). Also is this persistant?

**Comment by JonnyBurger** [comment]
Fixed by #3000 (this is a coincidence lol)

**Comment by evoxf1** [comment]
Wish  every bug could be fixed by coincidence every-time they appear :(

**Comment by JonnyBurger** [comment]
The coincidence is that the port and the issue number are both 3000 😆
