### ISSUE TITLE
Implement a "credits" component for the documentation

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3001]
Many people have contributed to the Remotion docs, but we do not have a nice way to give credits.  
The goal is to make a new component for which we can display the profile picture and name.

**Mockup**:

![image](https://github.com/remotion-dev/remotion/assets/1629785/890388ff-6e2f-43b6-a6ed-1dadff62ec2b)

## Acceptance criteria

- Create a new JSX component `<Credits>` in this file: https://github.com/remotion-dev/remotion/blob/50b1424eb14cc62cb805834bf63ee7901e56975c/packages/docs/src/theme/MDXComponents.js
- Make a component which can display one or multiple authors
- Each author can be clicked on to go to GitHub, has a picture (`https://github.com/[username].png`) and a subtitle specifying the type of contribution.
- On mobile, it should look good as well.
- Add the `<Credits>` component to different pages, highlighting at least 10 different contributors. You don't need to import the component to be available in markdown. You can for example look up previous Hacktoberfest contributions: https://github.com/remotion-dev/remotion/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22%F0%9F%A5%A8++hacktoberfest%22+is%3Aclosed

## Bounty
💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs (this one is helpful here)

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 200

**Comment by evoxf1** [comment]
May I try if no one wants to?

**Comment by JonnyBurger** [comment]
@evoxf1 If you are confident that you are able to do it, go ahead!

**Comment by evoxf1** [comment]
its scary but thanks, :)

**Comment by Aditya9764** [comment]
@JonnyBurger  can i give try

**Comment by JonnyBurger** [comment]
The issue is assigned to @evoxf1

**Comment by IamSAL** [comment]
I want to be in the queue for implementing this component!

**Comment by siddhakdak** [comment]
/attempt i want to work on this can i procees..

**Comment by CntrlX** [comment]
/attempt i want to work on this if or when i can.
