### ISSUE TITLE
Rendering on Cloud Run renders only the first 3 seconds

### ISSUE THREAD

**Issue by tzvc** [remotion-dev/remotion#3002]
Hey there,

I've been running remotion renderer on my own Cloud Run service for a while, but for sake of less maintenance, I've decided to give the new `cloudrun` package a try.

Setup was great and I was able to pretty much swap out my service for the one deployed by the package, but upon rendering my first video, it appears that only the first 3 seconds are rendered. I've since tried with many different videos and I still get the same outcome: No errors, but only the first 3 secs of the video are rendered.

I've noticed that the `renderMediaOnCloudrun` function does not include the `durationInFrames` and `fps` props from `renderMedia`. I'm assuming this is the reason why my renders don't include all the frames.

Is that on purpose? Where can I specify `durationInFrames` for my cloud renderring?

Cheers!

**Comment by JonnyBurger** [comment]
For Cloud Run and Lambda, you can only specify a composition name and the props + duration get resolved in the cloud.
To make the duration dynamic, you can use a calculateMetadata function: https://www.remotion.dev/docs/calculate-metadata#see-also

Indeed, no `config` option is available for Cloud Run. We assume you don't want to evaluate the composition on a different machine than you do want to do the render
