### ISSUE TITLE
"Timeline width is null"

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3006]
![image](https://github.com/remotion-dev/remotion/assets/1629785/2f3443e9-e9d7-4e40-8e17-e73decb2c68b)

https://discord.com/channels/809501355504959528/1161766838728937472/1161766838728937472

We should not allow it to happen

**Comment by CommanderGL** [comment]
same issue here, just randomly started happening

**Comment by AWATV** [comment]
Error started after I updated **Remotion** from `4.0.20` to `4.0.48`.
Reverted to `4.0.20` helps resolve it.
