### ISSUE TITLE
Split up `setPort()` option

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3008]
Currrently the `Config.setPort()` option sets the port for the Remotion Studio but also for rendering.
Now that you render from within the studio that leads to a conflict.

We should split it up to `Config.setStudioPort()` and `Config.setRendererPort()`. `Config.setPort()` should get a `@deprecated` JSDoc command but for now set both ports still.

The `--port` flag should set the Studio port when running the `remotion studio` command, but the renderer port when using any other  command.

**Comment by jkcs** [comment]
What do you think the `--port` in the `remotion preview` command changes - the studio port or the rendered port?

**Comment by JonnyBurger** [comment]
@jkcs I think it should change the port of where the Remotion Studio starts

**Comment by jkcs** [comment]
@JonnyBurger I have full confidence in completing this. I would like to understand how the `remotion cli` works by working on this issue. Can you assign this issue to me?

**Comment by JonnyBurger** [comment]
Absolutely!

Thanks a lot for stepping up! 😊 🙌
