### ISSUE TITLE
Tagging Lambda Function for easier billing analyse

### ISSUE THREAD

**Issue by alimirjahani7** [remotion-dev/remotion#3017]
# Feature Request 🛍️

a flag to tag lambda function for make it easier for user to find out remotion lambda function bills. as every version will create a new function it's hard for user to tag it himself

## Possible Solution

I think boto3 for lambda have the ability to tag a function on creation
also it could be good if there be a tag for remotion version to

**Comment by JonnyBurger** [comment]
Good idea!

**Comment by JonnyBurger** [comment]
I understand you are asking just for us to add some hardcoded tags:
I'm adding the following tags: 

<img width="581" alt="image" src="https://github.com/remotion-dev/remotion/assets/1629785/fecd3958-3448-4b0e-b6b0-0836e93d32b3">

Actually, memory etc. would also be useful, will add that as well!

For this to work, you will have to update your user policy

**Comment by alimirjahani7** [comment]
Yes exactly like that.
Thanks it's great
