### ISSUE TITLE
Timeline zoom is not persisted to localStorage anymore

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3023]

**Comment by kaf-lamed-beyt** [comment]
any idea why this is happening?

**Comment by JonnyBurger** [comment]
have not investigated it yet

**Comment by kaf-lamed-beyt** [comment]
Okay cool. When you do. please let me know. 

Or better still. If you don't mind I'd love to investigate too. If you can point me in the right direction.

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt A trick is to delete the repo and only pull the latest commit: https://www.remotion.dev/docs/contributing/

But no sweat, I will take a look at it myself soon.
This makes we want to investigate if we can reduce the size of the repo even...

**Comment by kaf-lamed-beyt** [comment]
Ah yes. The repo size is almost around 1GB+ 

I'll try what you suggested and let you know how it goes.

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt I just cleaned up the repo, used to be 2.5GB, now it is just 1.3GB

I recommend, if you don't have any work lying around, to run `git reset --hard origin` and then pull, and the repo is now only half the size

**Comment by kaf-lamed-beyt** [comment]
Wow! That's huge! Great work halving it. 🐐🙌🏽🙌🏽

I'll do the hard reset in a bit.

**Comment by kaf-lamed-beyt** [comment]
Cloning again now. It is halfway done.
