### ISSUE TITLE
@remotion/google-fonts: getAvailableFonts() - Can't load custom fonts into video on lambda function.

### ISSUE THREAD

**Issue by jackkingham-au** [remotion-dev/remotion#3024]
Hi all, I've set up an app,  to allow custom fonts to be passed dynamically to a video.

I use ```getAvailableFonts()``` to find the dynamic fonts and load those one-by-one. However, every time I render the video, the custom fonts are not applied.

**What the templates Are**
```<StaticTemplate />```, and the template variables, refer to an ```SVGElement``` as a string, that contain text elements among other elements. _This is where the custom fonts are used_. These templates are simply a string, that I add to the innerHTML in an overlay, of the video. 

**Where the Custom Fonts Come In**
With that in mind, I want to have the fontFamily specified in the template string, and have it loaded on the server.  

❌ I cannot access the ```style={}``` of the text directly, and add fontFamily to the style attribute. 
❌ I cannot access the ```class={}``` of the text directly, and add a className.

The appropriate elements will already have the dynamic fontFamily hardcoded into the string, as their fontFamily. 

**What I Need**
A way to globally load the dynamic CSS fontFamilies, without directly editing the text elements by class or style. Just like I would import a CSS statement with ```@import```,  or load a CSS stylesheet with a ```<link />``` element.

This is the same approach I use on my local machine - which works on the local environment. 

For reference, I am using ```getAvailableFonts()``` locally, to get the dynamic fontFamilies I can use. 

This is the composition component I pass;

```
import { ExportedSegment } from "@/types/config/appSettings";
import { ExportTimelineProps } from "@/types/remotion";
import { useCallback, useEffect, useState } from "react";
import { Audio, OffthreadVideo, Sequence, continueRender, delayRender } from "remotion";
import Transition from "../../components/transitions/Fade";
import StaticTemplate from "./StaticTemplate";
import { getAvailableFonts } from "@remotion/google-fonts";

const getRawTemplates = (segments: ExportedSegment[]) => {
    return Promise.all(segments.map((segment) => {
        return fetch(segment.templateSrc!).then(res => res.text()).then(res => {
            return {
                for: segment.id,
                template: res
            }
        })
    }))
}

const DynamicComposition = (props: ExportTimelineProps) => {
    const segments = props.segments!;
    const metrics = props.metrics;

    const [rawTemplates, setRawTemplates] = useState<null | { template: string | null, for: string }[]>(null);
    const [handle] = useState(() => delayRender());

    const loadTemplates = async () => {
        setRawTemplates(await getRawTemplates(segments));
    }

    // 1. Get all of the available fonts, using @remotion/google-fonts
    const allFonts = getAvailableFonts();
    
    // 2. Get the dynamic fonts passed by the user.
    const userSelectedFonts = [...new Set(segments.map(({ fonts }) => fonts))]

    // 3. Find and load these fonts one by one.
    const loadFonts = async () => {
        for (const fontToFind of userSelectedFonts) {
            const font = allFonts.find(({ fontFamily }) => fontFamily === fontToFind);

            if (!font) continue;

            font.load()
                // @ts-ignore (TSIGNORE - loadFont not typed to module)
                .then((module) => module.loadFont());
        }
    }

    const getDynamicProps = useCallback(async () => {
        await loadTemplates();
        // 4. Load Dynamically Passed Fonts 
        await loadFonts();

        continueRender(handle);
    }, [handle]);

    useEffect(() => { getDynamicProps() }, []);

    return (
        <>
            {
                segments!.map(({ src, id, audioSrc, muted }, index) => {
                    const rawTemplate = rawTemplates?.filter(template => template.for === id)[0];

                    return (
                        <Sequence
                            durationInFrames={metrics.segmentDurationInFrames}
                            from={index === 0 ? 0 : index *     metrics.segmentDurationInFrames}
                            key={index}
                        >
                            <OffthreadVideo src={src} muted={muted} />
                            <Transition metrics={props.metrics} />
                            {
                                (rawTemplate)
                                    ? <StaticTemplate template={rawTemplate.template!} />
                                    : ''
                            }
                            {
                                (audioSrc)
                                    ? <Audio src={audioSrc} />
                                    : ''
                            }
                        </Sequence>
                    )
                })
            }
        </>
    )

}

export default DynamicComposition;
``` 

I believe I am misunderstanding something with loading getAvailableFonts(), or there is a step I'm missing in the render process. 

I've cross-checked getAvailableFonts on my local machine, and it works as intended locally - just not on my AWS bucket.

**What I've attempted**

1. I have attempted to use the Google Font Picker example according to the docs - [Google Font Picker](https://www.remotion.dev/docs/font-picker).

2. Load fonts using the native FontFace() API. 

3. Load fonts using [https://fonts.google.com/](https://fonts.google.com/) API URLs.

**Version:** I am running that latest version of Remotion - 4.0.50

I would greatly appreciate any guidance you can provide to help me solve this. Thank you 🙏

**Comment by JonnyBurger** [comment]
I could not confirm the issue, the following works:

```tsx
import React, {useEffect, useState} from 'react';
import {getAvailableFonts} from '@remotion/google-fonts';
import {AbsoluteFill, continueRender, delayRender} from 'remotion';

const firstFont = getAvailableFonts()[0];

const ReactSvg: React.FC = () => {
	const [handle] = useState(() => delayRender());

	useEffect(() => {
		firstFont
			.load()
			.then((hi) => {
				return hi.loadFont();
			})
			.then(() => {
				continueRender(handle);
			});
	}, [handle]);

	return (
		<AbsoluteFill>
			<h1 style={{fontFamily: firstFont.fontFamily, fontSize: 500}}>
				{firstFont.fontFamily}
			</h1>
		</AbsoluteFill>
	);
};

export default ReactSvg;
```

This only works though if you let Webpack pick up that there are 5000 font files and let them upload to a S3 bucket. You are mentioning that you are doing something statically, so this might be a problem.

The error handling could be another problem, I recommend to add `.catch` to your promises and call cancelRender() so that if an error occurs, you get notified about it and it will not get swallowed.

The type error I can confirm happens and I'm improving the types in #3028!

**Comment by jackkingham-au** [comment]
Thank you for your quick response 🙏

I will add error handling to the ```.catch``` statements, that will help as well.

I believe the fact that everything is static as well may be causing the problem. 

You mention _" let Webpack pick up that there are 5000 font files and let them upload to a S3 bucket."_. Are you able to ellaborate more on how I can do this?

To give context, I am using Next JS 13.4.2 (with the app directory), Tailwind and I have added remotion to this project.

I use a ```WebpackOverrideFn``` from ```@remotion/bundler``` to add remotion the project. This is the current override function;

```
export const webpackOverride: WebpackOverrideFn = (currentConfiguration) => {
	return {
		...currentConfiguration,
		module: {
			...currentConfiguration.module,
			rules: [
				...(currentConfiguration.module?.rules
					? currentConfiguration.module.rules
					: []
				).filter((rule) => {
					if (rule === '...') {
						return false;
					}
					if (rule.test?.toString().includes('.css')) {
						return false;
					}
					return true;
				}),
				{
					test: /\.css$/i,
					use: [
						'style-loader',
						'css-loader',
						{
							loader: 'postcss-loader',
							options: {
								postcssOptions: {
									plugins: [
										'postcss-preset-env',
										'tailwindcss',
										'autoprefixer',
									],
								},
							},
						},
					],
				},
				{
					test: /\.svg$/i,
					issuer: /\.[jt]sx?$/,
					use: ['@svgr/webpack'],
				},
			],
		},
	};
};
```
Not sure if this is needed, but this is my ```remotion.config.ts```;

```
import { Config } from '@remotion/cli/config';
import { webpackOverride } from './webpack-override';

Config.setVideoImageFormat('jpeg');
Config.setStillImageFormat('jpeg');
Config.setOverwriteOutput(true);

Config.overrideWebpackConfig(webpackOverride);
```

Thank you once again for your help, I appreciate it!! 🙏
