### ISSUE TITLE
Unexpected: getPointAtLength() return wrong point sometimes

### ISSUE THREAD

**Issue by t6adev** [remotion-dev/remotion#3026]
Reported [here](https://discord.com/channels/809501355504959528/1164078615919607869/1164078615919607869)

 I'm trying to animate svg line and triangle like attempted video.
As you can see, the triangle almost works well but sometimes gets wrong positions. 

In a component, the triangle point position is calculated by this,
```
const svgPath = '...';
const pathLength = getLength(svgPath);

const frame = useCurrentFrame();
const rate = frame / durationInFrame;

const point = getPointAtLength(svgPath, pathLength * rate);
```

https://github.com/remotion-dev/remotion/assets/6883692/2c681ed2-9ccb-4c29-b5b2-47ab1e2b19b8

Here is a repro.
https://codesandbox.io/p/sandbox/remotion-unexpected-getpointatlength-f9tw6y

**Comment by JonnyBurger** [comment]
Yay 🙌  thanks for testing the new version! Nice to see it works now 😃
