### ISSUE TITLE
Package up a `@remotion/layout-utils` function with `measureText()` API

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3033]
I have already created a function `measureWord()`:

```tsx
type Dimensions = {
  width: number;
  height: number;
};

const wordCache = new Map<string, Dimensions>();

export const measureText = ({
  text,
  fontFamily,
  fontWeight,
  fontSize,
  letterSpacing,
}: {
  text: string;
  fontFamily: string;
  fontSize: number;
  fontWeight?: number | string;
  letterSpacing?: string;
}): Dimensions => {
  const key = `${text}-${fontFamily}-${fontWeight}-${fontSize}-${letterSpacing}`;

  if (wordCache.has(key)) {
    return wordCache.get(key) as Dimensions;
  }

  const node = document.createElement("span");

  node.style.fontFamily = fontFamily;
  node.style.display = "inline-block";
  node.style.position = "absolute";
  node.style.top = `-10000px`;
  node.style.whiteSpace = "pre";
  if (fontWeight) {
    node.style.fontWeight = fontWeight.toString();
  }

  node.style.fontSize = `${fontSize}px`;
  if (letterSpacing) {
    node.style.letterSpacing = letterSpacing;
  }

  node.innerText = text;

  document.body.appendChild(node);
  const boundingBox = node.getBoundingClientRect();
  document.body.removeChild(node);

  const result = { height: boundingBox.height, width: boundingBox.width };
  wordCache.set(key, result);
  return result;
};
```

- The goal is to ship this as an API in a new NPM package `@remotion/layout-utils`.
- It should ship with a CJS+ESM version, similar to how the `@remotion/noise` package is shipped. The folder could be copy-pasted to get started.
- The package should export one function that can be used with `import {measureText} from "@remotion/layout-utils"`
- A new page should be created similar to https://www.remotion.dev/docs/noise which includes a table of contents (for now just one function in it). The package can be MIT licensed
- A new documentation page should be created explaining the APIs. It should have a brief explanation what the API does, contain an example code snippet, show from which Remotion version the API is available (next release), list the options, explain if they are mandatory or optional, and link to the source code at the bottom of the page.
- `@remotion/layout-utils` should be added to `list-of-remotion-packages.ts` (2x in the monorepo)
- In the `packages/example` testbed, add a very simple composition that uses the API so that we can test for regressions in the future

## Bounty
💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 250

**Comment by JonnyBurger** [comment]
@jkcs You got it!

**Comment by evoxf1** [comment]
i would like to be in queue. @JonnyBurger
