### ISSUE TITLE
OffthreadVideo documentation page is missing props

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3035]
For example startFrom and endAt.
Those are in video.md but also weirdly formatting. Should improve both.

**Comment by CruuzAzul** [comment]
Hi @JonnyBurger I can take this one with more details 😊

**Comment by evoxf1** [comment]
any progress on this @JonnyBurger @CruuzAzul

**Comment by JonnyBurger** [comment]
Thanks a lot for the help offered 😊
Specifying the things to do here is maybe harder than just quickly doing it myself, so I'll take this one and do it now
