### ISSUE TITLE
Create a `<Polygon />` component for `@remotion/shapes`

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3059]
## Use Case

https://remotion.dev/shapes has several geometic shapes such as `<Pie>`, `<Rect>` and `<Star>`. This task is to implement a `<Polygon>` shape and a `makePolygon()` function.

## Acceptance criteria

- Make a `<Polygon>` component
- Make a `makePolygon()` function
- Add a `points` prop - 3 should be a triangle, 4 should be square, 5 should be a pentagon and so on
- Also support the `edgeRoundness` and `cornerRadius` prop like the other shapes
- Add 1-2 unit tests
- Document both in the same way as the other shapes are documented, including the playground
- There should be a prop `points`, it should validate that it is an integer and at least `3` (which would be a triangle)
- Add it to the table of contents on remotion.dev/shapes

## Resources

Previous implementations of shapes:

- `<Pie />`: https://github.com/remotion-dev/remotion/pull/1756
- `<Star />`: https://github.com/remotion-dev/remotion/pull/1726

## Bounty
💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- Only take an issue if you have an approximate idea on how to solve the issue.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 250

**Comment by JonnyBurger** [comment]
@neo773 That was fast! Almost too fast 🤔 

> Only take an issue if you have an approximate idea on how to solve the issue.
Do you feel confident that you are able to solve this issue?

**Comment by neo773** [comment]
@JonnyBurger haha, got the notification from your Discord channel,
And yes I can do it.

**Comment by JonnyBurger** [comment]
@neo773 Awesome! Thanks and good luck 🫡
