### ISSUE TITLE
Document `VERSION` from remotion

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3067]
## Use Case

```
import {VERSION} from 'remotion/version';
```

This is not yet documented but would be nice to! 

## Acceptance criteria
Let's add it here: https://www.remotion.dev/docs/remotion to table of contents and to the sidebar with a separate page.

You can also `import {VERSION} from "remotion/version"` instead of `import {VERSION} from 'remotion'` to not include the entirety of Remotion and it's dependencies (React), which is also a good trick worth documenting.

## Bounty
💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- Only take an issue if you have an approximate idea on how to solve the issue.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 100

**Comment by evoxf1** [comment]
May I? @JonnyBurger

**Comment by anuanu93** [comment]
Hello, @JonnyBurger  Can i do this issue its my first contribution.

**Comment by JonnyBurger** [comment]
Sorry @anuanu93 I already assigned @evoxf1 😔
If you want I can keep you in mind for the next documentation issue!

**Comment by evoxf1** [comment]
if @anuanu93 wants to do it I can resign, first contributors should be getting preference . @JonnyBurger

**Comment by JonnyBurger** [comment]
That's kind of you @evoxf1 🤗 That allows us to introduce more contributors which we are always happy about. Thanks @evoxf1 and good luck @anuanu93!

**Comment by anuanu93** [comment]
@JonnyBurger  thanks , i will clone and fork it an will ask for help if needed.

**Comment by anuanu93** [comment]
@JonnyBurger  Do I have to make a separate full page documentation for version?
