### ISSUE TITLE
Remotion Root issue with monorepos

### ISSUE THREAD

**Issue by rcomesan** [remotion-dev/remotion#3074]
I'm trying to add a remotion project to a monorepo created with nx. It has the following folder structure:
```
/organization
 ├── remotion
 │   ├── project.json (nx project configuration)
 │   ├── remotion.config.ts
 │   ├── src
 |   |   ├── index.ts (registerRoot entry point))
 │   ├── tsconfig.json (project specific ts configuration)
 ├── nx.json
 ├── node_modules (monorepo modules)
 ├── package.json (monorepo package.json)
 ├── package-lock.json
 ├── project.json
 └── tsconfig.base.json (base ts extended by projects)
```
I configured a "start" command in nx's configuration file (remotion/project.json) to start remotion studio:
```
"start": {
  "executor": "nx:run-commands",
  "options": {
    "command": "npx remotion studio remotion/src/index.ts --public-dir=remotion/public --config=remotion/remotion.config.ts"
  }
}
```
After executing it with ```nx run remotion:start``` I get the following error:
```
Could not find a tsconfig.json file in your project. Did you delete it? Create a tsconfig.json in the root of your project. Copy the default file from https://github.com/remotion-dev/template-helloworld/blob/main/tsconfig.json.
The root directory is: /organization
```
I still get the same error even if I change the command to execute inside the remotion project using the cwd option like this:
```
"start": {
  "executor": "nx:run-commands",
  "options": {
    "command": "npx remotion studio src/index.ts --public-dir=ublic --config=remotion.config.ts",
    "cwd ": "remotion"
  }
}
```
After a bit of debugging, it turns out that the [Remotion Root](https://www.remotion.dev/docs/terminology#remotion-root) is determined by the first package.json found in the parent directories. In my case, I have the package.json defined at the root of my workspace (or "monorepo"), but the root of the remotion project is in the ./remotion subfolder, so it's not being able to find the tsconfig.json file.

I was able to get the entry point and the public directory working by using the command options (as shown above), but there's no option to configure the remotion root. 

I'm not sure if there's any way to get around this issue. I've seen that the [findRemotionRoot](https://github.com/remotion-dev/remotion/blob/266d67d073cc1207261dd2aa2c018fb1499da155/packages/renderer/src/find-closest-package-json.ts#L22C14-L22C30) function first tries to find a package.json file and then falls back to the current working directory if it's not found.

Is there any reason for not using the current working directory as the remotion root instead of trying to find a package.json file first?
Would a CLI option such as --remotion-root be more suitable in this case?

Thanks

**Comment by JonnyBurger** [comment]
I see, yes Remotion expects the tsconfig.json to be adjacent to the package.json.
You could probably fix it by just adding a package.json with content `{}` to the `remotion` folder. Does that work?
Otherwise we need to introduce an option.

> Is there any reason for not using the current working directory as the remotion root instead of trying to find a package.json file first?

Yes, often times the CLI is called for example from `remotion/src`, so we need to go up one (or more) directories in order to find the config files.

**Comment by rcomesan** [comment]
That did the trick for me. Thank you, Jonny.

Also, just for reference, I had to run the command from the remotion project (using the cwd nx option), so that remotion finds the empty package.json first, instead of the package.json placed at the root of the monorepo, as it was doing before.
