### ISSUE TITLE
Document and test GPU instructions for Docker

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3087]
Made by @UmungoBungo https://locrian-polyester-b03.notion.site/EC2-GPU-within-Docker-ddfe8fae607042149a7df870a8347798

**Comment by kaf-lamed-beyt** [comment]
@JonnyBurger, do you need this to be in the docs on remotion.dev/docs?

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt That'd be the goal yes!

**Comment by kaf-lamed-beyt** [comment]
Awesome! I'll open a PR shortly.

**Comment by kaf-lamed-beyt** [comment]
This might take a while @JonnyBurger. I've tried cloning several times but it keeps disconnecting abruptly. It's mostly due to my internet connection though. 

When I pull through, I'll let you know
