### ISSUE TITLE
Failed to compile `compositor-linux-x64-gnu/compositor` when using `getAwsClient()`

### ISSUE THREAD

**Issue by pabloruizetc** [remotion-dev/remotion#3090]
I was trying to use the code snippet of the docs regarding presigned URLs. The `getAwsClient` function triggers the following error:

Failed to compile:
```
./node_modules/@remotion/compositor-linux-x64-gnu/compositor
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

I am using Ubuntu 22.04.3 LTS.

```
Import trace for requested module:
./node_modules/@remotion/compositor-linux-x64-gnu/compositor
./node_modules/@remotion/compositor-linux-x64-gnu/index.js
./node_modules/@remotion/renderer/dist/compositor/get-executable-path.js
./node_modules/@remotion/renderer/dist/index.js
./node_modules/@remotion/lambda/dist/api/download-media.js
./node_modules/@remotion/lambda/dist/index.js
```

**Comment by JonnyBurger** [comment]
This is because `getAwsClient()` is only meant to be used in a Node.js environment.
In the example, we use a API route, for example in Next.js.

While the error you are getting is not directly related, we will not change it because calling getAwsClient() in the browser is heavily discouraged because you will leak your AWS credentials and effectively you give your account away.

**Comment by JonnyBurger** [comment]
Leaving the issue open so we can clarify the docs.

**Comment by JonnyBurger** [comment]
I see, then the error is coming from somewhere different - you are using a framework like Next.js which bundles the backend code with Webpack.

We can actually expose `getAwsClient()` in `@remotion/lambda/client` which does not contain any code that cannot be bundled. Implementing this in #3096
