### ISSUE TITLE
Transparent gif export

### ISSUE THREAD

**Issue by peteruithoven** [remotion-dev/remotion#3099]
# Feature Request 🛍️
Being able to export transparent gif's. 
Currently, after creating an animation without a background, where you can see the checkerboard, after export / render the gif suddenly has a black background.

Support for transparency might be good to clarify in the docs, like on the following page 
https://www.remotion.dev/docs/render-as-gif

## Use Case
I want to create a simple ping animation for use inside Figma, but the black / non transparent background makes it unusable. 
GIF: 
![ping](https://github.com/remotion-dev/remotion/assets/523210/c2e7ef81-5ac7-4991-8982-d13a838e03c8)

Webm with transparency based on [Transparent videos](https://www.remotion.dev/docs/transparent-videos/#creating-a-webm-video-with-alpha-channel):
[Ping.webm](https://github.com/remotion-dev/remotion/assets/523210/fde27ef7-171b-4108-8e9e-e78edea75bba)

Note that simply using the webm video in Figma [currently doesn't work](https://forum.figma.com/t/prototyping-with-transparent-videos/45610/2). 

## Possible Solution
Support gif's without an explicit background color to be transparent by default?

**Comment by JonnyBurger** [comment]
Thanks for the suggestion! This is already filed in #2805, please follow this issue.

It's a good issue for Hacktoberfest actually, we'll fund the issue.

**Comment by peteruithoven** [comment]
Ah apologies for opening a duplicate. I did search al the open discussions, as I assumed feature requests would end up there. I should have also searched in the issues.

**Comment by JonnyBurger** [comment]
No problem!
