### ISSUE TITLE
Composition id can only contain a-z, A-Z, 0-9 and -

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3101]
### Discussed in https://github.com/orgs/remotion-dev/discussions/3100

<div type='discussions-op-text'>

<sup>Originally posted by **winner106** October 31, 2023</sup>
Can I set IDs in different languages, or can I display names in multiple languages ​​in the remotion studio? This would be more humane</div>

**Comment by JonnyBurger** [comment]
@winner106 Yes, this is an oversight. Can you suggest a regex adding more URL-safe characters? The current one is `/^([a-zA-Z0-9-])+$/g`.

**Comment by winner106** [comment]
perhaps id should not modify its regex, but add one more optional alias property to show on the page

**Comment by winner106** [comment]
Understood, so what characters are disallowed? Maximum flexibility can be achieved by setting a reverse regularity to disallow disallowed characters. For example, support for Chinese, Japanese and other languages

**Comment by JonnyBurger** [comment]
@winner106 Since there are like a million characters in Unicode and many of them will cause problems in the URL, I would like to not do that. How about we allow all CJK characters in the Regex as well?
