### ISSUE TITLE
Is it possible for developers to run node fs functions in the remotion?

### ISSUE THREAD

**Issue by anjalipandith** [remotion-dev/remotion#3109]
I understand that remotion is build using react, but it mostly runs locally.
Is there a way to use node fs functionalities in the remotion component?
This gives features like "ability to read images/files from the local directories using the react code".
Like electronjs.

Thanks

**Comment by JonnyBurger** [comment]
There is no way because web browsers don't have access to the file system.

We expose the `public` folder via HTTP server though - you can import those assets like this: https://www.remotion.dev/docs/assets
