### ISSUE TITLE
Configuration file `remotion studio` set default browser to open

### ISSUE THREAD

**Issue by shipurjan** [remotion-dev/remotion#3123]
# Feature Request 🛍️

Currently there exists option setBrowserExecutable(), but it seems that it only affects the browser used for `remotion render` command. I would like to have a similar command, but for the `remotion studio` command.

## Use Case

I would like to set (for example) the downloaded Thorium for my development browser as well without changing my default browser settings and the `remotion studio` command should open the selected executable instead of my default browser.

**Comment by shipurjan** [comment]
Okay I think it's not necessary, since it's possible to do this through environment variables:

.env
```
BROWSER="C:/Users/.../node_modules/.remotion/.thorium/win64/BIN/thorium.exe"
```

**Comment by JonnyBurger** [comment]
Right, thanks for answering it yourself! 🙌
