### ISSUE TITLE
I am using windows 11 and i have RTX 3060Ti graphic card, but "npx remotion gpu" command is not showing correctly

### ISSUE THREAD

**Issue by anjalipandith** [remotion-dev/remotion#3182]
Hi Remotion Team

I am using windows 11 and i have RTX 3060Ti graphic card, but "npx remotion gpu" command is not showing correctly
here is the output

PS F:\work\projectwindows\ytui\myvid> npx remotion gpu
Canvas: Software only, hardware acceleration unavailable
Canvas out-of-process rasterization: Disabled
Direct Rendering Display Compositor: Disabled
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
OpenGL: Disabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Skia Graphite: Disabled
Video Decode: Software only. Hardware acceleration disabled
Video Encode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable
WebGPU: Software only, hardware acceleration unavailable

PS F:\work\projectwindows\ytui\myvid> Get-WmiObject win32_VideoController | Format-List Name
Name : NVIDIA GeForce RTX 3060 Ti

If i install ubuntu, will it identify my gpu?

Or is this expected output?
Thanks

**Comment by JonnyBurger** [comment]
Hi Anjali!

To pick up the GPU, you probably need to pass a `--gl` flag. This flag should be passed to both the `npx remotion gpu` command as well as to the `npx remotion render` command.

If you are planning on using the GPU, please also read: https://www.remotion.dev/docs/gpu

We should update the docs to clarify this, it is very confusing.

**Comment by anjalipandith** [comment]
Thanks
I got it

/f/work/projectwindows/ytui/myvid (master)
$ npx remotion gpu --gl angle
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Enabled
Direct Rendering Display Compositor: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
OpenGL: Enabled
Rasterization: Hardware accelerated
Raw Draw: Disabled
Skia Graphite: Disabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
WebGPU: Hardware accelerated
