### ISSUE TITLE
DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

### ISSUE THREAD

**Issue by xixino** [remotion-dev/remotion#3188]
`D:\remotion-template-audiogram>npm run build

> remotion-template@1.0.0 build
> remotion render Audiogram out/video.mp4

(1/3) ╭───────────────────╮ Bundled code 961ms
Composition = Audiogram (Passed as argument), Codec = h264 (derived from out name), Output = out/video.mp4
(2/3)                       Rendering frames (1x) 0/885
(3/3)                       Encoding video 0/885
DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

D:\remotion-template-audiogram>npm start

> remotion-template@1.0.0 start
> remotion studio

Server ready - Local: http:localhost:3000, Network: http:172.17.128.1:3000
Built in 1677ms
(node:17584) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17584) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
╭─ Starting render
│ (1/3) ╭───────────────────╮ Bundled code 330ms
│ Composition = Audiogram (via UI), Codec = h264 (via UI), Output = out/Audiogram.mp4
│ (2/3)                       Rendering frames (1x) 0/885
│ (3/3)                       Encoding video 0/885╰─  Failed to render
DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data
`
Thank for all you done! I don't know how to solve it.
![image](https://github.com/remotion-dev/remotion/assets/72537603/2e4f4997-7c68-4021-927c-9a7bb99438f3)

**Comment by JonnyBurger** [comment]
Is this the default Audiogram template, and if not, what modifications did you make to it?
It would be helpful to see how you are including the audio.

**Comment by JonnyBurger** [comment]
Unfortunately I was not able to reproduce the issue with:

```
npm init video # Select audiogram
cd audiogram
npm run build
```

The video renders fine.
I need a better reproduction in order to investigate the issue.

**Comment by JonnyBurger** [comment]
(It also works with the render button)

**Comment by JonnyBurger** [comment]
Sorry, I cannot reproduce it still. Tried on Windows as well.
Are there any other factors in your environments that could play a factor? 
A special browser? Some extensions in it? A firewall or VPN?

> it works,but i run this [project,it](https://github.com/marcusstenbeck/remotion-template-audiogram.git) does't work.

This ia actually the same code, so that is another strange thing about it.

**Comment by JonnyBurger** [comment]
Oh thanks for letting us know! This is not the first time this thing has caused some trouble 😐 We'll inform other in the future if they have this problem.
