### ISSUE TITLE
Pixel format was set to 'yuva420p' but codec is not 'vp8' or 'vp9'. 

### ISSUE THREAD

**Issue by peteruithoven** [remotion-dev/remotion#3208]
# Bug Report 🐛
After selecting Gif as the codec in the Render menu I'm getting the following error:

> Pixel format was set to 'yuva420p' but codec is not 'vp8' or 'vp9'. 

Maybe the Pixel format list should be filtered by the currently selected codec? 

![Screenshot from 2023-11-23 10 09 39@2x](https://github.com/remotion-dev/remotion/assets/523210/fe904d05-6f95-4ae4-b58e-cc76c3928e71)

**Comment by JonnyBurger** [comment]
True, adding that, in the future we probably need to be less lenient but the alpha pixel formats are now excluded for VP8 and VP9
