### ISSUE TITLE
Update codec transparency info?

### ISSUE THREAD

**Issue by peteruithoven** [remotion-dev/remotion#3209]
# Bug Report 🐛
With the great improvement of https://github.com/remotion-dev/remotion/pull/3204, supporting transparent gifs, the following codec info is out of date. 
![Screenshot from 2023-11-23 10 10 29@2x](https://github.com/remotion-dev/remotion/assets/523210/4d2716d6-d726-46ae-ad4b-8d1c263c4a88)

**Comment by JonnyBurger** [comment]
Thanks for reporting!
