### ISSUE TITLE
Inaccurate Frame Rate Calculation in getVideoMetadata Function

### ISSUE THREAD

**Issue by xvoorvaa** [remotion-dev/remotion#3210]
# Bug Report 🐛

**Summary:**
When using the `getVideoMetadata` function on a video with an FPS (frames per second) of 29.999162, the function unexpectedly returns 46,254,000 frames, which is an extraordinarily high and incorrect number. This suggests a possible issue with how `getVideoMetadata` handles floating-point numbers for FPS values.

**Details:**
- **Expected Behavior:** The function should return a sensible frame count based on the video's FPS. Common expectations would be a frame rate close to 29, 30, or the exact FPS value of 29.999162.
- **Actual Behavior:** Instead of a reasonable frame rate, `getVideoMetadata` returns 46,254,000 frames, indicating a potential problem in the function's calculation or float handling mechanism.

**Screenshots:**
![Metadata with Incorrect Frame Count](https://github.com/remotion-dev/remotion/assets/56308735/197d9668-58a2-4ee4-a1f5-829c77d35ef2)
![Additional Screenshot Indicating Issue](https://github.com/remotion-dev/remotion/assets/56308735/b07a0dcc-433f-46de-91bf-3c31d252fa96)
You can download the video here:
https://lp-playback.com/hls/e672so6btugw9eap/video

I am using the latest Remotion (v4.0.74)

**Comment by JonnyBurger** [comment]
Thanks for reporting!

**Comment by JonnyBurger** [comment]
I could not download your video, but am still confident that the fix is real.
