### ISSUE TITLE
Return `pixelFormat` in `getVideoMetadata()`

### ISSUE THREAD

**Issue by carlesfernandeztena** [remotion-dev/remotion#3216]
Currently, we need to explicitly state if the source video is transparent in `OffthreadVideo`.
This sometimes causes problems, as video containers such as `.mov` can have or not have an alpha channel.

# Feature Request 🛍️
It would be very useful to detect whether a video has or not transparency, without requiring this explicit information from the user.

## Use Case
That would enhance support and generalization for different video encodings, especially when we don't know beforehand which types of videos are we going to receive.

## Possible Solution
A feature could be implemented to detect whether a video has a transparency channel or not in the already existing function [get-video-metadata](https://www.remotion.dev/docs/renderer/get-video-metadata).

**Comment by JonnyBurger** [comment]
## Acceptance criteria

Analogue to https://github.com/remotion-dev/remotion/pull/2809, implement another field that gets returned in `getVideoMetadata()` called `pixelFormat`. At least the pixel formats that Remotion knows (https://www.remotion.dev/docs/config#setpixelformat) should be recognized and be a possible return value. Unknown and rare pixel formats should return `"unknown"` for now.

Also extend the unit test and document the new field in the docs, like it was done in #2809.

## Hints

See here how to work with Rust code: https://www.remotion.dev/docs/contributing/rust

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 150

**Comment by JonnyBurger** [comment]
Good luck @mrkirthi-24!

FYI, I might take a bit longer to review this PR this time since we are in the hot phase of GitHub Unwrapped.

**Comment by mrkirthi-24** [comment]
@JonnyBurger 👍

**Comment by mrkirthi-24** [comment]
I would like to unassign myself as its beyond my scope.

**Comment by jkcs** [comment]
@JonnyBurger I can be assigned to this?
/attempt #3216

**Comment by JonnyBurger** [comment]
Sure, good luck! @jkcs

**Comment by JonnyBurger** [comment]
![image](https://github.com/remotion-dev/remotion/assets/1629785/dcea3832-7de5-4f17-8a06-00dd09f64ca2)

Here is how to get the pixel format in the existing implementation

**Comment by JonnyBurger** [comment]
@carlesfernandeztena Will release this feature now!
To check if Remotion considers a pixel format transparent, check if it is one of `yuva420p`, `yuva444p10le` or `yuva444P12le`

**Comment by carlesfernandeztena** [comment]
Great! Thank you team!
