### ISSUE TITLE
I face delayRender issue a lot! how to fix it?

### ISSUE THREAD

**Issue by astarsecurity** [remotion-dev/remotion#3222]
Hello I face delayRender error issue a lot of times.
It occurs when Encoding video freezed during Rendering frames.
I changed --concurrency from 8 to 4 or 2 at command, then it fixed first time.
However delayRender error occurs again.
Anybody help to fix it?

I'm using i7-13700K cpu and nvidia 3090ti GPU

below is my cli screen from code-server

# Bug Report 🐛

(venv) ubuntu@localmachine:~/code-dist/mp4worker/videoEncoder$ npm run build

> videoEncoder@1.0.0 build
> remotion render --gl=angle --concurrency=2 HelloWorld out/video.mp4

(1/3) ╭───────────────────╮ Bundled code 453ms
    + ╭───────────────────╮ Copying public dir 124ms
Composition = HelloWorld (Passed as argument), Codec = h264 (derived from out name), Output = out/video.mp4
(2/3) ╭─────────────────╴   Rendering frames (2x) 2639/3000
    + ╭───────────────────╮ Downloading 8 files
(3/3) ╭────────             Encoding video 1206/3000
💡 Get help for this issue at https://remotion.dev/docs/timeout

An error occurred while rendering frame 2501:
 Error  A delayRender() was called but not cleared after 28000ms. See https://remotion.dev/docs/timeout for help. 

at node_modules/remotion/dist/cjs/delay-render.js:46
44 │         ]
45 │             .filter(truthy_js_1.truthy)
46 │             .join(' ');
47 │         throw new Error(message);
48 │     }, timeoutToUse),
49 │ };

🕧 The delayRender() call is located at:

at node_modules/remotion/dist/cjs/delay-render.js:29
27 │ const handle = Math.random();
28 │ handles.push(handle);
29 │ const called = (_b = (_a = Error().stack) === null || _a === void 0 ? void 0 : _a.replace(/^Error/g, '')) !== null && _b !== void 0 ? _b : '';
30 │ if ((0, get_remotion_environment_js_1.getRemotionEnvironment)().isRendering) {
31 │     const timeoutToUse = typeof window === 'undefined'
32 │         ? defaultTimeout

at src/HelloWorld/RemotionOffthreadVideo.jsx:17
15 │  const [duration, setDuration] = useState<null | number>(null);
16 │  const [videoWidth, setVideoWidth] = useState<number | null>(null);
17 │  const [handle] = useState(() => delayRender());
18 │  const { fps, width: viewportWidth } = useVideoConfig();
19 │ 
20 │  useEffect(() => {
at qi [as useState] (node_modules/react-dom/cjs/react-dom.production.min.js:175)
at exports.useState (node_modules/react/cjs/react.production.min.js:25)

at src/HelloWorld/RemotionOffthreadVideo.jsx:17
15 │  const [duration, setDuration] = useState<null | number>(null);
16 │  const [videoWidth, setVideoWidth] = useState<number | null>(null);
17 │  const [handle] = useState(() => delayRender());
18 │  const { fps, width: viewportWidth } = useVideoConfig();
19 │ 
20 │  useEffect(() => {
at Xh (node_modules/react-dom/cjs/react-dom.production.min.js:167)
at Wk (node_modules/react-dom/cjs/react-dom.production.min.js:290)
at Vk (node_modules/react-dom/cjs/react-dom.production.min.js:280)
at Uk (node_modules/react-dom/cjs/react-dom.production.min.js:280)
at Jk (node_modules/react-dom/cjs/react-dom.production.min.js:280)
at (node_modules/remotion/dist/cjs/delay-render.js:47)

**Comment by JonnyBurger** [comment]
The timeout occurs because the handle at

> 17 │ const [handle] = useState(() => delayRender());

is not being continued in time. It is not clear from the issue what the handle does exactly.
It could be due to resource congestion though - I see you are on Linux, which by default runs in `--single-process` mode. 

You could try if enabling this flag https://www.remotion.dev/docs/miscellaneous/linux-single-process helps you. Otherwise, please post the code that is supposed to resolve the delayRender() call.

**Comment by astarsecurity** [comment]
I am using <OffthreadVideo> component from Remotion, and I guess it possibly cause this issue from documentation what you gave.

**Comment by JonnyBurger** [comment]
To get the video dimensions, a video tag must be mounted. This code gets executed in every tab that is opened, when the concurrency is 8x, then 8 video tags are mounted.

Depending on the system, Chrome will not like that and start throttling the operations, leading to a timeout.

Our recommendation is to instead do this calculation in calculateMetadata() and pass down the results as props to the component: https://www.remotion.dev/docs/dynamic-metadata#using-the-calculatemetadata-function

That way the video tag only gets mounted once and you should not have any problems.

**Comment by astarsecurity** [comment]
Thank you for your help! Your solution works very much
