### ISSUE TITLE
console.log in production ESM module

### ISSUE THREAD

**Issue by apolubek** [remotion-dev/remotion#3230]
# Bug Report 🐛

Hey! In npm dist ESM package starting from version 4.0.73, there's unnecessary `console.log` inside `useMediaPlayback` hook which makes multiple logs even on production (I'm using `@remotion/player` on a website).
You can see it using package browser on npmjs inside `/remotion/dist/esm/index.mjs` file.
1. https://www.npmjs.com/package/remotion/v/4.0.73?activeTab=code
2. https://www.npmjs.com/package/remotion/v/4.0.74?activeTab=code

<img width="787" alt="Screenshot 2023-11-27 at 16 45 41" src="https://github.com/remotion-dev/remotion/assets/75372400/2b44732d-9e3d-4677-8891-8bfb51968a52">

<img width="963" alt="Screenshot 2023-11-27 at 16 51 50" src="https://github.com/remotion-dev/remotion/assets/75372400/72fba035-c722-414a-af70-fa4631dda0bb">

Problem doesn't occur using version 4.0.72.

**Comment by JonnyBurger** [comment]
Thanks a lot for reporting!
This will be fixed in v4.0.75 and we added rules so that this cannot be committed again.
