### ISSUE TITLE
Add support for absolute file paths

### ISSUE THREAD

**Issue by yarrichar** [remotion-dev/remotion#3244]
# Feature Request 🛍️

I need to be able to work with files from arbitrary locations on disk, not just the public directory.

## Use Case

I am making a desktop app that makes it possible to create derivative videos based on videos users have locally. Elements to include in the video could come from several different locations on disk.

I also don't want to copy everything to the public directory since in some instances the source video(s) could be very large.

## Possible Solution

I'm not sure what the implementation should be since I'm not sure why this restriction is there to be begin with :)

**Comment by JonnyBurger** [comment]
We wrote down why Remotion doesn't/can't support it: https://www.remotion.dev/docs/miscellaneous/absolute-paths

In this case, I would suggest to you to serve the files via your own HTTP server.

**Comment by JonnyBurger** [comment]
You didn't miss it! I wrote it yesterday because it is a common question 🙂
