### ISSUE TITLE
Milliseconds calculated wrong in Remotion Studio

### ISSUE THREAD

**Issue by tpetry** [remotion-dev/remotion#3245]
The millisecond calculation based on the current frame is incorrect: One second has 1000 milliseconds. So if a video has 60 fps and the current frame is 30, it is currently half of a second. So 500ms.

But the remotion studio is showing 00:00.**30** indicating that the milliseconds are calculated based on a 60 range.

![CleanShot 2023-12-02 at 19 13 45](https://github.com/remotion-dev/remotion/assets/315686/7a382bd6-f9b7-46da-ae92-f0013fca91ab)

**Comment by JonnyBurger** [comment]
This is intended, and actually the same way that the most popular video editing programs display the time value. See a comparison here: https://github.com/remotion-dev/remotion/issues/694#issuecomment-968318664
