### ISSUE TITLE
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.

### ISSUE THREAD

**Issue by winner106** [remotion-dev/remotion#3246]
In Remotion Studio, The following error occurred in the browser

![image](https://github.com/remotion-dev/remotion/assets/50519642/2185d126-2bca-4e93-98cb-50deb0f636b2)
![image](https://github.com/remotion-dev/remotion/assets/50519642/efbce078-8625-41b4-b22f-c6589838aa6b)

Maybe it's related to this:

[https://stackoverflow.com/questions/61341666/validatedomnesting-button-cannot-appear-as-a-descendant-of-button](https://stackoverflow.com/questions/61341666/validatedomnesting-button-cannot-appear-as-a-descendant-of-button)

**Comment by JonnyBurger** [comment]
This is fixed as of 4.0.76!
