### ISSUE TITLE
`search` function in remotion studio Composition list

### ISSUE THREAD

**Issue by winner106** [remotion-dev/remotion#3247]
# Feature Request 🛍️

When there are a lot of `Compositions` in the remotion studio, you need to expand them step by step to find the target compositions, which is very troublesome. If there is a search function, it will save a lot of time.

Thanks for all the great work.

**Comment by JonnyBurger** [comment]
You can do so by invoking the Quick Switcher using Ctrl+K or Cmd+K! https://www.remotion.dev/docs/studio#quick-switcher
