### ISSUE TITLE
Can’t easily change the scale of a render

### ISSUE THREAD

**Issue by guillaumebrunerie** [remotion-dev/remotion#3251]
# Bug Report 🐛

In the Remotion Studio:
- click on "Render"
- click on "Picture"
- click on the "1.0x" next to "Scale"
- enter "0.5"
- press Enter

For some reason, this sets the scale to "0.1x" instead of "0.5x". The only way I found to be able to get 0.5x scale is to click and drag until I reach exactly 0.5x, which is significantly more annoying than being able to just type the number.

**Comment by JonnyBurger** [comment]
Thanks for reporting!
