### ISSUE TITLE
Case where Audio doesn't immediately play when mounted

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3253]
[From message posted on Discord by **raxrb**](https://discord.com/channels/809501355504959528/1177332819085774919/1179131781560156330)
----
Issue 3

I have an existing Audio getting played and I start another audio after delay in a new Audio tag it cut the exsiting Audio in between.

Both the audio files are prefetched when the components mount, ruling out the possibilty of network latency.

https://drive.google.com/file/d/1RVJt2w4yMHiM4h4qyJb_4ReS3vDC9VzA/view

Start from time stamp 10 seconds, Audio for prouncing the name Barthomolew is cut in half when the background music starts playing.
It does not occur always though.

This is the URL for playing it https://remotion-983bf.web.app/?firstName=Bartholomew&keyword=AI&company=ScaleFaster
  

Video Number 2 , the audio is getting cut at other locations.

https://drive.google.com/file/d/1PQbKobK4Y1nz6y3mw_v8Rmth7PKTV5xB/view

Check at timestamp 10 seconds.

I have also invited you to the remotion-jonathan github to help you view the code.

**Comment by rajaman0** [comment]
Also experiencing this one - find it similarly flaky

**Comment by JonnyBurger** [comment]
Fixed as of https://github.com/remotion-dev/remotion/pull/3888

`pauseWhenBuffering` should be added to the Audio + Video + OffthreadVideo tags now
