### ISSUE TITLE
Getting a different shade of green when rendering to a video

### ISSUE THREAD

**Issue by guillaumebrunerie** [remotion-dev/remotion#3263]
# Bug Report 🐛

I’m having a curious issue, when rendering my composition to a video, it slightly modifies one of my colors. More specifically, with the following composition:
```js
export const Test = () => {
    return (
        <AbsoluteFill style={{backgroundColor: "#008800"}}/>
    )
};
```
If I render it to either H.264 or VP8, I get a rectangle with color `#007300` instead of the expected `#008800`, which is noticeably different. The color is the correct one in the Studio and when taking stills, but not for rendered videos.

Is this normal?
I’m on Ubuntu, and I don’t have any special settings otherwise.

**Comment by JonnyBurger** [comment]
This in itself is normal, when encoding to a video, a lossy conversion from RGB to YUV is happening.
You will also see a different color just based on which browser you use 🙈

https://www.mux.com/blog/your-browser-and-my-browser-see-different-colors

This in itself is expected and it's out of our control to fix entirely. There are more technical discussions about the correct color spaces which are more actionable: #2936
