### ISSUE TITLE
remotion/google-fonts: Expose loadFont promise

### ISSUE THREAD

**Issue by slowbaker** [remotion-dev/remotion#3268]
The player has a Flash Of Unstyled Content (FOUC) when the user can dynamically change the font with a font selector (`fontInfo.loadFont()`).

This can be mitigated by exposing the FontFace promise:

```diff
// remotion/packages/google-fonts/src/base.ts

-- export const loadFonts = (
++ export const loadFonts = async (

// ...

-- fontFace
--  .load()
--  .then(() => {
--    (options?.document ?? document).fonts.add(fontFace);
--    continueRender(handle);
--  })
--  .catch((err) => {
--    //  Mark font as not loaded
--    loadedFonts[fontKey] = false;
--    throw err;
--  });

++ try {
++  await fontFace.load();
++  (options?.document ?? document).fonts.add(fontFace);
++  continueRender(handle);
++ } catch (err) {
++  //  Mark font as not loaded
++  loadedFonts[fontKey] = false;
++  throw err;
++ }
```

Having the promise enables us to handle various states in the font lifecycle (e.g., showing a loading indicator or waiting for the font to be ready before it gets applied)

**Comment by JonnyBurger** [comment]
Sounds good! We'll be looking to implment this suggestion.

**Comment by JonnyBurger** [comment]
Added in 22f4ae1a02204256bf70a672be24aeefd5b5cdb0

**Comment by JonnyBurger** [comment]
@slowbaker Thanks for letting me know! Fixed for the next version
