### ISSUE TITLE
Highlight Selected Composition in Compositions Panel when Found via Quick Switcher

### ISSUE THREAD

**Issue by winner106** [remotion-dev/remotion#3286]
I would like to suggest an enhancement for the Quick Switcher feature in the Compositions panel. 

Currently, when using the Quick Switcher search to find a specific composition, it does not provide any visual indication in the Compositions panel.

It would be helpful if, upon finding the target composition through the Quick Switcher, the corresponding composition in the Compositions panel is highlighted or selected. 

This visual cue would assist in quickly selecting other compositions within the same directory, improving the workflow efficiency.

Thank you for considering this enhancement request.

**Comment by JonnyBurger** [comment]
Thanks for this feature request - it is the intended behavior that the composition is selected, as is any other composition.

https://github.com/remotion-dev/remotion/assets/1629785/a654cd52-f24e-4939-9679-21bd637eaa85

Also, if the composition is in a folder, it should expand and be focused in the viewport.

Does this work for you? Anything you want to add in addition to this?

**Comment by winner106** [comment]
Thank you so much for implementing the feature request! I really appreciate your effort in making this happen. The feature works perfectly for me and fulfills all my requirements.

**Comment by JonnyBurger** [comment]
Nice!
Seems like all you need to do is upgrade then.

**Comment by winner106** [comment]
@JonnyBurger This feature has a bug, When the folder directory exceeds three levels, it will become invalid and the folder cannot be automatically expanded.

**Comment by winner106** [comment]
I would greatly appreciate it if the Quick Switcher could facilitate quick switching to folders. Currently, I am faced with a situation where there are over 200 compositions and about 4 layers of folders. Switching between them has become quite cumbersome. Would it be possible to consider this feature request?
