### ISSUE TITLE
Beep when a render is finished

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3296]
## Inspiration

Adobe Premiere 4.2 had a checkbox for making a sound when a render is finished.

<img width="515" alt="image" src="https://github.com/remotion-dev/remotion/assets/1629785/51614802-632e-4ab7-89ff-b5d6ca8d454d">

## Acceptance criteria

- In the Remotion Studio, add an option in the render dialogue to beep when a render is finished (default false)
- If the setting, is enabled, beep if the render is finished.
- We must be allowed to use the sound.

## Bounty

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 150

**Comment by JonnyBurger** [comment]
@mrkirthi-24 Good luck!
@DevGajjar28 Please stand by, thanks for your interest!

**Comment by mrkirthi-24** [comment]
The beep option should be added in other section, right??
![Screenshot 2023-12-25 at 10 59 49 AM](https://github.com/remotion-dev/remotion/assets/53830546/06f9a3e6-c471-455b-bde2-0a06faf17449)

**Comment by JonnyBurger** [comment]
Sounds good!

**Comment by mrkirthi-24** [comment]
While rendering test video, I am getting this error.
![Screenshot 2023-12-25 at 7 50 11 PM](https://github.com/remotion-dev/remotion/assets/53830546/4daab1af-39ed-400f-8182-0a67c7a958b5)

**Comment by JonnyBurger** [comment]
@mrkirthi-24 Oh weird! we should make a separate issue for this. Old macOS?

You should be able to test by rendering an image sequence instead or just a still!

**Comment by mrkirthi-24** [comment]
> @mrkirthi-24 Oh weird! we should make a separate issue for this. Old macOS?
Yeah using macOS Catalina 10.15

> You should be able to test by rendering an image sequence instead or just a still!
Thank you. I will give it a try

**Comment by mrkirthi-24** [comment]
@JonnyBurger The error still persists when rendering still or image sequence.

![Screenshot 2023-12-25 at 8 01 48 PM](https://github.com/remotion-dev/remotion/assets/53830546/ce03d8fd-4ccd-471f-aa70-a48eab0b56b9)

**Comment by mrkirthi-24** [comment]
@JonnyBurger Is there any other method I can use to test the alterations I've made?

**Comment by JonnyBurger** [comment]
the lowest I can set our compositor is unfportunately macOS `11.4.0` :(

It seems like the render nonetheless completes and this should also reflect in the browser, which then is not dependent on the crashing server anymore. Could you play the sound just then?

**Comment by mrkirthi-24** [comment]
> the lowest I can set our compositor is unfportunately macOS `11.4.0` :(
> 
> It seems like the render nonetheless completes and this should also reflect in the browser, which then is not dependent on the crashing server anymore. Could you play the sound just then?

Thank you for the help

**Comment by mrkirthi-24** [comment]
@JonnyBurger is there a specific sound file included in the package, or can I select any random file?

**Comment by JonnyBurger** [comment]
You can select a fitting sound, the requirement is that we are allowed to use it.

**Comment by PlanetKumbhaj** [comment]
ohk cool!

**Comment by mrkirthi-24** [comment]
> ohk cool!

I am about to complete it.
