### ISSUE TITLE
[Question] - AWS Lambda concurrency limit configuration

### ISSUE THREAD

**Issue by RukshanJS** [remotion-dev/remotion#3305]
Is there any way we can configure the number of `chunks` the video render will be split into? I'm asking because i want to trade-off the render speed for lambda concurrency limit. 

My understanding is that remotion will split the video into `chunks` to process the render parallelly, which is good, but in doing so it would exceed rate limits for some user accounts. 

Is there any way we can pre-define the `max_chunks` any video will be split into so that we can keep the render within the concurrency limits?

I have already requested aws to increase my quota, but i was wondering if this is possible or would be a nice feature.

More info,
https://github.com/remotion-dev/github-unwrapped-2023/issues/198

**Comment by JonnyBurger** [comment]
Yes, you can set the concurrency using `--frames-per-lambda`.

Example: You render a video that has a durationInFrames of 300 with a framePerLambda setting of 15. The concurrency is 300 / 15 = 20.

There is a calculator on: https://www.remotion.dev/docs/lambda/concurrency

**Comment by RukshanJS** [comment]
Yes that's what i wanted. Thanks a bunch!
