### ISSUE TITLE
Transitions make the elements unselectable by covering it

### ISSUE THREAD

**Issue by reactone** [remotion-dev/remotion#3312]
# Bug Report 🐛

Ive started playing around with transitions - they are very cool indeed. I have a bit of an issue however. When I wrap my elements with transitions they are displayed correctly. However, Ive implemented a feature where you can select the element to move it around using useDoubleTap hook. Ive noticed that the transitions somehow overlay those elements such that the elements are no longer selectable (although they are displayed correctly) Ive tried playing around with z-index of both TransitionsSeries and my component but it doesn't seem to solve the issue. Any advice would be appreciated.

@JonnyBurger 

Below you can see cloakWipe transition and my custom rectangle which no longer is selectable after wrapping it with TransitionSeries component.
![transitions-overlay](https://github.com/remotion-dev/remotion/assets/48355087/d1a96754-3009-4a18-836e-9ca8b0772cf7)

**Comment by JonnyBurger** [comment]
I'm adding props to every transition! `outerExitStyle` / `innerExitStyle` / `innerEnterStyle` / `innerExitStyle` / `enterStyle` / `exitStyle`.

You can pass `pointerEvents: "none"` to the container to make it not react to style changes.
Be advised that the entering scene always overlays the existing scene.


https://github.com/remotion-dev/remotion/pull/3322

**Comment by reactone** [comment]
> I'm adding props to every transition! `outerExitStyle` / `innerExitStyle` / `innerEnterStyle` / `innerExitStyle` / `enterStyle` / `exitStyle`.
 Great - thank you @JonnyBurger -  when is it going to be released so I can test it?

**Comment by JonnyBurger** [comment]
It's out now!
