### ISSUE TITLE
`deleteRender` is not available in `@remotion/lambda/client`

### ISSUE THREAD

**Issue by amirfakhrullah** [remotion-dev/remotion#3313]
I want to use `deleteRender` inside my serverless function but there's no `deleteRender` in `@remotion/lambda/client`. If I try to import `deleteRender` from `@remotion/lambda` instead, I will get this error:

![image](https://github.com/remotion-dev/remotion/assets/73758525/dc9b80bb-1036-469b-890f-314e9e02eaf3)

# Feature Request 🛍️

Include `deleteRender` in `@remotion/lambda/client`

## Use Case

Doing so, I can easily delete any render from my serverless endpoint.

**Comment by JonnyBurger** [comment]
You're right! Thanks for reporting https://github.com/remotion-dev/remotion/pull/3321
