### ISSUE TITLE
[feat] Make a Next.js + TailwindCSS template

### ISSUE THREAD

**Issue by polooner** [remotion-dev/remotion#3316]
As stated, I would love it if the Next.js template came in a TailwindCSS version as well. 

# Feature Request 🛍️

I am absolutely pro-Tailwind native for everything I do. I can make this PR myself as I'm switching the template to Tailwind right now. Why not also use shadcn/ui? ;)

## Use Case

Using Tailwind

**Comment by JonnyBurger** [comment]
Great idea! Also related: https://github.com/remotion-dev/remotion/issues/2320

I guess the dynamic way to do this is to codemod the project in the `create-video` package 🤔 but just adding it to the templates is also okay.
If you are up to it, then I am happy to accept a PR!

**Comment by polooner** [comment]
Great! So far I just made an ugly copy of the plain CSS Next.js app dir template. It was hard to navigate the tailwind plugin at first without examples I believe this might help others meanwhile until I'm done: https://github.com/polooner/remotion-template-next-app-dir-tailwind
