### ISSUE TITLE
Cannot import @remotion/transitions in backend

### ISSUE THREAD

**Issue by WilliamTraoreee** [remotion-dev/remotion#3333]
# I can't import anything from the @remotion/transitions package

I have this issue only with Transitions but I can't import `TransitionsSeries` or the effects `fade`, `wipe`... because it generate this error. I don't have any problem with the Player or Lambda, only with Transitions.

```
import { TransitionSeries } from "@remotion/transitions";
         ^^^^^^^^^^^^^^^^
SyntaxError: Named export 'TransitionSeries' not found. The requested module '@remotion/transitions' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@remotion/transitions';
const { TransitionSeries } = pkg;
```

**Comment by JonnyBurger** [comment]
Thanks for reporting!

**Comment by JonnyBurger** [comment]
It is a bit more complicated... this might be a workaround:

```tsx
import {TransitionSeries} = require("@remotion/transitions")
```

**Comment by WilliamTraoreee** [comment]
> It is a bit more complicated... this might be a workaround:
> 
> ```tsx
> import {TransitionSeries} = require("@remotion/transitions")
> ```

It doesn't seem to work for me.
I added a `"type": "module"` in the package.json at the moment, which seems to pass the time for me to develop my app

**Comment by JonnyBurger** [comment]
@WilliamTraoreee Will be properly fixed in the next version!
