### ISSUE TITLE
Over-aggressive Credentials Checking

### ISSUE THREAD

**Issue by shellscape** [remotion-dev/remotion#3362]
# Bug Report 🐛

When calling the lambda methods of `@remotion/lambda`, the code is overly aggressive in checking for AWS credentials, and doesn't take into account local AWS profiles. We're attempting to run test scripts locally, where we all use AWS profiles. Because we're using profiles, we don't have the need to specify environment variables for working with our development AWS account. This makes the environment variable requirements of remotion redundant. 

Additionally, the `getCredentials` method considers whether or not it's within a lambda https://github.com/remotion-dev/remotion/blob/d20f5db319d56f0c9c9152680dfc03c431ae4893/packages/lambda/src/shared/aws-clients.ts#L36, but `checkCredentials` doesn't consider this. 

Overall, it doesn't look as if the authors considered using the `@remotion/lambda` API directly in the design of these checks. Rather, assumed that this would only be consumed by the CLI and in an environment where credentials always had to be passed. In our setup, the code calling to `@remotion/lambda` directory has the appropriate permissions to call the deployed remotion lambda, and there's no need to specify any further credentials. I'd like to see a few changes made here that would create a much better DX:

- ability to bypass `checkCredentials`, where the developer already knows the code will run in an environment which has access
- `checkCredentials` considering that it is running within a lambda
- `checkCredentials` looking for and parsing an AWS profile (same would go for `getCredentials`
- allow the aws-sdk to use the local profile without intervention/overriding

_Edit:_

I wanted to add that while remotion will look at and load a profile if `AWS_PROFILE` is specified https://github.com/remotion-dev/remotion/blob/d20f5db319d56f0c9c9152680dfc03c431ae4893/packages/lambda/src/shared/aws-clients.ts#L70, that's not required by the aws-sdk itself. The aws-sdk will automatically load a profile if it exists in `$HOME/.aws/profile`.

**Comment by JonnyBurger** [comment]
Thanks @shellscape for filing!
We can implement a credentials bypass, but it could also be possible to just recognize `$HOME/.aws/profile`.

However, I cannot find any resources about the `$HOME/.aws/profile` feature. How did you learn about this?

**Comment by shellscape** [comment]
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-where

> The AWS CLI stores sensitive credential information that you specify with aws configure in a local file named credentials, in **a folder named .aws in your home directory**. The less sensitive configuration options that you specify with aws configure are stored in a local file named config, also stored in the .aws folder in your home directory.

And re: aws-sdk automatically loading the profile: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html

**Comment by JonnyBurger** [comment]
I see `$HOME/.aws/credentials`, but not `$HOME/.aws/profile`.
I assume it was meant in a paraphrased way.

Do you want to review https://github.com/remotion-dev/remotion/pull/3363?

**Comment by shellscape** [comment]
Thanks, I was context switching too much. `credentials` is correct.

**Comment by shellscape** [comment]
@JonnyBurger 4.0.86 solves the use case for `~/.aws/credentials`. Thanks for getting that in. I still believe that a switch for turning off checking would be useful, but that's up to you all. I'm unblocked as of 4.0.86 though.

**Comment by JonnyBurger** [comment]
@shellscape Great to hear! We'll be quick to react if a case surfaces where we need further loosening.
