### ISSUE TITLE
Webpack config: Resolve ESM versions in Studio, but CJS in development

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3367]
Confusing for contributors:

`pnpm watch` will live-reload some modules, but not all of them. This is because of the deduplication we do here: https://github.com/remotion-dev/remotion/blob/742c525ea1e7abf3d3ae7f4f1749f7bad2a492d0/packages/bundler/src/webpack-config.ts#L151

It means we use the CJS version of Remotion, but the ESM versions of others. One needs to run pnpm build in this directory to fast refresh.

We should:

1. In general only load ESM for consumers
2. For contributors. load the CJS modules so they fast refresh as expected

The behavior should be identical.
We cannot switch to an ESM mode only because Docusaurus 2 doesn't load them correctly.

**Comment by kaf-lamed-beyt** [comment]
@JonnyBurger  If I were to choose to work on this... how would you suggest I go about it?

**Comment by JonnyBurger** [comment]
Hey @kaf-lamed-beyt! It's a very simple change for me to do, so I think I'm just gonna do it myself soon.. thanks for offering to help! Happy for it on other issues :)

**Comment by kaf-lamed-beyt** [comment]
Sounds good. I'll let you know when I find any other issue to work on.
