### ISSUE TITLE
Make Lambda Python SDK async

### ISSUE THREAD

**Issue by polvallverdu** [remotion-dev/remotion#3390]
# Feature Request 🛍️

## Use Case

Be able to use the remotion client for Python to render with AWS Lambda with asyncio.

## Possible Solution

Currently there is RemotionClient. Create a drop-in replacement called `AsyncRemotionClient` that uses aioboto3

I'm looking forward to opening a PR once I need the async client 100%, and get some free time.

**Comment by JonnyBurger** [comment]
Unfortunately the issue is stuck and we don't have expertise to implement it ourselves.

If you want to contribute this in the future, you are always welcome to!
