### ISSUE TITLE
Link deployed Studio URL in templates section

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3393]
- [x] [Hello World (TypeScript)](https://github.com/remotion-dev/template-helloworld)
- [x] [Hello World (JavaScript)](https://github.com/remotion-dev/template-helloworld-javascript)
- [x] [Blank](https://github.com/remotion-dev/template-empty)
- [x] [React Three Fiber](https://github.com/remotion-dev/template-three)
- [ ] [Text-to-Speech Template (Azure)](https://github.com/FelippeChemello/Remotion-TTS-Example)
- [ ] [Text-to-Speech Template (Google)](https://github.com/thecmdrunner/remotion-gtts-template)
- [ ] [Audiogram](https://github.com/marcusstenbeck/remotion-template-audiogram)
- [ ] [Skia](https://github.com/remotion-dev/template-skia)
- [x] [Tailwind](https://github.com/remotion-dev/template-tailwind)
- [x] [Music with Tone.JS](https://github.com/remotion-dev/tone-js-example)
- [x] [Animate a .glb model](https://github.com/remotion-dev/glb-example)
- [x] [Typewriter effect](https://github.com/remotion-dev/typewriter)
- [x] [D3.js](https://github.com/remotion-dev/d3-example)
- [x] [3D Text](https://github.com/JonnyBurger/3d-text)
- [ ] [Wavy TikTok Effect](https://github.com/JonnyBurger/wavy-meme)
- [ ] [Apple "Spring loaded" animation](https://github.com/JonnyBurger/spring-loaded)
- [ ] [ThreeJS particles demo](https://github.com/JonnyBurger/three-particles)
- [ ] [Text Morphing](https://github.com/JonnyBurger/morph-text)
- [ ] [Text warping](https://github.com/remotion-dev/text-warping)
- [ ] [Include GLTF models](https://github.com/JonnyBurger/remotion-three-gltf-example)
- [ ] [OpenGL transitions](https://github.com/JonnyBurger/remotion-gl-transitions)
- [ ] [Conference talk in React](https://github.com/pomber/record-talk-with-remotion)
- [ ] [Twitch stinger example](https://github.com/JonnyBurger/ledevevent-stinger)
- [ ] [Usage with Anime.JS](https://github.com/remotion-dev/anime-example)
- [ ] [Displaying a spinner while content is loading](https://github.com/remotion-dev/video-buffering-example)
- [ ] [Mapbox example](https://github.com/remotion-dev/mapbox-example)
- [ ] [Shader example](https://github.com/onion2k/a-roll)
- [ ] [Jump cuts without re-mounting](https://github.com/remotion-dev/video-with-jump-cuts)
- [ ] [Globe.gl example](https://github.com/alexfernandez803/remotion-globegl)
- [ ] https://www.remotion.pro/cube-transition
- [ ] https://www.remotion.pro/shapes
- [ ] GitHub Unwrapped 2023

## How can we promote our deploys
- For templates: Link the deployment preview on remotion.dev/templates
- For examples: Link the preview in addition to the source in remotion.dev/resources
- For examples: Put it as the link in the GitHub repo
- For store items: Link in the store page

## Don't deploy
- Stills template (already deployed on Heroku)
- [Conference talk in React #2](https://github.com/JonnyBurger/react-summit-talk) (too big)

**Comment by JonnyBurger** [comment]
Thanks!

**Comment by MehmetAdemi** [comment]
![Image](https://github.com/remotion-dev/remotion/assets/86873911/008f0252-3cb7-4a49-8f86-4675ca99bf20)

**Comment by MehmetAdemi** [comment]
@JonnyBurger 
Initially, you also thought of deploying items from the Remotion Store, correct? To make sure, potential customers might click the <Sequence> in the deployed Remotion Studio but won't be able to look at the code since the repo is private, correct? I'm asking because this behavior isn't working for the Watercolor Map, I can't click the <Sequence>: 
Remotion Store, Watercolor Map: https://www.remotion.pro/watercolor-map
Deployed Remotion Studio of Watercolor Map: https://watercolor-map.vercel.app/?/MapAnimation

Should I deploy other items in the Remotion Store?

**Comment by JonnyBurger** [comment]
@MehmetAdemi Yes, that is right, they won't be able to access a private repo, they'll get a 404 link.

That is fine for now
