### ISSUE TITLE
GCP Alpha generated .env file has bad double quotes

### ISSUE THREAD

**Issue by fruitybits** [remotion-dev/remotion#3396]
# Bug Report 🐛

When using Cloud Shell on Step 5 [Validate Permission Setup](https://www.remotion.dev/docs/cloudrun/setup) the .env has bad double quotes.

**Error from local terminal when running npx remotion cloudrun permissions** - "Did not have the required permissions on GCP:
Error: 2 UNKNOWN: Getting metadata from plugin failed with error: error:1E08010C:DECODER routines::unsupported"

**Fix** - Remove double quotes around `REMOTION_GCP_CLIENT_EMAIL` value in .env

Installer / docs need an update!

**Comment by JonnyBurger** [comment]
I see, thanks for reporting!

Fixing in #3400. Curiously I also have double quotes in my env file and don't get the problem.
I am using macOS, I'm curious if you use a different OS?

In any case, removing the double quotes now.
