### ISSUE TITLE
Propose Remotion to be detected as a framework on Vercel

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3403]
Currently you need to configure a Vercel build

But we could send a PR to vercel/vercel to recognize remotion.config.ts and prefilling the values

![image](https://github.com/remotion-dev/remotion/assets/1629785/643b2c3b-57c0-4fa2-811b-5dd219205855)

**Comment by Just-Moh-it** [comment]
@JonnyBurger up for grabs? could work on it over the weekend if it's as simple as it sounds 😄

**Comment by JonnyBurger** [comment]
Hey @Just-Moh-it!

I have a very specific pitch in mind where I want to post all the use cases and merits of having this in the PR.  
This is also the reason I waited, because we have now deployed all examples on Vercel as of just a week ago. I'm now ready to do the pitch.

Can I for this reason do it myself? 🙂 Appreciate your willingness a lot though!

**Comment by JonnyBurger** [comment]
Discussion: https://github.com/orgs/vercel/discussions/6175
PR: https://github.com/vercel/vercel/pull/11298
