### ISSUE TITLE
Problem with Player

### ISSUE THREAD

**Issue by ilievkristian** [remotion-dev/remotion#3412]
I wanted to integrate a Remotion video inside my React app via Player component but I've got a JS error:

**Uncaught SyntaxError: missing ) after argument list**

After trying out couple of your demos the problem was still occuring so I tried to downgrade the version of the player + entire remotion (I was with the newest one 4.0.97) which also didn't work out and randomly installed an really older version from 6 months before - 4.0.18 and then everything compiled and worked out perfectly.

# Bug Report 🐛

**Comment by JonnyBurger** [comment]
Hey @ilievkristian!

Can you also post the code that leads to this problem, and the stack trace of the error. Otherwise I don't know where to start

**Comment by ilievkristian** [comment]
> Member

Hey there, @JonnyBurger 

Inside of "src" directory of my app I have "remotion" directory with the following files and their content:


MyComp.tsx
--------------
export const MyComp: React.FC<{ text: string }> = ({ text }) => {
  return <div>Hello {text}!</div>;
};

_________________________________________________________
Root.tsx
-------------
import { Composition } from "remotion";
import { MyComp } from "./MyComp";

export const MyVideo = () => {
  return (
    <>
      <Composition
        component={MyComp}
        durationInFrames={120}
        width={1920}
        height={1080}
        fps={30}
        id="my-comp"
        defaultProps={{ text: "World" }}
      />
    </>
  );
};

_________________________________________________________

index.ts
-------------
import { registerRoot } from "remotion";
import { MyVideo } from "./Root";

registerRoot(MyVideo);

_________________________________________________________

More info:

Uncaught SyntaxError: missing ) after argument list (at @remotion_player.js?v=ec49281c:2849:21)

<img width="267" alt="image" src="https://github.com/remotion-dev/remotion/assets/131285424/6699aaf5-8bdb-426b-af40-fd4456824caf">

**Comment by JonnyBurger** [comment]
Thanks, will be fixed for next release!
