### ISSUE TITLE
Steps for deploying Remotion Studio on Railway for cost-effective scaling.

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3419]
[From message posted on Discord by **mackeshots**](https://discord.com/channels/809501355504959528/817306238811111454/1200430862630658078)
----
## How to deploy Remotion Studio on Railway

Why? Railway scales up/down with resource usage. So if the app isn't used it'll be cheap, or even free.

The Free plan is enough. The Pro plan scales up to 32 vCPUs but Remotion Studio only seems to use up to ~6 vCPUs. The Free plan scales up to 8 vCPUs.

* Add the Dockerfile to the repo
* Click new project in the Railway dashboard
* Select "Deploy from GitHub repo"
* Select "Deploy now"

If you want a public URL
* Open up the settings for your service
* Scroll to "Networking"
* Click "Generate Doman" (or add a custom domain)

**Comment by marcusstenbeck** [comment]
The “Hobby” plan is the one I mean. It costs $5/mo + usage, and they include $5 usage pwr month for free. 

If you verify your account they waive the $5/mo fee, making it a free plan. See screenshots from my account. 

![IMG_0337](https://github.com/remotion-dev/remotion/assets/616906/d815f732-f738-49b3-8465-76e871bc6f24)
![IMG_0336](https://github.com/remotion-dev/remotion/assets/616906/cf986750-c0e5-448e-aa55-278f98d578e3)
