### ISSUE TITLE
Keyboard controls for player 

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#342]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/342)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($40.00)

### Submitted pull Requests
- [#505 [Player] Space key press to toggle play and pause if the video element is focused.](https://issuehunt.io/r/remotion-dev/remotion/pull/505)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by ashikmeerankutty** [comment]
@JonnyBurger  I would like to pick this up If you can provide me some context about what all things have to be done

**Comment by JonnyBurger** [comment]
Thanks again for the previous PR! This one is mainly being able to hit the space button to pause and play the video.

The main challenge is probably what happens if multiple players are on the page, there needs to be some kind of focus management.

Also there should be a prop to disable it if you want to use the player on the website and handle the space bar separately.

Thinking of it, there are no important keyboard shortcuts other than the space bar that I can think of.

**Comment by ashikmeerankutty** [comment]
The focus part seems to be a bit tricky rest is fine. I will try to figure out what kind of focus management is used in such cases   and let you know what can be done.

**Comment by JonnyBurger** [comment]
We also welcome an initial draft PR without the focus management. Any help is appreciated 🙌

**Comment by ashikmeerankutty** [comment]
Sure, I will start with the keyboard controls then and once everything works fine we can try the focus management.
