### ISSUE TITLE
After upgrading from `4.0.104` to `4.0.106` rendering got extremely slower

### ISSUE THREAD

**Issue by Dawsoncodes** [remotion-dev/remotion#3442]
After I upgraded my remotion packages from `4.0.104` to `4.0.106` rendering videos locally using the `renderMedia` function from the `@remotion/renderer` package got drastically slower.

I don't know what's the issue exactly, but the changes between those versions could have resulted in this problem.

**Comment by JonnyBurger** [comment]
Thanks for reporting!
That sheds some more light into the behavior of this flag, we are resolving it with #3443

**Comment by Dawsoncodes** [comment]
Upgraded it to `4.0.107` and I still have the same issue.

Are you sure it is not because of the `optimizeForSpeed: false` ?

**Comment by JonnyBurger** [comment]
@Dawsoncodes Oh yes that's it! Making another PR #3442

Thanks for letting us know
