### ISSUE TITLE
Audio track is not visible after update

### ISSUE THREAD

**Issue by riyasat** [remotion-dev/remotion#3463]
I updated remotion from 4.0.42 to 4.0.109 and now the audio track is not visible when I use startFrame or endFrame property.
# Bug Report 🐛
Steps to reproduce:
1. Create a new project `npm init video` 
2. Follow this tutorial https://www.remotion.dev/docs/using-audio
3. Use any staticFile from your local (Now, if you run `npm run start` , you will see audio track in the time line)
4. Now add `startFrom={60} endAt={120}` in the Audio Tag.
5. Now when you save and re-run the application, then the audio track will be removed from the track list but the name is still in the time line track list.

If I revert back to 4.0.42 then everything start working as expected

**Comment by JonnyBurger** [comment]
Thanks for reporting! This will be fixed in https://github.com/remotion-dev/remotion/pull/3466
