### ISSUE TITLE
npx render is erroring out with "Error: Error while downloading asset: Error: connect ECONNREFUSED ::1:3001"

### ISSUE THREAD

**Issue by anjalipandith** [remotion-dev/remotion#3471]
I have started the remotion studio "npm  start". Everything worked as usual.
When i tried to render it error out.
> remotion studio

Server ready - Local: http://localhost:3000, Network: http://192.168.0.149:3000
Built in 468ms
╭─ Starting render 
│ (1/3) ╭───────────────────╮ Bundled code 542ms
│ Composition = MyComp (via UI), Codec = h264 (via UI), Output = out/MyComp.mp4
│ (2/3) ╷                     Rendering frames (8x) 1/1060
│     + [0 B                ] Downloading http://localhost:3001/public/audio/ORendu.mp3
│ (3/3)                       Encoding video 0/1060╰─  Failed to render
Error: Error while downloading asset: Error: connect ECONNREFUSED ::1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
    at F:\bitbucket\new\lyricsremotion\gsaplyrics\node_modules\@remotion\renderer\dist\render│ (2/3) ╷                     Rendering frames (8x) 2/1060
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I m getting this error "Error: Error while downloading asset: Error: connect ECONNREFUSED ::1:3001"

<img width="446" alt="image" src="https://github.com/remotion-dev/remotion/assets/54518867/494674f3-851c-4b34-8a78-7e29a59e84dc">

Thanks
Anjali

**Comment by anjalipandith** [comment]
i used
			<Audio src={staticFile("/audio/ORendu.mp3")} />
to access the mp3 file

**Comment by JonnyBurger** [comment]
Hi Anjali!

I'm not sure why, I need to ask some questions:

- Which version of Windows is on this?
- Do you have any type of firewall?
- Which Remotion version (we fixed some of these bugs in the recent ones)
- Do you have Internet Download Manager installed?

**Comment by anjalipandith** [comment]
Hi Jonny

windows updated to latest : Windows 11, version 23H2
no firewall
remotion version:     "remotion": "4.0.110",

I used same code in mac m1 and it worked fine.
staticfile() function is trying to use localhost:port+1

Thanks
Anjali

**Comment by anjalipandith** [comment]
updating the npm to the latest and cleaning the npm cache helped the issue.

**Comment by anjalipandith** [comment]
update npm and that solved the issue

**Comment by TeamGreenheart** [comment]
+1 updating npm/node fixed this for me as well

**Comment by AmitDJagtap** [comment]
Still facing this issue.
```
>> npm run build

> autoeditor@1.0.0 build
> remotion render VideosConcat out/video.mp4

Bundled code         ━━━━━━━━━━━━━━━━━━ 1543ms
Copying public dir   ━━━━━━━━━━━━━━━━━━ 328ms 
Composition          VideosConcat
Codec                h264
Output               out/video.mp4
Concurrency          6x
Rendering frames     ━━━━━━━━━━━━━━━━━━    0/4500
Downloading assets   0 B                   1 file     
↓ 0 B      http://localhost:3000/public/warhammer1.mp4
Encoding video       ━━━━━━━━━━━━━━━━━━    0/4500Could not extract frame from compositor Error: connect ECONNREFUSED ::1:3000
 http://localhost:3000/proxy?src=http%3A%2F%2Flocalhost%3A3000%2Fpublic%2Fwarhammer1.mp4&time=0&transparent=false&toneMapped=true  Failed to load resource: the server responded with a status of 500 (Internal Server Error)



Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
    at execute (http://localhost:3000/bundle.js:8635:35)
```
