### ISSUE TITLE
Remote Studio won't reproduce sounds

### ISSUE THREAD

**Issue by loalf** [remotion-dev/remotion#3487]
I've just updated to the latest version of remotion and sound doesn't work 😢

**Comment by JonnyBurger** [comment]
You are right, we are fixing it in 4.0.113! Sorry about this

**Comment by loalf** [comment]
Thank you ever so much! You are amazing 😻

**Comment by JonnyBurger** [comment]
Sorry, it is becoming 4.0.114 after all!

**Comment by loalf** [comment]
Thanks!
