### ISSUE TITLE
Ability to modify `Comments` metadata field

### ISSUE THREAD

**Issue by samohovets** [remotion-dev/remotion#3489]
# Feature Request 🛍️

## Use Case

In the next banger.show update you'll be able to browse free 3D models from Sketchfab. We must credit the model's author to comply with Creative Commons 4.0 license. We can't credit the authors in the video itself, but we can do this in the `Comments` metadata field! That's the main usecase.

## Possible Solution

It's possible with ffmpeg, it would be really nice to have a parameter in `renderMedia()`

https://superuser.com/questions/1644304/how-can-i-edit-a-video-files-comments-field

**Comment by JonnyBurger** [comment]
I think you can cover it with https://www.remotion.dev/docs/renderer/render-media#ffmpegoverride!

**Comment by samohovets** [comment]
> I think you can cover it with https://www.remotion.dev/docs/renderer/render-media#ffmpegoverride!

Yeah I saw that and I'll use this, but the "Danger" section below says it possibly can break. That's why I created this issue :)
