### ISSUE TITLE
Speed up renders with "don't care" option for overwrite

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3496]
If `overwrite` is true, then it checks and deletes the previous files from S3
If `overwrite` is false, then it throws and error if the file exists on S3

But if you don't set a preference, it should just skip checking and speed up the Lambda render

**Comment by Nightrider0098** [comment]
@JonnyBurger Can i work on this issue?

**Comment by JonnyBurger** [comment]
Sorry for seeing this late @Nightrider0098!
I appreciate your willingness to contribute.

With #3803, users can set `overwrite: true` to skip the check.  
In Remotion 5.0, this will become the default.
