### ISSUE TITLE
Include Transition components as Helpers

### ISSUE THREAD

**Issue by BrunnerLivio** [remotion-dev/remotion#35]
I‘ve seen you already created some awesome transitions in your example repositories, such as [Transition.tsx](https://github.com/JonnyBurger/remotion-trailer/blob/main/src/Transition.tsx) or [FadeTransition.tsx](https://github.com/JonnyBurger/remotion-trailer/blob/main/src/FadeTransition.tsx).
I think it could be a nice addition to have since it is something a lot of videos will need to use!

**Comment by JonnyBurger** [comment]
True!

I'm thinking since they are opinionated, they shouldn't be released in core. It would be nice to publish them in some way. Maybe @remotion/transitions or maybe I release them in a separate repo personally.

I'm leaving this open until I'll do it which I plan to 👌

**Comment by nitinthewiz** [comment]
From what I understand, transitions are used only in Sequences and not with Compositions, right? They certainly make sense to be a part of a separate package for those who need them... Just my two cents! 😃

**Comment by JonnyBurger** [comment]
This is now WIP: https://github.com/remotion-dev/remotion/pull/1057
