### ISSUE TITLE
Support for loading 3D files through R3F and drei

### ISSUE THREAD

**Issue by reactone** [remotion-dev/remotion#3515]
# Feature Request 🛍️

I'm trying to figure out whether it's possible to load 3D files and render them in remotion. Im using remotion three package and also installed react-three/drei to load the GLTF file using useGLTF hook. Im able to render the 3D object on the screen but it doesn't render as a video. Is there currently a way to do that or to load any othr type of 3D files, such as .STL , .FBX etc?

**Comment by JonnyBurger** [comment]
Hello @reactone!

> Im able to render the 3D object on the screen but it doesn't render as a video

Can you clarify? What happens when you render?

**Comment by reactone** [comment]
@JonnyBurger it works fine actually, I assumed that a special loader is needed. Closed now.
