### ISSUE TITLE
Responsiveness bug in pricing page

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3521]
![image](https://github.com/remotion-dev/remotion/assets/1629785/e8b516dc-24bc-4a78-99fe-3d492f0bcfa4)

**Comment by vimode** [comment]
Can I work on this or is anyone else already on it?

**Comment by JonnyBurger** [comment]
@vimode Appreciate it a lot! I don't think we need volunteers to work for our pricing page, I think I'll happily do this myself though 🙂 otherwise I'd feel bad
