### ISSUE TITLE
Renders on AWS Lambda don't respect scaling

### ISSUE THREAD

**Issue by Nafeij** [remotion-dev/remotion#3537]
# Bug Report 🐛

Recently upgraded from `4.0.108` to `4.0.120`, and now renders on Lambda in a weird aspect ratio whenever the `--scale` flag is set.

Downgrading to `4.0.108` does not seem to fix this.

[Possibly-related issue](https://github.com/remotion-dev/remotion/issues/3508)

### Local render

https://github.com/remotion-dev/remotion/assets/20167059/9336f3fa-7d2b-443a-b534-5b4fdf8d8600

### Lambda render

https://github.com/remotion-dev/remotion/assets/20167059/b97da7eb-9285-4556-99e5-503d96d2b3ee

### Local render with `--scale=2`

https://github.com/remotion-dev/remotion/assets/20167059/53c53a5d-7191-4092-8d6d-33f325cc4b67

### Lambda render with `--scale=2` (!)

https://github.com/remotion-dev/remotion/assets/20167059/ebf1a5a8-1f7d-4237-a9eb-b0c5e1e25994

## Configuration

```ts
import {Config} from '@remotion/cli/config';

Config.setVideoImageFormat('jpeg');
Config.setOverwriteOutput(true);
```
```
npx remotion lambda render <URL> ScrollyComp --crf=1 --scale=2
```
or 
```
npx remotion render Comp out/video.mp4 --crf=1 --scale=2 --concurrency=100%
```

**Comment by JonnyBurger** [comment]
Thanks for reporting! It seems like #3543 works with both Lambda and local. Please give the next version a try :)
