### ISSUE TITLE
Failure to have permissions to access localStorage on device causes Player to crash

### ISSUE THREAD

**Issue by ZipBrandon** [remotion-dev/remotion#3540]
# Bug Report 🐛
From my app's Sentry:
![image](https://github.com/remotion-dev/remotion/assets/68867795/b8a986be-28bd-418c-be35-f0c5abc198f8)
![image](https://github.com/remotion-dev/remotion/assets/68867795/3d604292-d350-42d7-9a47-653ba021ff50)

Is there a way we can make this more graceful in circumstances when the device does not permit access to localStorage and the Player would like to non-critically access it?

**Comment by JonnyBurger** [comment]
Thanks for reporting!
