### ISSUE TITLE
On prefetch() with cloudfront aws - what is correct config?

### ISSUE THREAD

**Issue by Sof2222** [remotion-dev/remotion#3541]
Hi!

I am not the most experienced - especially with aws, but I am trying to use the <Series> and <Series.Sequence> part here to combine two cloudfront videos (aws) so they play one after another using <Player>. They should not just play one after another but actually look like one video is the idea (and later on - not yet - potentially add transitions and the like with this).

    ```
  <Player
        ref={playerRef}
        component={MyCombinedVideo}
        compositionWidth={1080}
        compositionHeight={1920}
        fps={fps}
        durationInFrames={duration} 
        controls
        style={{ width: "100%", height: "100%", borderRadius: "10px" }}
        inputProps={{ videos }}
        spaceKeyToPlayOrPause={true}
      />
```

```
export const MyCombinedVideo = ({ videos }: { videos: any[] }) => {
  let accumulatedFrames = 0;
  console.log("These are the videos", videos);

  return (
    <>
      <Series>
        {videos.map((video, index) => {
          const startFrame = accumulatedFrames;
          // console.log("startFrame", startFrame, index);
          const durationInFrames =
            (video.end_time - video.start_time) * video.fps;
          // console.log("durationInFrames", durationInFrames, index);
          accumulatedFrames += durationInFrames;
          // console.log("accumulatedFrames", accumulatedFrames, index);

          return (
            <Series.Sequence
              key={video.id + video.order}
              offset={-video.start_clip * video.fps}
              // from={startFrame}
              durationInFrames={durationInFrames}
              layout="absolute-fill"
            >
              <Video
                src={convertToCdnUrl(video.url)} //+ `#t=${video.start_clip}`}
              />
            </Series.Sequence>
          );
        })}
      </Series>
    </>
  );
};
```

I have tried the prefetch in different places in the app but have for example:

```
  useEffect(() => {
    const { free, waitUntilDone } = prefetch(videoUrl, {
      method: "blob-url",
    });
  }, [videoUrl]);
```

which is a simple, basic thing but it still gives me the same issues (below)

(note using nextjs14 - and have the code in a client component).

I keep getting these errors:

[Error] Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. Status code: 200
[Error] Fetch API cannot load https://-------.cloudfront.net/publicFiles/_public/filename.mp4 due to access control checks.
[Error] Failed to load resource: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. Status code: 200 (filename.mp4, line 0)
(note am developing locally right now but would be for prod)

My s3 bucket points to cloudfront and I have no issues just loading those items, however when I am trying to use prefetch, it starts multiple attempts to cache it and constantly fails. I am loading these videos in other parts of the page and they work fine.
(Am trying to use prefetch as there is a white gap between the two videos I would like to get rid of).

My config in cloudfront:
Under the distribution > Behaviours I have this: (note for Default (*))
![Screenshot 2024-03-01 at 13 23 34](https://github.com/remotion-dev/remotion/assets/131628600/13529f54-eae3-4db0-ab1c-e6a047523702)
![Screenshot 2024-03-01 at 13 23 51](https://github.com/remotion-dev/remotion/assets/131628600/08e13a20-185e-423f-9941-54420b55854c)

Where the policy is:

![Screenshot 2024-03-01 at 13 24 03](https://github.com/remotion-dev/remotion/assets/131628600/6fb915c0-5f54-493c-9ee9-1cba2063caed)

I notice on the prefetch page (https://www.remotion.dev/docs/prefetch) it has information about CORS but I just can't figure out what CORS is needed for this. (or maybe it is a different issue).

I feel I have been trying to find information on this but just can't seem to figure it out (maybe the docs could be updated? Or maybe I just don't know enough about CORS, cache and the policies etc.)

Thank you in advance!

**Comment by JonnyBurger** [comment]
Hi @Sof2222,

the problem you are facing is that the assets you are loading do not have CORS enabled. 
It is a browser policy that by default prevents assets from other domains being loaded into a website.

You can fix this by learning about CORS online and figuring out how to enable this for your CloudFront.

**Comment by aaa3334** [comment]
Hi @JonnyBurger - CORS is enabled in cloudfront though - the policy is above although I see the formatting has become odd (will try and fix that now). It is enabled for GET and I am passing some of the headers through.
I spent quite some time googling and trying to figure it out but I cannot figure out what different settings are needed here or what to change..
Thanks in advance!

**Comment by JonnyBurger** [comment]
@aaa3334 This is a general CORS error and has nothing to do with Remotion.

I recommend to debug to exactly analyze the error message and compare the headers that get sent.

> Origin http://localhost:3000/ is not allowed by Access-Control-Allow-Origin

It seems like you don't set the Access-Control-Allow-Origin header. The configuration you posted also is not directly related to CORS.

Please use one of the many resources online to know how to debug CORS.
