### ISSUE TITLE
Eslint issue: ESLint couldn't determine the plugin "@typescript-eslint" uniquely.

### ISSUE THREAD

**Issue by mnlbox** [remotion-dev/remotion#3553]
Hi @JonnyBurger 
I have a monorepo with NX and Remotion. After upgrading my packages I started to get error like this for my `lint` command:

```
Oops! Something went wrong! :(

ESLint: 8.57.0

ESLint couldn't determine the plugin "@typescript-eslint" uniquely.

- /remotionVid/node_modules/.pnpm/@typescript-eslint+eslint-plugin@6.7.4_@typescript-eslint+parser@6.7.4_eslint@8.57.0_typescript@5.3.3/node_modules/@typescript-eslint/eslint-plugin/dist/index.js (loaded in ".eslintrc » @remotion/eslint-config#overrides[0] » plugin:@typescript-eslint/recommended » ./configs/base")
- /remotionVid/node_modules/.pnpm/@typescript-eslint+eslint-plugin@6.21.0_@typescript-eslint+parser@6.21.0_eslint@8.57.0_typescript@5.3.3/node_modules/@typescript-eslint/eslint-plugin/dist/index.js (loaded in "../../.eslintrc.json#overrides[1] » plugin:@nx/typescript")

Please remove the "plugins" setting from either config or remove either plugin installation.

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

Warning: command "eslint ." exited with non-zero status code
```

As I checked with this command:
```
pnpm why @typescript-eslint/eslint-plugin

@remotion/eslint-config 4.0.121
└── @typescript-eslint/eslint-plugin 6.7.4
@typescript-eslint/eslint-plugin 6.21.0
```

And as I checked in the repo I found where you used this package:
https://github.com/remotion-dev/remotion/blob/main/packages/eslint-config/package.json#L20
And here you freezed the version to "6.7.4" but as I'm using **"@nx/eslint-plugin"** and it required at least "**@typescript-eslint/parser@^6.13.2**" the issue started. Is there any chance to fix this issue then we can use both eslint configs? (each one for relavant project)

I think if you switched the versions from this:
```
    "@typescript-eslint/eslint-plugin": "6.7.4",
    "@typescript-eslint/parser": "6.7.4",
```
to this:
```
    "@typescript-eslint/eslint-plugin": "^6.7.4",
    "@typescript-eslint/parser": "^6.7.4",
```
It will solve the issue. Or maybe move these two package to `peerDependeicies`.
What do you think?

**Comment by mnlbox** [comment]
It's tiny thing but if you want let ne know then i can send a pr to fix it.

**Comment by JonnyBurger** [comment]
Thanks for reporting, it is realized now!
