### ISSUE TITLE
Remotion Player: Hide the controls when the mouse doesn't move

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3557]
Currently the controls don't disappear as long as the mouse pointer is hovering the Player.  
Only when the mouse leaves the player, the controls hide.

We should make it that when the pointer doesn't move for 3 seconds, the controls also hide.
Moving it again should show it again.

The current behavior of leaving the pointer should remain intact.

This behavior should be on by default, but a new prop `hideControlsWhenPointerDoesntMove={false}` should be introduced that allows disabling this behavior.

The `alwaysShowControls` prop should also be respected, if it is set to `true`, then the controls should never hide.

The documentation of `alwaysShowControls` should also be amended to say that it also prevents hiding when pointer doesn't move.

This new prop should also be documented.

Current logic: https://github.com/remotion-dev/remotion/blob/93c6aa840a8947d523e896de703bc0f3a0e42a46/packages/player/src/PlayerControls.tsx#L189-L198

## Bounty

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 150

**Comment by JonnyBurger** [comment]
Thanks and good luck @hansel-cmd! 🙌🏼

**Comment by mrkirthi-24** [comment]
in waitlist if @hansel-cmd gives up

**Comment by thecmdrunner** [comment]
> We should make it that when the pointer doesn't move for 3 seconds, the controls also hide.
@JonnyBurger Would this hide the controls on iOS Safari too? If autoplay was not enabled, and the user clicked on the player's play button to play? or would it hide only if clicked on the rest of the player area to play? both? none?

**Comment by joaopaulo-capy** [comment]
If all else fails im willing to try it too

> in waitlist if @hansel-cmd gives up

**Comment by JonnyBurger** [comment]
Good point @thecmdrunner

On mobile, the current behavior should be kept, hope this is not too hard!
