### ISSUE TITLE
Issue with thumbnailRef.current being undefined in useEffect in stackBlitz app.

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3561]
[From message posted on Discord by **umungobungo**](https://discord.com/channels/809501355504959528/1214823151926513674/1214823154523050024)
----
Hey Jonny, I'm still having some issues with thumbnailRef 😦

You can see in the stackBlitz that thumbnailRef.current is never defined

```tsx
useEffect(() => {
  console.log('playerRef useEffect');
  const current = playerRef.current;
  if (!current) return;

  console.log('playerRef.current found');
}, [playerRef]);

useEffect(() => {
  console.log('thumbnailRef useEffect');
  const current = thumbnailRef.current;
  if (!current) return;

  console.log('thumbnailRef.current found');
}, [thumbnailRef]);
```

https://stackblitz.com/edit/vitejs-vite-u6rali?file=src%2FApp.tsx

**Comment by UmungoBungo** [comment]
![image](https://github.com/remotion-dev/remotion/assets/22192773/38baf7a6-d031-47ff-ab80-9acf004add2f)
playerRef.current is defined, but it isn't working for thumbnail
