### ISSUE TITLE
Unable to render my videos after upgrade to version "4.0.122"

### ISSUE THREAD

**Issue by mnlbox** [remotion-dev/remotion#3587]
I'm trying to render multi videos with a render script based on [this guide](https://www.remotion.dev/docs/dataset-render), but I'm getting this error:

```
Error: spawn /videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.125/node_modules/@remotion/compositor-linux-arm64-gnu/remotion EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.125/node_modules/@remotion/compositor-linux-arm64-gnu/remotion',
  path: '/videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.125/node_modules/@remotion/compositor-linux-arm64-gnu/remotion',
  spawnargs: [
    '{"nonce":"1j253g1k0icgx0ycl8hruw","payload":{"type":"StartLongRunningProcess","params":{"concurrency":1,"maximum_frame_cache_size_in_bytes":null,"verbose":false}}}'
  ]
}
```

As the error message is not clear I don't know where is the issue to fix. As far as I searched this error came from Rust components of Remotion @JonnyBurger any idea from this error message?

**Comment by JonnyBurger** [comment]
Thanks for filing an issue.

This is due to a permission problem. Can you run the following commands so we can see what we need to change?

```
ls -l /videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.125/node_modules/@remotion/compositor-linux-arm64-gnu/remotion
```

```
node -e "console.log(require('fs').accessSync('/videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.125/node_modules/@remotion/compositor-linux-arm64-gnu/remotion'))"
```
And tell us what is happening?
Can you also mention the OS you use and if you use Docker?

**Comment by mnlbox** [comment]
Thanks for your message @JonnyBurger 
These are the output for these two command that you mentioned:

First Command:
```
ls -l /videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.125/node_modules/@remotion/compositor-linux-arm64-gnu/remotion
```
Output:
```
-rw-r--r-- 1 node node 1993832 Mar 12 15:51 /videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.125/node_modules/@remotion/compositor-linux-arm64-gnu/remotion
```

Second Command:
```
node -e "console.log(require('fs').accessSync('/videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.125/node_modules/@remotion/compositor-linux-arm64-gnu/remotion'))"
```
Output:
```
undefined
```

I'm using MacOS but I'm developing this Remotion project in vsCode devContainer and I'm using a Docker image based on Debian bookworm version for that.
BTW, Previously I rendered my videos one time before and this is first time I see this error. I updated all of my packages. I don't know if it's related to that or not. 🤔

**Comment by mnlbox** [comment]
@JonnyBurger did you get a chance to check this issue?
Do you need more information from my side?
I'm somehow stuck here as my video is ready but I can't render any of my projects 😥

Thanks for your support in advance 🌺

**Comment by JonnyBurger** [comment]
Hi @mnlbox,

I just tried it myself. I used the Barebones Node.js Devcontainer. By default the binary is also not executable, but with the permissions we give ourselves, we make it runnable.

So cannot reproduce. There is also a difference between our paths somehow, mine start with `/workspaces/barebones-nodejs/node_modules/...`

So maybe a difference in DevContainers, can you post which DevContainer you use?

**Comment by mnlbox** [comment]
Thanks @JonnyBurger,

My docker file is something like this:
```
ARG VARIANT=20-bookworm
FROM mcr.microsoft.com/devcontainers/typescript-node:${VARIANT}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends chromium \
    && apt-get clean

ARG PNPM_VERSION=8.15.3
RUN su node -c "npm install -g pnpm@${PNPM_VERSION}"
```
Do I need to install anything else in addition to `chromium`?
Can you clarify what permission you gave yourselves and for which folder/file exactly? Which binary you are referring too here? 👇 👇 👇 

> By default the binary is also not executable, but with the permissions we give ourselves, we make it runnable.

**Comment by JonnyBurger** [comment]
I could also not reproduce this.

1. Cloned Hello World template
2. Added Dockerfile:

```dockerfile
ARG VARIANT=20-bookworm
FROM mcr.microsoft.com/devcontainers/typescript-node:${VARIANT}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install --no-install-recommends chromium \
  && apt-get clean

ARG PNPM_VERSION=8.15.3
RUN su node -c "npm install -g pnpm@${PNPM_VERSION}"
COPY . . 
RUN pnpm i
RUN node -e "console.log(require.resolve('@remotion/compositor-linux-arm64-gnu'))"
RUN node render.mjs
```

3. Add `render.mjs`

```js
import { bundle } from "@remotion/bundler";
import { renderMedia, selectComposition } from "@remotion/renderer";
import { createRequire } from "node:module";
 
const require = createRequire(import.meta.url);
 
const bundled = await bundle({
  entryPoint: require.resolve("./src/index.ts"),
  // If you have a Webpack override, make sure to import it here
  webpackOverride: (config) => config,
});
 
const composition = await selectComposition({
  serveUrl: bundled,
  id: "HelloWorld",
});
 
console.log("Starting to render composition");
 
await renderMedia({
  codec: "h264",
  composition,
  serveUrl: bundled,
  outputLocation: `out/${composition.id}.mp4`,
  chromiumOptions: {
    enableMultiProcessOnLinux: true,
  },
});
 
console.log(`Rendered composition ${composition.id}.`);
```

It works! All packages on Remotion 4.0.128.
At this point, I need to ask you to post a full repro in order to investigate this.

**Comment by mnlbox** [comment]
Hi @JonnyBurger  I think I found where the issue started.

As I said I rendered my videos previously before update my Remotion packages.
I tried to downgrade all of my Remotion packages from `4.0.128` to find from which version my render is not working, and I switched to this exact version:

```
dependencies: {
    "@remotion/animation-utils": "4.0.121",
    "@remotion/bundler": "4.0.121",
    "@remotion/cli": "4.0.121",
    "@remotion/google-fonts": "4.0.121",
    "@remotion/layout-utils": "4.0.121",
    "@remotion/media-utils": "4.0.121",
    "@remotion/renderer": "4.0.121",
    "@remotion/zod-types": "4.0.121",
    "remotion": "4.0.121",
}

"devDependencies": {
    "@remotion/eslint-config": "4.0.121",
    "@remotion/tailwind": "4.0.121",
}
```

✅  And Render is working well with version `4.0.121` but all the versions after this version has the same issue that I reported so I think something is wrong from version `4.0.122`. BTW, didn't set any permissions for the bundler script. After running `pnpm install` I see these downloads for Remotion:
```
$ pnpm install
Scope: all 5 workspace projects
Downloading registry.npmjs.org/@remotion/google-fonts/4.0.121: 9.80 MB/9.80 MB, done
Downloading registry.npmjs.org/@remotion/compositor-linux-arm64-gnu/4.0.121: 7.55 MB/7.55 MB, done
Packages: +18 -18
++++++++++++++++++------------------
Downloading registry.npmjs.org/@remotion/compositor-linux-arm64-musl/4.0.121: 7.72 MB/7.72 MB, done
Progress: resolved 2230, reused 2135, downloaded 18, added 18, done
```
💡 BTW, the output of this command is `undefined` same as 4.0.128 so I'm not sure if it's permission issue or not because even with `undefined` my render script is working now in `4.0.121`:

Permission for `4.0.121`:
```
node -e "console.log(require('fs').accessSync('/babakscript/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.121/node_modules/@remotion/compositor-linux-arm64-gnu/remotion'))"
```
Output:
```
undefined
```

I hope this issue help to find where the issue started if not let me know I'll try to create reproduce repo.

**Comment by mnlbox** [comment]
Hi @JonnyBurger  I think I found where the issue started.

As I said I rendered my videos previously before update my Remotion packages.
I tried to downgrade all of my Remotion packages from `4.0.128` to find from which version my render is not working, and I switched to this exact version:

```
dependencies: {
    "@remotion/animation-utils": "4.0.121",
    "@remotion/bundler": "4.0.121",
    "@remotion/cli": "4.0.121",
    "@remotion/google-fonts": "4.0.121",
    "@remotion/layout-utils": "4.0.121",
    "@remotion/media-utils": "4.0.121",
    "@remotion/renderer": "4.0.121",
    "@remotion/zod-types": "4.0.121",
    "remotion": "4.0.121",
}

"devDependencies": {
    "@remotion/eslint-config": "4.0.121",
    "@remotion/tailwind": "4.0.121",
}
```

✅  And Render is working well with version `4.0.121` but all the versions after this version has the same issue that I reported so I think something is wrong from ➡️ [version 4.0.122](https://github.com/remotion-dev/remotion/releases/tag/v4.0.122). BTW, didn't set any permissions for the bundler script. After running `pnpm install` I see these downloads for Remotion:
```
$ pnpm install
Scope: all 5 workspace projects
Downloading registry.npmjs.org/@remotion/google-fonts/4.0.121: 9.80 MB/9.80 MB, done
Downloading registry.npmjs.org/@remotion/compositor-linux-arm64-gnu/4.0.121: 7.55 MB/7.55 MB, done
Packages: +18 -18
++++++++++++++++++------------------
Downloading registry.npmjs.org/@remotion/compositor-linux-arm64-musl/4.0.121: 7.72 MB/7.72 MB, done
Progress: resolved 2230, reused 2135, downloaded 18, added 18, done
```
💡 BTW, the output of this command is `undefined` same as 4.0.128 so I'm not sure if it's permission issue or not because even with `undefined` my render script is working now in `4.0.121`:

Permission for `4.0.121`:
```
node -e "console.log(require('fs').accessSync('/videos/node_modules/.pnpm/@remotion+compositor-linux-arm64-gnu@4.0.121/node_modules/@remotion/compositor-linux-arm64-gnu/remotion'))"
```
Output:
```
undefined
```
As I checked the repo it seems this bundle script is the only change in the `compositor` packages as well:
![image](https://github.com/remotion-dev/remotion/assets/25859075/1d417ae5-7fff-4408-9bb6-665e894089e6)


I'm not sure but maybe it's related to this PR:
https://github.com/remotion-dev/remotion/pull/3549

I hope these information help to find where the issue started, if not let me know I'll try to create reproduce repo.

**Comment by JonnyBurger** [comment]
Thanks for the investigation!
I thought as well that this breaks it.

But the previous implementation was flawed as well, so I don't just want to revert.

That's why I was asking for an exact way to reproduce, since building it with the information you gave me currently did not allow me to produce the same problem.

**Comment by mnlbox** [comment]
> Thanks for the investigation! I thought as well that this breaks it.
> 
> But the previous implementation was flawed as well, so I don't just want to revert.
> 
> That's why I was asking for an exact way to reproduce, since building it with the information you gave me currently did not allow me to produce the same problem.

@JonnyBurger No problem, I created a simple reproduce repo here:
https://github.com/mnlbox/remotion-issues?tab=readme-ov-file#issue-3587

Hope that it help to reproduce it.

**Comment by JonnyBurger** [comment]
Thanks a lot! I was able to reproduce now 🙏

**Comment by mnlbox** [comment]
Thanks @JonnyBurger,

I can confirm that it's working now.
Thanks for your support and for this awesome project. 👍

**Comment by JonnyBurger** [comment]
Nice, thanks for reporting back!
