### ISSUE TITLE
Instructions for deploying the Studio on GitHub Pages

### ISSUE THREAD

**Issue by musafiroon** [remotion-dev/remotion#3602]
Officially recommend serving the studio (using gh pages) as a demo instead of a rendered video.

We could include a workflow to the starter templates that would bundle studio and serve it on GitHub pages whenever a push is made
[Build-studio.yml.txt](https://github.com/remotion-dev/remotion/files/14638246/Build-studio.yml.txt)
is a workflow to do this

**Comment by JonnyBurger** [comment]
Thanks for the ideas!

While in the early templates, we had a GitHub Action to render a video on every push, we stopped doing this and removed it from all templates.
Instead, we point to the docs and allow to quickly compose it.

However, I do think adding instructions for how to deploy to GitHub pages is a good idea! This we'd like to do.
