### ISSUE TITLE
playbackRate applies to full audio when rendering the video.

### ISSUE THREAD

**Issue by riyasat** [remotion-dev/remotion#3610]
Hi,
I created a project where I need a part of audio in 1.04 playbackRate instead of 1. 

It works as expected only in preview mode but when I render it, this playbackRate applies to full audio. 

### How to re-produce?

1. Create a composition 
2. add audio file that has 4 minutes of audio
3. change playbackRate to 1.05
4. change startFrom to 1000
5. change endAt to 2000
6. run preview, you will see that audio speed is increased only that specific part of the audio only in preview mode.
7. render the video
8. now the playbackRate would be applied to whole 5 minutes.

### Expected Result:
**If startFrom or endAt is/are provided then playbackRate should only be applied to that specific part of the audio.**

`<Audio
  src={staticFile('audio/audio.mp3')}
  playbackRate={1.02}
  startFrom={1000}
  endAt={2000}
/>`

Can you please solve this issue?

Thanks

**Comment by JonnyBurger** [comment]
Thanks for reporting!
Yes certainly we can solve it.

Will be fixed in v4.0.129
