### ISSUE TITLE
Use `remotionb` if the `bun create video` was used to scaffold

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3628]
If we use `bun create video` to scaffold a new video, it would be great if the scripts in package.json would use `remotionb` to also use Bun:

```diff
- "start": "remotion studio"
+ "start": "remotionb studio"
```

## Acceptance criteria

Change https://github.com/remotion-dev/remotion/blob/747571b53ff95e81585636c9e272176b08dd8457/packages/create-video/src/patch-package-json.ts#L16 so that if Bun was used, then change all NPM scripts to use the `remotionb` binary instead of `remotion`

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 75

**Comment by abhishek818** [comment]
@mrkirthi-24 hey, i was working on it, forgot to comment attempt.. Have pushed a PR.

**Comment by abhishek818** [comment]
cc: @JonnyBurger

**Comment by abhishek818** [comment]
There was bounty on this 😅 ? @JonnyBurger

**Comment by JonnyBurger** [comment]
Yes sorry! You can submit a claim by using the `/claim` command and then it will be auto-rewarded next time
