### ISSUE TITLE
props value returned from calculateMetadata() not displayed in Remotion Studio sidebar.

### ISSUE THREAD

**Issue by AliRoshaniDev** [remotion-dev/remotion#3636]
I tried to dynamically return the value of props from the calculateMetaData function, and although this works correctly, the new values returned for props are not displayed in the studio sidebar unless I switch between the Schema and JSON tabs once, after which the new props values are shown.

**Comment by JonnyBurger** [comment]
It is expected that you edit the default props in the sidebar, not the mapped props.

So that you can always use code to override the data in the sidebar.

We should update the docs and also investigate your claim that the JSON tab shows the mapped props, which should actually not happen 😬

**Comment by AliRoshaniDev** [comment]
> It is expected that you edit the default props in the sidebar, not the mapped props.
> 
> So that you can always use code to override the data in the sidebar.
> 
> We should update the docs and also investigate your claim that the JSON tab shows the mapped props, which should actually not happen 😬

So, not displaying props in the sidebar is normal behavior. But is there a way to modify the data of the sidebar props from within the code?
@JonnyBurger

**Comment by JonnyBurger** [comment]
Well, you can edit the default props in the sidebar.

To calculate the final props, you have the calculateMetadata() function to map over the sidebar props.
Those props are then final, no other ways exist
