### ISSUE TITLE
Batch Render failed randomly even with Concurrency=1

### ISSUE THREAD

**Issue by mnlbox** [remotion-dev/remotion#3639]
# Bug Report 🐛

Hi @JonnyBurger,

I'm trying to use my script to render multiple videos based on [this page](https://www.remotion.dev/docs/dataset-render) in docs.
But it's randomy crashed with this error:
```bash
Get help for this issue at https://remotion.dev/docs/timeout
Error rendering "My Video": SymbolicateableError: A delayRender() "Rendering <Video /> with src="/public/my-video/background.webm"" was called but not cleared after 28000ms. See https://remotion.dev/docs/timeout for help. The delayRender was called: 
    at delayRender (http://localhost:3000/bundle.js:31499:32)
    at http://localhost:3000/bundle.js:35690:58
    at Rj (http://localhost:3000/bundle.js:4372:332)
    at Ik (http://localhost:3000/bundle.js:4414:111)
    at http://localhost:3000/bundle.js:4410:391
    at J (http://localhost:3000/bundle.js:36350:203)
    at MessagePort.R (http://localhost:3000/bundle.js:36351:128)
    at http://localhost:3000/bundle.js:31517:27 {
```

I have a `<Video>` tag in my composition. I'm using devContainer and Remotion version `4.0.132`.
It rendered one time without any issue and now crash randomly. Sometimes after rendering the first video. And sometimes after 6 videos.

What did I tried to solve it until now:
1. 
I tried to decrease the Concurrency by adding `Config.setConcurrency(1);` in my `remotion.config.ts` but it's not working.
I guess I have 12 core cpus as the result of this command is 12 for me:
```
node -e "console.log(os.cpus().length)"
```

I also tried to increase the timeout by changing my render script like this:

```typescript
await renderMedia({
			composition,
			serveUrl: bundleLocation,
			codec: 'h264',
			outputLocation: `./out/${folderName}/${entry.key}.mp4`,
			inputProps,
			chromiumOptions: {
				enableMultiProcessOnLinux: true,
			},
			timeoutInMilliseconds: 30000, <---------------- Added this one
		});
```
But it still show `28000ms` in the error message so it seems the timeout not applied at all.

What else can I check to solve the issue?

**Comment by JonnyBurger** [comment]
Ok, let's debug it.. first question, is the file actually located in public/my-video/background.webm?

Or is it supposed to be another path? I recommend OffthreadVideo instead of Video for better performance and also better error messages

**Comment by mnlbox** [comment]
Thanks for your reply, yes the file is there. And as I mentioned actually the render is working sometimes without any issue. I just have to re run my render script multiple times to make sure all videos created successfully. So it's not an urgent issue for me at all.
But I wondered why timeout in the error message always shows `28000ms` even when I changed it via `timeoutInMilliseconds: 30000,` property and why the render still sometimes not working even with `Config.setConcurrency(1);`? (as it's the lowest possible value it should and the video file also loaded from localhost not through network it shouldn't be any issue)

BTW, I'm using GreenScreen effect in my video my video component is something like this: (I don't know if it's related or not)
https://github.com/orgs/remotion-dev/discussions/3534
So I have a single image and one greenscreen on top of that. And these are my only assets in this video.

I didn't know that I can replace my `<Video>` component with `<OffthreadVideo>` even when I'm using the "[video manipulation](https://www.remotion.dev/docs/video-manipulation#greenscreen-example)" techniques that you mentioned here in the docs. It wasn't clear for me because all the examples in the docs used `<Video>` component as well and in docs even mentioned:

<img width="853" alt="image" src="https://github.com/remotion-dev/remotion/assets/25859075/d906cb4d-03e7-4964-8dc5-d44e2a39c180">

So let me turn this `<Video>` component to `<OffthreadVideo>` to see if it solve the issue or not and I'll keep you updated.

**Comment by JonnyBurger** [comment]
Sorry for the late response!

Yes, unfortunately, `<OffthreadVideo>` cannot be combined with canvas manipulation.
I noticed something in your explanation - you mention you set the concurrency in the config file, however the config file does not apply for server-side rendering APIs!

If you want that, add `concurrency: 1` to the renderMedia() call. Does that help?

**Comment by mnlbox** [comment]
@JonnyBurger Oops sorry for the late reply I just missed your messages here in this issue. I'll check it today and keep you updated here.
