### ISSUE TITLE
Add whisper max-length parameter

### ISSUE THREAD

**Issue by youssefbenlemlih** [remotion-dev/remotion#3688]
# Feature Request 🛍️

It would be practical to have the option to omit (don't pass any) or set the max-length parameter passed to whisper.cpp in the transcribe function.

 https://github.com/remotion-dev/remotion/blob/main/packages/install-whisper-cpp/src/transcribe.ts
 
This would make it possible to easily generate sentence transcription: Each transcription would contain multiple tokens instead of one, which is whisper.cpp's default behavior.

## Use Case

Create movie-style subtitles for a video, using whisper.cpp's default token grouping.

## Possible Solution

Add an optional parameter tokens per transcript, with a default of 1 (backwards compatibility). If set to null then don't pass any value to the whisper command.

Option 2: add an optional argument processArgs that applies changes to the args passed to whispercpp.

**Comment by JonnyBurger** [comment]
Great idea! I like it. I'm gonna put a bounty on it!

## Acceptance criteria

Add a new `maxLength` option to `transcribe()` which controls this option.  
If left out, the current behavior should be kept.
It should be documented in transcribe.mdx and being marked as available for the next patch version.

/bounty 100

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 50

**Comment by JonnyBurger** [comment]
@youssefbenlemlih Cool you give it a try yourself! Good luck!
