### ISSUE TITLE
How to make font smooth? 

### ISSUE THREAD

**Issue by anjalipandith** [remotion-dev/remotion#3715]
Fonts in the rendered video is not smooth like Adobe Premiere pro, any way to make font look better or smooth??

**Comment by JonnyBurger** [comment]
Give some information about your environment, which OS are you rendering on?

**Comment by anjalipandith** [comment]
I used both Ubuntu 22.04 and Windows 11.
Is is possible for the render command to use user chrome with use specific settings (we can enable graphics for the chrome browser)?

**Comment by JonnyBurger** [comment]
I have not heard reports in general that font rendering is broken on regular Windows or Ubuntu.
Need a more descriptive issue how you ended up with a blurry font.

Note that in a video, you have 1x pixel density. You might need to increase the resolution of the video by 2x to get the same amount of pixels than on a regular 2x display.

**Comment by anjalipandith** [comment]
Have doubled the width and height, now it's smooth but quality of fonts rendering should in on par with video editing software
