### ISSUE TITLE
Implement a `getImageDimensions()` function for `@remotion/media-utils`

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3719]
Make a new API in `@remotion/media-utils` called `getImageDimensions()`, a simple version can be this:

```tsx
type Dimensions = {width: number; height: number};

export const getImageDimensions = (src: string): Promise<Dimensions> => {
  const img = new Image();
  img.src = src;
  return new Promise((resolve, reject) => {
    img.onload = () => {
      resolve({
        width: img.width,
        height: img.height,
      });
    };

    img.onerror = reject;
  });
};
```

then document it at least as well as getVideoMetadata(): https://www.remotion.dev/docs/get-video-metadata, add it to the @remotion/media-utils table of contents: https://www.remotion.dev/docs/media-utils/ and the sidebar in API -> @remotion/media-utils

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 100

**Comment by JonnyBurger** [comment]
@jkcs Yes! Thanks and good luck 🙌🏼

**Comment by webbdays** [comment]
@jkcs
are you still on this?
