### ISSUE TITLE
Update docs for next.js 13/14 route handlers.

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3731]
[From message posted on Discord by **1voy**](https://discord.com/channels/809501355504959528/817306238811111454/1230656235683057665)
----
Also, a little update to those docs with next.js 13/14 route handlers would be nice

**Comment by JonnyBurger** [comment]
Is someone with Next.js knowledge able to help and rewrite this for the App Router?

`pages/api/webhook.ts`

```ts
import {
  validateWebhookSignature,
  WebhookPayload,
} from "@remotion/lambda/client";
 
// Enable testing through the tool below
const ENABLE_TESTING = true;
 
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  if (ENABLE_TESTING) {
    res.setHeader("Access-Control-Allow-Origin", "https://www.remotion.dev");
    res.setHeader("Access-Control-Allow-Methods", "OPTIONS,POST");
    res.setHeader(
      "Access-Control-Allow-Headers",
      "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, X-Remotion-Status, X-Remotion-Signature, X-Remotion-Mode",
    );
  }
  if (req.method === "OPTIONS") {
    res.status(200).end();
    return;
  }
 
  validateWebhookSignature({
    secret: process.env.WEBHOOK_SECRET as string,
    body: req.body,
    signatureHeader: req.headers["x-remotion-signature"] as string,
  });
 
  // If code reaches this path, the webhook is authentic.
  const payload = req.body as WebhookPayload;
  if (payload.type === "success") {
    // ...
  } else if (payload.type === "timeout") {
    // ...
  }
 
  res.status(200).json({
    success: true,
  });
}
```

Don't try submit a ChatGPT solution, it is not correct!

/bounty 60

**Comment by hunxjunedo** [comment]
Hey @JonnyBurger, requesting assignment. I have a strong background of working with express js and routing with it, I'm confident I can rewrite this in a simple manner.

**Comment by JonnyBurger** [comment]
Thanks @hunxjunedo!

**Comment by hunxjunedo** [comment]
@JonnyBurger I looked at the message in Discord and just to be sure, what we intend to do is rewrite this code for App Router instead of Pages router, AND add support for cross-domain requests. Please confirm.

**Comment by JonnyBurger** [comment]
@hunxjunedo No, the scope of this issue is just to rewrite the endpoint in App Router and update the docs 👍
