### ISSUE TITLE
Cannot install and build repo locally due to paid package (@remotion-dev/cube-presentation)

### ISSUE THREAD

**Issue by 0018akhil** [remotion-dev/remotion#3738]
I tried running Remotion locally. I cannot complete the installation due to the paid package presence.

# Bug Report 🐛

![image](https://github.com/remotion-dev/remotion/assets/62931444/ab24d4dd-665c-4308-8988-a69f42b63757)

The above is the installation error.

I tried removing the **"@remotion-dev/cube-presentation"** from package.json and successfully installed it.
But I get an error in build **(pnpm build)** due to there being dependencies with the package @remotion-dev/cube-presentation

**Comment by JonnyBurger** [comment]
The pnpm version you use to install Remotion must be exactly the same as in the contributing docs: https://www.remotion.dev/docs/contributing

We whitelist this version only because otherwise you could run the command somewhere else and access the paid package for free.
