### ISSUE TITLE
`loop` not available on `<OffthreadVideo />`

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#3762]
Not really a major one but someone who's using `<Video />` would expect `<OffthreadVideo />` to be a drop in replacement for `<Video />`.

Was having issues with rendering not pausing for buffering to finish for `<Video />` elements, resulting in the first frame being black. But it worked on `<OffthreadVideo />` so tried replacing it throughout the app but had this type error of `loop` missing from `<OffthreadVideo />`

**Comment by JonnyBurger** [comment]
It's not a bad idea anyway.
Problem is that if you drop in like a ProRes file, then we need to get the duration from somewhere else, maybe from the server using FFmpeg.

Probably at some point we make a proxy so we can call `getVideoMetadata()` from the frontend if you are connected to a server (going into this direction now with https://github.com/remotion-dev/remotion/pull/3760) and then we could conceivably implement it properly.
