### ISSUE TITLE
Setting spring config.damping to 0 makes browser page to hang.

### ISSUE THREAD

**Issue by curvednebula** [remotion-dev/remotion#3771]
I think it makes sense to put assertion somewhere inside spring() - to avoid this condition - I almost decided to abandon remotion altogether, because I made a few innocent (as I thought) changes and couldn't understand why UI suddenly stopped working - I thought it was just very unstable and it stopped working for no reason.

	const translationMotion = spring({
		frame: frame - startTime,
		fps,
		durationInFrames: 25,
		config: {
			damping: 10, // WARNING: don't put 0 - browser hangs!!!
		},
	});

**Comment by JonnyBurger** [comment]
This is a great point, thanks for telling your story!

**Comment by JonnyBurger** [comment]
Fixed in #3792
