### ISSUE TITLE
Rive sound support in Remotion

### ISSUE THREAD

**Issue by federico-hv** [remotion-dev/remotion#3783]
Hi, thanks again for this amazing library. I didn't know if this should be considered a bug or a feature request. Recently Rive [added support for sound](https://rive.app/blog/add-sounds-to-animations-with-audio-events). I tried this with remotion but it seems to not be working yet. I was wondering if updating @rive-app/canvas-advanced to the latest version (2.15.0)  would be enough to add this on remotion too or it would require more effort than that? Audio seems to be working fine in other react apps and is nice cause now you can just add those sounds inside the rive app and everything works just using the .riv file instead of having separate audio files on the web app and call those with events, but I don't know if this would be a problem with how remotion handles sound?

**Comment by JonnyBurger** [comment]
Hi @federico-hv,

thanks for the request! I looked at it and it seems hard to integrate unfortunately. 
Both Rive and Remotion have their own Audio system - in Remotion, we have the `<Audio>` tag, which under the hood is quite complicated, also with support for varying playback rates.
Adding another provider to this pipeline is probably non-trivial.

For this, Rive has currently too little traction that we can consider it an important feature. I recommend to, if you want to add sound effects, place them as `<Audio>` tags alongside the Rive canvas. Sorry!
