### ISSUE TITLE
[Idea] Add paused support for video

### ISSUE THREAD

**Issue by sashee** [remotion-dev/remotion#381]
I record screencasts and I usually want them to play a bit, then pause so that I can explain a concept, then play a bit more, then pause again. I made a Webpack loader that splits an input video at keyframes and also outputs still images ([ref](https://github.com/sashee/video-loader)). This works great, but I'm looking for a more Remotion-friendly solution.

With the support for changing the speed of the Video element and the start-end arguments I can take care of the video scenes part. But AFAIK there is no way to show a single frame of a video as an image. It would be great if the Video element could support the paused attribute.

**Comment by JonnyBurger** [comment]
Thanks for continuing to bring these awesome ideas!

I've drafted a concept of a `<Freeze />` component. You can use it in your project:

```tsx
import {useContext, useMemo} from 'react';
import {Internals, TimelineContextValue} from 'remotion';

type FreezeProps = {
	frame: number;
};

export const Freeze = (props: FreezeProps) => {
	const context = useContext(Internals.Timeline.TimelineContext);
	const value: TimelineContextValue = useMemo(() => {
		return {
			...context,
			frame: props.frame,
		};
	}, [context, props.frame]);

	return <Internals.Timeline.TimelineContext.Provider value={value} />;
};
```

You can use it like this:

```tsx
<Freeze frame={50}>
  <Video {...videoProps} />
</Freeze>
```

It's not yet tested and I just wrote this, but it should work.
What do you think about this? We are considering to add it to the core library.

**Comment by sashee** [comment]
Yes, that would be a more generic solution that would support more use-cases. I haven't tried it yet, but two things came into my mind:

* As the ```<Video>``` element is using a native HTML5 video in development mode, wouldn't this ```<Freeze>``` component interfere with the player?
* And why stop here?:) Instead of a freeze, you could add a ```<Loop>``` with a start and an end frame and play the video between these two frames over and over again. When the start and the end frame is the same it could work the same as the ```<Freeze>```.

**Comment by JonnyBurger** [comment]
@sashee 

- You are probably right, since the video is still playing, it might cause the video to play but then jump back to the frame, which is not very optimal. I wrote an optimized version, now the video should think it's paused:

```tsx
import React, {useContext, useMemo} from 'react';
import {Internals, TimelineContextValue} from 'remotion';

type FreezeProps = {
	frame: number;
};

export const Freeze: React.FC<FreezeProps> = (props) => {
	const context = useContext(Internals.Timeline.TimelineContext);

	const value: TimelineContextValue = useMemo(() => {
		return {
			...context,
			playing: false,
			frame: props.frame,
		};
	}, [context, props.frame]);

	return (
		<Internals.Timeline.TimelineContext.Provider value={value}>
			{props.children}
		</Internals.Timeline.TimelineContext.Provider>
	);
};
```

- I love the idea! 😍  we have an issue for the `loop` #254 property but I think a `<Loop>` component is even better because you can use it for anything. I'll rewrite the other issue!

**Comment by sashee** [comment]
@JonnyBurger , the ```Freeze``` component works great! I had time to experiment with it and it renders a paused video. Thanks!
