### ISSUE TITLE
Sequences children components are not 100% align ONLY in studio mode

### ISSUE THREAD

**Issue by mnlbox** [remotion-dev/remotion#3822]
# Bug Report 🐛

Hi,

I have a sequence with 2 component and 1 audio but the element positions in the Studio is not align:

<img width="528" alt="image" src="https://github.com/remotion-dev/remotion/assets/25859075/89a96175-d4fb-4aec-9a94-9fe07bd25c48">

- The length of audio track and first component is same = 266 frames
- The end frame for all elements is same
- The length of second track is 246 frame (20 frames less than other two element)

I think it's a UI bug but it's not urgent as it doesn't effect on the video in studio or during the render time and the timings are correct there.

**Comment by JonnyBurger** [comment]
You are right, this is weird! We should fix this
