### ISSUE TITLE
Issue with offthreadvideo extracting frames on lambda with preflight request differences.

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3865]
[From message posted on Discord by **jonnyburger**](https://discord.com/channels/809501355504959528/1238460318506811463/1239660807755927633)
----
hmm, thanks for posting!
that seems problematic actually, something that might have gone under my radar and might have just surfaced it

offthreadvideo should not try to extract frames when there is a preflight request
normally there is no preflight request except when the domains differ

but I just realized that on lambda this is different
the website is hosted on S3 but the asset is proxied through localhost

I'll file that! currently I am a bit slower because I am going to react conf but I'm trying to get it this fixed in a new update soon

did you delete the original message? I cannot read it anymore 🤔

**Comment by tsejerome** [comment]
Please note that we didn't face this situation in lambda, but it happens in a ubuntu pm2 server, we are trying to have an instance of g4dn.xlarge, with 6GB ram within the pm2 (reserving the remaining RAM for basic operations like `ls`

**Comment by tsejerome** [comment]
Also attaching our error log and out log in case it is helpful

out-log link (too large so I put on google drive): https://drive.google.com/file/d/1Q-FJI5S27ug6NcK7kATZbMJ6qs3zEfQk/view?usp=sharing
error-log link: [remotion-debian-error-0.log](https://github.com/remotion-dev/remotion/files/15311686/remotion-debian-error-0.log)

Attaching some screenshots that might be relevant - 
<img width="920" alt="image" src="https://github.com/remotion-dev/remotion/assets/20391660/ebb8f60e-8d01-46a7-9de1-cc016c50756a">
<img width="899" alt="image" src="https://github.com/remotion-dev/remotion/assets/20391660/af41e0d1-18d0-4087-a92d-16e6191a061b">

**Comment by JonnyBurger** [comment]
We'll still investigate the issue until the end, but I am closing the issue because OffthreadVideo doesn't have the problem as described in the title.

OffthreadVideo does reply to preflight requests correctly (if there are any) and immediately.

This issue is just the same as https://remotion-git-delay-render-proxy-docs-remotion.vercel.app/docs/troubleshooting/delay-render-proxy
