### ISSUE TITLE
`stitchFramesToVideo` documentation seems to be stale

### ISSUE THREAD

**Issue by Mike-Dax** [remotion-dev/remotion#3893]
# Bug Report 🐛

The argument documentation for [`stitchFramesToVideo`](https://www.remotion.dev/docs/renderer/stitch-frames-to-video) seems to be stale. It no longer takes a `dir` argument.

[`assetsInfo`](https://www.remotion.dev/docs/renderer/stitch-frames-to-video#assetsinfo) appears to contain more than just the audio mix, such as the pattern for file matching for passing to ffmpeg.

It would be nice for that pattern to be passed from `renderFrames` then separately passable into `stitchFramesToVideo`, since `assetsInfo` is considered an opaque internal type to Remotion that might break on version upgrades.

**Comment by JonnyBurger** [comment]
Thanks for filing this!
