### ISSUE TITLE
New `@remotion/fonts` package with `loadFont()` function

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3904]
This package should just wrap the following function (from [here](https://www.remotion.dev/docs/fonts#example-using-local-fonts)):

```tsx
import { continueRender, delayRender, staticFile, cancelRender } from "remotion";
 
const waitForFont = delayRender();
const font = new FontFace(
  `Bangers`,
  `url('${staticFile("bangers.woff2")}') format('woff2')`,
);
 
font
  .load()
  .then(() => {
    document.fonts.add(font);
    continueRender(waitForFont);
  })
  .catch((err) => cancelRender(err));
```

Pain points for users who copy this manually:
- Properly awaiting
- Missing to use url()
- Missing to use `staticFile()`
- Setting the right `format()` value (e.g. putting `otf` instead of `opentype`)
- Messing up the parentheses
- Missing error handling
- Missing that there are options you can pass:
<img width="1013" alt="image" src="https://github.com/remotion-dev/remotion/assets/1629785/6356ca83-6436-4d1f-b8bd-26a83a5c68b8">

We should make an API that is easier: `loadFont()` and it should live in a new package `@remotion/fonts`.

## Acceptance criteria

1. Implement a function with this signature:

```tsx
import {loadFont} from "@remotion/fonts";

await loadFont({
	fontFamily: 'some name',
	url: 'someName',
	weight: '500',
	// ... the other options as seen in the screenshot above
})
```

2. Create documentation for this page similar to other packages - main page and 1 page for the specific `loadFont()` function. All options should be documented and have similar or better quality than the other documentation pages.
3. Add a sample composition to `packages/example` so we can test the function. For this, add `@remotion/fonts` to it's package.json

## Bounty

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 300

**Comment by benya7** [comment]
Hi! I'm interested in working on this. Thank you
/attemp

**Comment by benya7** [comment]
Hi! I'm interested in working on this. Thank you.

/attempt

**Comment by JonnyBurger** [comment]
Cool! Good luck @benya7!

**Comment by abhishek818** [comment]
Adding myself in the queue..
