### ISSUE TITLE
Video's load method being called repeatedly in player causing flickering

### ISSUE THREAD

**Issue by calebfoss** [remotion-dev/remotion#3915]
# Bug Report 🐛

When using Remotion 4.0.160 in Firefox 126.0 on Windows 10, videos in a player are flickering when loading with pauseWhenBuffering set to true. It looks like this is  #3888 because the issue started when updating to this version of Remotion, and in the debugger I am seeing current.load() being called repeatedly with readyState at 4 and HAVE_FUTURE_DATA at 3. When I set pauseWhenBuffering to false, the issue is not present. I tried updating to 4.0.163 just in case, but the issue is still there.

Thank you for fixing the Electron for loop issue with that version by the way! That was fast, and I can confirm that it fixed the issue I was seeing!

**Comment by JonnyBurger** [comment]
Thanks!

Trying to get a fix out by Monday.
Weird because .load() should only be called with readyState < 3

So maybe I need to disable it for Firefox
