### ISSUE TITLE
How to upgrade Remotion?

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3959]
We should write a doc for it, surprised we don't have one

**Comment by DhairyaMajmudar** [comment]
Hi @JonnyBurger I would love to go for this issue can you pls. provide some reference from which I can start

**Comment by JonnyBurger** [comment]
@DhairyaMajmudar This is not a bounty issue, hence /attempt does nothing.

If you like to contribute nonetheless, I can write up some requirements!

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar This is not a bounty issue, hence /attempt does nothing.
> 
> If you like to contribute nonetheless, I can write up some requirements!

I would love to contribute, but it will be really great of you if its converted into bounty

**Comment by JonnyBurger** [comment]
Thanks for that!
We are posting some bounties soon and then also properly assist whoever works on it. 

This is now fixed in https://github.com/remotion-dev/remotion/pull/3974
