### ISSUE TITLE
template repository for remotion player

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#396]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/396)

CRA or Next.JS (with SSR)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($100.00)

### Submitted pull Requests
- [#471 add nextjs-remotion-example](https://issuehunt.io/r/JonnyBurger/remotion/pull/471)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by sohamsshah** [comment]
Hey can I work on this? I just came across this project and found it quite interesting to contribute to!

**Comment by Iamshankhadeep** [comment]
@sohamsshah definately go ahead and if you face any issue just tag Jonny or me on discord or github.

**Comment by JonnyBurger** [comment]
@sohamsshah Definitely!

To quickly elaborate the idea a bit further, the idea is to create a minimal template of a Next.JS project with the Remotion Player pre-installed.

If possible, we even add server-side rendering using our Node.JS APIs but I am not sure if it's even possible, so this can be an additional step later.

**Comment by sohamsshah** [comment]
Thanks Man. Is it okay if I take a bit time to solve this issue (4-5 days) ? Actually I am not pro with NextJS, so gotta explore that; but surely I will keep you posted with updates on this task.

Also, can you also elaborate upon Node.js APIs? Quite interested on that!

**Comment by JonnyBurger** [comment]
I also added a bounty so that if you work on it doesn't have to be for free 🙌🏼

**Comment by sohamsshah** [comment]
> For sure, take your time! Any progress is appreciated, if it takes longer, you can always make a draft PR and we can easily help out.
> 
> The NodeJS APIs are a bunch of functions that allow one to render Remotion videos on the server side. Since NextJS also can run server-side code it would be interesting to see if we can get this to run. Maybe it's hard on Vercel because it uses lambda functions but then we could still try to get it to work for other hosting services.
> 
> It's all documented here: https://www.remotion.dev/docs/ssr/

Wow! This is super impressive. Actually I had a nice OSS project Idea that uses Remotion, and was exactly looking for something like this!

**Comment by sohamsshah** [comment]
> I also added a bounty so that if you work on it doesn't have to be for free 🙌🏼

This is a real great motivation man. Appreciate it and thanks. Will be working on this :)

**Comment by JonnyBurger** [comment]
The plan for this issue is to integrate it with Lambda once it's released so you can render videos with scale and then announce the template 🚀

**Comment by JonnyBurger** [comment]
Closing this in favor of #809 which also includes the Player
