### ISSUE TITLE
In Studio, preview is not consistently centered when adding/removing sidebars

### ISSUE THREAD

**Issue by UmungoBungo** [remotion-dev/remotion#3997]
# Bug Report 🐛

https://github.com/remotion-dev/remotion/assets/22192773/7700194f-a42f-4ca2-9792-35296522ed13

1. Make the preview small by setting the scale to 25%
2. Turn off both sidebars
3. Enable the left-hand sidebar, and see the preview pushed to the right and no longer appear centered in the available space.
4. Enable the right-hand sidebar, and then disable it. Only the left-hand sidebar is enabled, and the preview is now correctly centered.

**Comment by JonnyBurger** [comment]
Thanks for reporting!
