### ISSUE TITLE
Lambda v4.0.174 may not clean up resolved-props after error

### ISSUE THREAD

**Issue by mw10013** [remotion-dev/remotion#4006]
# Bug Report 🐛

Remotion 4.0.174

Screenshot below shows instance on 6/16/2024 where resolved-props were not cleaned up.
 
<img width="1251" alt="Screenshot 2024-06-16 at 8 59 07 PM" src="https://github.com/remotion-dev/remotion/assets/425584/792f3ef6-24f5-4a13-b037-4b7b4913c6dc">

This may be due to a main function error of TooManyRequestsException, perhaps because we hit our concurrency limit of 1000.

<img width="1391" alt="Screenshot 2024-06-16 at 9 06 03 PM" src="https://github.com/remotion-dev/remotion/assets/425584/a82ad514-5b09-425a-b2e9-b5aafb44994f">

And seems to cause a timeout.

<img width="1268" alt="Screenshot 2024-06-16 at 9 08 42 PM" src="https://github.com/remotion-dev/remotion/assets/425584/ef3eacd9-e993-4a98-91fc-58b0fc83dd4f">

**Comment by JonnyBurger** [comment]
Thanks for reporting!
