### ISSUE TITLE
Recorder: Document how to crop a video

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#4015]
With OBS Virtual Camera

**Comment by hunxjunedo** [comment]
Hey @JonnyBurger ! Requesting assignment,  would love to contribute!

**Comment by JonnyBurger** [comment]
Hey @hunxjunedo!
Since the Recorder is a commercial product of ours, we'll not ask for external help. Wouldn't be fair, thanks for your offer though!

**Comment by estiny001** [comment]
Great

**Comment by estiny001** [comment]
jjj
