### ISSUE TITLE
timeline preview images missing

### ISSUE THREAD

**Issue by 3tlam** [remotion-dev/remotion#405]
Hi Jonny!
Thanks so much for remotion!

I'm new to react and so this might be a stupid question / problem, but I'm out of my depth right now.
Everything works locally, but once I push it to glitch.me or a custom server running pm2 + nginx the timeline images are no longer displayed:
should be like this:
![image](https://user-images.githubusercontent.com/6067365/120074074-6f9dab80-c09b-11eb-9fbf-6a276a9f8bd5.png)

but it shows as
![image](https://user-images.githubusercontent.com/6067365/120073787-226d0a00-c09a-11eb-8fff-3fa46b315d80.png)

`FullImg` and `FullImg2` are `AbsoluteFill` images that are animated.
Once on a server I can see the http request to the image and then it is loaded, but the image get's loaded on every iteration of the timeline and takes a couple of seconds.

Images can be selected using URL params and I think I did everytging according to the docs (Webpack dynamic imports).

```jsx
/* Video.tsx */
const params = new URLSearchParams(windowUrl);
(..)
const img = params.has('img') ? params.get('img') : 'tea.jpg';
const img2 = params.has('img2') ? params.get('img2') : 'tea.jpg';

return (
	<>
		<Composition
			id="Comp"
			component={Comp}
			durationInFrames={400}
			fps={30}
			width={1920}
			height={1080}
			defaultProps={{
				(..)
				img: img,
				img2: img2,
			}}
		/>
	</>

/* Comp.tsx just passes those along to `FullImg` and `FullImg2` */

/* FullImg.tsx */
(..)
export const FullImg: React.FC<{
	img: string;
}> = ({img}) => {
  const frame = useCurrentFrame();
	const videoConfig = useVideoConfig();
	const imgsrc = require(`../assets/imgs/${img}`);
(..)
```

Any idea what I am doing wrong?
Also sorry, if I've not given all the necessary details :(

//edit: this isn't tooo bad to be honest, my main concern it, that during the first timeline play the images are not loaded already and therefore the animation is not really working and looks choppy. on the second play everything seems to be loaded

Thanks!!

**Comment by JonnyBurger** [comment]
Hey Malte!

Sorry for the late response, I kind of lost track of the issues!

My suspicion is that when proxying, you are serving the preview on a different domain and the settings get reset since Remotion stores them in Local Storage.

The setting for showing the thumnail images is "Rich Timeline" and is by **default off**. That means you should be able to enable it again by toggling the rich timeline: https://www.remotion.dev/docs/timeline/

**Comment by 3tlam** [comment]
Hey Jonny

no worries! Thanks for the answer anyway!
And for my stupidity of not being able to switch die timeline... works fine now ;)

Any idea how get by the proxy issue?
Is there a config option that I might've missed?

Thanks!

**Comment by JonnyBurger** [comment]
@3tlam I don't quite understand the proxy issue you are having, sorry. The images gets reloaded more often than when running via `npm start`?

**Comment by JonnyBurger** [comment]
Just as an FYI, Unless I get a response, I'll close this soon!
