### ISSUE TITLE
Add concurrency in RenderMediaOnProgress callback arguments for better estimating

### ISSUE THREAD

**Issue by XeroAlpha** [remotion-dev/remotion#4051]
# Feature Request 🛍️

The `progress.renderEstimatedTime` value in the `RenderMediaOnProgress` callback represents the sum of the estimated rendering times for each remaining page. To obtain the actual estimated rendering time, I need to divide it by the `concurrency` field. Therefore, it would be helpful to include the `concurrency` field in order to perform the calculation.

## Use Case

```ts
await renderMedia({
  onProgress({ progress, renderEstimatedTime, concurrency }) {
    console.log(`${progress * 100}% ${renderEstimatedTime / concurrency / 1000} second(s) left`);
  }
});
```

**Comment by JonnyBurger** [comment]
Thanks for the suggestion!
