### ISSUE TITLE
motion canvas' Camera api is missing. 

### ISSUE THREAD

**Issue by aliveornot** [remotion-dev/remotion#4061]
Hi, thanks for your great your work.

While exploring this repository, I noticed that the [Camera API](https://motioncanvas.io/api/2d/components/Camera) from Motion Canvas, which I found quite useful, is missing. Could you kindly inform me if there are any plans to reintroduce it in the future, or if there was a specific reason for its removal?

**Comment by JonnyBurger** [comment]
We are a completely different project than Motion Canvas, maybe you meant to file on Motion Canvas or re.video?

**Comment by aliveornot** [comment]
Oh my.... What have I done..

You're right. I'm mistaken. I apologize.
