### ISSUE TITLE
Throw error is setWebpackOverride() is specified multiple times

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#4063]
`remotion.config.ts`:
```ts
import {Config} from "@remotion/config/cli"

Config.overrideWebpackConfig((c) => enableSass(c));
Config.overrideWebpackConfig((c) => enableTailwind(c))
```

is wrong. Only the last override is applied. It should throw an error if this is happening.  
Instead, it should be 

```ts
Config.overrideWebpackConfig(c => enableSass(enableTailwind(c)));
```

## Acceptance criteria

It should give a nice error message if the user makes this mistake.  
Here is the override logic: https://github.com/remotion-dev/remotion/blob/929a56204956ef37231ab907f07ae1040b7e1e01/packages/cli/src/config/override-webpack.ts#L16
Probably this can be easily tested by just using the testbed: https://www.remotion.dev/docs/contributing/#testing-your-changes
It should also be mentioned somewhere in the docs how to correctly apply multiple webpack overrides so we can link to it.
Ideally the error message also links to that doc article.

/bounty 80

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

**Comment by hunxjunedo** [comment]
/attempt #4063
Hey! can I get assigned?

**Comment by JonnyBurger** [comment]
@hunxjunedo Yes, thanks for grabbing!

**Comment by abhishek818** [comment]
@JonnyBurger adding myself in queue..

**Comment by hunxjunedo** [comment]
@JonnyBurger I've just reached a solution, however I have a question: should it throw a warning and continue or throw an error and terminate and exit ? Please guide me here.
