### ISSUE TITLE
paintOrder property is not supported in AWS Lambda.

### ISSUE THREAD

**Issue by UMCEKO** [remotion-dev/remotion#4080]
# Bug Report 🐛

The paintOrder property works in my browser on remotion studio, and also I can initiate a render from code with the rendering api without it breaking. The issue lies in aws lambda not supporting this crucial feature (for our project).

**Comment by UMCEKO** [comment]
![image](https://github.com/user-attachments/assets/f2242ebe-db56-40f3-8e63-471d305f1c1a)
This is how it should look like ^

![image](https://github.com/user-attachments/assets/d6e41d20-5574-4784-ac5d-9dd9755cb57c)
This is how it looks

**Comment by JonnyBurger** [comment]
The Chrome on Lambda is v114: https://www.remotion.dev/docs/lambda/runtime#chrome

On this page you can find how to enable a newer version of Chrome also! This new runtime should then support the paint-order property.
