### ISSUE TITLE
tailwind config file not found unless command is run from project root

### ISSUE THREAD

**Issue by kirankunigiri** [remotion-dev/remotion#4097]
# Bug Report 🐛

I have a monorepo with client and server project folders. I setup a command to run remotion studio from the monorepo root. While the studio starts, the `~/client/tailwind.config.js` doesn't get picked up and tailwind doesn't work, since the command is being run from `~` root.

This starts studio, but tailwind won't work.
`bunx remotion studio client/src/remotion/index.ts --config client/src/remotion/remotion.config.ts`

What works is `cd` into the client folder, and then running studio
`cd client && bunx remotion studio ./src/remotion/index.ts --config ./src/remotion/remotion.config.ts`

This is only a minor inconvenience, so perhaps it doesn't need a fix. It would help to add this to the docs (something about how the command needs to be run from the project root), as I spent a bit of time figuring out why my tailwind config file wasn't being picked up. If a flag is easy enough to add, it would be great to have an option like `--tailwindConfig` to pass the tailwind config file path manually.

**Comment by JonnyBurger** [comment]
Thanks for reporting! See the PR with the updated docs for an example how you can fix this.
I think we cannot automatically do it because the `__dirname` is different in our source code.
