### ISSUE TITLE
Suspense support 

### ISSUE THREAD

**Issue by jeetiss** [remotion-dev/remotion#41]
Remotion allow pause render with `delayRender/continueRender` but it can be implemented with `Suspense`

previous discussion: https://github.com/JonnyBurger/remotion/issues/29

**Comment by JonnyBurger** [comment]
Thanks for bringing it up!

I am looking through the examples but would like to understand the use case more. It seems like if you use Suspense, you still need a custom hook, or a custom <Img/> component... is it supposed to bring a benefit over the current implementation of <Img/> component?

Btw, Remotion currently supports Suspense in a way that you can lazy load compositions. https://www.remotion.dev/docs/composition#api

So I'm a fan of it but would want to understand the use case better.

**Comment by JonnyBurger** [comment]
Do you still want to proceed with this idea? @jeetiss?

As I mentioned I don't quite understand the motivation. I'll close it soon if no more comments come.

**Comment by jeetiss** [comment]
Hey, I wanna improve remotion's resource management overall

Remotion should have track ability for all heavy videos, audios, images, thats help build better ux for preview / embedded player and maybe be helpful for audio support. So `Suspemse` is one way how to achieve better RM

Strong Suspense parts:
- this isn't Remotion's specific feature like `delayRender/continueRender` and can be used in all react environments
- all components and libraries for fetching data that supports suspense should work out of the box
- small learning curve

Weak parts: 
- Suspense doesn't allow easily preload all resources on all frames 
- it still experimental and will be changed in near future 

I've experimented little bit with Suspense, but I don't like result ):
https://codesandbox.io/s/react-cache-forked-9xhfo

Do you have any thoughts about this?

**Comment by JonnyBurger** [comment]
I have played around with it and there is some support for Suspense in Remotion for loading components. If you add an import with `lazyComponent` (https://www.remotion.dev/docs/composition/), it will load it with Suspense and I even enabled the new Webpack lazy compilation feature so it even only compiles the composition when it's accessed.

I support the vision of expanding this to more things 👍  the thing with heavy video/images is that they are loaded from a file, Webpack shouldn't have to do any processing, I think JS assets are way more heavy on the bundling time. Browser should also already have capability to do smart buffering, so not sure if Suspense can help.

I always like the things that you come up with, so I totally support you researching these things 👍

**Comment by JonnyBurger** [comment]
All Remotion videos are automatically wrapped in <Suspense>, therefore you should be able to use it without problems. I'll close this soon unless someone wants to bring up a suggestion what we should do.
