### ISSUE TITLE
Lint conflict issue in my NX workspace for @remotion/eslint-config package

### ISSUE THREAD

**Issue by mnlbox** [remotion-dev/remotion#4127]
# Bug Report 🐛
Hi @JonnyBurger ,
 
I just wanted to report this issue. I upgrade my NX workspace from v18 to V19 and my workspace stopped working with this error:
```
An error occurred while processing files for the @nx/eslint/plugin plugin.
    - videos/remotion-vid1/.eslintrc: Plugin "@typescript-eslint" was conflicted between ".eslintrc » @remotion/eslint-config#overrides[0] » plugin:@typescript-eslint/recommended » ./configs/base" and "../../.eslintrc.json#overrides[1] » plugin:@nx/typescript".
      Error: Plugin "@typescript-eslint" was conflicted between ".eslintrc » @remotion/eslint-config#overrides[0] » plugin:@typescript-eslint/recommended » ./configs/base" and "../../.eslintrc.json#overrides[1] » plugin:@nx/typescript".
```

Maybe related to this PR: https://github.com/nrwl/nx/pull/26011

**Comment by JonnyBurger** [comment]
This error does not come from us, but either from ESLint or NX side.
The config is meant to be used standalone and not mixed with other configs, which indeed might conflict.

Maybe remove either the Remotion or NX config and only use one of them?
You can still use the Remotion ESLint Plugin probably `@remotion/eslint-plugin` without having to use `@remotion/eslint-config`

**Comment by mnlbox** [comment]
@JonnyBurger  Can you explain a bit more? I still have eslint error.
Should I remove the `.eslintrc` file in the root of my Remotion project?
```
{
	"extends": "@remotion",
	"env": {
		"node": true
	}
}

```

Can you clarify this part of your message, please?

> You can still use the Remotion ESLint Plugin probably @remotion/eslint-plugin without having to use @remotion/eslint-config

**Comment by mnlbox** [comment]
@JonnyBurger Any idea about this? 👆👆👆
