### ISSUE TITLE
Clipping Audio

### ISSUE THREAD

**Issue by gpiechnik2** [remotion-dev/remotion#4143]
Hey! I'm currently working on an application designed to help with audio and video editing. I'm implementing a solution in Remotion. My (simplified) code looks like this:

```javascript
const audioFiles = Array.from({ length: 20 }, (_, index) => ({
  src: "npc.mp3",
  from: index * 30,
  startFrom: index * 30,
  endAt: (index + 1) * 30
}));

return (
  <div ref={ref}>
    <AbsoluteFill >
      {audioFiles.map((audio, index) => (
        <Sequence key={index} from={audio.from}>
          <Audio
            key={index}
            src={audio.src}
            startFrom={audio.startFrom}
            endAt={audio.endAt}
          />
        </Sequence>
      ))}
    </AbsoluteFill>
  </div>
)
```

While testing the whole setup in <Player />, I can hear subtle transitions between the <Audio /> clips. I'm wondering how I can bypass this issue "natively" in Remotion. I've tried modifying parameters like endAt, but it doesn't achieve the desired smooth transitions.

Example audio below.

https://github.com/user-attachments/assets/e12f9bdd-0c78-4d53-abd5-bd894b3b1995

**Comment by JonnyBurger** [comment]
Hey @gpiechnik2!

We can investigate more deeply, but the thing that comes to mind is that premounting could help here: https://www.remotion.dev/docs/player/premounting

(Apply the premountFor prop to your Sequence tag in this case)
