### ISSUE TITLE
[install-whisper-cpp]DTW parameter is incorrect for large model

### ISSUE THREAD

**Issue by zhaoshengjun** [remotion-dev/remotion#4168]
# Bug Report 🐛

When using large model(including `large-v1/v2/v3`)  for `transcribe` function, it will throw an error " error: unknown DTW preset 'large-v3'".

This is due to the `dtw` parameter used in `whisper.cpp` for large model is not using `-`, but instead it's using `.`. e.g.: `large.v3`
Here's the link to the source: 
https://github.com/ggerganov/whisper.cpp/blob/fe36c909715e6751277ddb020e7892c7670b61d4/examples/main/main.cpp#L997

**Comment by JonnyBurger** [comment]
Thanks for reporting!

**Comment by zhaoshengjun** [comment]
👍 Appreciate the quick response!

**Comment by saurabhthesuperhero** [comment]
@zhaoshengjun I am still facing this error : 
Model already exists at /Users/saurabhthesuperhero/Documents/template-tiktok/whisper.cpp/ggml-large-v3-turbo.bin
Extracting audio from file vv.mp4
/Users/saurabhthesuperhero/Documents/template-tiktok/node_modules/@remotion/install-whisper-cpp/dist/transcribe.js:149
            reject(new Error(`No transcription was created (process exited with code ${code}): ${output}`));
                   ^

Error: No transcription was created (process exited with code 3): error: input file not found 'true'
error: unknown DTW preset 'large.v3.turbo'

    at ChildProcess.<anonymous> (/Users/saurabhthesuperhero/Documents/template-tiktok/node_modules/@remotion/install-whisper-cpp/dist/transcribe.js:149:20)
    at ChildProcess.emit (node:events:507:28)
    at ChildProcess._handle.onexit (node:in

Any suggestions ?
