### ISSUE TITLE
 Issues with Render Button and UI Changes After Deploying Remotion Project to S3 Bucket

### ISSUE THREAD

**Issue by Kunj-dhakad** [remotion-dev/remotion#4176]
Hi everyone,

I've deployed my Remotion project to an S3 bucket and set up Lambda for rendering. However, I'm encountering a couple of issues:

Render Button Visibility: After deployment, the render popup does not appear on the live site, although it works correctly in my local environment. Has anyone experienced this issue or have suggestions on how to fix it?

UI Customization: I'm also having difficulty changing the UI and adding a render button. Could anyone provide guidance on how to make UI changes and properly integrate the render button?

Any help or advice would be greatly appreciated!

Thanks in advance!

**Comment by JonnyBurger** [comment]
Hi @Kunj-dhakad,

rendering is only possible with a server. 
A site deployed to S3 is a static site without any server attached to it (https://www.remotion.dev/docs/studio/deploy-static)

But you can take the URL and pass it to a Remotion Lambda API like `npx remotion lambda render` or `renderMediaOnLambda()` (search the docs to see how to use these APIs).


Regarding customization of the Remotion Studio, we don't support that or just to a very limited extent.
If you want to build a custom UI around the Player, you need to use the Remotion Player in a regular React project.

Here is a guide explaining how to convert a Studio to an app: https://www.remotion.dev/docs/studio-into-app

**Comment by Kunj-dhakad** [comment]
I want to create a video editor, but I've run into an issue. I understand that rendering is only possible with a server, and since the site deployed to S3 is a static site, there isn't a server attached to it. However, I want to provide users with a render button after the site is hosted on S3, instead of expecting them to use the npx remotion lambda render command.

How can I enable a render button in the UI after deploying the website to an S3 bucket? Currently, the render option isn't showing up after deployment.

**Comment by Kunj-dhakad** [comment]
I have deployed my project to S3  `https://remotionlambda-useast1-qe2jk3zrmz.s3.amazonaws.com/sites/videoeditor/index.html?/MyComp.` However, the render button is still not showing up. Could you please help me resolve this issue?"

@
![Screenshot 2024-08-08 181922](https://github.com/user-attachments/assets/9a22ad3d-f6ef-4a71-acef-4b7c2bf6bde3)
