### ISSUE TITLE
TypeError Cannot read properties of null (reading 'children')

### ISSUE THREAD

**Issue by shaurya-sharma064** [remotion-dev/remotion#4190]
# Bug Report 🐛

TypeError
Cannot read properties of null (reading 'children')

injectedScript.js:29 Uncaught TypeError: Cannot read properties of null (reading 'children')
    at findReactComponents (injectedScript.js:29:22)
    at injectedScript.js:44:25
    
Getting this error on both my react setups tried changing node version npm etc nothing works

**Comment by JonnyBurger** [comment]
Its not from Remotion either.

`injectedScript` leads me to
believe that this comes from a Chrome extension. Try disabling all of them.
