### ISSUE TITLE
Amazon Linux 2023 EC2 - version `GLIBC_2.35' not found

### ISSUE THREAD

**Issue by deepaktammali** [remotion-dev/remotion#4207]
Hello, thanks for the library.

As the title suggest, I am trying to render a video with Amazon Linux 2023 AMI image in EC2 and I am facing this error. I read that Amazon Linux 2023 comes with GLIBC_2.34. How can I fix this?

**Comment by JonnyBurger** [comment]
I think the x86 version of our Linux GNU compositor is compiled to require Libc 2.35 (sorry, the documentation is wrong then - I'll fix that)

But the ARM version is compiled with Amazon Linux 2023 itself!
Can you consider using the arm64 container with Graviton? It's also faster and cheaper.
