### ISSUE TITLE
Typo, missing plural "s" in `unrotatedDimension`?

### ISSUE THREAD

**Issue by mortenjust** [remotion-dev/remotion#4209]
Hi, thanks for making this! Not sure if this is a typo, here's why it could be: 

It looks like the `Options` type has the plural "s".
The `dimensions` option has the plural "s".

https://github.com/remotion-dev/remotion/blob/bd8fd039924008afb1bb4c9e8530f866a4c63bae/packages/media-parser/src/options.ts#L46

**Comment by JonnyBurger** [comment]
Thanks a lot for reporting!
