### ISSUE TITLE
@remotion/player - Very very low performance on Safari, almost unplayable

### ISSUE THREAD

**Issue by leogaudin** [remotion-dev/remotion#4214]
Hello,

The issue is pretty straightforward, **videos do not play correctly at all on Safari** (the sound is glitched too), **but perfectly on Chrome and others**.

Already tried rendering an **OffthreadVideo** instead of a Video component, **prefetching**, putting **only memoized input props**, etc.

The following example is done with the mentioned optimization intents.

https://github.com/user-attachments/assets/1e08db57-c5b8-4558-ab01-8c6ccafcf9eb

**Comment by JonnyBurger** [comment]
This definitely should not be if the video plays well in Safari otherwise.
It's also highly dependent on the video.

Are you using `pauseWhenBuffering`?
Which Remotion version is this on?

Do you want to post the source video so I can reproduce the issue?

**Comment by leogaudin** [comment]
> This definitely should not be if the video plays well in Safari otherwise. It's also highly dependent on the video.
> 
> Are you using `pauseWhenBuffering`? Which Remotion version is this on?
> 
> Do you want to post the source video so I can reproduce the issue?

**Using `pauseWhenBuffering` fixes the issue on Safari.**

Thank you a lot!
