### ISSUE TITLE
Is Remotion Studio Required for AWS S3 Bucket Deployment with npx create-video@latest Template?

### ISSUE THREAD

**Issue by Kunj-dhakad** [remotion-dev/remotion#4227]
"Hi Remotion Team,

I am using the npx create-video@latest --next-tailwind template to set up my project. However, when I run node deploy.mjs, it results in deploying Remotion Studio to my S3 bucket, which is not my intention.

I want to build a video editor using Remotion Player and Remotion Rendering. Could you please clarify the following:

Is it necessary to include Remotion Studio in the S3 bucket deployment, or can I deploy only the Remotion Player and still achieve the desired video rendering functionality?
Do I need to host the site with a serve URL separately from the video editor, or can both be managed within the same S3 bucket?
The documentation did not provide clear guidance on this. Any help to understand this setup would be greatly appreciated.

Thank you!"

**Comment by JonnyBurger** [comment]
You'll need both - deploy the Remotion project using `node deploy.mjs` - this gives you a URL that you can render the video with! Yes, it displays the Studio but you can disregard this.

If you want to deploy the Next.js app and build a user interface around your Player, you use:

- `npm run dev` during development
- You push the Next.js project to Vercel or Netlify, and you deploy it like any other Next.js project.

Your Next.js project can then reference the URL that the Remotion Studio is hosted on, when you are calling renderMediaOnLambda() in your Next.js function.

So both is needed, but it seems like you are on a good way!
