### ISSUE TITLE
Remotion renderMedia gets stuck

### ISSUE THREAD

**Issue by deepaktammali** [remotion-dev/remotion#4233]
Hello,

I am trying to generate a video using renderMedia and the process sometimes get stuck with the following as the last log in with logging set to verbose
[compositor] Starting Rust process. Max video cache size: X MB, max concurrency = Y

Thanks.

Thanks.

**Comment by JonnyBurger** [comment]
This issue could arise for example if you have a delayRender() handle open and a big timeout so nothing happens.
Try reducing the `--timeout`, and you will get an error eventually, with a stacktrace from which you will be able to tell the problem.
