### ISSUE TITLE
CORS issue in video preview

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#4247]
[From message posted on Discord by **borjasoler**](https://discord.com/channels/809501355504959528/1276582276045607034/1278041663247224853)
----
I am having similar errors, since upgrading from 4.0.180 to 4.0.204

I am getting the following error on my player: Access to video at 'https://domain.nyc3.cdn.digitaloceanspaces.com/Videotok/backgrounds-videos/squares-animated-white.webm#t=0,2.57' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by ntgussoni** [comment]
Im having the same issue but from cloudflare. Only when by having the disable cache option while keeping the console open works. 

I'm wondering if this person is also using Nextjs. It's most likely the patched fetch messing with this.

**Comment by JonnyBurger** [comment]
It is fixed in 4.0.206! :)

**Comment by ntgussoni** [comment]
I confirm it's working, thanks a lot!
