### ISSUE TITLE
Preview and rendered image are different

### ISSUE THREAD

**Issue by andrasferenczi** [remotion-dev/remotion#4262]
# Bug Report 🐛

I just found out that sometimes Remotion renders the content differently from the preview. I haven't tracked down the why (it seems to be related to the `align-self`), but I have some reproducible code at least. 

I don't know at this point if this CSS makes much sense (bit tired atm), but the point is that regardless how weird the CSS is, I think the exact same result for the preview and the rendered frame should be produced.

Code:

```typescript
export const HelloWorld: React.FC<z.infer<typeof myCompSchema>> = () => {
    return (
        <div style={{
            position: 'relative',
            backgroundColor: "#663300",
            width: '100%',
            height: '100%',
            display: 'flex',
        }}>
            <p style={{
                color: '#ffffff',
                fontSize: 200,
                lineHeight: 0.2,
                margin: 0,
                position: "absolute",
                top: 0,
                left: 0,
                bottom: 0,
                right: 0,
                textAlign: "center",
                alignSelf: "center",
            }}>Some text here</p>
        </div>
    );
};
```

Screenshot:

<img width="1086" alt="Screenshot 2024-09-02 at 22 42 34" src="https://github.com/user-attachments/assets/2cdc3a22-bcd7-4582-8ad2-bbc372163cc3">

Rendered image:

![HelloWorld](https://github.com/user-attachments/assets/ce59b1c0-7a80-4dc5-8161-78e56ccf98d2)

Reproducible code is on [this](https://github.com/andrasferenczi/remotion-issues/tree/render-vs-preview-diff-bug) branch.

**Comment by JonnyBurger** [comment]
Hi, thanks for making a reproduction!

I get the correctly centered text when rendering a video or still.
I think it has to do with the browser that is being used when rendering. Maybe it uses an old version of Chrome during rendering. If you enable verbose logging, then you can see which one is used.

What is working for sure though: v4.0.208!
It will use Chrome Headless Shell. From this version on, everybody will always use the same version of Chrome for rendering, ruling out these kind of differences between our setups.

If you run `npx remotion upgrade`, your next render will be successful :)

**Comment by andrasferenczi** [comment]
Awesome, it is indeed the same on v4.0.208. Thanks for the reply!
