### ISSUE TITLE
Guidance Needed on Controlling Video Duration and Image Timing in Remotion Editor

### ISSUE THREAD

**Issue by Kunj-dhakad** [remotion-dev/remotion#4263]
Hi Remotion Team,

I am building a video editor using the Next.js (App directory + TailwindCSS) template, and I've created a basic video editor. However, I'm struggling with managing some aspects like video duration, image position, and when an image should appear or disappear in the composition.

Here is a part of my current setup:

import { z } from "zod";

export const COMP_NAME = "MyComp";

export const CompositionProps = z.object({
  title: z.string(),
  image: z.string(),
  video: z.string(),
});

export const defaultMyCompProps: z.infer<typeof CompositionProps> = {
  title: "Welcome to my video editor",
  image: "https://picsum.photos/200/300",
  video: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
};

export const DURATION_IN_FRAMES = 200;
export const VIDEO_WIDTH = 1280;
export const VIDEO_HEIGHT = 720;
export const VIDEO_FPS = 30;

With the above setup, I'm able to pass only basic JSON data (like title, image, and video). I haven't found any documentation that helps with managing more complex properties like specific frame timings for showing/hiding images or setting video durations dynamically.

Could you please guide me on how to send more detailed JSON data to control these aspects or point me to the relevant documentation?

Thank you for your help!

**Comment by JonnyBurger** [comment]
Usually people pass in a JSON array of layers.

Each layer is rendered as a `<Sequence>` and may contain timing information such as `start` and `end`.

They also support multiple layer types (z.discriminatedUnion) such as `type: "image"`, `type: "title"` and so on.
For each layer type there can be more properties such as `src` for videos or `text` for titles.

You loop over this array with `.map` and render each layer, the one that gets rendered last appears at the top.
