### ISSUE TITLE
Problems with rendering - Video rendered twice

### ISSUE THREAD

**Issue by reactone** [remotion-dev/remotion#4276]
Im using C LI rendering in node and suddenly the video started to render twice, next to each other. I thought I introduced it but when I reverted to an old branch I can see the issue as well and it definitely wasnt happening before. The only thing I did is upgrading the macOS to the latest (not sure if this is anyhow related though). I also checked different version of Node but it happens everytime. Here is how it looks like:

![rendering-bug](https://github.com/user-attachments/assets/b92c720b-e571-4870-a529-06bea51805a3)

The frame (15) is repeated twice. Also the additional video on the right is flickering. Any ideas how to fix it?

**Comment by JonnyBurger** [comment]
I never heard of such an issue - if it renders twice, then my question is: Does it also appear twice in the DOM tree if you open the DevTools?

**Comment by reactone** [comment]
Very odd, I think it appeared after upgrading Chrome from quite an old version.  Its all good after upgrading remotion to the newest package - I was on 4.0.84 so quite an ancient one. Closing now.

**Comment by JonnyBurger** [comment]
Yes could be now we pin Chrome to a specific version that we test, so hopefully this doesn't happen again!
