### ISSUE TITLE
Add net::ERR_NETWORK_CHANGED to the list of flaky errors

### ISSUE THREAD

**Issue by samohovets** [remotion-dev/remotion#4320]
**net::ERR_NETWORK_CHANGED** is a Chrome-specific error that occurs when the user's network state changes

The use case is this: when waking up the rendering machine via Wake on LAN and render starts immediately, it's common to get an error like this because the machine may re-arrange / switch between internal LAN adapters. Or switch between Wi-Fi or LAN connection.

**Comment by JonnyBurger** [comment]
Good idea!

**Comment by samohovets** [comment]
Thank you so much for implementing @JonnyBurger!

**Comment by samohovets** [comment]
@JonnyBurger Oh I just noticed that the flaky errors concept applies only to `@remotion/lambda`? It won't restart render in `@remotion/renderer` in case of a flaky error?

**Comment by samohovets** [comment]
Awesome! Thank you 🤝
