### ISSUE TITLE
`metadata` field for `renderMedia()`, `renderMediaOnLambda()` and `renderMediaOnCloudRun()` API

### ISSUE THREAD

**Issue by 9vs** [remotion-dev/remotion#4342]
I would like to request a feature that enables the modification of EXIF data, such as the "Comment" and "Author" fields, after a video has been rendered via AWS Lambda.

**Comment by JonnyBurger** [comment]
In https://github.com/remotion-dev/remotion/blob/main/packages/renderer/src/stitch-frames-to-video.ts, we add `-metadata` to the video and in https://github.com/remotion-dev/remotion/blob/4f5aeeaf5b33bcf615c9485c975f24a217b86085/packages/renderer/src/mux-video-and-audio.ts#L46 as well.

- There should be an option to pass an object to renderMedia() and renderMediaOnLambda()

```tsx
renderMedia({
	metadata: {
		'Author': 'Lunar'
	}
})
```

- The best way to do it is to add a mandatory field `metadata` to `innerStitchFramesToVideo` and work your way through the errors that appear when running `pnpm watch`
- If the `comment` metadata is set, it should be combined with the existing `Made with Remotion ${VERSION}` comment
- If a setting is added to the public API, it should also be added to the corresponding documentation page - this is probably renderMedia(), stitchFramesToVideo(), renderMediaOnCloudRun(), renderMediaOnLambda()

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 200

**Comment by akhilender-bongirwar** [comment]
@JonnyBurger, I am interested to work on this issue.

**Comment by JonnyBurger** [comment]
I'm giving it to @akhilender-bongirwar because they wrote first!

Please hold off @Myestery :)
