### ISSUE TITLE
Add large-v3-turbo.bin to @remotion/install-whisper-cpp

### ISSUE THREAD

**Issue by voladelta** [remotion-dev/remotion#4346]
> Whisper large-v3-turbo is a distilled version of [Whisper large-v3](https://huggingface.co/openai/whisper-large-v3). In other words, it's the exact same model, except that the number of decoding layers have reduced from 32 to 4. As a result, the model is way faster, at the expense of a minor quality degradation.

# Feature Request 🛍️

Add large-v3-turbo.bin to @remotion/install-whisper-cpp

## Use Case

Save time and increase quality compared to `medium.en`

## Possible Solution

None. I tried to download model myself and place it in the same place as medium.en but it doesn't work.

**Comment by JonnyBurger** [comment]
Thanks for the suggestion!
