### ISSUE TITLE
youtube channel link wrong in Help menu

### ISSUE THREAD

**Issue by send2cloud** [remotion-dev/remotion#4369]
https://www.youtube./@remotion_dev

# Bug Report 🐛

I am using bolt.net to make remotion video - in that i clicked on Help > Youtube and chrome opened with error - the .com is missing
![Image](https://github.com/user-attachments/assets/48a8327e-ec4d-4d17-871d-897ea750c5ba)
![Image](https://github.com/user-attachments/assets/1cfbec06-fcc3-4be9-85ed-663e4688826d)

![Image](https://github.com/user-attachments/assets/c6eb164e-838d-4b9e-854d-164f76a46cf8)

**Comment by JonnyBurger** [comment]
Thanks for noticing that!
