### ISSUE TITLE
OffthreadVideo is positioned differently in rendered output than in browser Player

### ISSUE THREAD

**Issue by empz** [remotion-dev/remotion#4410]
Remotion Version: 4.0.221

Preview `Player` in browser:
![Image](https://github.com/user-attachments/assets/e3cfc13c-c0b7-4683-947e-f3d2647132c4)

Rendered output:
![Image](https://github.com/user-attachments/assets/b847899a-2daa-4054-bfa1-800fa999bbb0)

Using the following component:
```tsx
import { Loop, OffthreadVideo } from "remotion";

export const LoopedOffthreadVideo: React.FC<{
  durationInFrames: number;
  src: string;
  muted?: boolean;
}> = ({ durationInFrames, src }) => {
  if (durationInFrames <= 0) {
    throw new Error("durationInFrames must be greater than 0");
  }

  return (
    <Loop durationInFrames={durationInFrames}>
      <OffthreadVideo src={src} muted />
    </Loop>
  );
};
```

This component is just rendered inside the top-level `AbsoluteFill`:

```tsx
<AbsoluteFill style={{ background: bgColor, cursor: "default", userSelect: "none" }}>
      <LoopedOffthreadVideo
          durationInFrames={bgVideoDurationInFrames}
          src={bgMediaUrl}
          muted={true}
        />

       // Other components
</AbsoluteFill>
```

**Comment by JonnyBurger** [comment]
Also this CSS injection has to work, it usually does: https://github.com/remotion-dev/remotion/blob/087645f19f1aefde55263e263443723ca9033b30/packages/core/src/default-css.ts#L52

 Unless there is something you to override / remove it, if you end having to investigate this further, can you also check this?

**Comment by empz** [comment]
Uhm, I don't have any global styles, it's all scoped CSS modules so I wouldn't know what might be affecting the preview. Maybe it's not a global CSS, but just some CSS applied to a parent of the Player that causes this (think typical "container" elements in UI libraries which are usually centered).

I'll dig further into this and get back to you.

Btw, I don't seem to have access to that link.

**Comment by JonnyBurger** [comment]
The link now does not 404 anymore

If you feel there is a Remotion bug, let me know and I'll reopen it.

**Comment by empz** [comment]
> The link now does not 404 anymore
> 
> If you feel there is a Remotion bug, let me know and I'll reopen it.

I'm not sure. I had to be explicit with the CSS of the video in order to get it to display the same in the 3 places (my own preview player, Remotion studio and final render output). I guess by not being explicit there's some inheritance of styles that caused the issue.

**Comment by JonnyBurger** [comment]
That's correct - Remotion does only reset the most common properties inside a Player, currently you need to ensure that you don't apply styles to elements inside the Player from the outside.

Maybe we can create a more thoughtful CSS Reset in the future.
