### ISSUE TITLE
Video freezes intermittently

### ISSUE THREAD

**Issue by markolofsen** [remotion-dev/remotion#4435]
During testing of the `ConcatenatedVideo` component, it has been noted that videos freeze unexpectedly at various points during playback. This issue affects the overall viewing experience, particularly around the transition points between videos.

## Steps to Reproduce
1. Load the `ConcatenatedVideo` component with the following embedded video data:
   ```javascript
   const videos = [
     {
       src: "https://unreal-studio-bucket.s3.amazonaws.com/users/f15cf406-4cef-4e96-9547-ee0f359a0f95/videos/639415e8-aff5-4632-946f-9e5cb8ab0680/d5ab17bc-01bf-4755-9310-7128a3d478fc/51b8181c-8830-4aba-a70f-b7717e3d85f4.mp4",
       startFrom: 0,
       endAt: 5,
     },
     {
       src: "https://unreal-studio-bucket.s3.amazonaws.com/users/f15cf406-4cef-4e96-9547-ee0f359a0f95/videos/639415e8-aff5-4632-946f-9e5cb8ab0680/8fa81ea9-e6e0-49d6-9382-a352e1707910/508153ce-7ddf-4ee2-83b7-a6e8a9fdc5a9.mp4",
       startFrom: 5,
       endAt: 10,
     },
     {
       src: "https://unreal-studio-bucket.s3.amazonaws.com/users/f15cf406-4cef-4e96-9547-ee0f359a0f95/videos/639415e8-aff5-4632-946f-9e5cb8ab0680/af15f7e1-19a1-4767-99c4-336ce0a8994e/4124024-uhd_4096_2160_25fps.mp4",
       startFrom: 10,
       endAt: 15,
     },
     {
       src: "https://unreal-studio-bucket.s3.amazonaws.com/users/f15cf406-4cef-4e96-9547-ee0f359a0f95/videos/639415e8-aff5-4632-946f-9e5cb8ab0680/60c65298-d2df-474c-9655-bec1514aef49/0abdc723-e5aa-4a8c-8a04-fa8839c5ad71.mp4",
       startFrom: 15,
       endAt: 20,
     },
   ];
   ```

2. Play the video in the `ConcatenatedVideo` component.

3. Observe the playback behavior.

### Expected Result
- Videos should play smoothly without interruptions or freezes.

### Actual Result
- The video freezes intermittently during playback, especially at the 4-second mark and during transitions.

## Additional Information
- The issue persists across different browsers and devices.
- Below is the relevant code snippet for the `ConcatenatedVideo` component:

```javascript
import { AbsoluteFill, Audio, Series, Video } from 'remotion';

export const ConcatenatedVideo = () => {
  const videos = [
    {
      src: "https://unreal-studio-bucket.s3.amazonaws.com/users/f15cf406-4cef-4e96-9547-ee0f359a0f95/videos/639415e8-aff5-4632-946f-9e5cb8ab0680/d5ab17bc-01bf-4755-9310-7128a3d478fc/51b8181c-8830-4aba-a70f-b7717e3d85f4.mp4",
      startFrom: 0,
      endAt: 5,
    },
    {
      src: "https://unreal-studio-bucket.s3.amazonaws.com/users/f15cf406-4cef-4e96-9547-ee0f359a0f95/videos/639415e8-aff5-4632-946f-9e5cb8ab0680/8fa81ea9-e6e0-49d6-9382-a352e1707910/508153ce-7ddf-4ee2-83b7-a6e8a9fdc5a9.mp4",
      startFrom: 5,
      endAt: 10,
    },
    {
      src: "https://unreal-studio-bucket.s3.amazonaws.com/users/f15cf406-4cef-4e96-9547-ee0f359a0f95/videos/639415e8-aff5-4632-946f-9e5cb8ab0680/af15f7e1-19a1-4767-99c4-336ce0a8994e/4124024-uhd_4096_2160_25fps.mp4",
      startFrom: 10,
      endAt: 15,
    },
    {
      src: "https://unreal-studio-bucket.s3.amazonaws.com/users/f15cf406-4cef-4e96-9547-ee0f359a0f95/videos/639415e8-aff5-4632-946f-9e5cb8ab0680/60c65298-d2df-474c-9655-bec1514aef49/0abdc723-e5aa-4a8c-8a04-fa8839c5ad71.mp4",
      startFrom: 15,
      endAt: 20,
    },
  ];

  const fps = 30;

  return (
    <AbsoluteFill>
      <Series>
        {videos.map((video, index) => (
          <Series.Sequence key={index} durationInFrames={...}>
            <Video src={video.src} startFrom={video.startFrom * fps} />
          </Series.Sequence>
        ))}
      </Series>
      <Audio src={staticFile("audio/background-music.mp3")} startFrom={0} />
    </AbsoluteFill>
  );
};
```

**Comment by JonnyBurger** [comment]
Out of curiousity, where did you get the `ConcatenatedVideo` component from?

The videos only load at the time they enter the scene.
There are various solutions to preload/premount the videos or to use a buffer state, seems like you do not use out any of them at the moment: https://www.remotion.dev/docs/troubleshooting/player-flicker

**Comment by markolofsen** [comment]
@JonnyBurger 
I'm experiencing an issue with playing videos from a remote URL using the OffthreadVideo component. When I try to load a video directly from an external source, I receive the following error:


Error: staticFile() does not support remote URLs - got "https://unreal-studio-bucket.s3.amazonaws.com/users/1e6c2a91-eb5c-4a80-b518-c7b5f59fbcc5/videos/d3b4c66d-9e31-4d17-8bd5-9621dba15e21/file/33ff975e-d010-4854-af78-0d1ba221a536.mp4". Instead, pass the URL without wrapping it in staticFile(). See: https://remotion.dev/docs/staticfile-remote-urls
I’ve made sure to pass the URL directly without using staticFile(), but the error still appears. Here’s a simplified version of my code:

```javascript
import { AbsoluteFill, OffthreadVideo } from 'remotion';

export const ConcatenatedVideo = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: '#000', width: '100%', height: '100%' }}>
      <OffthreadVideo
        src="https://unreal-studio-bucket.s3.amazonaws.com/users/1e6c2a91-eb5c-4a80-b518-c7b5f59fbcc5/videos/d3b4c66d-9e31-4d17-8bd5-9621dba15e21/file/33ff975e-d010-4854-af78-0d1ba221a536.mp4"
        pauseWhenBuffering
        style={{
          width: '100%',
          height: '100%',
        }}
      />
    </AbsoluteFill>
  );
};
```

I’ve tried clearing my cache, updating Remotion, and simplifying the component to isolate the issue, but nothing has worked so far.

Could you advise on how to resolve this or if there are any known issues with remote video URLs in OffthreadVideo?

**Comment by JonnyBurger** [comment]
@markolofsen It's impossible, OffthreadVideo doesn't call staticFile, and only staticFile gives this error.

You probably get a stacktrace as well, this would be interesting, what does it say?
