### ISSUE TITLE
SSR using Node.js Backend API issue

### ISSUE THREAD

**Issue by harmanmakkar1** [remotion-dev/remotion#4442]
In Remotion, my frontend and backend code are in separate folders. Currently, I use the local file path src/index.js to access the bundle, as per the official Remotion documentation. However, I want to deploy my frontend and backend in separate folders, and I would like to pass the bundle compositions for the video through an API instead of using the local src/index.js file.

Is this possible? If so, what would be the best solution for achieving this?

**Comment by harmanmakkar1** [comment]
I want that my bundle should change dynamically every time not static one time.

**Comment by JonnyBurger** [comment]
You should use input props to parametrize the bundle: https://www.remotion.dev/docs/lambda/faq#do-i-have-to-deploy-a-new-site-for-every-render

(Lambda docs but it still applies)

**Comment by harmanmakkar1** [comment]
I want to set up AWS Lambda without needing to pass an entry file. How can I achieve this?

**Comment by JonnyBurger** [comment]
You can render with any Serve URL: https://www.remotion.dev/docs/terminology/serve-url

**Comment by harmanmakkar1** [comment]
To serve the URL, I need to upload the src/index.js file to Amazon S3?

**Comment by JonnyBurger** [comment]
No, read the doc page I linked.
You need to bundle at one point with an entry point, no way around it.

**Comment by harmanmakkar1** [comment]
But this supports static deployments but i want to make dynamic data to be render when video is downloaded. How can I achieve this?

**Comment by JonnyBurger** [comment]
Parametrize the video only using input props.
Don't change the bundle but make the bundle accept dynamic props

**Comment by harmanmakkar1** [comment]
I want to ask something: we need to provide an entry point to make Remotion Video to Render?
