### ISSUE TITLE
updateDefaultProps() does not update the properties

### ISSUE THREAD

**Issue by ma-foss** [remotion-dev/remotion#4502]
# Bug Report 🐛

Within my remotion project, I was having a problem with `updateDefaultProps` not updating the properties, but after thoroughly checking my code and reading the docs a few times, I could not find a problem here.

So I checked out the remotion repository and started the TestBed as per the [Contributing Guide](https://www.remotion.dev/docs/contributing) and started playing around with the _"SaveDefaultProps"_ composition. If I understand correctly, clicking on the _"Update some props"_ button should update the color property from blue to red - but nothing happens.

In the attached screencast, you can see that the color property stays blue and does not change to red.

https://github.com/user-attachments/assets/c701f326-ccb6-463b-8111-5fac67f67300

**Comment by hunxjunedo** [comment]
Have you tried changing the property in props menu and clicking on 'save some props' ?

**Comment by JonnyBurger** [comment]
Thanks for reporting this!
