### ISSUE TITLE
Ubuntu 24.04 Dependency libasound2 Change

### ISSUE THREAD

**Issue by vinlegend1** [remotion-dev/remotion#4508]
Hello, I tried installing dependencies on Ubuntu 24.04 WSL using (according to [this page in the documentation](https://www.remotion.dev/docs/miscellaneous/linux-dependencies#ubuntu))

```console
RUN apt install -y \
  libnss3 \
  libdbus-1-3 \
  libatk1.0-0 \
  libasound2 \
  libxrandr2 \
  libxkbcommon-dev \
  libxfixes3 \
  libxcomposite1 \
  libxdamage1 \
  libgbm-dev \
  libatk-bridge2.0-0
```

and got an error:

```console
E: Package 'libasound2' has no installation candidate
```

It seems like in ubuntu 24.04, `libasound2` is renamed as `libasound2t64` according to this [source](https://github.com/cypress-io/cypress-documentation/issues/5816)

I suggest having a separate installation instruction for Ubuntu 24.04 and below 24.04. Thank you.

**Comment by JonnyBurger** [comment]
Thanks for reporting this!
