### ISSUE TITLE
Doc improvement: Mention adding empty space at text for createTikTokStyleCaptions

### ISSUE THREAD

**Issue by mokuzuu** [remotion-dev/remotion#4555]
Hi team! Thank you so much for great library.

I was playing around with tiktok caption example app, and I struggle to make it work as my captions json `text` field doesn't start with empty space. I found out while reading source code. 

I think it's worth mentioning in doc so if we convert caption file to `Caption` type json data manually, they don't have to figure it out by themselves.

**Comment by JonnyBurger** [comment]
Thanks for bringing it up!

What exactly is the problem with the `text` field not starting with an empty space?

**Comment by mokuzuu** [comment]
It's not really the problem of its own. basically createTikTokStyleCaptions function doesn't work if caption is 
```
[
  {
    "text": "Using",
    ...
  },
  {
    "text": "Remotion's",
    ...
  },
  {
    "text": "TikTok",
    ...
  },
  {
    "text": "template,",
    ...
  },
]
```
and it works when
```
```
[
  {
    "text": "Using",
    ...
  },
  {
    "text": " Remotion's", <- need to have space to make tiktok style work
    ...
  },
  {
    "text": " TikTok",
    ...
  },
  {
    "text": " template,",
    ...
  },
]
```

This is totally fine! But I thought it would be very nice if its been mentioned in doc. Currently i needed to figure it out by reading source code.

**Comment by mokuzuu** [comment]
When text doesn't start with empty space, caption looks like this
![Image](https://github.com/user-attachments/assets/84451ec3-7db3-4d31-9e87-7232ec8d8190)

**Comment by JonnyBurger** [comment]
I see, that makes a lot of sense, thanks for bringing it up!

**Comment by PierreAndreis** [comment]
spent a considerable amount of time to figure out that the space needs to be beforehand, not at the end (like what I did). should've included better in the docs! cheers
