### ISSUE TITLE
Question: how to get current progress time of playing audio?

### ISSUE THREAD

**Issue by benjamingorman** [remotion-dev/remotion#4560]
I'd like to use Remotion to generate a music playlist video featuring a media player with a progress bar.

To render the progress, I need to get the currently playing song and figure out the current progress and max duration.

Max duration is easy - as there is a clear API for this via `useAudioData` https://www.remotion.dev/docs/use-audio-data

Current progress is not so easy, as this isn't included in `AudioData`. I imagine it's not that straightforward to compute due to the calculation involving the frame rate etc. Is there an existing way to do this that I haven't been able to find in the docs?

I've found [useCurrentFrame ](https://www.remotion.dev/docs/use-current-frame) however this would be the globally current frame and not the frame since the current song started playing and so this would still be tricky.

**Comment by JonnyBurger** [comment]
You should know at which point you are based on useCurrentFrame().

If you mounted the `<Audio>` tag as it is, the current playback time is the same as `useCurrentFrame()`.
If you mounted the Audio inside a `<Sequence>`, the current time is shifted by that amount.
If you used the `startFrom` prop, the current time is also shifted by that amount.

If you don't use `<Audio>` to play audio, or mess with the audio tag in another way, it might be an indication that you are breaking the rules of Remotion (https://www.remotion.dev/docs/flickering)
