### ISSUE TITLE
can we update the enum of a scheme, so that i can play with the options in the select box

### ISSUE THREAD

**Issue by anjalipandith** [remotion-dev/remotion#4561]
Hi Remotioneers

can we update the enum of a scheme, so that i can play with the options in the select box.

![Image](https://github.com/user-attachments/assets/2246373f-92b6-41ac-a917-f580d4baf0f3)

Can i update the schema enum in the calculateMetadata?

Thanks

**Comment by JonnyBurger** [comment]
It's not intended to be able to do that, however, you could try to dynamically create the `z.enum()` for example inside a useEffect() and then pass it to a composition.

I would be curious to know if that works

**Comment by anjalipandith** [comment]
I tried multiple ways like follows
I created a const array and pass to the enum-> it worked
export const ConfigState = z.object({
    state: z.enum(stateValues as const).default("new"),
    states: z.string(),
});

When i create a let array and it does not allowed me to create the schema
let states=["new", "old", "bad"];
getStateValues() {
return states
}
export const ConfigState = z.object({
    state: z.enum(getStateValues()).default("new"),
    states: z.string(),
});

it did not allowed me to change the schema once defined.
Uncaught ReferenceError: Cannot access 'states' before initialization
