### ISSUE TITLE
MacOS M2 chip: getRenderProgress fails due to Module not found: Can't resolve '@remotion/compositor-win32-x64-msvc'

### ISSUE THREAD

**Issue by Et3rnel** [remotion-dev/remotion#4576]
Hi!
I encountered an issue while using the `getRenderProgress` function imported from `@remotion/lambda/client` in a local Next.js project on macOS (M2 chip). When trying to render, I get the following error:

```console
Import trace for requested module:
./node_modules/@remotion/renderer/dist/index.js
./node_modules/@remotion/lambda/dist/api/download-media.js
./node_modules/@remotion/lambda/dist/index.js
./app/api/render/[renderId]/status/route.ts
 ⨯ ./node_modules/@remotion/renderer/dist/compositor/get-executable-path.js:61:1
Module not found: Can't resolve '@remotion/compositor-win32-x64-msvc'
```

**Steps to Reproduce**
- Set up a Next.js project on macOS.
- Add Remotion and attempt to use getRenderProgress.
- Run the code and observe the error.
- Expected Behavior

The compositor should resolve to a macOS-compatible module (e.g., @remotion/compositor-darwin-x64) and render successfully.

**Actual Behavior**
The module resolution attempts to load `@remotion/compositor-win32-x64-msvc`, which is specific to Windows, causing the build to fail on macOS.

**Environment**
macOS Version:
```console
❯ sw_vers
ProductName:		macOS
ProductVersion:		15.1.1
BuildVersion:		24B91
```

Node.js Version: 
```console
❯ node -v
v23.3.0
```

NPM Version:
```console
❯ npm -v
10.9.0
```

Architecture:
```console
❯ node -p process.arch
arm64
```

Remotion Version: `^4.0.229`
Next.js Version: `^14.2.14`

Thanks for your help!

**Comment by JonnyBurger** [comment]
Make sure you have no import from `@remotion/lambda`.

This does not happen if you only import `@remotion/lambda/client`. I don't really believe you that you imported only from `/client` since there are many other users who use this Next.js flow and don't have this problem 🤔 

If in doubt, please post the full /app/api/render/[renderId]/status/route.ts code?

**Comment by Et3rnel** [comment]
I checked and I had an import from `@remotion/lambda` for the `getRegions()` function that I use to ensure my configured region is correct:
```js
const supportedRegions = getRegions();
if (!supportedRegions.includes(region as AwsRegion)) {
    return internalServerErrorResponse(`The AWS region "${region}" is not supported for video rendering`, RESOURCE_NOT_FOUND_CODE);
}
```

It seems to work seemlessly after removing this code!
I didn't find its equivalent in `@remotion/lambda/client`.
