### ISSUE TITLE
update Node CI version

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#4579]
# Feature Request 🛍️
Seems in [my PR](https://github.com/remotion-dev/remotion/pull/4577) `Build Node 16 `

## Use Case

Node 16 is year+ outdated
No immediate issue for me, but may be soon, since newer versions have features & security patches that may be needed soon.

## Possible Solution

Could manually patch, or automate by scraping the latest version from [somewhere](https://endoflife.date/api/nodejs.json).

**Comment by JonnyBurger** [comment]
This is intended for backwards compatibility

When Remotion 4.0 was released, this was LTS
It is convention that you only stop supporting old runtimes when you do a major version bump

Remotion 5.0 is in preparation and in there Node 16 has already been removed from the CI.

**Comment by tomByrer** [comment]
> Remotion 5.0 is in preparation 

![Image](https://github.com/user-attachments/assets/2b843b18-2970-436c-aaae-77fca1484f50)
