### ISSUE TITLE
Loading silent audio file throws error in the console

### ISSUE THREAD

**Issue by smlkdev** [remotion-dev/remotion#4583]
# Bug Report 🐛

1. I made 60 seconds of silence for test purposes: `sox -n -r 44100 -c 1 ./60s.wav trim 0.0 60.0`
2. Loaded through remotion's `<Audio>`.
3. Error occured in the console (related to drawing waveform bar in the timeline):

![Image](https://github.com/user-attachments/assets/82709a16-9716-4a12-8db6-ed918946632a)

4. It does not occur when using 5s file:
![Image](https://github.com/user-attachments/assets/a951e1d7-794a-4208-bb78-441f1f75d2dd)

**Comment by JonnyBurger** [comment]
Thanks for reporting!

This happens if the audio is completely silent. Just to let you know in case you did not intend to to this :P
