### ISSUE TITLE
@remotion/shapes: rectangle docs page crash

### ISSUE THREAD

**Issue by thecmdrunner** [remotion-dev/remotion#4592]
# Bug Report 🐛

The docs page for <Rect/> crashes upon setting a combination of options.

In the screenshot below, the shape is a little weird, but the controls still function.

![Image](https://github.com/user-attachments/assets/ff45eb79-884b-4ee7-940a-b618d5afa81d)

If I enable `edgeRoundness`, the page crashes

![Image](https://github.com/user-attachments/assets/c7046b21-a19d-48f3-b8c6-ebe684d94d02)

**Comment by JonnyBurger** [comment]
Oh, thanks for reporting!
I think this could be a more serious bug actually, checking with #4601

**Comment by JonnyBurger** [comment]
Fixed by #4601
