### ISSUE TITLE
Make remotion.dev/convert work offline using a Service Worker

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#4607]
We have a site remotion.dev/convert built with Remix/Vite where you can convert videos using WebCodecs.
It works offline, but you have to load the site.

Idea: Use a Service Worker to make the site available offline and add a manifest, so the site can be installed as a progressive web app.

Design guidelines:

- It should by default always load the newest version of the site, it should **only fallback to the cached version** in case of the user being offline. That way we avoid tricky caching issues.
- If installed as an app, the name of the app is "Remotion Convert" and the logo is the Remotion icon from http://remotion.dev/brand.

Architecture:

This is a Vite+Remix app that is hosted on localhost:5173, but it is then exported as a SPA and copied over to the Docusaurus build.

Basically the flow is:

- Setup using https://www.remotion.dev/docs/contributing
- Run `npm run dev` in `packages/convert` to develop:
- To test production, run `npm run build-docs` in `packages/docs` (unfortunately a bit slow, might take 10min)
- To copy the app into the Remotion website, run `bun copy-convert.ts` in `packages/docs`
- To run the production website, run `npx serve build` in `packages/docs`

It is important that it works in the production site, not so important that it works in other environments or in other modes.

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 250

**Comment by Myestery** [comment]
Hi @JonnyBurger 

I'll like to be assigned this
I can complete it on or before Tuesday next week

**Comment by hunxjunedo** [comment]
@JonnyBurger can I work on this one ?

**Comment by JonnyBurger** [comment]
I'll give this one to @Myestery since he was first. Good luck!

## No more attempts

This issue has been assigned to @Myestery  🎉  

Do not send pull requests for this issue, do not ask to be in the queue, do not bother the assignee.  
**We will not accept any PRs not from the assignee and not award any bounties.**

Follow the #bounties channel on the Remotion Discord to get notified of new bounties.
