### ISSUE TITLE
Problem with Noto fonts not rendering properly

### ISSUE THREAD

**Issue by empz** [remotion-dev/remotion#4628]
I'm trying to load and use Noto Google Fonts but they don't seem to be rendering properly. The Player doesn't seem to be rendering the font properly (but it's still able to display the characters in some kind of font). When rendering the video, the text output comes as `ㅁㅁㅁ ㅁㅁㅁ` denoting that the font is indeed not rendered properly.

I'm having this issue with Korean characters and their corresponding **Noto Sans Korean** and **Noto Serif Korean** Google fonts.

I've created a repro using the Next.js App Router template.

The Main composition has been modified to accept a `font` prop, which is passed to the `WaitForFonts` component in charge of blocking the render of its children until the font is loaded. The default value is `Noto Serif Korean` which imports the font dynamically from `@remotion/google-fonts/NotoSerifKR`.

The following screenshot shows all the font variations are loaded properly from fonts.gstatic.com. But if we compare the actual font being renderer, we can clearly see it's not the same font. Also, changing the `font` prop to any other font doesn't change the font either.
![Image](https://github.com/user-attachments/assets/aa9bbc91-4e70-40f2-bc6e-11752b791b58)

The code works fine when using standard Latin/Roman alphabet and non-Noto Google fonts.

Inter font
![Image](https://github.com/user-attachments/assets/2bc2e057-941e-42de-b1af-2505c2ae716e)

Merienda font
![Image](https://github.com/user-attachments/assets/80205ccf-8d03-482e-83cd-93f9e11d0da5)

Here's the link to the repro:
https://stackblitz.com/edit/github-bkhzajzg?file=app%2Fpage.tsx

**Comment by empz** [comment]
The problem seems to be specific to Korean fonts. Or, at least, it doesn't happen with Arabic fonts.

Noto Kufi Arabic ✅
![Image](https://github.com/user-attachments/assets/630ed616-3393-48a2-b918-b3add0de431b)

Noto Sans Arabic ✅
![Image](https://github.com/user-attachments/assets/cf991331-faef-4fa1-82fa-005a1735f5c4)

**Comment by empz** [comment]
Further investigation suggests this might be an issue with the Google Fonts API itself.
https://github.com/google/fonts/issues/6960

**Comment by JonnyBurger** [comment]
Thanks for reporting! Hopefully others will find this useful when they google for this issue.

If we inherit the problem from Google Fonts, then nothing we can do from our side unfortunately.
