### ISSUE TITLE
i tried different versions and changed disk size , but always video stuck on 89 %

### ISSUE THREAD

**Issue by nikhilkcodes** [remotion-dev/remotion#4642]
# Bug Report 🐛

here is my deployLambda.js code : 

const { deployFunction } = require("@remotion/lambda")
require('dotenv').config()

async function deploy(params) {
    const { functionName } = await deployFunction({
        region: process.env.REMOTION_AWS_REGION,
        timeoutInSeconds: 900,
        memorySizeInMb: 3008,
        createCloudWatchLogGroup: true,
        diskSizeInMb: 8192,
        architecture: "arm64"
    });
    console.log(functionName, "finished");
}

deploy()

**Comment by JonnyBurger** [comment]
This comment contains no information about the actual issue, I cannot help - please see https://www.remotion.dev/docs/lambda/troubleshooting/debug and follow the instructions there.
