### ISSUE TITLE
Error: Unable to determine video metadata when calling getRenderProgress()

### ISSUE THREAD

**Issue by StevenOng97** [remotion-dev/remotion#4665]
I'm facing the issue when I tried to call getRenderProgress() to track the progress of renderMediaOnLambda
![Image](https://github.com/user-attachments/assets/cdca1017-3153-48de-87cf-a74d7b320e70)

**Comment by JonnyBurger** [comment]
Probably because you are calling `getVideoMetadata()` on a HEVC video, that is not supported on Chrome for Linux.

We have a solution for this now: Use `parseMedia()` over `getVideoMetadata()`!
https://www.remotion.dev/docs/dynamic-metadata
