### ISSUE TITLE
media-parser: EBML ID 0x536e is not supported

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#4668]
https://x.com/mdhruvill/status/1871913434146886086?s=46&t=f6GPOafkhl93XtnYcCk3Zg

# Bug Report 🐛

**Comment by mdhruvil** [comment]
https://github.com/user-attachments/assets/7a2327fe-daf9-42bb-8c85-f9261d6540fe
This is the video file I was trying to resize
