### ISSUE TITLE
—sequence CLI flag is confusing

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#477]
--frames=0 renders a video

--frames=0 --sequence out.mp4 returns "Pass another argument". It parses as {sequence: "out.mp4"}.

**Comment by sohamsshah** [comment]
Hi, I would like to work on this :) Can you elaborate this a bit (or some way I can reproduce it?)

**Comment by JonnyBurger** [comment]
Hi @sohamsshah! Thanks a lot for offering it! 
I think it's pretty simple, we are using minimist, https://www.npmjs.com/package/minimist

and we need to tell minimist that `--sequence` is a `boolean` flag, otherwise it will think that `--sequence out.mp4` is a key-value pair.

I see in the minimist documentation there is support for passing an array of values that should be treated as boolean!
