### ISSUE TITLE
Copy button does not copy

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#496]
In documentation

**Comment by JonnyBurger** [comment]
It seems to be not the same always, it works on my Mac Mini but not on my laptop 🤔

**Comment by arthurdenner** [comment]
Very strange. Running the `docs` package in development, works fine. After bundling and serving with the `docusaurus` commands, it doesn't.

I created a `docusaurus` project from scratch with `npx @docusaurus/init@latest init my-website classic` and it worked both in development and after bundling and serving.

**Comment by frencojobs** [comment]
Sorry about that, it was my fault. I forgot to test it in production. I've already merged and deployed the fix from @arthurdenner, and #516 will close this.
