### ISSUE TITLE
New Flag for rendering one or multiple thumbnail alongside redered video 

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#507]
It could be a separate command, a flag, a separate Node.JS API, a method on Lambda.. or multiple of these.

**Comment by Iamshankhadeep** [comment]
so let's say we want to render a thumbnail and video we need to run remotion twice one for the video and one for the thumbnail right?
`remotion render src/entry.jsx framer thumbnail --frames=10`
`remotion render src/entry.jsx framer video.mp4`

But I am suggesting we have a flag thumbnail so the shortcut for the above scenario will be. this command
`remotion render src/entry.jsx framer video.mp4 --thumbnails={10,20,30}`
this will give use a video.mp4 and 3 still images `thumbnails10.jpg` (11th frame) like this
