### ISSUE TITLE
By default, put the video in an `out` folder

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#518]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Funded-%2300A156.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/518)

This simplifies the .gitignore template by allowing to just ignore the `out` directory instead of unignoring the .mp4 files in the `src` folder and also think it's nice to have a dedicated folder.

cc @aVileBroker who came up with the idea

---

🎃  This issue is eligible for **Hacktoberfest**!
In addition to helping you get a contribution towards your [Hacktoberfest](https://hacktoberfest.digitalocean.com/) reward, Remotion pays a $100 bounty for it!

**Read**: [How to contribute to Remotion](https://github.com/remotion-dev/remotion/blob/main/CONTRIBUTING.md)

- Let us know when you are interested in this issue, and we'll assign you!
- In order to prevent issues from getting stuck, try to progress the issue by opening a PR and adding commits. If your progress is stale for 7 days, another user can ask to take over the issue.

**Approval criteria for this PR:**
- Change `packages/cli/src/render.tsx` so that if you render the video into a folder, and that folder doesn't exist, you create it. The following command should work in the `example` folder: `npx remotion render src/index.tsx react-svg any/nested/folder/video.mp4`
- Go through all the templates we support, and instead of rendering to `out.mp4`, render to `out/video.mp4` (adjust the script in `package.json`). Make a separate PR for each of those templates!
- Also remove the `**.mp4` references in the `.gitignore` of the templates, and add `out` instead.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by ahmadrosid** [comment]
Hi @JonnyBurger I would like to work on this issue.

**Comment by JonnyBurger** [comment]
@ahmadrosid sure! Assigning you.

**Comment by ahmadrosid** [comment]
Hi @JonnyBurger pull request created here https://github.com/remotion-dev/remotion/pull/618 would you mind to review it? Thank you
