### ISSUE TITLE
Proposal: Allow to omit `durationInFrames={Infinity}` for sequence

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#526]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/526)

We can make it that if you omit it this is assumed as default. Makes the syntax a bit more concise.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)

### Submitted pull Requests
- [#621 Make durationInFrames optional](https://issuehunt.io/r/JonnyBurger/remotion/pull/621)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by nandorojo** [comment]
Or `-1` 😎

**Comment by JonnyBurger** [comment]
We could allow it as well, but isn't it better if you can just not specify anything at all? 😁

**Comment by nandorojo** [comment]
Yeah agreed

**Comment by JonnyBurger** [comment]
🎃  This issue is eligible for **Hacktoberfest**!
In addition to helping you get a contribution towards your [Hacktoberfest](https://hacktoberfest.digitalocean.com/) reward, Remotion pays a $100 bounty for it!

**Read**: [How to contribute to Remotion](https://github.com/remotion-dev/remotion/blob/main/CONTRIBUTING.md)

- Let us know when you are interested in this issue, and we'll assign you!
- In order to prevent issues from getting stuck, try to progress the issue by opening a PR and adding commits. If your progress is stale for 7 days, another user can ask to take over the issue.

**Approval criteria for this PR:**
- Make the `durationInFrames` property optional for the `<Sequence />` component and fallback to `Infinity`.
- Update the documentation for `<Sequence />`.
- Update the examples in the documentation
- Go through the [list of templates](https://github.com/remotion-dev/remotion/blob/main/packages/create-video/src/init.ts#L16) and make a PR to remove the `durationInFrames={Infinity}` props if necessary
- Extend the ESLint plugin to give a warning if `durationInFrames={Infinity}` is set. You can [duplicate this rule](https://github.com/remotion-dev/remotion/blob/ac70cd1b47c77f13b7fea9826d8885279082ac3e/packages/eslint-plugin/src/rules/even-dimensions.ts#L24-L24) which is very similar and adjust it.

**Comment by khalid283** [comment]
@JonnyBurger Just gone through the Sequence compoent and some tests, I can take this.

**Comment by JonnyBurger** [comment]
@khalid283 You got it! Good luck 🎃
