### ISSUE TITLE
New project from template includes the original template git history

### ISSUE THREAD

**Issue by micnic** [remotion-dev/remotion#546]
After running `npm init video` or `yarn create video` the resulting project is just a cloned git repository of the template with the full git history of it.

It is expected that the created project has a clean history or no git set in place at all.

It would be better to use something like [degit](https://www.npmjs.com/package/degit), which is faster as it does not download the full git history (it downloads the `.tar.gz` file of repo and unpack it).

**Comment by JonnyBurger** [comment]
Thanks a lot for the report! I acknowledge as a bug, we'll fix it. I'm also in favor of using degit, that sounds like a great idea!

**Comment by Iamshankhadeep** [comment]
@micnic can you let me know Happy Birthday your os, node and npm version?

**Comment by micnic** [comment]
I use Ubuntu 20.04, node 16 and npm 7
