### ISSUE TITLE
Investigation: Can we support units like 100%, 100vh, by putting the rendered content in an iframe?

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#547]
Maybe it's useful for some to be able to use those units, but only if they are relative to the frame size (e.g 50vw should be 50% of the composition width, not the window width). So maybe an iframe is a good idea? But maybe iframe also has disadvantages? We should kick off an investigation :)

**Comment by johann04** [comment]
how can I render to an iframe?

**Comment by JonnyBurger** [comment]
We have an IFrame component which can render an `<iframe>`. https://www.remotion.dev/docs/iframe

It's not so related to this PR but hope it's what you are looking for!

**Comment by johann04** [comment]
mmm no... 

and sorry if this is a "basic" question...

I would like to create an endpoint in my server.tsx something like "/html?titleText=Hello" that renders something similar to the "npx remotion preview" but without the controls... only the html animated as the video... 

I want to quickly render a preview of the video (with the specific parameters)...

does that make sense?

(I am pretty sure you open that so puppeteer can use it for rendering... I want to publish directly that using express)

**Comment by JonnyBurger** [comment]
@johann04 First regarding the IFrame thing - maybe you are looking for @remotion/player?

https://remotion.dev/docs/player
It's a component that you can include in any React App to play a Remotion video.

Regarding your second question, an example for exactly that is included in your template - just run `npm run server` in your Remotion project!
You can open server.tsx to edit the source.

**Comment by JonnyBurger** [comment]
I investigated it (see branch `iframe-testing`) and while it could be possible to add the imported CSS styles into the iFrame instead of into the global scope using Webpack hacks, that would not work in the `<Player />`. We would make it harder to create videos that look the same in the <Player/> and in the preview, therefore I think we are not actively pursuing this idea.
