### ISSUE TITLE
[iOS] Audio asset doesn't pause when pausing the video

### ISSUE THREAD

**Issue by pmourelle** [remotion-dev/remotion#551]
Tested on iphone7 (chrome and safari), having a video preview formed by a set of elements (videos, images) and audio tracks, when pausing the video, the "video part" been played pauses fine, but audio tracks (in same Sequence) keep playing as the pause didn't affect them.
In desktop works fine, and pausing the video properly pauses both video and audio.

# Bug Report 🐛

**Comment by JonnyBurger** [comment]
Thanks! We'll investigate it. If possible, can you also mention the iOS version this is happening on?

**Comment by pmourelle** [comment]
Sure! Really appreciate your quick return 😃 .
Doesn't seem specific for a particular version. I'm seeing this in last version today (iOS 14.7.1). But also in previous version 14.6.x also happened.

**Comment by JonnyBurger** [comment]
I think this has to do with iOS playback policy. I am starting a PR to address it: #554
