### ISSUE TITLE
Config setLevel does not work

### ISSUE THREAD

**Issue by bichotll** [remotion-dev/remotion#567]
# Bug Report 🐛

The `config.setLevel(X)` does not work. Or at least I'm not getting the desired output on the terminal.
I have tried both, setting it up from the `remotion.config.ts` file and from the command line.

On remotion.config.ts:
```Config.Log.setLevel('error');```

```"build": "remotion render src/index.tsx App out.mp4 --overwrite --crf 1 --log error",```

I'm expecting it to be "Silent except error messages" when the log level is set to "error".

Besides that, the correct value is "warn", not "warning" as the docs estipulate:
https://www.remotion.dev/docs/cli#--log
https://www.remotion.dev/docs/config/#setlevel

Thanks!

**Comment by JonnyBurger** [comment]
Thanks for reporting! You are right, some console output does log regardless of the log level.
We'll fix this, and the docs issue soon!
