### ISSUE TITLE
Remotion render doesn't wait for the s3 resource to completely load

### ISSUE THREAD

**Issue by fais3000** [remotion-dev/remotion#568]
Software versions
```
"@aws-sdk/client-s3": "^3.17.0",
"@remotion/bundler": "^2.0.0",
"@remotion/cli": "^2.0.0",
"@remotion/eslint-config": "^2.0.0",
"@remotion/lambda": "^2.2.0-alpha.9d9cdf5c",
"@remotion/renderer": "^2.0.0",
```

When setting up text to speech boilerplate all works well in the preview mode. But if a video is generated (rendered) without running the preview mode first with new text following error is thrown. This is because the upload file to S3 is slow but the JS code tries to read the file which is not downloaded from s3 yet. 

```
The following error occurred when trying to render frame 134:
Error: Could not play video with src https://xyz.s3.amazonaws.com/0a19f2532d32344e849dacd5a6b5c6c1.mp3
    at http://localhost:3000/bundle.js:51530:15
    at Object.Rb (http://localhost:3000/bundle.js:50778:317)
    at Xb (http://localhost:3000/bundle.js:50778:471)
    at Yb (http://localhost:3000/bundle.js:50779:35)
    at Ze (http://localhost:3000/bundle.js:50826:68)
    at se (http://localhost:3000/bundle.js:50827:380)
    at http://localhost:3000/bundle.js:50839:65
    at Jb (http://localhost:3000/bundle.js:51018:189)
    at Nb (http://localhost:3000/bundle.js:50776:57)
    at jd (http://localhost:3000/bundle.js:50831:469)
```

**Comment by JonnyBurger** [comment]
Hi @fais3000, thanks for reporting!

I fixed it in this commit:
https://github.com/FelippeChemello/Remotion-TTS-Example/commit/47d31b1d1f5ee9a532e534406cf10e7b674c3b9d

You can add the changes to your project, most importantly the `await` in front of the S3 upload, to fix the issue.
