### ISSUE TITLE
remotion.dev websites gives the error 182.79.218.106 refused to connect.

### ISSUE THREAD

**Issue by sinayanaik** [remotion-dev/remotion#569]

**Comment by Iamshankhadeep** [comment]
The IP is of public ip of airtel in delhi. maybe some issues with airtel. btw you can hit 172.67.208.61 this for remotion.dev

**Comment by Iamshankhadeep** [comment]
The IP is of public ip of airtel in delhi. maybe some issues with airtel.

**Comment by JonnyBurger** [comment]
For the future, we now have a mirror, different root zone, and hosted on a different provider: https://remotiondocs.com
