### ISSUE TITLE
https://www.remotion.dev is down

### ISSUE THREAD

**Issue by johann04** [remotion-dev/remotion#576]

**Comment by Iamshankhadeep** [comment]
You can use this link also https://remotiondocs.com .

**Comment by JonnyBurger** [comment]
Hey @johann04! Sorry this is happening, we would like to investigate the issue which only seems to happen with certain ISPs.


Are you also on Airtel in India?
Can you reach showcase-uploader.remotion.dev? (To see if it's a problem with the .dev domain)
We now point remotion.dev to a different host, can you reach it now? (It might take a few hours to update the DNS).

It would be very helpful to learn about it!

**Comment by johann04** [comment]
hi, I am in Costa Rica.

No, cannot reach showcase-uploader.remotion.dev either

Still cannot reach it.

**Comment by JonnyBurger** [comment]
Thanks for letting us know. This is a real problem... does anyone know how we can resolve those issues on the DNS level?

**Comment by johann04** [comment]
johann04@Johanns-MacBook-Pro audio % ping remotion.dev
PING remotion.dev (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.032 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.088 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.080 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.094 ms
64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.091 ms

**Comment by johann04** [comment]
I my computer, remotion.dev is resolving to 127.0.0.1

**Comment by johann04** [comment]
OMG this is embarrassing...

I followed this tutorial https://passingcuriosity.com/2013/dnsmasq-dev-osx/ to point all .dev domains to localhost for a project... 

Sorry!
