### ISSUE TITLE
remotion website focuses on video demo immediately

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#582]
I guess this is a new bug in remotion player. need to investigate

**Comment by yuyuyzl** [comment]
ur input for inserting github username has a autofocus attribute.
should get rid of it.
<input class="parametrizeinput_1SDR" autofocus="" placeholder="Your GitHub username">

**Comment by JonnyBurger** [comment]
Thanks a lot @yuyuyzl for identifying the issue!
