### ISSUE TITLE
Parallel frame capturing and encoding for better performance

### ISSUE THREAD

**Issue by yuyuyzl** [remotion-dev/remotion#584]
In fact i am using another project like Remotion to make some video to post.
https://github.com/dtinth/html5-animation-video-renderer
this is kind of a much simpler version of remotion, it only has a renderer and simply feeding ffmpeg with stdin
https://github.com/dtinth/html5-animation-video-renderer/blob/master/render.js#L186

After some benchmarking, as for me, it is 3x faster than remotion.
I'm rendering only a moving title with some text-shadow, and animated it as below:
document.querySelector("#title").style.transform=`translate(${frame%300-150}px,${frame/300}px)`
btw im using a 5900x and 32g ram. 

In my opinion, the difference of raw performance between React and vanilla js cannot be avoided,
but using memory instead of hard drive to store frames might be a good way to improve rendering performance.

# Feature Request 🛍️

Parallel frame capturing and encoding for better performance.

**Comment by JonnyBurger** [comment]
Hey @yuyuyzl!

Thanks a lot for filing the issue, I appreciate every thought about how to improve the performance of the render pipeline.

My computer specs are pretty different, but I've cloned your repo and could not see it being 3x faster than Remotion. It took 27sec to render, I'm sure Remotion would perform similarly for me. Is there a benchmark command to demonstrate the huge performance difference?

You have found an interesting way to start encoding the video while the frames are still rendering. I would indeed like to try to implement this into Remotion as well! So I'll leave this issue open until we have explored this.

By the way, we have found that screenshotting in JPEG is much faster than in PNG. Of course only when no alpha channel is required. Maybe this helps you improve the performance of your project even further!

**Comment by yuyuyzl** [comment]
I refactored the benchmark project for remotion, and admittedly it is not 3x slower than the vanilla way (i mean dtinth's project) but still has some difference (about 60s:35s).

https://github.com/yuyuyzl/mybenchmark4remotion

https://user-images.githubusercontent.com/14276008/132247985-6b9400fb-975e-4a83-b6ee-fbfdcb9c8390.mp4

The task manager shows a huge difference on cpu utilization, and it doesn't change even if i set concurrency to 24.

**Comment by JonnyBurger** [comment]
Thanks a lot @yuyuyzl for sharing this! I'll definitely take a look and dive into what is needed. It might take some time to tackle as we are working on a lot of things, but I will definitely look into it! This is much appreciated ☺️

**Comment by yuyuyzl** [comment]
Oh, I tried to render the bundle from remotion in html5-animation-video-renderer, and it works really well, at least for my simple demo. The rendering process didn't slow down at all, and the output video has no glitch or any problem, so i think it is not React's fault.

My demo repo is updated and if you want to try, use `node render --url=file://<ABSOLUTE_PATH>\remotion-test\helloworldvanilla/examples/index.html?composition=HelloWorld`

**Comment by JonnyBurger** [comment]
That's interesting, I was assuming those are performant. But I'll take this into my investigation, thank you!

Appreciate you updating the demo 😊 does the fact that remotion needs to bundle using webpack cause the difference maybe?

**Comment by yuyuyzl** [comment]
> and it leads to a simple conclusion, async function calls or waitForFunction or `requestAnimationFrame(() => continueRender(id))` may be wasting time if the rendering process is instantly done after remotion_setFrame calls...?

Forked the whole repo and tested.
`await page.waitForFunction('window.ready === true');` has a small effect (about 10%) on frame render time, but this is not the main problem.

Aside from the difference in feeding ffmpeg (buffer/file), I have noticed Remotion doesn't create a bunch of browser instances like dtinth's renderer. Instead, it creates a single browser with multiple tabs, and "cycle browser tabs" around.

Will it be the main reason of the performance difference? Since a Chrome instance can only have 1 foreground tab, this might cause the browser behave like single threaded.

(btw, thanks for reading my poor English lol)

**Comment by yuyuyzl** [comment]
> Aside from the difference in feeding ffmpeg (buffer/file), I have noticed Remotion doesn't create a bunch of browser instances like dtinth's renderer. Instead, it creates a single browser with multiple tabs, and "cycle browser tabs" around.
> 
> Will it be the main reason of the performance difference? Since a Chrome instance can only have 1 foreground tab, this might cause the browser behave like single threaded.

YES IT IS, 67088ms -> 43183ms in frame rendering.
![image](https://user-images.githubusercontent.com/14276008/132469957-60b1ba02-de08-41d6-94f4-5bcadbad764a.png)
1 browser, 6 tabs (original)

![image](https://user-images.githubusercontent.com/14276008/132469989-03b6570a-8d69-4060-a83f-7e9b719afc41.png)
6 browsers (improved)

Run on a MBP, 6 core i7.

Code diff here:
https://github.com/remotion-dev/remotion/compare/main...yuyuyzl:test-multi-browser-instance?expand=1

**Comment by yuyuyzl** [comment]
![image](https://user-images.githubusercontent.com/14276008/132521761-688fe014-53d6-4cee-bd0b-d80293bdfe6b.png)
Got similar result on my 5900x, 39739ms -> 22189ms this time.

Maybe we should have a cli flag to enable this feature, or just change it all at once?
Honestly I can't get the point to create multiple tabs in one browser...

**Comment by yuyuyzl** [comment]
As for the audio part (assets), it can be encoded and mux to the video after the rendering and encoding process, since it is faster than encoding h264.

I'm preparing a pr for these performance fixes.
2 config parameters will be added to control tabs/browsers concurrent rendering(done for now) and parallel encoding(wip).

**Comment by JonnyBurger** [comment]
Thanks a lot for the benchmarks and the updates!

We are certainly interested in these kind of PRs, they can also contain some breaking changes and we'll merge them for Remotion V3.

Right now we are busy with Lambda and few other smaller projects but we'd love to revisit the rendering pipeline before the next major release.

Always happy to look at your experiments in the meanwhile.

Also we may have wrongly closed #176. I cannot see those performance benefits myself, but we can give the option to open multiple browsers.

**Comment by yuyuyzl** [comment]
> Also we may have wrongly closed #176. I cannot see those performance benefits myself, but we can give the option to open multiple browsers.
Yes, the difference of performance depends highly on the thread count of the cpu and the complexity of the project itself.
I did read that issue while benchmarking lol.

The PR branch is mostly done, and i have some good results to share.
![image](https://user-images.githubusercontent.com/14276008/133588588-c056f510-2884-41d6-8041-5022f9117bd5.png)
Original (86s)

![image](https://user-images.githubusercontent.com/14276008/133588847-fc2503be-011d-428a-9922-e5c960527f82.png)
Multiple browser rendering with`Config.Rendering.setConcurrentMode('browser');` (65s)

![image](https://user-images.githubusercontent.com/14276008/133589093-6e77bb7f-7d7c-4fa5-a5de-9b301d441f05.png)
Parallel encoding and rendering with`Config.Rendering.setParallelEncoding(true);` (59s)

**Comment by iamkhalidbashir** [comment]
![Screenshot from 2021-09-25 16-33-18](https://user-images.githubusercontent.com/27646811/134770016-d6e55cad-80ed-4006-bde5-9b766a19f353.png)

Also, the original repo doesn't open a server to load pages, rather hit an HTML file directly

as compared to remotion
![Screenshot from 2021-09-25 16-36-40](https://user-images.githubusercontent.com/27646811/134770086-07522529-d125-4de0-8813-aea3a67d103a.png)

Although not sure about the performance increment of using this technique but I think the CPU utilization will be far less

**Comment by iamkhalidbashir** [comment]
![Screenshot from 2021-09-25 19-39-47](https://user-images.githubusercontent.com/27646811/134775339-c435e8d9-18c9-484e-8efe-00916daf68e2.png)


Also, I think we should remove the guards, rather add a warning

because for concurrent mode browser I am reaching 70% CPU utilization with all cores used
and I would like to increase it further to use maximum CPU utilization which it seems I cant
