### ISSUE TITLE
Possibility to use twin.macro

### ISSUE THREAD

**Issue by marcusstenbeck** [remotion-dev/remotion#601]
# Feature Request 🛍️

Add setup example of using `twin.macro` with Remotion.

## Use Case

[twin.macro](https://github.com/ben-rogerson/twin.macro) improves greatly on the the developer experience when working with TailwindCSS.

## Possible Solution

The main issue is that `twin.macro` uses `babel-loader`, and for Remotion 2.0 the decision was made to move to `esbuild`. I'm not familiar enough with `esbuild` to determine whether there's a way to make it work with `twin.macro`.

Here's the default setup guide for react + styled-components: https://github.com/ben-rogerson/twin.examples/tree/master/react-styled-components

Check if there's a way to use this without reverting to using `babel-loader`.

**Comment by JonnyBurger** [comment]
Thanks for filing the issue!

We already make it possible to use babel-loader: https://www.remotion.dev/docs/legacy-babel
So it should be possible to add the twin.macro plugin by using the babel-loader in combination with overrideWebpackConfig().

To make the twin.macro plugin work with esbuild is IMO outside the scope of our project! So I don't see something actionable in regard to this and would suggest to close this issue.

**Comment by marcusstenbeck** [comment]
OK, I'll close.

Will `babel-loader` support continue, or is there a plan to only support esbuild in the long term?

**Comment by JonnyBurger** [comment]
We'll still support it for the foreseeable future, but if it will block us massively in the future, we'll consider dropping it as the adoption of ESBuild has been super successful.

That being said, I don't see a roadblock in front of us right now that would cause us to drop support for babel-loader.
