### ISSUE TITLE
Nitpick in `remotion/init.ts` for create-video package.  

### ISSUE THREAD

**Issue by sohamsshah** [remotion-dev/remotion#605]
# Bug Report 🐛
https://github.com/remotion-dev/remotion/blob/6472f8820cee03fcbaa29b6289bed002fdb3040b/packages/create-video/src/init.ts#L215

In `short` attribute, shouldn't we have `template.shortName` instead of `template.name`?

Was actually trying to understand the codebase; had a question around if this is a bug or not.

**Comment by JonnyBurger** [comment]
Thanks for pointing this out! Based on this code https://github.com/terkelg/prompts/blob/d7d2c37a0009e3235b2e88a7d5cdbb114ac271b2/lib/elements/select.js#L29

My investigation led me to believe that the `short` option has no effect at all. I will remove this property.
