### ISSUE TITLE
`index.js` doesn't exist for `create-video` package 

### ISSUE THREAD

**Issue by sohamsshah** [remotion-dev/remotion#607]
# Bug Report 🐛

A small nitpick. In the `package.json` of the `create-video` package, the main field suggests to use `index.js` file. While, the index.js doesn't exist in the project. 

https://github.com/remotion-dev/remotion/blob/b4686244b64ddc732924ed92a06cf4e35f7ed420/packages/create-video/package.json#L5

Tried to fetch https://unpkg.com/create-video@2.3.3/index.js from unpkg, it showed same error.

Not Priority, but an enhancement. Please suggest what we can do (also description, keywords etc. can be changed/added). I would like to make a small contribution; if possible.

Thanks Jonny! This Package is very being helpful for me to make an `npx starter` kit for my personal project. Truly Open Source is 😍

**Comment by JonnyBurger** [comment]
Thanks a lot for reporting!

**Comment by sohamsshah** [comment]
No problem!
