### ISSUE TITLE
Css reset overwrites inherited properties

### ISSUE THREAD

**Issue by sashee** [remotion-dev/remotion#608]
I've updated to 2.4.0 and all texts disappeared from the videos. I drilled down and it seems like the css-reset overwrites inherited properties.

Here's a screenshot of a component:
![image](https://user-images.githubusercontent.com/82075/135235535-c3cd9e4f-c78d-4549-9201-d4619833f989.png)

Notice that the ```color: var(--color-foreground);``` is crossed (~bottom right corner). It is overwritten by the ```.css-reset *``` rule:

![image](https://user-images.githubusercontent.com/82075/135235758-08f2f1e2-282d-4e1d-86fb-6d3e7dffc9e8.png)

Since the ```.css-reset *``` is more specific than  the ```div.marpit > section``` (that is the ancestor of the ```h1```) it overwrites the color with white.

Since all the properties in the ```.css-reset``` are inherited, the ```*``` should be removed.

**Comment by JonnyBurger** [comment]
Thanks a lot for reporting! Indeed an annoying regression, sorry for it! Just published v2.4.1 to fix it.

**Comment by sashee** [comment]
That was fast:) Thanks!
