### ISSUE TITLE
Remotion Preview: Change dimensions in preview

### ISSUE THREAD

**Issue by marcusstenbeck** [remotion-dev/remotion#610]
# Feature Request 🛍️

Toggle between composition size and custom size.

## Use Case

I'm making videos that targets the usual sizes (16:9, 1:1, 9:16). In order to speed up my work I'd love to be able to toggle between different sizes to "check my template". My need is very similar to testing different screen sizes in web dev. 😄 

## Possible Solution

- Add toggle between custom size (user defined) and Composition size.

**Comment by Iamshankhadeep** [comment]
this is definitely a nice idea. I think we should implement in the future. what do you say @JonnyBurger ?

**Comment by JonnyBurger** [comment]
We already have a way to do it, to duplicate the composition for each resolution that you would like to test. I'll give an example of what you could render in `src/Video.tsx`:

```tsx
const resolutions = [[1920, 1080], [1080, 1080], [1080, 1920]];

return (
   <>
      {resolutions.map(([width, height]) => {
          return (
             <Composition
                id={`MyComp-${width}-${height}`}
                fps={30}
                width={width}
                height={height}
                durationInFrames={150}
             />
          )
      })}
   </>
)
```

Now you can switch between different resolutions with 1 click.
I don't want to add a feature in the editor to change the dimensions dynamically, because then it will not be reflected back into the code and source control.

**Comment by marcusstenbeck** [comment]
@JonnyBurger I did actually test that solution, and it's the way I'm doing it right now.

It's very tedious to switch composition, sync playheads, and then flip back and forth. Then change playhead position, sync with the other comp. Since I'm checking 4 different dimensions (1920x1080, 1080x1080, 1080x1920, 1280x720) I have to sync 4 different playheads in order to check things.

I was thinking about either syncing playheads somehow OR toggling between original and custom dimensions, but since timings may be different between a 2 minute video and a 15 second story version I thought the dimension toggle is the better option.

Come to think of it, it doesn't need to be a toggle. It can be a momentary switch even (e.g. only active on mousedown).

If this really isn't something that the Preview app should do, is there possibly a way to keep the playhead in sync between the compositions? Or set playhead position with some keyboard combination. Anything to make the process less tedious.

What do you think?

**Comment by JonnyBurger** [comment]
@marcusstenbeck The main issue in essence then, from what I can gather is that the time shifts when switching between compositions, not that it's hard to switch between compositions. (To have a UI that changes the dimensions on-the-fly is IMO a very unnatural feature and I would rather not have it, since then a video is changed and that change will not be reflected in the code.)

What we could do is:

If the composition is switched && the new composition has the same component => then we keep the same time (if time is between 0 and new duration)

or:

If the composition is switched && the new composition has the same component && the new composition has the same duration => then we keep the same time

Which one would you prefer?

**Comment by marcusstenbeck** [comment]
@JonnyBurger After having thought about it for a bit I've realized that syncing on time isn't a great solution since it makes too many assumptions about the two compositions being compared. And really, it's the comparison of two things that I'm after. 

I believe both the suggestions you made and my idea about syncing playheads are the wrong path to take to solve this. It makes implicit assumptions about the relationship between two compositions that really might not be there. I can see that implementing some sort of time-sync feature has a big risk of being potentially confusing and/or a center of growing complexity.

Instead, I've looked back at the video editing suites I've used, and their approaches to comparing or evaluating something. They have a "source monitor" and a "program monitor". The source monitor is kind of a staging area where you can evaluate some media before potentially adding it to the timeline, and the program monitor reflects what's in the timeline at the moment. So in a sense it's a main preview and a secondary preview, side by side.

Viewing two compositions, main and reference, would solve my issue and maybe be more in line with the scope of Remotion?

![image](https://user-images.githubusercontent.com/616906/135812146-f5913f56-2f2f-435a-9827-df4ad6dcc294.png)

**Comment by JonnyBurger** [comment]
I like that we don't make any assumption about any connections between two compositions, but wouldn't it be even more complicated to show two compositions at the same time? If we don't assume any connection between them, we also need two timelines and the problem is not really solved then either.

**Comment by marcusstenbeck** [comment]
Keeping track of two individually uncoupled timelines has some technical complexity to it, but I think it's more straightforward than making assumptions about how time is connected between two compositions (there's framerates to consider then too!).

I still think the original suggestion I made is the cleanest way of doing things, but I respect that you have a strong opinion against it.

I'll leave it for now, and might just `patch-package` the Preview locally for myself.

Cheers!

**Comment by JonnyBurger** [comment]
Sounds good to me, before we make any change, let's be sure it holds up for many years.

Once we have good ideas, we can implement those.
