### ISSUE TITLE
Autocomplete for Fig Terminal (Fig.io)

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#614]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/614)

[Fig](fig.io) is a really nice Terminal extension.

We should contribute autocomplete suggestions for Remotion to. https://github.com/withfig/autocomplete

---

🎃   This issue is eligible for **Hacktoberfest**!
In addition to helping you get a contribution towards your [Hacktoberfest](https://hacktoberfest.digitalocean.com/) reward, Remotion pays a $100 bounty for it!

**Read**: [How to contribute to Remotion](https://github.com/remotion-dev/remotion/blob/main/CONTRIBUTING.md)

- Let us know when you are interested in this issue, and we'll assign you!
- In order to prevent issues from getting stuck, try to progress the issue by opening a PR and adding commits. If your progress is stale for 7 days, another user can ask to take over the issue.

**Approval criteria for this PR:**
- Submit an autocomplete JSON file to https://github.com/withfig/autocomplete and follow their guidelines.
- We should support the `npx remotion render`, `npx remotion still`, `npx remotion preview`, and `npx remotion upgrade` commands and the respective flags. See `npx remotion` for a reference of the schema.
- _Bonus_ but not required: Autocomplete for `npx remotion lambda`

We will pay out the bounty regardless of whether Fig merges the PR if we think it's a good schema!

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)

### Submitted pull Requests
- [#625 Adding Fig.io section to the docs](https://issuehunt.io/r/JonnyBurger/remotion/pull/625)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JonnyBurger** [comment]
Yep! I'm assigning you, good luck! 😊

**Comment by MatteoGauthier** [comment]
> Yep! I'm assigning you, good luck! 😊 

Thanks a lot ! 😁

**Comment by MatteoGauthier** [comment]
@JonnyBurger Do you want the auto-completion for `npm init video` ?

**Comment by MatteoGauthier** [comment]
Hi @JonnyBurger i've created the pull request with the autocompletion works done 😁. Let me know if you have comments. Thanks for this opportunity

**Comment by JonnyBurger** [comment]
Wow 👏  This is nice! Looking at the schema, it looks correct and complete! Thanks a lot for making it!
- Lambda: I thought about it and the schema will probably change still, and you cannot use it in the current release anyway. So we can skip it!
- `npm init video` / `yarn create video`: I didn't even think about it, but if it's possible that would be sick! Looks like for `yarn` two suggestions are there, but none for NPM:
![image](https://user-images.githubusercontent.com/1629785/135720616-ab7b0196-2f5d-43db-b7dd-4b59775fb3fe.png)

If you are done making changes to the PR, please make a mock PR to Remotion (maybe you can even add to the bottom of `cli.md` that, by the way, you can use Fig), that's the only way the PR counts towards hacktoberfest and I can pay you the $100 bounty!

**Comment by MatteoGauthier** [comment]
Okay i will add `create-video` to fig autocompletion, the `npm init` command is not implemented in fig...

**Comment by MatteoGauthier** [comment]
@JonnyBurger Thanks a lot for your work, remotion is a great product ! ✨
(The PR is submitted to IssueHunt)

**Comment by JonnyBurger** [comment]
Thanks a lot! 🙌🏼 one last thing, can you mark the PR as ready to review? Right now it's still a draft.

**Comment by MatteoGauthier** [comment]
> Thanks a lot! 🙌🏼 one last thing, can you mark the PR as ready to review? Right now it's still a draft.

Done ✅

**Comment by JonnyBurger** [comment]
Nice!! Now let's hope for the best 😃
Thanks a lot once again!
