### ISSUE TITLE
Template "Empty"

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#616]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Funded-%2300A156.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/616)

For those people who already know Remotion, it might be useful to skip the "Hello World" and start with an "Empty" template. This template should be the default Typescript template but a blank Canvas.

---

🎃  This issue is eligible for **Hacktoberfest**!
In addition to helping you get a contribution towards your [Hacktoberfest](https://hacktoberfest.digitalocean.com/) reward, Remotion pays a $100 bounty for it!

**Read**: [How to contribute to Remotion](https://github.com/remotion-dev/remotion/blob/main/CONTRIBUTING.md)

- Let us know when you are interested in this issue, and we'll assign you!
- In order to prevent issues from getting stuck, try to progress the issue by opening a PR and adding commits. If your progress is stale for 7 days, another user can ask to take over the issue.

**Approval criteria for this PR:**
- Make a new repo, `template-still`, which should contain the same code as https://github.com/remotion-dev/template-helloworld
- Remove the Hello World code and only have 1 composition, 1280x720 and empty.
- Remove the SSR code and dependencies.
- Adapt the README if necessary.
- Transfer the repo to the `remotion-dev` organization.
- Make a PR to add it to the list of templates.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)

### Submitted pull Requests
- [#620 add template-empty to the template list](https://issuehunt.io/r/remotion-dev/remotion/pull/620)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by aneeshrelan** [comment]
I'd like to give this a try. Can you please assign this to me?

**Comment by Iamshankhadeep** [comment]
@aneeshrelan I am assigning it to you. all the best
