### ISSUE TITLE
Still image is black when using @react-three/postprocessing <DepthOfField/>

### ISSUE THREAD

**Issue by dnnsjsk** [remotion-dev/remotion#623]
Hey, first of all: thanks for this awesome tool! It works wonderfully!

I have been using Remotion with great success in combination with React Three Fiber. Even the post-processing is working wonderfully, however, it seems like when the ```<DepthOfField />``` [component](https://github.com/pmndrs/react-postprocessing/blob/master/src/effects/DepthOfField.tsx) is used, the render output is just black.

I'm not using Remotion to export videos, only stills.

**Comment by JonnyBurger** [comment]
Hey Dennis!

Thanks a lot for the nice words, really glad to hear you are enjoying Remotion!

I never used that component before, so could you post an example or a snippet of how you use the component? Then we can evaluate whether it's an issue with Remotion, or try to help out in general.

**Comment by dnnsjsk** [comment]
I've created a minimal repo showcasing the problem here: https://github.com/dnnsjsk/r3fpp-remotion-bug

```npm run still``` will work

However, once you uncomment this bit here: https://github.com/dnnsjsk/r3fpp-remotion-bug/blob/main/src/Scene.tsx#L61-L66

The still from the command will be just black

**Comment by JonnyBurger** [comment]
Thanks a lot for the repro!
Very glad you raised this issue. It turns out it's a behavior of Chrome that only activates in headless mode. After playing around with flags, I merged #624 which will solve your issue and some other ones too!

**Comment by dnnsjsk** [comment]
Legend, thank you!!
