### ISSUE TITLE
Remotion still image is blank unless <Video/ > element is present

### ISSUE THREAD

**Issue by dnnsjsk** [remotion-dev/remotion#636]
Hey,

I am not sure this is a bug or me doing something wrong. While reproducing the issue I noticed that it worked in the standard Remotion R3F template. However, it only works if Remotions ```<Video />``` element is present.

The repo is here: https://github.com/dnnsjsk/r3fpp-remotion-bug/tree/video

```npm run still``` will result in a blank image.

Uncomment this line: https://github.com/dnnsjsk/r3fpp-remotion-bug/blob/video/src/Scene.tsx#L30

And ```npm run still``` will render the image correctly.

**Comment by JonnyBurger** [comment]
Thanks a lot for filing! We just finally released v2.4.3 which should resolve your previous bug. Can you do a check whether the bug is also fixed with the new release?
