### ISSUE TITLE
Media tag duplicates if volume is interpolated

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#652]
![image](https://user-images.githubusercontent.com/1629785/137771931-ecb467e4-d99d-450b-8478-3d3827bd0a0a.png)

![image](https://user-images.githubusercontent.com/1629785/137771943-3a42e3fd-070e-4eb3-aa2e-11a530d30702.png)

**Comment by JonnyBurger** [comment]
@nandorojo

This is a case where Remotion cannot gather enough context to display a good timeline in rich timeline mode.

So we are suggesting to use a callback function for the volume prop instead. To educate users better, we are adding a console warning + ESLint rule for this case: #680

**Comment by nandorojo** [comment]
I think that works! That API was solid for me.
