### ISSUE TITLE
Dynamic durationinFPS for Audio

### ISSUE THREAD

**Issue by ThatNerdUKnow** [remotion-dev/remotion#653]
I was looking through the docs and you can parametrize pretty much everything using the delayrender and continuerender hooks. The example on the website shows how to wait until the metadata for a video is loaded then continue rendering to load the full video. Is there a way to dynamically set the duration for audio as well?

**Comment by JonnyBurger** [comment]
Hi Brandon!

Yes indeed, you can use the function [`getAudioDuration()`](https://remotion.dev/docs/get-audio-duration) from `@remotion/media-utils` and use the same technique - delay the render, fetch the duration, and use it as an input prop to parametrize the video.

Hope this helps!
