### ISSUE TITLE
Player custom playback buggy behavior

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#658]
Reported by `@krlk89` on Discord:

> 1) i am calling the toggle() method when clicking on my play button and also listening for the ended event to change the state of my button in case the video has played to completion. in the event handler i have to call the pause() method otherwise the next time toggle() is called it will be out of sync with the palyer. imho it makes sense that when the video has ended then calling toggle() will start it from the beginning?
> 2) the video might start looping when i have used seeking (sometimes with no sound).
> 3) maybe there could be a check that seekTo does nothing when the frame number that gets passed is greater than durationInFrames? it could be done on the implementation side, but if there are no downsides then maybe it can be built in?

**Comment by JonnyBurger** [comment]
Hi @krlk89, regarding 1. I find that calling `.toggle()` after the `ended` event will start the video from the beginning, no matter if done immediately, or with a timeout.

```tsx
		playerRef.current.addEventListener('ended', (e) => {
			setTimeout(() => {
				current.toggle();
			}, 1000);
		});

```

Do you have the `loop` property and so the video never even stops?

#2 was a race condition which we fixed already in the meanwhile in #631.

Regarding #3, I agree and have opened a fix here: #688

**Comment by JonnyBurger** [comment]
I merged fixes for 2 and 3, for 1) if you have a better repro I am happy to reopen the issue!

**Comment by krlk89** [comment]
thank you for the fixes!
i could not reproduce 1) anymore, so it's all good from my side.
