### ISSUE TITLE
backdropFilter blur() doesn't apply in rendering mode due to ANGLE renderer

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#659]
to be confirmed and fixed

**Comment by nandorojo** [comment]
In my case, it works but only sometimes. 

One thing to keep in mind if you fade in a component: be sure to apply `opacity` to the same element that has the blur

**Comment by JonnyBurger** [comment]
Updated the repo with green text as suggested.
While the blur works, it disappears fast as you decrease the opacity.

But, same in preview as in render :(

If no repro can be done, I suggest the closing of the issue.

**Comment by nandorojo** [comment]
Yeah just go ahead and close fhen

**Comment by nandorojo** [comment]
@JonnyBurger weirdly I have once again gotten this issue (only when rendering). I tried adding `--angle=gl` when exporting my video, but still no luck. 

<img width="1179" alt="Screen Shot 2022-10-13 at 12 59 15 PM" src="https://user-images.githubusercontent.com/13172299/195659995-aae75a0d-f748-4a9a-aa84-08ef92f2bedb.png">

^ preview mode, works properly

<img width="1143" alt="Screen Shot 2022-10-13 at 12 58 58 PM" src="https://user-images.githubusercontent.com/13172299/195660020-880355e3-7a6d-4d1e-9f33-352c0c8dab30.png">

^ exported, doesn't actually blur correctly.

I'm doing it like this:

```tsx
const opacity = interpolate(
	frame,
	[fadeInAtFrame, fadeInAtFrame + fadeInFrameDuration],
	[0, 1],
	{
		extrapolateRight: 'clamp',
		extrapolateLeft: 'clamp',
		easing: Easing.inOut(Easing.quad),
	}
)

<AbsoluteFill
	style={{
		// backgroundColor: `rgba(28,28,28,0.5)`,
		backgroundColor: `rgba(255,255,255, ${interpolate(
			opacity,
			[0, 1],
			[0, 0.3],
			{
				extrapolateLeft: 'clamp',
				extrapolateRight: 'clamp',
			}
		)})`,
		backdropFilter: `blur(${interpolate(
			opacity,
			[0, 0.1, 1],
			[0, 10, 20],
			{
				extrapolateLeft: 'clamp',
				extrapolateRight: 'clamp',
			}
		)}px)`,
		zIndex: -1,
	}}
/>
```

**Comment by JonnyBurger** [comment]
Hi @nandorojo!

I tried to break down the example into a component that I could run:

```tsx
import {AbsoluteFill, OffthreadVideo} from 'remotion';

export const Blur: React.FC = () => {
	return (
		<AbsoluteFill>
			<OffthreadVideo src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" />

			<AbsoluteFill
				style={{
					width: '50%',
					height: '50%',
					left: '25%',
					top: '25%',
					backgroundColor: `rgba(255,255,255, 0.3)`,
					backdropFilter: `blur(20px)`,
				}}
			/>
		</AbsoluteFill>
	);
};
```

To render:

```
npx remotion render src/index.tsx blur --frames=230-260
```

Newest Remotion version, default settings. It seems to work for me!
Are you able to find the difference between my and your setup and if you find a bug, can you provide a runnable component?

https://user-images.githubusercontent.com/1629785/195853717-97d3c717-7145-4be2-b6e4-f997e01ddacb.mp4
