### ISSUE TITLE
Have a way to import static assets locally via URL (not via import)

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#675]
This is a pretty popular usecase, all kind of assets get imported that way.. .glt, .ttf...

**Comment by loicnestler** [comment]
Any updates on this?
Or at least workarounds?

**Comment by JonnyBurger** [comment]
The best workaround is to host it publicly, e.g. in a S3 bucket.

I realize this is annoying, I'll make sure to prioritize it higher!

**Comment by loicnestler** [comment]
Would you be fine with a solution like:

Add an argument to remotion's run / dev command that runs `vercel/serve` in parallel to webpacks build steps? 
I might find the time to create a small PR for this.

**Comment by Iamshankhadeep** [comment]
hey @loicnestler if you want do consider sending a PR for it. We would be happy to implement this feature. thanks

**Comment by JonnyBurger** [comment]
Fixed by #736 !
