### ISSUE TITLE
Wrapping a Three.JS component in <Suspense> causes a silent timeout

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#676]
Because we already wrap it in Suspense. Probably not so obvious for the user why this happens...

**Comment by JonnyBurger** [comment]
You are right @dnnsjsk! Sorry for the repeated trouble with the Three integration. Now it was broken when there was no component suspending.

Will fix it with #679 and will be in the next release, you can install `2.6.0-alpha.1+ec1b2dd3e` to get the bugfix right now.

**Comment by dnnsjsk** [comment]
Hey @JonnyBurger 
I've just tried this project with 2.6.0-alpha.3 and now it renders without problems.

However, uncommenting https://github.com/dnnsjsk/r3fpp-remotion-bug/blob/video/src/Phone.tsx#L30 will render a blank image.

**Comment by JonnyBurger** [comment]
@dnnsjsk Thanks for reporting! We've fixed this as well, and sent you a PR
