### ISSUE TITLE
PlayerUI Uncaught Error.  Dynamic Import -> Mentions React.lazy()

### ISSUE THREAD

**Issue by blakebullis** [remotion-dev/remotion#682]
Here is a screenshot of my Chrome console.  It looks like the error boundary inside the remotion/player is being fired off.  Not sure what or where it is exactly being fired from.  I am using the player inside a next@12 and react@17 setup.

I just started getting the error after a large upgrade across multiple packages.

https://res.cloudinary.com/missilemedia/image/upload/v1635868293/Screen_Shot_2021-11-02_at_11.49.33_AM.png

**Comment by blakebullis** [comment]
Issue is resolved.  It was not a PlayerUI issue.  There was an error within from a component that was being passed into the PlayerUI and captured by the ErrorBoundary of the PlayerUI.

**Comment by JonnyBurger** [comment]
Glad it got resolved!
