### ISSUE TITLE
Series.Sequence cannot be nested

### ISSUE THREAD

**Issue by wcandillon** [remotion-dev/remotion#684]
I love `Series.Sequence`, it just makes things so much easier.
I used to rely on nested sequences. For instance:
```jsx
  <Sequence from={160} durationInFrames={330} layout="none">
      <Scene1 />
     <Sequence from={0} durationInFrames={80} layout="none">
       <CenteredText lines={names.slice(0, 3)} />
     </Sequence>
     <Sequence from={80} durationInFrames={80} layout="none">
       <CenteredText lines={names.slice(3, 7)} />
     </Sequence>
  </Sequence>
```

Not a big deal at all but I wasn't able to build the same nesting with `Series.Sequence`

**Comment by JonnyBurger** [comment]
On the contrary, I was able to nest a series inside a series and it worked:

![image](https://user-images.githubusercontent.com/1629785/141085635-c7fb9d15-5726-488a-84ed-5eb5741ed9b7.png)

You can nest another `Series` or just a `Sequence` inside a `Series.Sequence`. Need a better repro or I'll need to close the issue unfortunately.

**Comment by wcandillon** [comment]
Thanks a lot! My issue was that I never used `<Series>` standalone. My apologies.
