### ISSUE TITLE
TimeValue component does not show time but a combination of time and frames

### ISSUE THREAD

**Issue by nestorconde** [remotion-dev/remotion#694]
# Bug Report

TimeValue shows minutes:seconds before the decimal point and after it shows the number of frames after the second. For example, when showing 00:43.17 this is in fact 00:43.{17*fps}. This is a screenshot of the place in the interface I'm talking about.

<img width="408" alt="Screenshot 2021-11-12 at 07 51 32" src="https://user-images.githubusercontent.com/201103/141417024-c79efe3e-796b-43e0-8705-c1d1bc253a75.png">

This is because the component is using renderFrame which does exactly what I described.

In my opinion this is confusing for users. I was trying to create subtitles for a video by using this value as reference and only after spending a lot of time adjusting them to what is shown in TimeValue I realised that my subtitles where not adjusted to the real time of the video.

## Possible Solution

Perhaps create a secondary function renderTime (if it does not already exist in the codebase) instead of renderFrame and use that one instead. Could be something like this:

const renderTime = (frame: number, fps: number): string => {

	const minutes = Math.floor(frame / fps / 60);

	const remainingSec = frame - minutes * fps * 60;

	const seconds = Math.floor(remainingSec / fps);

	const timeAfterSec = Math.round((frame % fps) / fps * 100);

	return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(
		2,
		'0'
	)}.${String(timeAfterSec).padStart(2, '0')}`;
};

If keeping the information of the frames after second (Math.round(frame % fps))  is useful it could be done by adding them between square brackets after the time.

Wasn't sure whether to place this as a bug since perhaps I do not understand why putting a combination of time and frames is useful :)

**Comment by JonnyBurger** [comment]
Hi there! Thanks for bringing this up. I actually never thought about it as much.
While I don't necessarily have a specific preference for one way or another, I think it makes sense to keep it in the same format as other video editing programs. I checked how other vendors (Davinci, Adobe and Apple) do it and it seems like everybody encodes the time in the same format as we do.

Davinci Resolve (opened it and tested myself):
![image](https://user-images.githubusercontent.com/1629785/141688333-016606d4-d4d4-4c3e-a2da-418413ed51ed.png)

Adobe (all the sub-second units are < 30):
![image](https://user-images.githubusercontent.com/1629785/141688403-75dd48fd-7dff-47aa-ad7e-316a05b07836.png)

From Final Cut Pro handbook:
![image](https://user-images.githubusercontent.com/1629785/141688521-21fb1184-ac9a-4590-9221-4075e4b94dc7.png)

So from my point of view, I would like to keep the current format, at least as a default.
