### ISSUE TITLE
StackBlitz template

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#710]
StackBlitz seems nice. Would be cool if we can preview it online

**Comment by sulco** [comment]
Let me know if the StackBlitz team can be of any help! 

I love the idea behind Remotion, but/and that would be an interesting stress test for WebContainers! :)

**Comment by JonnyBurger** [comment]
Thank you @sulco! I will look forward to playing around with it. As a starter, we can get web preview working, which is super useful already, if rendering a video works as well, I will be pleasantly surprised!

**Comment by arthurdenner** [comment]
I did a quick try and the HelloWorld and ThreeJS templates just worked with `npm start`! 🤩 

I imported them directly from GitHub with the following URLs:

- https://stackblitz.com/github/remotion-dev/template-helloworld
- https://stackblitz.com/github/remotion-dev/template-three

I had issues linking my forks to a GitHub repo.

<details>
<summary>More details if you're interested:</summary>

It didn't happen with a static project but it failed for the links above.

https://stackblitz.com/edit/github-4y5bri logs the below in the console.
`client-491bcee22192.js:2 Uncaught (in promise) Error: EEXIST: file already exists`
</details>

**Comment by JonnyBurger** [comment]
That's sick! We are probably going to link StackBlitz containers in #478 so people can test it in the web.

What doesn't work is rendering. I think we cannot add native FFMPEG binaries or launch Puppeteer because everything runs in the browser (let me know if I am wrong about this @sulco) but it is still very useful for quickly experimenting!

**Comment by sulco** [comment]
That's correct, @JonnyBurger – unless we can use something like [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm) at some point?

**Comment by JonnyBurger** [comment]
@sulco Yes, I think it's not ready and Puppeteer is the bigger problem - hope some dope web tech comes to the rescue in the future! :)

**Comment by JonnyBurger** [comment]
A small blocker that degrades the UX a bit: https://github.com/stackblitz/webcontainer-core/issues/643

Other than that, everything is in place to provide StackBlitz links for the future!

**Comment by SamVerschueren** [comment]
That issue is now fixed so it's working as it should be 🔥 🎉 !

**Comment by sulco** [comment]
Wow, I've just tried several templates and it works crazy well! 😍 Can't wait to play with it more! 
And now a "before you buy" experience [like this](https://github.com/faker-js/faker#try-it-online-%EF%B8%8F) should be super easy to add to your readme! :)

Btw. I think we should put one of them on our official starters list on StackBlitz.com too – this could be https://stackblitz.com/github/remotion-dev/template-helloworld, but maybe you have another one that you'd prefer, @JonnyBurger?

**Comment by JonnyBurger** [comment]
Super sick! Incredible how well it works, and how fast! Definitely the best solution out of of all the ones I’ve tried 😃

We’re gonna build a template selector on our homepage and will give the option to clone or use StackBlitz, therefore leaving this issue open 🙂 

@sulco This template is the ideal one to use! Thanks for featuring us as well! 😊
