### ISSUE TITLE
Ensure each npm package has a suitable `README.md` 

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#713]
For those who find e.g. Remotion via npmjs.org

**Comment by Caleb335** [comment]
Hi @JonnyBurger,

If this is still up for grabs, I can work on it. Perhaps you could put me through the necessary things that can be done.

**Comment by JonnyBurger** [comment]
Hi @Caleb335 thank you so much! 😊 Appreciate it!

So each package (such as `cli`, `bundler`, `player`, `renderer`) has a separate page on npm, like this: https://www.npmjs.com/package/@remotion/player

Often times the description is very spare, or there is no README.md file at all. The goal would be to improve it by briefly describing what the package does, mentioning it is part of the Remotion Suite, how to install it, and linking to the docs. Maybe you know about other useful as well!

Also, it doesn't have to be for all packages - even improving one or two for the start would already be appreciated!

**Comment by Caleb335** [comment]
Thank you so much for your feedback @JonnyBurger. It is very detailed. 😎

I get the concept of adding docs for each package, can you point me to the repository where the readme files of the packages that I'll be interacting with are? 

Thanks, and I look forward to your response.

**Comment by JonnyBurger** [comment]
Yes for sure!

For the example of the @remotion/player, you find the README here: https://github.com/remotion-dev/remotion/blob/main/packages/player/README.md

In this example (@remotion/gif), the package has no README at all and the goal would be to add a new file in this directory: https://github.com/remotion-dev/remotion/tree/main/packages/gif

**Comment by Caleb335** [comment]
Thank you for this.

I'll get on to it ASAP.

**Comment by Caleb335** [comment]
Hi @JonnyBurger,

Sorry that this is taking a while. I've not been close to my machine for a while now. When I am. I will definitely send a PR.

**Comment by JonnyBurger** [comment]
@Caleb335 Don't worry, thanks for the update 😊 Enjoy your time off the keyboard 😃

**Comment by Slashgear** [comment]
Maybe we could use https://github.com/kefranabg/readme-md-generator to generate packages README ?

**Comment by Caleb335** [comment]
> Maybe we could use https://github.com/kefranabg/readme-md-generator to generate packages README ?

Oh wow! 

This is a very nice suggestion  @Slashgear. 🔥

I could give this a try, if you don't mind @JonnyBurger

**Comment by JonnyBurger** [comment]
Would be nice! Happy if you go for it @Caleb335 🙂

**Comment by Caleb335** [comment]
Awesome! I'll do just that.
