### ISSUE TITLE
Compositions grouping

### ISSUE THREAD

**Issue by gorhom** [remotion-dev/remotion#730]
Introduce compositions grouping on the side bar.

# Feature Request 🛍️

The request is to provide a way to group compositions on the side bar which will help users to focus on selected groups that they are working on.

## Use Case

For mid to large scale projects, we would en up with a lot of compositions that makes it difficult to find them, for example:

having multiple compositions that serve under the same category like:

![image](https://user-images.githubusercontent.com/4061838/146276293-aca8bf7a-eef4-4d9a-8a61-b2a5c4e020f3.png)

## Possible Solution

1. we could introduce a new grouping component that users has to wrap their compositions under like: 

```tsx
...
<Group id="video" open={true}>
  <Composition
    id="video-1"
  />
  <Composition
    id="video-2"
  />
</Group>
...
```

2. extract group id from compositions id prefix `{id}-name-name}` and then group every composition that include the group id as a prefix. this i have already done in [my fork](https://github.com/gorhom/remotion) which i will be happy to polish and submit a pr if needed ;)

https://user-images.githubusercontent.com/4061838/146276907-290a0445-3300-4b51-bdef-e7f768c5f4df.mov

Finally, thanks a lot for this amazing library @JonnyBurger

**Comment by JonnyBurger** [comment]
Thanks a lot for the feature request @gorhom and sorry for responding only now!

I like the idea in general and would be interested in implementing a `<Folder />` component:

```tsx
export const Video = () => {
   return (
     <Folder name="Video Testing">
		<Composition
				id="video-testing-mp4"
				component={VideoTesting}
				width={1080}
				height={1080}
				fps={30}
				durationInFrames={100}
				defaultProps={{
					codec: 'mp4',
				}}
			/>
			<Composition
				id="video-testing-webm"
				component={VideoTesting}
				width={1080}
				height={1080}
				fps={30}
				durationInFrames={100}
				defaultProps={{
					codec: 'webm',
				}}
			/>
      </Folder>
      <Composition
				id="audio-testing"
				component={VideoTesting}
				width={1080}
				height={1080}
				fps={30}
				durationInFrames={100}
				defaultProps={{
					codec: 'webm',
				}}
	/>
   )
}
```

I prefer this explicit way rather than doing it automatically using the prefix. Would this also work for you?

**Comment by tomByrer** [comment]
> interested in implementing a `<Folder />` component

Seems good for me.
I like the `Folder` term, I was hoping to use [`Group` elsewhere](https://github.com/remotion-dev/remotion/issues/755)

**Comment by JonnyBurger** [comment]
Added in v3.0.1! https://remotion.dev/docs/folder
