### ISSUE TITLE
Get all props/inputProps associated with composition on server-side

### ISSUE THREAD

**Issue by AbdulBsit** [remotion-dev/remotion#731]
Helper Function to get the all inputProps from bundle associated with particular composition or global on server-side, structure may be looks like
```
{
    "compositions": {
        "HelloWorld": {
            fields: ["title", "subTitle"],
            //... other properties of composition (same as return type of getCompositions() )
        },
        "Logo": {
            fields: ["title", "subTitle"],
            //... other properties of composition (same as return type of getCompositions() )
        }
    }
}
```

# Feature Request 🛍️

What i want is the key/fields/inputProps associated with the composition, as they are the placeholder for parameterized/dynamic rendering.

## Use Case

Can be used in creating forms for dynamic parameterized rendering, we can map user inputs with the key assocaited with inputProps used in compositions

**Comment by JonnyBurger** [comment]
Thanks for the feature request! This is a good idea, although currently the schema is defined nowhere, except for in Typescript, which compiles away.

But what we can do is to return the `defaultProps` you defined for each composition, when you call `getCompositions()`. Would that solve your problem?

**Comment by AbdulBsit** [comment]
Yes, that would solve my problem, thanks 👍

**Comment by JonnyBurger** [comment]
Thanks for the offer! It's kinda trivial, already opened a PR. Will do some testing and looking forward to a release in the next few days.

**Comment by AbdulBsit** [comment]
Okay, That's great
