### ISSUE TITLE
Compatibility with Tailwind CSS v3.x

### ISSUE THREAD

**Issue by sboli** [remotion-dev/remotion#737]
Support version 3.x of TailwindCSS

# Feature Request 🛍️
As of now, following the guide on how to integrate TailwindCSS leads to build errors. I figured maybe it was not compatible with 3.x yet. And indeed, setting tailwind to 2.x it did work;

## Use Case

Command line instructed in the docs should work (will install tailwind 3x.)
https://www.remotion.dev/docs/webpack/#enable-tailwindcss-support

**Comment by JonnyBurger** [comment]
Thanks for filing! This is a valid issue.
We'll look forward to updating the docs, for now we added a warning that this documentation concerns V2 of Tailwind.

**Comment by arthurdenner** [comment]
I was testing this today and have some things to share.
I added Tailwind v2 to a new project and then updated it to v2.

On v3, the config file seems to be required, so I had to run `npx tailwind init` to create it. After doing that, Remotion's preview loaded but the styles were not applied.

To fix that, I had to add `content: ['./src/**/*.{ts,tsx}']` to the Tailwind config, so it knows where to find the classes to generate and the styles were applied. To clarify, the value can change if you're using JavaScript, e.g `.{js,jsx}`.

But this resulted in another issue. Often, new styles were not applied and I think it has something to do with other cache issues reported before (maybe https://github.com/remotion-dev/remotion/issues/553?).

The config file gets cached and I had to save it just to "update" it.
Here is a reproduction of the described behaviour:

https://user-images.githubusercontent.com/13774309/148576069-b615a02a-e5f1-4f43-af0d-cafda97d92ad.mp4

**Comment by arthurdenner** [comment]
But if you're okay with this, the steps are:

- Update Tailwind to the v3 (e.g `npm i tailwindcss@latest`)
- Run `npx tailwindcss init` to create the config file
- Add `content: ['./src/**/*.{js,jsx,ts,tsx}']` or similar to the config file

**Comment by JonnyBurger** [comment]
thank you for the research @arthurdenner, I also tried it and came to the same conclusion. Tailwind works on the first load, and will recompile once you change the className once, but always fails on the second attempt. I don't have more info right now, in the worst case we create a repro and file it with the Tailwind team to get advice.

**Comment by arthurdenner** [comment]
No worries. I hope we can find a proper solution. Feel free to fork or use the one I created if you decide to file an issue on Tailwind:

https://github.com/arthurdenner/remotion-tailwind-v3-test

Would you like the update the instructions for v3 on the docs with a disclaimer or not at the moment?

**Comment by JonnyBurger** [comment]
Thanks, will do for sure 😊 

I think better not support v3 at the moment. I wouldn't like the experience of it to always have to restart...

**Comment by HelloKashif** [comment]
@JonnyBurger @arthurdenner fyi: I was able to run v3 without any issues for rendering.

Actually you don't need any of the custom webpack config because you can simply generate the tailwindcss output file before render (even minification isn't needed, because bundle size is not a concern during render)

Simply call `tailwindcss -i <input-css> -o <output.css>` to create the css file and then just import this into your compositions `import ../input-css-file`

Here's my package.json
```
  "scripts": {
    "prerender": "tailwindcss -i ./styles/globals.css -o ./styles/tailwind.css",
    "render": "remotion render remotion/index.js Default out/video.mp4",
  },

```

postcss.config.js nothing fancy
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

Ofcourse for running the preview you might need some effort, but that wasn't my use-case so didn't try.
Hope this helps

**Comment by greendesertsnow** [comment]
I added postcss.config.ts file to the root, with the following code in it:
```
import tailwindcss from 'tailwindcss';
module.exports = {
	plugins: ['postcss-preset-env', tailwindcss],
};
```
And it builds the Hello world template with tailwind classes perfectly fine on Tailwind 3

**Comment by yashness** [comment]
Kindly update the docs, if this is supported now

**Comment by JonnyBurger** [comment]
It does indeed seem to work now without any changes, so I suppose the Webpack or Tailwind update made it possible!

I've created a new template and will add it to `npm init video` as well as our website with #1110! This PR also includes updated documentation.
