### ISSUE TITLE
Improve explanation of the difference between `<Sequence>` and `<Composition>`

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#738]
The docs for these fundamental components could use an overhaul and maybe a more visual explanation.

**Comment by tomByrer** [comment]
`<Composition>` = acts in a play ? (only 1 at a time, in sequence)
`<Sequence>` = a 'track' in the timeline
?

**Comment by Cruz-Azul** [comment]
I'm on it 😉

**Comment by JonnyBurger** [comment]
@Cruz-Azul 🙌
