### ISSUE TITLE
Minor visual regression on current composition

### ISSUE THREAD

**Issue by vincsb** [remotion-dev/remotion#739]
# Bug Report 🐛

Hello there,

In the player, i think there is a minor visual regression on current composition overview. I tag it as bug but it's really not a big deal.

Here is the issue, no margin between image and metadatas:

<img width="1382" alt="current" src="https://user-images.githubusercontent.com/8859537/147146884-3aa6c76d-8f43-425a-9831-bd6463984a6c.png">

Find a screenshot on Remotion blog post for 2.3 version, there was a margin: https://www.remotion.dev/img/still-thumbnail.png

I dig a little bit, this comes from this PR: https://github.com/remotion-dev/remotion/pull/602/files#diff-a45f52ee6f57b84ad186cac2863b29603158b14b6c72050f1e7a44d969e240e8R59

A div with custom styles was replace by `<Spacing />` component, but without `x` props. 
`<Spacing />` component have a default `x` value to `0`, so no margin. (https://github.com/remotion-dev/remotion/blob/main/packages/cli/src/editor/components/layout.tsx#L8)

Just add a value to `1` will be fix it, I can make the PR if you want.

**Comment by JonnyBurger** [comment]
Thanks a lot for reporting! 😊
