### ISSUE TITLE
Many mp4 videos in Sequenze

### ISSUE THREAD

**Issue by raphibolliger** [remotion-dev/remotion#745]
# Bug Report 🐛

I have a Sequenz with 1 or n `.mp4` videos. The following code is more or less in the `RaceClips.tsx` file
```html
return (
  <div>
    <Video startFrom={0} endAt={400} src={sequenz.videoFiles[0].fileName}></Video>
    <Video startFrom={401} endAt={800} src={sequenz.videoFiles[1].fileName}></Video>
    <Video startFrom={801} endAt={1200} src={sequenz.videoFiles[2].fileName}></Video>
  </div>
);
```
This will always play all videos at the same time at the start of the Sequenze. My idea was that each video is playing after the previous one. I am not sure if this is a bug or it is not possible to play more then one video inside a Sequenze.

![image](https://user-images.githubusercontent.com/6289764/147594563-0c660806-5e0a-4ab3-a2a9-00082d144e6d.png)
The output in the Remotion Preview shows also all videos at the beginning of the Sequenze.

**Comment by JonnyBurger** [comment]
Hoi Raphi!

This prop defines how much of the beginning of the video should be cut off, not where in the timeline it should start.

You could therefore refactor code as follows:

```tsx
<div>
  <Sequence from={0} durationInFrames={400}>
    <Video src={sequenz.videoFiles[0].fileName} />
  </Sequence>
  <Sequence from={400} durationInFrames={400}>
    <Video src={sequenz.videoFiles[1].fileName} />
  </Sequence>
  <Sequence from={800} durationInFrames={400}>
    <Video src={sequenz.videoFiles[2].fileName} />
  </Sequence>
</div>
```

or more concise:

```tsx
<div>
  <Series>
    {sequenz.videoFiles.map((video, i) => {
      return (
        <Series.Sequence key={i} durationInFrames={400}>
          <Video src={video.fileName} />
        </Series.Sequence>
       )
    })}
  </Series>
</div>
```

I assume this will solve it, let me know if not!
