### ISSUE TITLE
Provide error warnings in timeline UI

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#754]
# Feature Request 🛍️

Have a pop-up box or something in the timeline-player, when bad React programmers like myself make an error.  Console does provide errors, but took me a minute to think of looking there.

## Use Case

Console.log :
`Uncaught Error: Groupings(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`
oops

edit: [might be fixed in v2.6](https://github.com/remotion-dev/remotion/pull/751/files#diff-24cb3220cd3e5318fc73d775b6f8422b5779f9f1c1917885771fe82d861ee790)

**Comment by JonnyBurger** [comment]
You are right, it is fixed in 2.6 😃 Same idea as I had!

**Comment by tomByrer** [comment]
I think I saw the new in-UI error report once of the past 2 days.  I keep seeing the "White Screen of Death" & have to open DevTools:Console to figure out the cryptic errors to find my typos.

**Comment by JonnyBurger** [comment]
@tomByrer can you give an example of how to trigger an error that does not pop up the overlay?

**Comment by tomByrer** [comment]
Works better now; cheers!
