### ISSUE TITLE
TimelineSliderHandle is not draggable

### ISSUE THREAD

**Issue by flowforfrank** [remotion-dev/remotion#760]
# Bug Report 🐛

Thank you for the awesome tool @JonnyBurger!

Usually, in video editors, the user can drag the seek bar around in the timeline by grabbing the knob at the top. This is not possible in Remotion as it grabs click events:

![seeking](https://user-images.githubusercontent.com/7797154/148521251-0fa9b392-a10c-465f-99bd-9d415f8d9216.gif)

The issue likely could be fixed by applying `pointer-events: none` to the said element's container as shown in the gif above. While it's a small change, it would allow users to navigate the timeline more easily.

**Comment by JonnyBurger** [comment]
Hey Ferenc! 

Thanks a lot for the report, I love these issues coming from attention to detail 🙂  Will be fixed soon!
