### ISSUE TITLE
Render with audioData and visualization

### ISSUE THREAD

**Issue by michaelGregoire** [remotion-dev/remotion#768]
First I want to say thanks for such a terrific framework! This is something I've long needed. So far everything's been working beautifully when previewed. However, when it comes time to rendering it, that's another thing altogether.

When I try to build, I get the following error, with the frame number being anywhere between 3 and 6:

`The following error occurred when trying to render frame 5:
Error: A delayRender was called but not cleared after 25000ms. See https://remotion.dev/docs/timeout for help. The delayRender was called:
    at delayRender (http://localhost:3000/bundle.js:4594:32)`

I have no problem rendering when I'm not getting audioData from useAudioData() or using visualizeAudio, though, so it's clearly that which is the problem.

I first experienced this issue when trying to render the audiogram demo. At the time I simply ignored that and proceeded to try and create my own project to see what happens. Again, everything was great until trying to get audioData and visualize audio. The minute I tried to render again, it failed.

What's weird is that I went back to the audiogram project and tried it again. It suddenly rendered. So, I don't know if there's any caching that's occurring that eventually allowed the audiogram project to render after a few tries, or not. 

However, I'm beginning to think that even if there's caching of the data, my chance of a successful build are slim. I'm doing this to create an hour long video for my music label's monthly podcast. I've tried reducing the audio file size by using an .mp3 instead of a .wav, but that hasn't helped.

I checked out the timeout troubleshooting page, and tried a delayRender/continueRender solution similar to what's outlined here (https://www.remotion.dev/docs/delay-render), but that hasn't helped.

Anyway, does anyone have any ideas on how to handle such a long audio file? Is this a lost cause?

Oh… and a few details:

**Audio file length:** 60:15
**Format:** .jsx
**Node:** v16.13.1
**OS:** macOS 10.14.6
**Processor:** 2.6 GHz Intel Core i7
**Memory:** 16 GB 2400 MHz DDR4
**CPU usage before:** 2%
**Peak CPU usage during:** 57.58%
**Memory usage before:** 7GB
**Peak memory usage during:** 14.78GB

I'd be happy to zip up the project and send it to someone on the remotion team via dropbox, if you want to take a deeper look.

**Comment by tomByrer** [comment]
> long audio file?

How long is long?  What is your system & renderer memory usage before & during this?

One of my main use cases is to use Remotion with podcasts.

**Comment by michaelGregoire** [comment]
> > long audio file?
> 
> How long is long? What is your system & renderer memory usage before & during this?
> 
> One of my main use cases is to use Remotion with podcasts.

Good questions. I've updated the details.

**Comment by JonnyBurger** [comment]
Hi Michael!

Thanks a lot for the detailed writeup 👌  very helpful.
The API is designed that it needs to fetch the full audio file and process it, for which 25 seconds is probably too little in your case. For your scenario I don't see any solution other than increasing the timeout.

This is something we want to support anyway, I'll work on adding this to unblock you hopefully as soon as possible.

**Comment by michaelGregoire** [comment]
Hi Jonny! Thanks so much! Yeah, increasing the timeout was one thing that I looked into doing and did see that's currently not configurable. So, yeah, if you could add support for that, it would be fantastic! Thank you!

**Comment by JonnyBurger** [comment]
Possible in Remotion 2.6.3!

https://www.remotion.dev/docs/timeout#increase-timeout

**Comment by michaelGregoire** [comment]
That was fast! Thanks Jonny!

**Comment by michaelGregoire** [comment]
100000 was the magic #! Thanks again.

**Comment by michaelGregoire** [comment]
And here's a snippet… https://www.dropbox.com/s/aoauuzl1osqs77x/BSBCTBR0041.mp4?dl=0

**Comment by JonnyBurger** [comment]
@michaelGregoire Dope! 🔥

**Comment by michaelGregoire** [comment]
Another couple snippets… 

https://www.dropbox.com/s/b0s3w7vwpsep3b3/BSBCTBR0041-a.mp4?dl=0

https://www.dropbox.com/s/m2y28huer9nd169/BSBCTBR0041-b.mp4?dl=0

This framework is blowing my mind and I know I'm just beginning to scratch the service!

**Comment by michaelGregoire** [comment]
@JonnyBurger I thought you might like to see the final result! https://www.youtube.com/watch?v=UnXHmCV7NRE

**Comment by JonnyBurger** [comment]
@michaelGregoire Indeed! Super nice usecase, now I see why the timeout increase function had to happen 😊

The visuals look awesome, I'm happy to see you're live with an awesome project 🙂  Congrats 🎉

**Comment by michaelGregoire** [comment]
> @michaelGregoire Indeed! Super nice usecase, now I see why the timeout increase function had to happen 😊
> 
> The visuals look awesome, I'm happy to see you're live with an awesome project 🙂 Congrats 🎉

Thanks @JonnyBurger!
