### ISSUE TITLE
remotion upgrade command does not update package.json

### ISSUE THREAD

**Issue by michaelGregoire** [remotion-dev/remotion#772]
I just used the `remotion upgrade` command to upgrade to 2.6.3, but the versions in my `package.json` were not also updated to match the newly installed version. Fixing that might prevent any confusion.

**Comment by JonnyBurger** [comment]
It just runs `npm update remotion @remotion/cli ...` under the hood and this is the behavior that it does.

However, maybe we can change the command so it does `npm install remotion@^2.6.3 @remotion/cli@^2.6.3 @remotion/renderer@^2.6.3`  and this would update + be less confusing 😃. Good idea!

**Comment by michaelGregoire** [comment]
Yeah, that'd be great! I was so confused after running that and the package.json still showing the previous version. 😂

Doing the npm install would be a good idea so that when you push the project to a remote repo and another dev pulls it down, npm ci will install the most recent version and the other dev doesn't have to run the upgrade command, too.

**Comment by JonnyBurger** [comment]
Sounds good! I'll try that soon and also make it package-manager-agnostic (npm / yarn / pnpm).
Just to clarify: What it currently does is an actual upgrade though, because it updates the lockfile. So the other dev will also get the newer version.

**Comment by michaelGregoire** [comment]
Cool. Thanks! Oh, I never checked the lockfile.
