### ISSUE TITLE
CLI --quality option support for environment variables

### ISSUE THREAD

**Issue by michaelGregoire** [remotion-dev/remotion#778]
So, I'm adding a couple custom scripts to my package.json to make rendering a little more configurable via environment variables. One of the scripts I added is the following:

```
"build:frames": "FRAMES=0-1000 QUALITY=50 remotion render --frames=$FRAMES --image-format='jpeg' --quality=$QUALITY src/index.jsx IDENTIFIER out/segment.mp4",
```
As you can see, I'm making the `--frames` and `--quality` configurable via environment variables in the command line. `--frames` works perfectly. However, `--quality` complains that the value provided by the environment variable is a string and seems to end up with an empty string. 

```
Error: Quality option must be a number or undefined. Got string ("")
```

It would be great if the option passed the value through to parseInt() and then only throw the error when the output from parseInt() is `NaN`.

**Comment by JonnyBurger** [comment]
Hi @michaelGregoire! Thanks for filing the issue.

After some tinkering, I find that this is purely a behavior of the shell / npm scripts and not with Remotion - you cannot define env variables this way. For example:

```json
"scripts": {
	"quality": "QUALITY=50 echo $QUALITY"
}
```

`npm run quality` will yield an empty string (this is also why you got this error message).

But what would work is `QUALITY=50 npm run update`. This probably makes more sense than defining a env variable and then hardcoding it in the same command.

Potentially interesting for you: You may also use the config file and script it with Typescript: https://www.remotion.dev/docs/config#setquality

**Comment by michaelGregoire** [comment]
Thanks @JonnyBurger. It turns out I was doing what I wanted to do initially wrong.

I had started with the following and it seemed to work for FRAMES, but when I added QUALITY, it failed:

```console
"build:frames": "remotion render --frames=${FRAMES:0-100} --image-format='jpeg' --quality=${QUALITY:50} src/index.jsx IDENTIFIER out/segment.mp4",
```

…so I moved on to what I previously showed you:

```console
"build:frames": "FRAMES=0-1000 QUALITY=50 remotion render --frames=$FRAMES --image-format='jpeg' --quality=$QUALITY src/index.jsx IDENTIFIER out/segment.mp4",
```

However, what I needed to do was the following, which works:

```console
"build:frames": "remotion render --frames=${FRAMES:-0-100} --image-format='jpeg' --quality=${QUALITY:-50} src/index.jsx IDENTIFIER out/segment.mp4",
```

Now, I can override with environment variables like so:

```console
FRAMES=0-1000 QUALITY=70 npm run build:frames
```

**Comment by JonnyBurger** [comment]
Perfect, glad the problem is resolved!
