### ISSUE TITLE
validateOutname error on Lambda Rendering via Node.js API

### ISSUE THREAD

**Issue by mindbugg** [remotion-dev/remotion#781]
We tried rendering using Lambda function with Node.Js API and getting this error

`{"chunk":null,"frame":null,"stack":"TypeError: The `outName` property must be a string. Passed an object of type undefined\n    at validateOutname (/var/task/index.js:137695:11)\n    at innerLaunchHandler (/var/task/index.js:139197:3)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async launchHandler (/var/task/index.js:139444:5)","type":"stitcher","isFatal":true,"tmpDir":null,"attempt":1,"totalAttempts":1,"willRetry":false}`

**Comment by JonnyBurger** [comment]
As you mentioned in Discord, you solved the issue.

Resolution for those facing this problem: Upgrade to the newest version of Remotion Lambda.
