### ISSUE TITLE
docs/player/integration is confusing & semi-broken

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#785]
1st issue for [/docs/player/integration](https://www.remotion.dev/docs/player/integration)

# Bug Report 🐛

defaultProps in Player example doesn't render

For both a new NextJS project & Astro, I can get the [example tutorial](https://www.remotion.dev/docs/player/integration) to work, somewhat.  I see the player that displays `Hello !`, but it is missing "World" from the `<Composition ... defaultProps={{ text: "World" }}/>`.  I do change the file extensions to `.jsx`, so one of my files is slightly different:
```jsx
// MyComp.jsx
export function MyComp({ text }) {
	return <div>Hello {text}!</div>
}
```

But that does render& seems like valid JSX to me, just props are not being passed *into* it....

TIA :)

**Comment by tomByrer** [comment]
OK, I figured it out; the `<Player>` in the example was missing `inputProps`, which is called `defaultProps` in `<Composition>`.  I fixed the example in the docs, so short-term problem solved.

But having 2 different prop names for the same thing is confusing to me; could there be a single name, either `inputProps` (preferred) or `defaultProps` for both `<Player>` & `<Composition>`.  My brain can remember only so much.  ;)

**Comment by tomByrer** [comment]
Seems the files `index.tsx` & `Video.tsx` are only needed when running [Remotion preview](https://www.remotion.dev/docs/player/integration#using-remotion-preview) from inside the app's 'monorepo'.  Likewise, installing the bundler, cli, & renderer are unneeded dependencies if all one wants to do is just install the `<Player>`?

I think there should be separate web pages, or at least clear, distinct sections for those who just want to add a `<Player>` to an existing app, vs those who want the entire Remotion ecosystem in an existing 'monorepo'.  Both are valid & common enough use cases, but not the same IMHO.

**Comment by JonnyBurger** [comment]
Thanks for the report!

- 1st/2nd: It's always `inputProps` for all rendering purposes, but while starting the preview, you would have to restart the server to pass `inputProps` (which you can actually), but there can be default props, for when you pass no input props. I think it makes sense to keep them as two different prop names as they are two different things. I am however adding a validation to  give you an error if you pass `defaultProps` accidentially to hopefully ease the confusion you faced 🙂 

- 3rd: That's true, my intended structure is to have the [Player installation section](https://remotion-9t4524p63-remotion.vercel.app/docs/player#installation) for if you only want Remotion Player in a React App, and [Integration](https://www.remotion.dev/docs/player/integration) for if you want a hybrid project with CRA setup and Remotion setup, so you can use the Preview to quickly iterate. I'll improve on this structure by making a separate installation page.

I'm taking this feedback and fixing it with #787
