### ISSUE TITLE
[FEATURE-REQUEST] Ignore SSL certificate errors

### ISSUE THREAD

**Issue by psociety** [remotion-dev/remotion#789]
ty for making remotion!! It makes video creation really easy!!!

When playing in localhost, SSL certs are usually self signed and chrome likes to cry about it (breaking all images in the process) .

# Feature Request 🛍️

I would be cool to add `--ignore-certificate-errors` to puppeteer, so localhost development isn't affected by SSL.

## Use Case

Request an image under a selfsigned SSL host like (`https://remotion.localhost/img/demo.jpg`), see how it shows broken on rendered video.

## Possible Solution

Add `--ignore-certificate-errors` to puppeteer startup.

**Comment by JonnyBurger** [comment]
Good idea! Implemented.

Please wait for the 2.6.5 release and then look here: https://www.remotion.dev/docs/chromium-flags

**Comment by psociety** [comment]
**GOD LIKE**
https://www.youtube.com/watch?v=i23s-i3C-nU
