### ISSUE TITLE
Bug related to <Sequence> and <Freeze>

### ISSUE THREAD

**Issue by White-Green** [remotion-dev/remotion#792]
Thanks to useful tools!

I use following environment.
- Remotion: "^2.3.2"
- Google Chrome: 97.0.4692.71 (Official Build) （64 bit） (cohort: Stable)
- OS: Windows 10 Version 21H1 (Build 19043.1469)

In the following code, I expected the Test component displays "100", but in fact it displays "-100".

```tsx
export const Test: React.FC = () => {
	const SequenceFrom = 200;
	const FreezeFrame = 100;
	return <>
		<Sequence from={SequenceFrom}>
			<Freeze frame={FreezeFrame}>
				<TestComponent />
			</Freeze>
		</Sequence>
	</>;
};

const TestComponent: React.FC = () => {
	const frame = useCurrentFrame();
	return <>{frame}</>;
};
```

I tried some combinations of SequenceFrom and FreezeFrame, and the result is shown in the below table.

| SequenceFrom | FreezeFrame | I expected | Displayed |
|:-:|:-:|:-:|:-:|
| 200 | 200 | 200 | 0 |
| 200 | 100 | 100 | -100 |
| 200 | 0 | 0 | -200 |
| 100 | 200 | 200 | 100 |
| 100 | 100 | 100 | 0 |
| 100 | 0 | 0 | -100 |
| 0 | 200 | 200 | 200 |
| 0 | 100 | 100 | 100 |
| 0 | 0 | 0 | 0 |

I think the frame calculation of the Freeze component does not consider the effect of Sequence.

**Comment by JonnyBurger** [comment]
Woah thanks for reporting and the clear reproduction!

Will fix this with #793.
