### ISSUE TITLE
Problem with `--single-process` and concurrency on Linux

### ISSUE THREAD

**Issue by rebotnix** [remotion-dev/remotion#807]
Hi, i´m not able to render any demo on ubuntu 18.04, i try to render it via remote ssh shell. 

npx remotion render src/index.tsx Audiogram out.mp4
📦 (1/3) [====================] Bundled code 625ms
🖼  (2/3) [                    ] Rendering frames (6x) 0/900
The following error occurred when trying to render frame 0:
Protocol error (Runtime.callFunctionOn): Target closed.

Chromium engine was installed successfully and i followed the apt-get install packages for ubuntu.

I use nodejs verson 14.16.1. Anyone had the same issue?

Thanks for any help.

**Comment by JonnyBurger** [comment]
Hey Gary!

This is an error with Google Chrome where the tab crashes when you are trying to render. Given that you said you followed the installation instructions and the Audiogram template is a very computationally heavy template, you might have to decrease the concurrency for it to work on your system:

npx remotion render src/index.tsx Audiogram out.mp4 -- --concurrency=1

Let me know if this works! It might be good to update the template to set a lower concurrency.

By the way - I took this as an inspiration to create a new documentation page: https://github.com/remotion-dev/remotion/commit/609c9d8dc81b41a7cb52b4e192fc1a503bc03130

Soon it will be documented here: https://www.remotion.dev/docs/target-closed

**Comment by rebotnix** [comment]
@JonnyBurger Wow, it works and i got my first rendering in 4k done. Powerful that you made here. 

Demo:
https://www.youtube.com/watch?v=oGfhyrKcZO8

Can now play and test more thanks to your help and sure it can help other devs as well.

**Comment by JonnyBurger** [comment]
Nice 😁 Looks clean!

Yes, the concurrency means how many tabs are being opened in the headless browser at the same time. Normally every tab runs in a separate process, **but there is a special case in Linux: The browser doesn't open in headless mode without the `--single-process`** flag. So the render crashed because it did try to use a high concurrency, but ended up doing everything in one process.

This is a bigger problem actually, and I just realized why. I'll change the issue title to track the issue! One solution could be on Linux to open multiple browser instances, or to find the bug that requires to pass the `--single-process` flag (this is a problem beyond Remotion)

**Comment by rebotnix** [comment]
I also think also that this is a problem beyond Remotion and we have a way to run it on ubuntu. As soon as i have more infos, i come back with the result.

**Comment by JonnyBurger** [comment]
You're right thanks for self-closing the issue! I'm interested in improving this though by opening multiple Chrome instances instead to allow multi-core. So I'm reopening it!

**Comment by preetparm** [comment]
Not sure if posting on the right section. I just started with remotion. I am using Series. Sequence to render 10 minute composition . However remotion Taking forever to render it. It seems that it is processing  single frame per second  https://user-images.githubusercontent.com/9877580/229567799-bcf7ae41-7718-45aa-913d-819012f02af8.mp4

**Comment by JonnyBurger** [comment]
Newer versions of Chrome run headlessly on Linux without `--single-process`. 
Adding documentation for how to enable it: https://remotion.dev/docs/miscellaneous/linux-single-process
