### ISSUE TITLE
Minor: Sometimes <Series.Sequence> lanes 'fold in Preview, sometimes doesn't

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#811]
# Bug Report 🐛

Very minor bug: I just tried to use <Series.Sequence> with several sub-<Sequence> inside 3 times.  All 3 <Series.Sequence> use the same component that hold the 3 <Sequence>.  But only 1 (middle) of their lanes will 'fold' in the preview.

Here you can see the middle SeriesSequence unfolded, while the other 2 don't have to arrows to fold/unfold:
![image](https://user-images.githubusercontent.com/1308419/151906866-205ae2b8-2247-44bd-8343-700fc52e8680.png)

Here it is folded:
![remotion-series0](https://user-images.githubusercontent.com/1308419/151906928-3a5745d5-cb69-491b-bacf-1c3509c3cf52.JPG)

The Sequence with the MovieCamera icon is the one the folds:
```jsx
export function AboutRemotion() {
	return (<Series>
		<Series.Sequence durationInFrames={60}>
			<OneTitle
				titleText='What would you build if you could...'
				frontColor='#d9d0c6'
				backColor='#10131f'
			/>
		</Series.Sequence>
		<Series.Sequence durationInFrames={120}>
			<LogoTwoTitle
				logo={<Lift><ReactLogo /></Lift>}
				titleText='use ReactJS to build animations...'
				subtitleText='Animate with web technologies you know & love.'
				frontColor='#e9e4d7'
				backColor='#161b28'
			/>
		</Series.Sequence>
		<Series.Sequence durationInFrames={120}>
			<LogoTwoTitle
				logo={<Lift><MovieCameraIcon color='#acb0bd'/></Lift>}
				titleText='then capture them as a movie... '
				subtitleText='Export a MP4 file or use the &lt;Player&gt;.'
				frontColor='#d7d9df'
				backColor='#21304c'
			/>
		</Series.Sequence>
		<Series.Sequence durationInFrames={120}>
			<LogoTwoTitle
				logo={<Lift><RemotionLogo scaleOuter={3.3} /></Lift>}
				titleText='with Remotion'
				subtitleText='Create videos programmatically in React!'
				frontColor='#deefed'
				backColor='#2b4673'
			/>
		</Series.Sequence>
	</Series>)
}
```

I restarted the preview to ensure it was not a rendering quirk.
Low-priority, but could be handy to work properly in long & complex videos.

Cheers

**Comment by JonnyBurger** [comment]
Seems odd. I think the issue has to do with the fact that the cursor is at the time of the sequence that is collapsed.
But I don't know why that one can be collapsed and the other ones don't. Will investigate when I get some time.

**Comment by tomByrer** [comment]
More testing with my [timeline arrangement](https://github.com/tomByrer/remotion-demo-compose/blob/main/src/arrangements/AboutRemotion.jsx)

It is always & only the second Sequence that will fold.  I can copy/paste more sequences before & after it, & still what ever is the second, it alone will fold.

**Comment by JonnyBurger** [comment]
This was a result of the Rich timeline mode. It indeed had some problems, and we ended up removing it in v4.
