### ISSUE TITLE
macOS Monterey

### ISSUE THREAD

**Issue by michaelGregoire** [remotion-dev/remotion#821]
This is just to see if anyone else is having issues rendering on macOS Monterey? 

After upgrading to it, I just tried rendering a video and it fails miserably at about the 3000 frame mark, crashing my system. That's regardless if I set concurrency to just 1. The minute I start rendering, memory usage on my system climbs to 13G, that's even if I quit all other applications that are a little heavier on the memory usage. The memory pressure continues to rise until at about 3000 frames rendered, it climbs to over 15Gb and then my system with 16G RAM freezes up and crashes. 

I heard that Monterey 12.1 has some memory leak issues, so I upgraded to 12.2, but that didn't help at all.

I suspect it may be Chromium that's the problem. Not sure, though.

**Comment by JonnyBurger** [comment]
@michaelGregoire you can send it to hi@jonny.io or share it on our Discord or invite me to the repo.

I'm gone this weekend and got some things to do until then, so might become early next week until I can look. Just as a disclaimer!

**Comment by michaelGregoire** [comment]
Thanks @JonnyBurger. Emailed you.

**Comment by tomByrer** [comment]
Maybe when you upgraded, you lost some installed dependencies (or their references), like FFMPEG?
More similar bugs in search:
https://trac.ffmpeg.org/ticket/9505

**Comment by JonnyBurger** [comment]
I can reproduce the issue in the project sent to me.
Unlikely to be the OS - I'll get back to it this week!

**Comment by michaelGregoire** [comment]
Oh, ok, I'm glad you were able to! Thanks again for taking a look.

**Comment by michaelGregoire** [comment]
Thanks for finding the problem! I'm currently rendering with 2.6.7 and it seems to be stable again.

**Comment by JonnyBurger** [comment]
Nice! Also glad we managed to find the bug 😊
