### ISSUE TITLE
Remotion homepage shows `<img>` tag

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#824]
It should of course be an `<Img>` tag! or another example!

**Comment by JasterV** [comment]
@JonnyBurger 
I've created a new image with carbon

![carbon](https://user-images.githubusercontent.com/49537445/152535885-67a468e3-414b-4d67-8996-34e2eaa7fabc.png)

**Comment by JonnyBurger** [comment]
@JasterV Thank you so much! I wonder if it picked up that the syntax should be JSX?

BTW, we should also add an import: `import {Img} from "remotion"`

**Comment by JasterV** [comment]
Perfect in fact they have support for .jsx :smile:

Last thing I would have to check is the font, I think you used a different one when creating the current image

Now it looks like this:

![Remotion code example (1)](https://user-images.githubusercontent.com/49537445/152554658-2f350b83-d797-4856-9abb-a732a2316e89.png)

**Comment by JasterV** [comment]
@JonnyBurger I've open a PR but idk how to link it to this issue :(

**Comment by JonnyBurger** [comment]
All good, I can take care of the rest on Monday! 😊 thanks a lot

**Comment by JonnyBurger** [comment]
Fixed in #828.
