### ISSUE TITLE
i have following issue in yarn to create a video

### ISSUE THREAD

**Issue by reshma651999** [remotion-dev/remotion#837]
# Bug Report 🐛

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/cjs/puppeteer/node/install' is not defined by "exports" in /Users/kite/my-video/node_modules/puppeteer-core/package.json

**Comment by JonnyBurger** [comment]
Fixed in v2.6.8!

You can run `npx remotion upgrade` to fix your project. Sorry for the problem!
