### ISSUE TITLE
<Freeze> component does not function properly in conjunction with @remotion/player and <Video>

### ISSUE THREAD

**Issue by SkyezerFox** [remotion-dev/remotion#841]
# Bug Report 🐛

The `<Freeze>` component does not function as expected when used with the `@remotion/player` package, when used with the `<Video>` component. The player often continues to play underlying video elements when the player is paused on a frame the Freeze component is active.

This makes it exceedingly difficult to construct any form of live video player, or custom video editor (in my case) without your web app looking really bad!

> The <Freeze> component functions as expected when the videos are rendered, but not during preview or when using the player package externally.

Please excuse the use of the terrible football clips - building some telestration software to help annotate them!

## Example 1

When run using `yarn preview`, the player produces the following:

```tsx
const MyVideo = () => (
	<Freeze frame={30}>
		<Video src={video} />
	</Freeze>
);
```

https://user-images.githubusercontent.com/12949077/153636145-dfb93bca-40e4-4c85-b0dc-5d81bc053a36.mp4

Contrast the player output to what `yarn build` produces, which works as expected:

https://user-images.githubusercontent.com/12949077/153636572-d3158d29-6211-45f5-ab0f-cff381743b05.mp4

## Example 2

A more complicated example with `Series` that makes the effects more obvious.

```tsx
const MyVideo = () => (
	<Series>
		<Series.Sequence durationInFrames={25}>
			<Freeze frame={0}>
				<Video src={video} />
			</Freeze>
		</Series.Sequence>
		<Series.Sequence durationInFrames={50}>
			<Video src={video} />
		</Series.Sequence>
		<Series.Sequence durationInFrames={50}>
			<Freeze frame={126}>
				<Video src={video} />
			</Freeze>
		</Series.Sequence>
	</Series>
);
```

When run using `yarn preview`, the player produces the following:

https://user-images.githubusercontent.com/12949077/153635535-4e481c62-9d12-436c-b601-56a7a96401b4.mp4

Note that the video continues to play even when the player is paused on the second run of the video.

**Comment by JonnyBurger** [comment]
Hi @SkyezerFox! Thanks for filing, I'm gonna try to reproduce it this weekend.

Since you mention it's acting weird in the @remotion/player, can you tell me if you are using Next.JS and whether your next config file has strict mode enabled (this is the default)?
I could imagine it as a potential issue.

**Comment by SkyezerFox** [comment]
Good point, I have that on atm, I'll try turning it off and see what happens.

**Comment by SkyezerFox** [comment]
I can't see any difference if I'm honest? It still jumps around and will play when it should be paused, unfortunatley :(

**Comment by SkyezerFox** [comment]
I imagine this is probably to do with how freeze handles videos? Perhaps the buffering is causing some problems when the timeline tries to sync it. It is *quite* a big video (70mb or so), I'll try re-encoding it on Monday and test a smaller video.

**Comment by JonnyBurger** [comment]
I found the bug and managed to fix it! Thanks a lot for the good repro 😊

Making a new release which includes the fix.
