### ISSUE TITLE
ZlibError: ... Error with template cloning

### ISSUE THREAD

**Issue by kave-me** [remotion-dev/remotion#852]
When I try to create a template using `yarn create video` command, the template I choose is `Audiogram` the following error appears but when I choose another template like `react three Fiber` it's fine and I don't get any error like when I choose the other template.

# Bug Report 🐛
kave@me:~/Creativity$ yarn create video 
yarn create v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-video@2.6.9" with binaries:
      - create-video
✔ What would you like to name your video? … aa
✔ Choose a template: › Audiogram                 Text and waveform visualization for podcasts
ZlibError: zlib: unexpected end of file
Error with template cloning. Aborting
error Command failed.
Exit code: 1
Command: /home/kave/.yarn/bin/create-video
Arguments: 
Directory: /home/kave/Creativity
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

---
I did search about the issues and the first recommendation I got was cleaning my npm cach using `npm cache clean --force` command but that didn't solve the issue.

I suspected maybe I need to deal with my Zlib it self so as I had no clue I installed all the zlib packages on ubuntu package repository using `sudo apt install zlib*` but that didn't solve the issue as well.

I'm using `Ubuntu 20.04.4 LTS`

**Comment by JonnyBurger** [comment]
Hi @kave-me, thanks for reporting the issue! It looks like an upstream issue (https://github.com/Rich-Harris/degit/issues/313).

I put a workaround in #854 now and will follow the original issue and upgrade in case a fix will surface.
