### ISSUE TITLE
UI: Dropdown menus not updating their position properly

### ISSUE THREAD

**Issue by Baegus** [remotion-dev/remotion#861]
# Bug Report 🐛

When I open the Zoom/Playback speed dropdown menu, then resize the timeline window and open one of the dropdowns again, it still has its original position and doesn't adjust for the new configuration.

**Comment by Baegus** [comment]
This could be fixed by adding `window.dispatchEvent(new Event('resize'))` in the [`cleanup()` function for SplitterHandle](https://github.com/remotion-dev/remotion/blob/5b5893862d1070ea65114e894c9a2b80bde9a789/packages/cli/src/editor/components/Splitter/SplitterHandle.tsx#L95).

**Comment by JonnyBurger** [comment]
Thanks for filing! I was able to reproduce the bug and hope to fix it in one of my next sessions.
