### ISSUE TITLE
Use of the cli apis from JS

### ISSUE THREAD

**Issue by JacopoPatroclo** [remotion-dev/remotion#863]
# Feature Request 🛍️

I'm working on a plugin for [Nx](https://nx.dev/)  that will enable the use (without managing a lot of custom configs) of this amazing product inside an Nx monorepo.
The request that I'm making is related to the use of the functionalities exposed by the cli throught javascript.
Like Vite for [example](https://vitejs.dev/guide/api-javascript.html).

## Use Case

The issue is that I want to provide a custom webpack configuration inside the context of an executor. This seems to be impossible to do with the [configuration file](https://www.remotion.dev/docs/config). As a reference I leave the Nx implementation of the [webpack executor](https://github.com/nrwl/nx/blob/master/packages/web/src/executors/webpack/webpack.impl.ts#L195). I want to create something like this but for Remotion.

## Possible Solution

Seems like that the render logic is in [here](https://github.com/remotion-dev/remotion/blob/main/packages/cli/src/render.tsx) and it could be abstracted into a  function that return an observable or an event emitter that could be used by the actual cli render function to log and recive all the options.
This could be also done for the preview functionality.

I could implement this myself opening a PR but I will need some guidance, I'm not that familiar with the internals of this project.

BTW This project ROCK!!!

**Comment by JonnyBurger** [comment]
Hey Jacopo!

Thanks a lot for filing the issue! We do expose most of our functionality as Node.JS APIs. See: [`bundle()`](https://www.remotion.dev/docs/bundle), [`getCompositions()`](https://www.remotion.dev/docs/get-compositions) [`renderFrames()`](https://www.remotion.dev/docs/render-frames) etc.

You can override the webpack config using the `webpackOverride` option: https://www.remotion.dev/docs/bundle#webpackoverride

These APIs are mostly for rendering, we currently don't have any for previewing the video. However I also don't see many usecases for it. Is this what you have been looking for?

**Comment by JacopoPatroclo** [comment]
Hey Jonny,
thanks for the quick response.

Seems like the functionality exposed by bundle is the one I was lookin for. Looks like I will need, in order to have a full video, to integrate that with the renderFrames call. Seems like a straightforward thing to do. Thanks.

The issue with the missing "preview" apis is that if I want to "develop the video" (so cool that we can use this expression; thanks to your work 💯 ) reusing the same experience that `npx remotion preview` provide it will be impossible to do in an nx monorepo (mainly due tho package resolution issues, hence the need of changing the webpack config).

What are the difficulties to implement something like the bundle functionality but for the preview? Where in the monorepo this functionality, in your opinion, should be placed? I could develop this thing. It could be realy helpful for other tools that want to integrate with this one in a programmatic way (without the need of spawning shell processes calling npx).
If you are fine with that oviously.

**Comment by JonnyBurger** [comment]
Hi Jacopo,

Wouldn't it be better we figure out the package resolution issues rather than develop a new API?
From what I understand, you are having trouble reading the config file when you start the the Remotion Preview.

You can put the config file anywhere on your disk and specify a webpack override.
Then you can run `npx remotion preview [absolute-entry-point-file] --config=[config-file-location]` anywhere where the remotion packages are installed `remotion, @remotion/cli and @remotion/bundler`.

It is all very explicit and don't see why it would not work this way. Maybe by using the `--config` option you will have some luck?

**Comment by JacopoPatroclo** [comment]
That's exacly my issue.

Is impossible in the same context of calling the preview npx script and providing a dynamic webpack config (with options depending on information aviable only during that execution). The solution (on the nx-plugin side) could be to put somewhare in a temporary directory the "just in time" create config file and execute the preview script targeting that config file but is not a very good solution. Mainly because if I want to expose the config file (for example in the root of the project) it will became quickly a mess.

I get that maintaning a "new" api could be a burden but in my opinion there shoul be a specularity between the functionalities exposes using a Node api. Why we have a [bundle()](https://www.remotion.dev/docs/bundle), [getCompositions()](https://www.remotion.dev/docs/get-compositions) [renderFrames()](https://www.remotion.dev/docs/render-frames) apis but not a preview() one. There is a technical reason behind it?

I could develop an alpha version of the plugin with the solution discussed above to create a better context around what I'm trying to achive.

**Comment by JonnyBurger** [comment]
I have realized that this API is (inofficially) accessible:

```tsx
import {BundlerInternals} from "@remotion/bundler";

BundlerInternals.startServer(
	require.resolve('@remotion/cli/dist/previewEntry.js'),
	path.join(process.cwd(), 'src/index.tsx'),
	{
		port: 3000,
		inputProps: {},
		envVariables: {}
	}
)
```

This could become an official documented API indeed. Very few users will have a use for it that it will not be worth the effort for us to implement, however I'd be happy to accept a PR if you want to turn this into a public API, given that it has the same quality level and documentation as the other APIs.
