### ISSUE TITLE
Puppeteer fails to launch, can't build video Windows

### ISSUE THREAD

**Issue by tharpooljha** [remotion-dev/remotion#868]
Node.js v17.6.0
PS C:\code\demo-1-alpha> npm run build

> remotion-template@1.0.0 build
> remotion render src/index.tsx Demo-1-Alpha out/Demo-1-Alpha.mp4
```
📦 (1/3) [==                  ] Bundling code 10%C:\code\demo-1-alpha\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:229
            reject(new Error([
                   ^

Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (C:\code\demo-1-alpha\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:229:20)
    at ChildProcess.<anonymous> (C:\code\demo-1-alpha\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:220:79)
    at ChildProcess.emit (node:events:539:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Node.js v17.6.0
Deps:
```
		"@remotion/bundler": "^2.6.9",
		"@remotion/cli": "^2.6.9",
		"@remotion/eslint-config": "^2.6.9",
		"@remotion/renderer": "^2.6.9",
		"eslint": "^7.15.0",
		"prettier": "^2.2.1",
		"react": "^17.0.2",
		"react-dom": "^17.0.2",
		"remotion": "^2.6.9",
		"typescript": "4.4.2"
```
Replicate
- Using node 17.6.0
- npm init video
- default blank TS template
- Get error above

remotion.config.ts
```
import {Config} from 'remotion';

Config.Rendering.setImageFormat('jpeg');
Config.Output.setOverwriteOutput(true);
Config.Puppeteer.setChromiumHeadlessMode(true);
Config.Puppeteer.setChromiumDisableWebSecurity(true);
Config.Puppeteer.setChromiumIgnoreCertificateErrors(true);

```

**Comment by JonnyBurger** [comment]
Hi @tharpooljha! Sorry you are having this issue. I need a bit more information to help.

- Do you have a regular Chrome installation or a custom one (Beta, Chromium, Canary, Self-built?)
- If you remove the following lines:

```diff
- Config.Puppeteer.setChromiumHeadlessMode(true);
- Config.Puppeteer.setChromiumDisableWebSecurity(true);
- Config.Puppeteer.setChromiumIgnoreCertificateErrors(true);
```

does it allow you to run?

**Comment by tharpooljha** [comment]
Removed the lines, chrome launches, but puppeteer acts like something has failed.
Windows 10 64bit
Might file a bug at puppteer-core?

**Comment by kave-me** [comment]
Hi @tharpooljha 👋
Do you still have the issue?

**Comment by JonnyBurger** [comment]
Apologies for looking into it late (I only occasionally use Windows to test).
For me everything is fine with those flags 🤔 Node 17.7.2, Remotion 2.6.11, Windows 10 Pro Version 21H2.

Sorry about this, but I cannot do anything about this unless I get more information about the environment 😞 

![image](https://user-images.githubusercontent.com/1629785/159427121-92dc3bf9-08ee-4e24-8ed0-b442722939dd.png)

**Comment by JonnyBurger** [comment]
I'm closing it due to no response and no guidance on how to debug. Let us know if you still suffer from the problem.

**Comment by greffgreff** [comment]
One of 2 issues in the world that has this issue like me. Gotta love software!

**Comment by JonnyBurger** [comment]
@greffgreff What is the output when adding --log=verbose?

Try the newest version and 

npx remotion browser ensure

to download a browser that should be guaranteed compatible

**Comment by greffgreff** [comment]
Hello! Thanks for the (very) fast reply. I just created an issue regarding my issue. I'll give that a try.
