### ISSUE TITLE
Docker Alpine server does not start render without gl = angle

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#871]
Report from Anon1m on GitHub:

- Render worked well until 2.5.5
- With 2.6.9 it did not start consistently
- Adding `--gl=angle`, ~`--font-render-hinting=none`, `--disable-gpu` and `disable-software-rasterizer`~ (probably not relevant) did help resolve the issue.
- Using node:alpine base image 

https://discord.com/channels/809501355504959528/817306238811111454/951038165060304936

**Comment by Ivraj** [comment]
Hi @JonnyBurger. We also run Remotion with an express server in an alpine docker container and started running into a similar issue as Anon1m. Suddenly our video rendering started hanging on the `renderFrames()` function, before `onStart` was called. It was difficult to predict when it would happen, but anecdotally, it was occurring roughly 9 out of 10 renders. 

I can confirm that adding `chromiumOptions: { gl: 'angle' }` has seemed to resolve the issue (at least for the last dozen or so renders 🤞 ). 

After digging through our logs, I found that prior to adding `gl: 'angle'` the following error message would appear periodically:

```
ProtocolError: Protocol error (Target.setAutoAttach): Target closed.
    at /node_modules/puppeteer-core/src/common/Connection.ts:304:16
    at new Promise (<anonymous>)
    at CDPSession.send (/node_modules/puppeteer-core/src/common/Connection.ts:300:12)
    at Page._initialize (/node_modules/puppeteer-core/src/common/Page.ts:586:20)
    at Function.create (/node_modules/puppeteer-core/src/common/Page.ts:434:16)
    at /node_modules/puppeteer-core/src/common/Target.ts:124:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Browser._createPageInContext (/node_modules/puppeteer-core/src/common/Browser.ts:495:18)
    at /node_modules/@remotion/renderer/src/render.ts:110:16
    at async Promise.all (index 0) {
```

I don't have as strong a background with Puppeteer, but it seems like an issue with Puppeteer not being able to create a new page on the browser instance? Not sure if anyone had mentioned ^that in the Discord, but wanted to leave it here if it could be of any use for debugging.

Platform: GCP Kubernetes Engine
Docker Image: `node:gallium-alpine`
Chromium Version in Docker Container: `chromium-93.0.4577.82-r3`
Node Version: `16.4.2`
@remotion/bundler Version: `2.6.11`
@remotion/cli Version: `2.6.11`
@remotion/renderer Version: `2.6.11`
remotion Version: `2.6.11`


Happy to provide more information or help run tests. Thanks!

**Comment by JonnyBurger** [comment]
Hi @Ivraj, thanks a lot for adding more information!
We should default to --angle in that case. It's weird that Chrome doesn't recognize it automatically.

I'll not prioritize this issue at the moment since it has a relatively easy workaround, but will investigate it once I have more time!

**Comment by JonnyBurger** [comment]
We have added an example Dockerfile now that works: https://www.remotion.dev/docs/docker
