### ISSUE TITLE
<Sequence> after previous (instead of timing manually)

### ISSUE THREAD

**Issue by abjeroen** [remotion-dev/remotion#873]
# Feature Request 🛍️

I spend a lot of time adjusting each sequence from-value when I add something at the beginning of the video. Is it possible to have the start of a sequence kick in when the previous sequence is done, so I don't have to tweak the starting position manually? 9 out of 10 times my sequences are "sequential" :)..

**Comment by JonnyBurger** [comment]
Hi @abjeroen!

I think you'll enjoy the `<Series>` component, which was made exactly for that :)

https://www.remotion.dev/docs/series
