### ISSUE TITLE
Add JSDocs documentation to common APIs

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#880]
Just like we do on the Lambda APIs, the core APIs would be nicer, if we put JSDoc comments with brief descriptions, and link to the full documentation.

**Comment by JonnyBurger** [comment]
Hi @Slashgear! Absolutely! Thanks a lot for stepping up!

Here is an example of how we do it with the new Lambda APIs that are coming out soon:

https://github.com/remotion-dev/remotion/blob/e218958c9db0e127407caa240c0cc29b3282b4f6/packages/lambda/src/api/deploy-site.ts#L34-L43

This is all that's needed for helpful tooltips to show up when you hover over the function name:

![Screenshot 2022-03-15 at 10 15 00](https://user-images.githubusercontent.com/1629785/158345193-9023de7d-ab72-4c52-950c-5166e42f488c.png)

What would be useful is to annotate the most commonly used functions like useCurrentFrame, useVideoConfig, interpolate and spring!

**Comment by Slashgear** [comment]
Ok ! I am on it 😄

**Comment by JonnyBurger** [comment]
@Slashgear 🙌
