### ISSUE TITLE
Clarify meaning of `startFrom` and `endAt` parameters for Audio and Video

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#882]
> I'm having some trouble understanding the reference frame for startFrom, and endAt. For the Audio component, are those parameters relative to from or are they global?

We don't do a good job of explaining it in the docs and don't give any examples.

**Comment by CruuzAzul** [comment]
I'm on it 😉

**Comment by JonnyBurger** [comment]
@CruuzAzul 🙌

**Comment by JonnyBurger** [comment]
Fixed in e7f919685969c63549639700383e221bd0c075b0 + 767dfc92486af5fd152765a8ad18f44ce84abd65 + da390f266e2794bc7fae3bda1e4a53daa0dc94df!
