### ISSUE TITLE
Streamline FFMPEG Windows installation

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#892]
The instructions for when you don't have FFMPEG on Windows could be improved.
Also, the instructions tell you to go to this site:

![image](https://user-images.githubusercontent.com/1629785/159426151-a2fcd82e-e50d-44d6-9afb-b0f8782532cd.png)

but it's very hard to find the right download link. The other steps are also not easy, but not sure if it can be improved.

**Comment by AbdulBsit** [comment]
@JonnyBurger  May be this will help, let me know I can try submitting a PR.

Have a look at this source, here we have binaries for ffmpeg [https://github.com/eugeneware/ffmpeg-static/](url)
And we can do like this ...
```
 const version = "b5.0.1";
 const filename = `ffmpeg-${version}${process.platform == "win32" ? ".exe" : ""}`;
 const fileurl = `https://github.com/eugeneware/ffmpeg-static/releases/download/${version}/${process.platform}-x64`;
```

**Comment by JonnyBurger** [comment]
That sounds reasonable indeed!

I'm happy for PR it and if it does not come in a while, I might take a stab at it myself.
Important note: We also need `ffprobe` binaries in addition to `ffmpeg` (this could work: https://github.com/chrislearn/ffprobe-static)
