### ISSUE TITLE
staticFile wont load MP3 file

### ISSUE THREAD

**Issue by ValentinHLica** [remotion-dev/remotion#908]
I have audio file in public path (public/audio/0-0-0.mp3), i am trying to import it into my project using staticFile(public/audio/0-0-0.mp3) and the returned value use as a prop for Audio component, in dev works fine but when i try to render it, it crashes.

`$ npm run build

 aaaa@1.0.0 build
 remotion render src/index.tsx Empty out/video.mp4

📦 (1/3) [====================] Bundled code 742ms
🖼  (2/3) [====================] Rendered frames (4x)  3144ms
🎞  (3/3) [                    ] Encoding video 0/60 Error: Command failed with exit code 1: ffprobe -v error -show_entries stream=channels -of default=nw=1 C:\Users\licav\AppData\Local\Temp\react-motion-graphicsaAQQJt\publicaudio0-0-0.mp3
C:\Users\licav\AppData\Local\Temp\react-motion-graphicsaAQQJt\publicaudio0-0-0.mp3: No such file or directory
    at makeError (C:\Users\licav\Desktop\dev\aaaa\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\licav\Desktop\dev\aaaa\node_modules\execa\index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getAudioChannels (C:\Users\licav\Desktop\dev\aaaa\node_modules\@remotion\renderer\dist\assets\get-audio-channels.js:17:18) `
    
Code: [https://github.com/ValentinHLica/aaa](https://github.com/ValentinHLica/aaa)

i used the empty template provided by remotion, i have not configured anything

**Comment by JonnyBurger** [comment]
Hi Valentin! You should not pass the public/ part:

staticFile('audio/0-0-0.mp3')

will work!

I’ll keep the issue open because we can introduce a helpful warning in this case.

**Comment by ValentinHLica** [comment]
sorry typo on my part i have set staticFile('audio/0-0-0.mp3') 
<img width="946" alt="aaaa" src="https://user-images.githubusercontent.com/74852397/161501975-56a3e8ec-3769-4194-b809-8e33c5d0365e.PNG">

**Comment by JonnyBurger** [comment]
I see, bug is confirmed! I made a candidate PR #911 that fixes it. I have yet to check for security regressions, but hope to merge it soon and release a new version that fixes the bug!

**Comment by JonnyBurger** [comment]
@Devinpennings I tried to implement it a bit more securely - if you are on Windows right now, can you see if that works as well?

**Comment by JonnyBurger** [comment]
@Devinpennings Thanks a lot for testing! Will release momentarily. Gave you a contribution credit as well in the latest commit!
