### ISSUE TITLE
ffprobe Failed to read frame size: Could not seek to 1479 - tts template build fail, file copying fail.

### ISSUE THREAD

**Issue by karlmacklin** [remotion-dev/remotion#917]
# Bug Report 🐛

I tried the text to speech template. I have AWS and Azure set up properly, as I can view the example video when running `npm run start`.

However, when I try `npm run build` I get the following error:

```> my-video@1.0.0 build
> remotion render src/index.tsx HelloWorld out/video.mp4

📦 (1/3) [====================] Bundled code 932ms
🖼  (2/3) [====================] Rendered frames (6x)  17155ms
🎞  (3/3) [                    ] Encoding video 0/500
Downloading asset...  https://redacted.s3.amazonaws.com/cea5840f2fc63ec41a7ada897545f609.mp3
Error: Command failed with exit code 1: ffprobe -v error -show_entries stream=channels -of default=nw=1 /tmp/react-motion-graphics1USDTR/9126596876885742.mp3
[mp3 @ 0x55efb9ccae00] Failed to read frame size: Could not seek to 1479.
/tmp/react-motion-graphics1USDTR/9126596876885742.mp3: Invalid argument
    at makeError (/home/username/code/autovideo/my-video/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/username/code/autovideo/my-video/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getAudioChannels (/home/username/code/autovideo/my-video/node_modules/@remotion/renderer/dist/assets/get-audio-channels.js:17:18)
```

The asset being downloaded (correct url here is redacted for privacy reasons) contains the correct mp3 file. It's 31kb of correct audio, the same heard when previewing the video.

However, the other file mentioned after that: `/tmp/react-motion-graphics1USDTR/9126596876885742.mp3` is really weird. It's only 456 bytes.
Not sure what the point of it is.
The folder it's in listing:
![image](https://user-images.githubusercontent.com/353806/162317451-6cf12d98-7a4d-4323-844f-66b29c3634d7.png)

- If I copy the whole ffprobe command and run by myself, I get the exact error as shown.
- If I modify that command and point it to a separate downloaded copy of the mp3 file that is correct, then it outputs: `channels=1`.

My guess something goes wrong in a copying process somewhere?

I've tried `npm run server` as well without luck, the template has some issues with `process.env` variables. I have them all set correctly but when running that command they don't seem to exist weirdly enough. I'll wait with raising an issue for that though until we've solved this first one.

Running node17 in Ubuntu 20.04 WSL2.

**Comment by JonnyBurger** [comment]
Thanks for filing the issue and sorry for the trouble 😌
Would you be willing to share the troubled MP3 file link privately? (hi@jonny.io)

I would take a look at it and see what I can do.

Some suspicions: Could it be that the `Access Denied` page from S3 was downloaded by any chance and put into an MP3 file? That would approximately match the 456 byte length of the file.

**Comment by karlmacklin** [comment]
Ok so this is awkward.

Without even rebooting my system or closing anything, I tried the same command today and it worked.
Can't think of a single thing that has changed other than the passing of time.

It builds the video fine now. I can also run `npm run server` and have it build video via http get request as per instructions. This did not work either, it could never find the .env variables.

I thought about your assumption, and I think you are right.

I'll email you a couple of problem mp3 urls and a working one, though I bet there's no real difference between them at this point.

You can close this issue unless you have any question that could help.

**Comment by JonnyBurger** [comment]
@karlmacklin Ok, whatever the reason, glad it's resolved 🥳

I can download all assets from your email fine. It's probably not worth investigating now if the problem is gone, but should one appear again, feel free to open a new issue.
