### ISSUE TITLE
TypeError: results.flat is not a function

### ISSUE THREAD

**Issue by khalidahmed1101** [remotion-dev/remotion#919]
I am getting error while building or converting to out/video.mp4
Can anyone help me out what I am doing wrong? thanks

![image](https://user-images.githubusercontent.com/78547959/162511157-8026131e-a041-4227-afd4-7d9355971815.png)

**Comment by arthurdenner** [comment]
`Array.flat` was only added in Node v11.0.0 - see [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility).
However, you should update your Node to >=12.10.0 as described in the first two lines on the screenshot.

**Comment by khalidahmed1101** [comment]
Thank you so much @arthurdenner,
You saved me a a lot of time :)
