### ISSUE TITLE
Allow to start a video in the <Player /> from an offset

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#922]
# Feature Request 🛍️

From Shaun Trennery on Discord:
> Is it possible to start from a set time offset? i.e. skip ahead 15 seconds.

**Comment by tomByrer** [comment]
Simple solution; provide in the [`<Player>` demo](https://github.com/remotion-dev/remotion/blob/main/packages/player-example/src/App.tsx) an example on how to do it:

```jsx
const {fps} = useVideoConfig() // or however you get FPS
function seekSecondsPlay(n){
  seekTo(fps * n)
  play()
}
...
<button type="button" onClick={()=> seekSecondsPlay(3)}>
  play 3sec mark
</button>
```

(I haven't tested in your environment, but works in [my weird setup](https://tombyrer.github.io/remotion-aspectratio-demo/).)
