### ISSUE TITLE
how to work with `d3.js`?

### ISSUE THREAD

**Issue by winner106** [remotion-dev/remotion#924]
[D3](https://d3js.org/) is a JavaScript library used to create bespoke, interactive charts and maps on the web.

I used `d3.js` set all the transition, some code as follows, but I don't know how to connect `frame` with my react componet, could you please give some advice? thank you very much!

```js

	useEffect(() => {
		const svg = d3
			.select(svgRef.current)
			.attr('viewBox', [0, 0, width, height]);

		const updateBars = bars(svg);
		const updateAxis = axis(svg);
		const updateLabels = labels(svg);
		const updateTicker = ticker(svg);

		console.log(frame / duration);

		async function render() {
			for (const keyframe of keyframes) {
				const transition = svg
					.transition()
					.duration(duration)
					.ease(d3.easeLinear);

				x.domain([0, keyframe[1][0].value]);
				updateAxis(keyframe, transition);
				updateBars(keyframe, transition);
				updateLabels(keyframe, transition);
				updateTicker(keyframe, transition);

				await transition.end();
			}
		}

		render();
	}, []);

	return (
		<>
			<svg ref={svgRef}></svg>
		</>
	);
};

```

**Comment by JonnyBurger** [comment]
Thanks for the question!

We made an example for D3: https://github.com/remotion-dev/d3-example

It is advised to keep the scale static so it does not animate, but animate the bar width based on Remotion's `useCurrentFrame()` value.

**Comment by winner106** [comment]
> Thanks for the question!
> 
> We made an example for D3: https://github.com/remotion-dev/d3-example
> 
> It is advised to keep the scale static so it does not animate, but animate the bar width based on Remotion's `useCurrentFrame()` value.

Thank you very much for your guidance. I tried for a day today, but still failed to achieve it. I made a more complex animation using many years of data, I look forward to your more guidance. Thank you very much!

the repo address : [https://github.com/winner106/remotion-d3.git](https://github.com/winner106/remotion-d3.git)

**Comment by winner106** [comment]
> Thanks for the question!
> 
> 
> 
> We made an example for D3: https://github.com/remotion-dev/d3-example
> 
> 
> 
> It is advised to keep the scale static so it does not animate, but animate the bar width based on Remotion's `useCurrentFrame()` value.

 Thanks, but if I want scale animate，could you please give me some probable solutions direction？

**Comment by JonnyBurger** [comment]
Let's say you want to animate from scale 0 to 1:

```tsx
import {useCurrentFrame, interpolate} from "remotion";

const MyComp = () => {
	const frame = useCurrentFrame();
	const scale = interpolate(frame, [0, 30], [0, 1])
}
```

Afterwards, you need to find the property in D3 that defines the scale and replace it with the property you just defined.

Unfortunately I don't have the time to explain everything step by step, I recommend you learn these techniques from the beginning of the docs or ask the Discord community for help.

**Comment by winner106** [comment]
> Let's say you want to animate from scale 0 to 1:
> 
> 
> 
> ```tsx
> 
> import {useCurrentFrame, interpolate} from "remotion";
> 
> 
> 
> const MyComp = () => {
> 
> 	const frame = useCurrentFrame();
> 
> 	const scale = interpolate(frame, [0, 30], [0, 1])
> 
> }
> 
> ```
> 
> 
> 
> Afterwards, you need to find the property in D3 that defines the scale and replace it with the property you just defined.
> 
> 
> 
> Unfortunately I don't have the time to explain everything step by step, I recommend you learn these techniques from the beginning of the docs or ask the Discord community for help.

Thank you very much for your guidance

**Comment by winner106** [comment]
Thanks for your guidance last time. Now I can make the D3 animation in Remotion, but the effect is not smooth, and there will be some lag. I have been trying these days, but I still can't find a solution. I hope you can have a look at my animation effect. I really hope to combine Remotionand D3 perfectly.

[https://github.com/winner106/remotiond3](https://github.com/winner106/remotiond3)

![image](https://user-images.githubusercontent.com/50519642/166853184-96c12924-a57a-4610-ad58-6434640e6509.png)

**Comment by winner106** [comment]
> Let's say you want to animate from scale 0 to 1:
> 
> ```tsx
> import {useCurrentFrame, interpolate} from "remotion";
> 
> const MyComp = () => {
> 	const frame = useCurrentFrame();
> 	const scale = interpolate(frame, [0, 30], [0, 1])
> }
> ```
> 
> Afterwards, you need to find the property in D3 that defines the scale and replace it with the property you just defined.
> 
> Unfortunately I don't have the time to explain everything step by step, I recommend you learn these techniques from the beginning of the docs or ask the Discord community for help.

I have link `frame` to the `rect` element's y and width attribute, but the effect is not smooth, I tried `spring` function , but failed too😢

part of code as bellow:
```ts
.attr('y', (d) =>
interpolate(
	frame,
	[
		frameDataIdx * videoFramesPerDataKeyframe,
		frameDataIdx * videoFramesPerDataKeyframe +
			videoFramesPerDataKeyframe,
	],
	[y((allData.prev.get(d) || d).rank), y(d.rank)],
	{
		extrapolateRight: 'clamp',
	}
)
)
.attr('width', (d) =>
interpolate(
	frame,
	[
		frameDataIdx * videoFramesPerDataKeyframe,
		frameDataIdx * videoFramesPerDataKeyframe +
			videoFramesPerDataKeyframe,
	],
	[x((allData.prev.get(d) || d).value) - x(0), x(d.value) - x(0)],
	{
		extrapolateRight: 'clamp',
	}
)
);
```

**Comment by JonnyBurger** [comment]
Hi @winner106,

unfortunately due to high demand I cannot review every request for potential bugs.
It also does not look like a Remotion bug but like a miscalculation due to opaque data structure.

I'd like to recommend once again to ask on Discord, or a general-purpose help site like StackOverflow.

Some general advice, your animation looks simple enough that it might not need D3.js at all.
You could render some <div>'s instead and calculate width over time. With simplified math, you can maybe more easily debug why the values don't animate over time nicely.

**Comment by winner106** [comment]
OK，Thanks.
