### ISSUE TITLE
Video volume increases abruptly at the end + audio mixing cracks

### ISSUE THREAD

**Issue by yuvraj108c** [remotion-dev/remotion#930]
I have rendered the following video for a project using remotion. It consists of a background music, alongside with some voice overs played at different time frames.

https://user-images.githubusercontent.com/42040906/163758279-b2966d76-4e3a-4b1a-9205-847a821d3c50.mp4

- If you listen carefully, there is an audio crack when the second voiceover (audio_2) starts playing. The same problem occurs if I add audio_3, audio_4 etc
- At the end of the video, the volume increases unexpectedly.

The video works fine during the preview mode. I believe the video render process is causing this weird bug. I have crosschecked the audio files and they are all of good quality, with no cracks/noises. This is my code below. 

```js
import bgMusic from "./assets/bgMusic.mp3";
import audio_1 from "./assets/1.mp3";
import audio_2 from "./assets/2.mp3";
import { Audio, Sequence } from "remotion";

export const Bug: React.FC<{}> = () => {
  return (
    <div className="audios">
      <Audio src={bgMusic} volume={0.3} />;
      <Sequence from={15}>
        <Audio src={audio_1} />
      </Sequence>
      <Sequence from={90}>
        <Audio src={audio_2} />
      </Sequence>
    </div>
  );
};

```

**Comment by JonnyBurger** [comment]
Hi @yuvraj108c! Thanks for the report.
I can understand the issue arising due to how FFMPEG works.

To investigate, I need the 3 MP3 files, can you share them as well? If you want, privately under jonny@remotion.dev - I'll take a look at what we can do to improve the mixing in your scenario!

**Comment by yuvraj108c** [comment]
Thanks for replying. I have zipped the 3 audios here: [audios.zip](https://github.com/remotion-dev/remotion/files/8505038/audios.zip)

**Comment by yuvraj108c** [comment]
No worries Jonny, I will use FFMPEG for now until the issue is resolved.

Looking forward for the v3 launch.
