### ISSUE TITLE
Access video file

### ISSUE THREAD

**Issue by khalidahmed1101** [remotion-dev/remotion#941]
Hi, 
I need to get video file of the rendered video on the reactjs tsx component after rendering to upload it to server through API,

Can anyone help with this issue please, thanks

**Comment by JonnyBurger** [comment]
You cannot render inside the browser due to a limitation.

See: #655 
Use server-side rendering instead: https://remotion.dev/docs/renderer

**Comment by khalidahmed1101** [comment]
I want to export basically videos of graphs with different data, there is may be 20 to 30 videos with the graph data,
What approach would be good?
@JonnyBurger

**Comment by JonnyBurger** [comment]
If you are fine with rendering locally, just use the `npx remotion render` command a bunch of times and parametrize the video render differently each time: https://www.remotion.dev/docs/parametrized-rendering

**Comment by khalidahmed1101** [comment]
Can I use this command with loop on a script? with params of each array item?

**Comment by JonnyBurger** [comment]
@khalidahmed1101 

Yes, e.g. bash loop, something like this

```sh
props=('{"a": "b"}' '{"c": "d"}')
for prop in "${props[@]}"
do :
  npx remotion render src/index.tsx MyComp --props=$prop "$prop.mp4"
done
```

Or write a node.js script that calls SSR APIs https://remotion.dev/docs/ssr

**Comment by khalidahmed1101** [comment]
Thank you so much @JonnyBurger ,
Will try these
