### ISSUE TITLE
Module '"remotion"' has no exported member 'Audio'

### ISSUE THREAD

**Issue by uditkumar01** [remotion-dev/remotion#942]
# Bug Report 🐛

![Screenshot (2)](https://user-images.githubusercontent.com/55291327/165051956-cbfc6aed-4e36-4193-935d-084a39851602.png)

- I am using `Remotion v3`

**Comment by uditkumar01** [comment]
It is exported, my ts server wasn't working properly.

**Comment by JonnyBurger** [comment]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/1629785/165054077-398f1ac3-65e5-42b3-809b-75600afbf7ee.png">

I could not reproduce this, how does it look in node_modules/remotion? Is it there?

**Comment by JonnyBurger** [comment]
I see. 👍
