### ISSUE TITLE
"DropDots" Component exported twice

### ISSUE THREAD

**Issue by uditkumar01** [remotion-dev/remotion#944]
https://github.com/remotion-dev/remotion/blob/2131354ee58e122097114002b77d6aa7e67c60e4/packages/example/src/DropDots/DropDots.tsx#L19

https://github.com/remotion-dev/remotion/blob/2131354ee58e122097114002b77d6aa7e67c60e4/packages/example/src/DropDots/DropDots.tsx#L159

**Comment by JonnyBurger** [comment]
Thanks!
