### ISSUE TITLE
<Player /> audio keeps playing after reaching the video end

### ISSUE THREAD

**Issue by danistefanovic** [remotion-dev/remotion#957]
# Bug Report 🐛

When an audio track is longer than the total video duration, the audio is still playing after <Player /> has reached `durationInFrames`. Reproduction repository: https://github.com/danistefanovic/remotion-player-audio-issue

**Comment by danistefanovic** [comment]
Disabling the strict mode in React seems to fix the issue.

**Comment by JonnyBurger** [comment]
Indeed, we have already filed it. Sorry and we'll put our minds towards solving this soon!
