### ISSUE TITLE
Add link to source code for each function in docs

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#972]
E.g.: https://www.remotion.dev/docs/audio-buffer-to-data-url/

Would be nice if in the `audioBufferToDataUrl()`, you could click and see the source code of said function!

**Comment by tomByrer** [comment]
Fast solution: create a search URL:
https://github.com/remotion-dev/remotion/search?q=audioBufferToDataUrl

**Comment by JonnyBurger** [comment]
Good idea, though it yields not just the source but also all the usages and the source is not always at the top. I applied some naming conventions no and don't plan on doing random renames going forward.
