### ISSUE TITLE
Player - doesn’t work in storybook

### ISSUE THREAD

**Issue by helkaroui** [remotion-dev/remotion#973]
# Bug Report 🐛
I integrated storybook in my remotion project, so that I get a preview of my assets and compositions. 
Unfortunately the Player doesn't seem to work inside storybook stories.

I've used the HelloWorld component to demonstrate the bug, here is the code :
```js

const HelloWorldComposition: React.FC = () => {
	return (
		<Composition
			id="HelloWorld"
			component={HelloWorld}
			durationInFrames={1000}
			fps={30}
			width={1024}
			height={800}
			defaultProps={{
				titleText: 'Welcome to Remotion',
				titleColor: 'red',
			}}
		/>
	)
}

const MyPlayer: React.FC = () => {
	return (
		<Player
			component={RemotionVideo}
			durationInFrames={1000}
			compositionWidth={1024}
			compositionHeight={800}
			fps={30}
			controls
			loop
			autoPlay
		/>
	);
};


export default {
	title: 'Compositions/Sequences/HelloWorld',
	component: MyPlayer,
	argTypes: {
		backgroundColor: { control: 'color' },
	},
} as ComponentMeta<typeof MyPlayer>;


const Template: ComponentStory<typeof MyPlayer> = (args) => <MyPlayer {...args} />;
export const Primary = Template.bind({});
```

In storybook, the player is showing and functional. But  the rendering area is blank.
![image](https://user-images.githubusercontent.com/22795356/167090549-c9981e1c-40be-4d43-a37b-db4d52144d2a.png)

Anyone was able to make it work with Storybook ?

**Comment by JonnyBurger** [comment]
Thanks for the report! Will investigate it.
What would be helpful to know: 
Do you see any errors in the console, and is the markup inside the player, when you inspect it, empty?

**Comment by helkaroui** [comment]
No errors in the console.
I replaced the Composition object with a simple Component and now it's working : 
```js
const MyVideo = () => {
	const frame = useCurrentFrame();

	return (
		<div
			style={{
				flex: 1,
				textAlign: 'center',
				fontSize: '7em',
			}}
		>
			The current frame is {frame}.
		</div>
	);
};
```
So now the error only happens when using <Composition> with player.

**Comment by JonnyBurger** [comment]
Makes sense! Glad you figured it out! 🙌
