### ISSUE TITLE
Flickering when using `<Video>` with multiple `<Series.Sequence>`s on Lambda

### ISSUE THREAD

**Issue by Ivraj** [remotion-dev/remotion#991]
# Bug Report 🐛

Hi @JonnyBurger! We just finished our move to Remotion Lambda and our team is loving it. However, we've been seeing minor flickering issues with videos rendered with Lambda. 

## Background and Issue Description

Our use case is creating a sports highlights clip from a single source video. In order to accomplish this, we use a set of `<Series.Sequence>`s to sequentially display playing/frozen sections of the source video. For reference, the relevant section of our composition looks like this: 

```
// ...
<Series>
  {sequences.map((sequence) => {
    const { type, durationInFrames } = sequence;
    const startFromInFrames = Math.round(sequence.startFromInFrames);
    // ...

    if (type === "playing") {
      return (
        <Series.Sequence
          key={`${durationInFrames}-${startFromInFrames}`}
          durationInFrames={durationInFrames}
        >
          <Video
            src={url}
            startFrom={startFromInFrames}
	    // ...
          />
        </Series.Sequence>
      );
    } else if (type === "frozen") {
      return (
        <Series.Sequence
          key={`${durationInFrames}-${startFromInFrames}`}
          durationInFrames={durationInFrames}
        >
          <Freeze frame={0}>
            <Video
              src={url}
              startFrom={startFromInFrames}
	      // ...
            />
          </Freeze>
        </Series.Sequence>
      );
    }
  })}
</Series>
// ...
```

This method was working well for us when using `renderFrames` on a server. However, after moving to Remotion Lambda, we started to notice flickering throughout the rendered video. The flicker would briefly show either (a) the first frame of the source video or (b) a black screen.

## Further Investigation

To hone in on the issue, we used a blank Remotion project to create 2 simple compositions. In one, we had a `<Video>` in a single `<Series.Sequence>`. In the other, we had multiple `<Series.Sequence>`s. Then, we generated each video locally and in Lambda. This gave us a total of 4 test videos. We observed the following results: 

-  The locally rendered video with a `<Video>` in a single `<Series.Sequence>` worked fine.  
-  The Lambda rendered video with a `<Video>` in a single `<Series.Sequence>` worked fine.  
-  The locally rendered video with `<Video>`s in multiple `<Series.Sequence>`s worked fine.  
-  The Lambda rendered video with `<Video>`s in multiple `<Series.Sequence>`s had the flickering issue.  

Upon closer examination, we also noticed that the flickers were happening where rendering chunks were joined (in other words, if Remotion assigned x frames per lambda, the flicker would happen at some multiple of x).

At this moment, we're looking into [the Remotion docs on flickering](https://www.remotion.dev/docs/flickering). However, if this were a multi-threading issue, wouldn't we also expect to see a similar issue in the local videos since our machines also do some multi-threading? 

Below we've included our specs, the test videos we generated, as well as a repo with the source code to generate those test videos. 

## Specs

Local Machine: macOS Monterey, MacBook Pro, Apple M1 chip
Node version: `16.14.0`
Remotion version: `3.0.4`
Remotion Function: `remotion-render-2022-05-07-mem2048mb-disk1024mb-120sec`

## Test Videos

Here are the test videos mentioned in "Further Investigation". 

**`<Video>` with single `<Series.Sequence>` generated locally**
https://user-images.githubusercontent.com/14335084/168698851-27e396e6-d26e-4dc8-8a01-ce2ea37b1c05.mp4

**`<Video>` with single `<Series.Sequence>` generated in Lambda**
https://user-images.githubusercontent.com/14335084/168698873-f085e3c4-c8a2-451d-ac63-b170a25bce74.mp4

**`<Video>` with multiple `<Series.Sequence>` generated locally**
https://user-images.githubusercontent.com/14335084/168698889-85b7c796-b470-47fe-b5c5-5fe807ed649a.mp4

**`<Video>` with multiple `<Series.Sequence>` generated in Lambda**
https://user-images.githubusercontent.com/14335084/168698901-c93c81e5-6224-46a1-b661-7a53860a7005.mp4

## Replication Instructions

We've included the repo we used to generate the test videos [here](https://github.com/Ivraj/multi-seq-lambda-repro). Simply follow the instructions in the `README.md`. 

If there are any more details we can add, let us know! Happy to help debug. Also, based on our use case, feel free to let us know if there is perhaps a way to show sequential playing/frozen sections of a video without using the `<Series>`.

**Comment by JonnyBurger** [comment]
Thanks a lot for providing this excellent reproduction. I'll dig in now!

**Comment by Ivraj** [comment]
Awesome. Thanks for the quick response! We'll try that workaround to see if it does the trick.

**Comment by Ivraj** [comment]
Our team got a chance to test out the workaround of increasing the memory dedicated to the function. It works well!

When generating test videos (we used the same test videos from the [replication repo](https://github.com/Ivraj/multi-seq-lambda-repro) mentioned in the initial issue comment), we got the following results: 

**3072MB**: Out of 10 videos...
- 8 render with no issue
- 1 renders with 1 flicker
- 1 renders with 2 flickers. 

**4096MB**: Out of 10 videos...
- 10 render with no issue. 

This is a big contrast from the default 2048MB, which for us had flickers maybe ~80-90% of the time (that's just anecdotal, I didn't do as precise a test). Of course, with such a small sample size, it's hard to say whether the success rate is precisely 80% with 3GB and 100% with 4GB, but so far the trend of "more memory = fewer flickers" seems to hold. 

For our use case and scale, the cost of using 4GB functions is totally negligible, so we're going to go ahead and move forward with the workaround for now. We'll keep checking in on this issue, though, and provide more info if we discover anything as we're developing.

**Comment by JonnyBurger** [comment]
Hey guys, I've been digging a bit today and I think I got a good hint! The flicker always happens on the first frame of the chunk and it might be due to a bug.

I have to run off, but I'll verify that tomorrow and keep you up to date!

**Comment by JonnyBurger** [comment]
Hi! I released 3.0.8 which I think vastly improved on the flickering. I rendered 8 videos with 1024MB of RAM and only 1 video had a flicker at the 150 frame mark (where the <Sequence/> seam is).

Still, this is not perfect and I'm going to leave this issue open. Since you've been unblocked, I'm going to revisit the issue within the next few weeks and maybe use a completely different approach like exploding the video using FFMPEG and using an image to display the video, since this is a common Remotion pitfall and the browser cannot be trusted (also #200).

Thank you for the beautiful reproduction which almost made me shed a tear by the way! It is so pleasant to work with 🥲 you guys are highly valued customers.

**Comment by Ivraj** [comment]
Incredible! We'll upgrade to `3.0.8` as soon as we get a chance. Best of luck with those browser issues.

Haha, thanks man! It warms my heart to know that the reproduction was so easy to use. But, of course, such a repro is only possible when the original API is so well written 😃 . 

Once again, thanks for the quick responses and fixes!

**Comment by JonnyBurger** [comment]
We have a new component called `<OffthreadVideo />` that behaves correctly even under low resources: https://remotion.dev/docs/offthreadvideo
