### ISSUE TITLE
Set poster image for output video

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#998]
This is possible apparently: https://superuser.com/questions/1357459/add-poster-frame-artwork-to-mp4

**Comment by Ananya2003Gupta** [comment]
Can I work on this ?

**Comment by JonnyBurger** [comment]
Gladly! Assigned you!

**Comment by Ananya2003Gupta** [comment]
Can you please elaborate the problem and what possible solution should be implemented.

**Comment by Ananya2003Gupta** [comment]
I actually wanted to know how is useCurrentFrame() been implemented in remotion and also how remotion is using ffmpeg?
I read the documentation of remotion and found that useCurrentFrame() is being used for rendering videos frame by frame.

**Comment by JonnyBurger** [comment]
Hey @Ananya2003Gupta, I am very sorry for the late response!

This is actually a pretty hard issue that I am myself not sure how to achieve it and whether it's worth the effort.
As you know Remotion generates an MP4 out of a lot of screenshots that the browser takes. To encode that video, we use FFMPEG. Now if you have that MP4 file somewhere laying around, be it in your file explorer or in a media library in your video player, sometimes a thumbnail is displayed of a still frame of the video.

Now it seems that it is possible to customize that thumbnail by adding a parameter to the FFmpeg command, as shown in the first comment. The problem is that we sometimes spawn FFmpeg before the render start in order to it in parallel, and in that case we don't have any frames rendered yet, including the thumbnail.

And this is also a pretty niche feature, and one that can also be done outside of Remotion, so I am pondering heavily if it's worth to implement this feature and add more constraints to the renderer which we want to make more flexible in the future.

I would still love to help you become a contributor and guide you on the way! I would just propose that you pick a different issue, one that also has to do with React if you want to learn that. I'm actually going to close this issue as I don't plan to implement this feature.

**Comment by Ananya2003Gupta** [comment]
Sure, I would love to contribute to Remotion. I will keep a check on issues and will take up the ones that I would be able to contribute to : )

**Comment by JonnyBurger** [comment]
@Ananya2003Gupta Sounds perfect! Thanks a lot for your help :)
